Repository diffblue/cbmc, pull requests merged in 2018-08, with the labels that each got.

#2650 add clcache to Windows build
  buildspec-windows.yml
Labels: Build

#2462 Avoid signed/unsigned casts and conversion in goto_inline
  src/goto-programs/goto_inline_class.cpp
Labels: cleanup

#2667 Remove no-longer-used ifdef
  src/goto-instrument/full_slicer.cpp
Labels: cleanup

#2665 Clean GCC conditional expressions in right-hand sides of declarations
  regression/cbmc/gcc_conditional_expr1/main.c
  src/goto-programs/goto_convert.cpp
Labels: bugfix

#2669 use assertion in test regenerate-entry-function
  regression/goto-cc-cbmc/regenerate-entry-function/main.c
  regression/goto-cc-cbmc/regenerate-entry-function/test.desc
Labels: cleanup

#2671 fix get_base_name
  src/util/get_base_name.cpp
  unit/Makefile
  unit/util/get_base_name.cpp
Labels: bugfix

#2679 Refine test patterns to avoid spurious matches
  jbmc/regression/jbmc/reachability-slice/test.desc
  jbmc/regression/jbmc/reachability-slice/test2.desc
  jbmc/regression/jbmc/reachability-slice/test3.desc
  regression/cbmc/reachability-slice/test.desc
  regression/cbmc/reachability-slice/test2.desc
  regression/cbmc/reachability-slice/test3.desc
Labels: Build, bugfix

#2641 ansi-c: introduce typedef type
  src/ansi-c/ansi_c_declaration.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/scanner.l
  src/ansi-c/typedef_type.h
  src/util/irep_ids.def
Labels: C Front End, cleanup

#2483 Java front-end: remove unused parameters
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_utils.cpp
  jbmc/src/java_bytecode/java_utils.h
  jbmc/src/java_bytecode/select_pointer_type.cpp
Labels: Java Front End, cleanup

#2682 Codebuild for windows: set up cache path properly
  buildspec-windows.yml
Labels: Build

#2474 Remove unused parameter identifier
  src/goto-diff/unified_diff.cpp
  src/goto-diff/unified_diff.h
Labels: cleanup

#2467 Remove unused exception name from catch statement
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_target_equation.cpp
  src/jsil/jsil_typecheck.cpp
  src/solvers/flattening/boolbv_byte_extract.cpp
Labels: cleanup

#2675 CL echos the source file name
  regression/goto-cl/echo-file/echo-file.desc
  regression/goto-cl/echo-file/some_funny_file.c
  src/goto-cc/compile.cpp
Labels: enhancement

#2688 Fix concat_dir_file for Windows and unit-test it
  src/util/file_util.cpp
  unit/util/file_util.cpp
Labels: bugfix

#2674 Microsoft LINK personality
  regression/goto-cl/Fo/link.desc
  regression/goto-cl/Makefile
  src/goto-cc/Makefile
  src/goto-cc/goto_cc_main.cpp
  src/goto-cc/ms_link_cmdline.cpp
  src/goto-cc/ms_link_cmdline.h
  src/goto-cc/ms_link_mode.cpp
  src/goto-cc/ms_link_mode.h
Labels: work in progress

#2692 Follow tag types
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/padding.cpp
  src/util/namespace.cpp
  src/util/pointer_offset_size.cpp
  src/util/std_types.h
Labels: C Front End, cleanup

#2615 Create CBMC developer guide documentation
  doc/architectural/background-concepts.md
  doc/architectural/bmct-class.md
  doc/architectural/cbmc-architecture.md
  doc/architectural/compilation-and-development.md
  doc/architectural/cprover-architecture-overview.md
  doc/architectural/data-structures-core-structures-and-ast.md
  doc/architectural/data-structures-from-ast-to-goto-program.md
  doc/architectural/folder-walkthrough.md
  doc/architectural/front-end-languages-generating-codet-from-multiple-languages.md
  doc/architectural/front-page.md
  doc/architectural/other-tools.md
  doc/architectural/solvers-infrastructure.md
  doc/architectural/static-analysis-apis.md
  doc/architectural/symbolic-executors.md
Labels: documentation

#2711 set mode for functions added by remove_asm
  src/goto-programs/remove_asm.cpp
Labels: bugfix

#2699 goto-cc: use result of native compiler detection
  src/goto-cc/gcc_mode.cpp
Labels: C Front End, enhancement

#2716 CodeBuild: Remove empty artifact stanza
  buildspec-windows.yml
  buildspec.yml
Labels: Build, bugfix

#2714 add support for Visual Studio style inline assembler
  regression/goto-instrument/assembly_call_graph_test/main.c
  src/goto-programs/remove_asm.cpp
Labels: enhancement, work in progress

#2719 Make unit tests quiet
  unit/goto-programs/goto_trace_output.cpp
  unit/path_strategies.cpp
Labels: cleanup

#2725 replace_symbolt: report replacements in code_typet::return_type
  src/util/replace_symbol.cpp
Labels: bugfix

#2430 Java string preprocessing: Remove or document unused parameter function_id
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
Labels: Java Front End, cleanup

#2705 Replace function calls with calls to other functions
  regression/goto-instrument/replace-calls-01/main.c
  regression/goto-instrument/replace-calls-01/test.desc
  regression/goto-instrument/replace-calls-02/main.c
  regression/goto-instrument/replace-calls-02/test.desc
  regression/goto-instrument/replace-calls-03/main.c
  regression/goto-instrument/replace-calls-03/test.desc
  regression/goto-instrument/replace-calls-04/main.c
  regression/goto-instrument/replace-calls-04/test.desc
  regression/goto-instrument/replace-calls-05/main.c
  regression/goto-instrument/replace-calls-05/test.desc
  regression/goto-instrument/replace-calls-06/main.c
  regression/goto-instrument/replace-calls-06/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-programs/Makefile
  src/goto-programs/replace_calls.cpp
  src/goto-programs/replace_calls.h
Labels: new feature

#2729 Use pointer difference type when adding to pointer
  regression/cbmc/member1/main.c
  regression/cbmc/member1/test.desc
  src/analyses/goto_check.cpp
Labels: bugfix

#2727 Function-pointer remvoval: print human-friendly debug messages
  src/goto-programs/remove_const_function_pointers.cpp
Labels: cleanup

#2743 Fix boolbv_widtht::get_entry and fail for unknown types
  regression/cbmc/struct10/main.c
  regression/cbmc/struct10/test.desc
  src/solvers/flattening/boolbv_width.cpp
Labels: bugfix

#2738 remove memory-models
  CMakeLists.txt
  src/CMakeLists.txt
  src/Makefile
  src/memory-models/CMakeLists.txt
  src/memory-models/Makefile
  src/memory-models/README.md
  src/memory-models/cat-files/pso2.cat
  src/memory-models/cat-files/rmo2.cat
  src/memory-models/cat-files/tso2.cat
  src/memory-models/grammar.txt
  src/memory-models/mm2cpp.cpp
  src/memory-models/mm2cpp.h
  src/memory-models/mm_parser.cpp
  src/memory-models/mm_parser.h
  src/memory-models/mmcc_main.cpp
  src/memory-models/mmcc_parse_options.cpp
  src/memory-models/mmcc_parse_options.h
  src/memory-models/module_dependencies.txt
  src/memory-models/parser.y
  src/memory-models/scanner.l
  src/util/irep_ids.def
Labels: Needs rebase

#2720 replace_symbolt: hide {expr,type}_map
  src/analyses/constant_propagator.cpp
  src/analyses/constant_propagator.h
  src/goto-programs/link_goto_model.cpp
  src/util/replace_symbol.h
  unit/util/replace_symbol.cpp
Labels: cleanup

#2698 two further clang builtins
  regression/ansi-c/builtin_ia32_undef/main.c
  regression/ansi-c/builtin_ia32_undef/test.desc
  regression/ansi-c/builtin_nontemporal_load_store/main.c
  regression/ansi-c/builtin_nontemporal_load_store/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/clang_builtin_headers.h
Labels: C Front End, enhancement

#2765 factor out jar pool class
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/jar_pool.cpp
  jbmc/src/java_bytecode/jar_pool.h
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_class_loader.h
Labels: Java Front End, cleanup

#2769 Add a little more detail and discussion on irept
  src/util/README.md
Labels: documentation

#2770 Document symbol table and namespace
  src/util/README.md
Labels: documentation

#2774 Add documentation for object numbering
  src/pointer-analysis/README.md
  src/pointer-analysis/object_numbering.h
Labels: documentation

#2778 Add overview of constant propagator
  src/analyses/README.md
  src/analyses/constant_propagator.h
Labels: documentation

#2776 Add call-graph overview
  src/analyses/README.md
  src/analyses/call_graph.h
Labels: documentation

#2779 Document dstringt to string conversions
  src/util/README.md
Labels: documentation

#2799 Change doxygen settings
  src/doxyfile
Labels: documentation

#2797 fix some doxygen errors
  jbmc/unit/java-testing-utils/require_type.cpp
  src/goto-programs/remove_virtual_functions.cpp
  src/goto-programs/show_goto_functions_json.cpp
  src/goto-programs/show_goto_functions_xml.cpp
  src/goto-programs/system_library_symbols.cpp
  src/pointer-analysis/value_set.h
  src/util/journalling_symbol_table.h
  unit/testing-utils/require_expr.cpp
Labels: documentation

#2763 unify jar list and classpath
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_bytecode_language.h
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_class_loader.h
Labels: Java Front End, cleanup

#2804 Use a switch statement for clarity
  jbmc/src/java_bytecode/java_bytecode_language.cpp
Labels: cleanup

#2796 Improve goto-symex documentation
  src/goto-symex/README.md
Labels: documentation

#2783 Update docs for goto-programs
  src/goto-programs/README.md
Labels: documentation

#2781 Briefly document flow-insensitive analysis
  src/analyses/README.md
  src/analyses/flow_insensitive_analysis.h
Labels: documentation

#2771 Complete typet documentation [DOC-12]
  src/util/base_type.cpp
  src/util/std_types.cpp
  src/util/std_types.h
  src/util/type.cpp
  src/util/type.h
  src/util/type_eq.cpp
  src/util/type_eq.h
Labels: documentation

#2801 First part of DOC-13 codet documentation
  src/util/README.md
  src/util/std_code.cpp
  src/util/std_code.h
Labels: documentation

#2812 Deconflict README labels
  src/goto-programs/README.md
  src/util/README.md
Labels: documentation

#2818 rename 'identifier' to 'function_identifier'
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
  src/goto-programs/interpreter.cpp
  src/goto-programs/json_goto_trace.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: Symbolic Execution, cleanup

#2772 [DOC-21] Documentation for java loading from jar / class files
  jbmc/src/java_bytecode/jar_file.cpp
  jbmc/src/java_bytecode/jar_file.h
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_class_loader.h
  jbmc/src/java_bytecode/java_class_loader_limit.cpp
  jbmc/src/java_bytecode/java_class_loader_limit.h
Labels: documentation

#2807 Documentation: Overview of SSA
  src/goto-symex/README.md
Labels: documentation

#2819 goto_trace now contains the arguments of function calls
  regression/cbmc/trace_show_function_calls/test.desc
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: Symbolic Execution, enhancement

#2790 Document util/expr.{cpp,h} [DOC-11]
  doc/assets/expr.dot
  src/doxyfile
  src/util/expr.cpp
  src/util/expr.h
Labels: documentation

#2828 cpp_typecheckt::cpp_constructor now returns optionalt<codet>
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_destructor.cpp
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_declaration.cpp
  src/cpp/cpp_typecheck_destructor.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_initializer.cpp
Labels: C++ Front End, cleanup

#2766 jar_index cleanout
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_class_loader.h
Labels: Java Front End, cleanup

#2833 move object_descriptor_exprt::root_object into .cpp
  src/util/std_expr.cpp
  src/util/std_expr.h
Labels: cleanup

#2832 Stack traces
  jbmc/src/jbmc/jbmc_parse_options.cpp
  regression/cbmc/stack-trace/main.c
  regression/cbmc/stack-trace/test.desc
  src/cbmc/cbmc_parse_options.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
Labels: enhancement

#2837 add typing for convert_dowhile
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_class.h
Labels: cleanup

#2788 Update folder walkthrough [DOC-5]
  doc/architectural/folder-walkthrough.md
Labels: documentation

#2834 add protection to internal methods of exprt
  src/util/expr.h
Labels: cleanup

#2782 [DOC-20] Document class file content for JBMC / java_bytecode readme
  jbmc/src/java_bytecode/README.md
Labels: documentation

#2795 Tweak styling of html doxygen output
  doc/assets/cbmc_style.css
  src/doxyfile
Labels: documentation

#2843 split_string cleanup
  src/goto-instrument/unwindset.cpp
  src/util/config.cpp
  src/util/string_utils.cpp
  src/util/string_utils.h
  src/util/unwrap_nested_exception.cpp
  unit/util/string_utils/split_string.cpp
Labels: cleanup

#2839 factor out classpath functionality into separate class
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_class_loader.h
  jbmc/src/java_bytecode/java_class_loader_base.cpp
  jbmc/src/java_bytecode/java_class_loader_base.h
Labels: Java Front End, cleanup

#2787 Adds documentation for natural loops
  src/analyses/README.md
  src/analyses/natural_loops.h
Labels: documentation

#2863 Travis: Mark all Linux builds as sudo-required as maven workaround
  .travis.yml
Labels: Build, bugfix

#2773 Add overview documentation for the remove_java_new [DOC-25]
  jbmc/src/java_bytecode/README.md
Labels: documentation

#2853 include correct header for hostent
  src/ansi-c/library/netdb.c
Labels: bugfix

#2800 Doc std exprt [DOC-11]
  src/util/std_expr.h
Labels: documentation

#2792 Add an overview of what lowerings are done [DOC-25]
  jbmc/src/java_bytecode/README.md
Labels: documentation

#2793 Add some usage examples into the goto-instrument readme file. [DOC-41]
  src/goto-instrument/README.md
Labels: documentation

#2789 Update compilation and development docs
  COMPILING.md
  doc/architectural/compilation-and-development.md
Labels: documentation

#2869 Clean up run.h interface
  src/goto-cc/as_mode.cpp
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/hybrid_binary.cpp
  src/goto-cc/ld_mode.cpp
  src/goto-cc/linker_script_merge.cpp
  src/util/run.cpp
  src/util/run.h
Labels: cleanup

#2849 run now does I/O redirection on Windows
  src/util/run.cpp
Labels: enhancement
