Repository diffblue/cbmc, pull requests merged in 2018-02, with the labels that each got.

#1822 moving language.h and language_file.h to langapi folder
  src/ansi-c/ansi_c_language.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/clobber/clobber_parse_options.cpp
  src/cpp/cpp_language.h
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-instrument/dump_c_class.h
  src/goto-instrument/splice_call.cpp
  src/goto-programs/initialize_goto_model.cpp
  src/goto-programs/lazy_goto_functions_map.h
  src/goto-programs/lazy_goto_model.cpp
  src/goto-programs/lazy_goto_model.h
  src/goto-programs/rebuild_goto_start_function.cpp
  src/goto-programs/show_symbol_table.cpp
  src/java_bytecode/java_bytecode_language.h
  src/jbmc/jbmc_parse_options.cpp
  src/jbmc/jbmc_parse_options.h
  src/jsil/jsil_language.h
  src/langapi/Makefile
  src/langapi/language.cpp
  src/langapi/language.h
  src/langapi/language_file.cpp
  src/langapi/language_file.h
  src/langapi/language_ui.cpp
  src/langapi/language_ui.h
  src/langapi/language_util.cpp
  src/langapi/mode.cpp
  src/util/Makefile
  src/util/json_expr.cpp
  unit/java_bytecode/java_bytecode_convert_class/convert_abstract_class.cpp
  unit/testing-utils/load_java_class.cpp
  unit/testing-utils/load_java_class.h
Labels: enhancement

#1751 C front-end: fix promotion order for types ranking lower than int
  regression/cbmc/Pointer_byte_extract5/main.c
  regression/cbmc/Pointer_byte_extract8/main.c
  regression/cbmc/Promotion4/main.c
  regression/cbmc/Promotion4/test.desc
  regression/cbmc/address_space_size_limit2/test.c
  src/ansi-c/c_preprocess.cpp
  src/ansi-c/c_typecast.cpp
Labels: C Front End, bugfix

#853 Clean up code for pointer function parameters
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/util/std_code.h
Labels: cleanup

#1845 Fix building without USE_DSTRING
  .travis.yml
  doc/architectural/cbmc-guide.md
  src/ansi-c/ansi_c_scope.h
  src/goto-programs/class_hierarchy.h
  src/goto-programs/interpreter.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/java_bytecode/character_refine_preprocess.h
  src/java_bytecode/java_bytecode_convert_class.cpp
  src/java_bytecode/java_bytecode_convert_method.cpp
  src/java_bytecode/java_object_factory.cpp
  src/solvers/prop/bdd_expr.h
  src/util/expr.h
  src/util/irep_ids.h
  src/util/replace_expr.h
  src/util/replace_symbol.h
  src/util/std_types.h
  src/util/symbol_table_base.cpp
Labels: bugfix

#1883 Implement popcount
  regression/cbmc/gcc_popcount1/main.c
  regression/cbmc/gcc_popcount1/test.desc
  regression/cbmc/gcc_popcount2/main.c
  regression/cbmc/gcc_popcount2/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/solvers/Makefile
  src/solvers/flattening/boolbv.cpp
  src/solvers/lowering/expr_lowering.h
  src/solvers/lowering/popcount.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/std_expr.h
Labels: bugfix
