Repository diffblue/cbmc, pull requests merged in 2018-05, with the labels that each got.

#2155 Add missing mode
  src/goto-programs/goto_convert_side_effect.cpp
Labels: bugfix

#2162 Fix duplicate output of id in format()
  src/util/format_expr.cpp
Labels: bugfix

#2163 Remove unnecessary (and inconsistent) return statement
  regression/cbmc/Float22/main.c
Labels: bugfix

#2164 Cleanup comments and unnecessary global in mp_arith.h
  src/util/mp_arith.h
Labels: bugfix

#2179 Java concurrency support
  regression/cbmc-java-concurrency/CMakeLists.txt
  regression/cbmc-java-concurrency/Makefile
  regression/cbmc-java-concurrency/explicit_thread_blocks/A.class
  regression/cbmc-java-concurrency/explicit_thread_blocks/A.java
  regression/cbmc-java-concurrency/explicit_thread_blocks/test.desc
  regression/cbmc-java-concurrency/explicit_thread_blocks/test2.desc
  src/java_bytecode/Makefile
  src/java_bytecode/java_bytecode_convert_method.cpp
  src/java_bytecode/java_bytecode_convert_threadblock.cpp
  src/java_bytecode/java_bytecode_convert_threadblock.h
  src/java_bytecode/java_bytecode_language.cpp
  src/java_bytecode/library/src/org/cprover/CProver.java
Labels: Java Front End, Merge before removing java

#2168 Don't phi-merge uninitialised objects
  regression/cbmc-java/phi-merge_uninitialized_values/PhiMergeUninitialized.class
  regression/cbmc-java/phi-merge_uninitialized_values/PhiMergeUninitialized.java
  regression/cbmc-java/phi-merge_uninitialized_values/field.desc
  regression/cbmc-java/phi-merge_uninitialized_values/local.desc
  regression/cbmc-java/phi-merge_uninitialized_values/static_field.desc
  regression/cbmc/phi-merge_uninitialized_values/dynamic.desc
  regression/cbmc/phi-merge_uninitialized_values/global.desc
  regression/cbmc/phi-merge_uninitialized_values/local.desc
  regression/cbmc/phi-merge_uninitialized_values/static_local.desc
  regression/cbmc/phi-merge_uninitialized_values/test.c
  regression/test.pl
  src/goto-symex/goto_symex.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_goto.cpp
Labels: Merge before removing java

#2124 Lazy methods: allow driver program to provide stubs
  src/goto-programs/lazy_goto_functions_map.h
  src/goto-programs/lazy_goto_model.cpp
  src/goto-programs/lazy_goto_model.h
  src/java_bytecode/Makefile
  src/java_bytecode/simple_method_stubbing.cpp
  src/java_bytecode/simple_method_stubbing.h
  src/jbmc/jbmc_parse_options.cpp
  src/jbmc/jbmc_parse_options.h
  unit/testing-utils/load_java_class.cpp
Labels: Merge before removing java

#2011 Add storage of final modifier status of java classes in `java_class_typet`.
  src/java_bytecode/java_bytecode_convert_class.cpp
  src/java_bytecode/java_bytecode_parse_tree.cpp
  src/java_bytecode/java_bytecode_parse_tree.h
  src/java_bytecode/java_bytecode_parser.cpp
  src/java_bytecode/java_types.h
  src/util/irep_ids.def
Labels: Java Front End, Merge before removing java

#2187 Move convert_nondet to java_bytecode
  src/cbmc/cbmc_parse_options.cpp
  src/goto-programs/Makefile
  src/java_bytecode/Makefile
  src/java_bytecode/convert_java_nondet.cpp
  src/java_bytecode/convert_java_nondet.h
  src/jbmc/jbmc_parse_options.cpp
Labels: Do not merge

#2198 Fix perl regular expressions in regression test descriptions
  regression/goto-analyzer/approx-const-fp-array-variable-cast-const-fp/test.desc
  regression/goto-analyzer/approx-const-fp-array-variable-const-fp-with-null/test.desc
  regression/goto-analyzer/approx-const-fp-array-variable-const-fp/test.desc
  regression/goto-analyzer/approx-const-fp-array-variable-const-pointer-const-struct-non-const-fp/test.desc
  regression/goto-analyzer/approx-const-fp-array-variable-const-struct-non-const-fp/test.desc
  regression/goto-analyzer/approx-const-fp-array-variable-invalid-cast-const-fp/test.desc
  regression/goto-analyzer/constant_propagation_05/test.desc
  regression/goto-analyzer/constant_propagation_10/test.desc
  regression/goto-analyzer/constant_propagation_11/test.desc
  regression/goto-analyzer/constant_propagation_13/test.desc
  regression/goto-analyzer/constant_propagation_14/test.desc
  regression/goto-analyzer/constant_propagation_15/test.desc
  regression/goto-analyzer/intervals_02/test.desc
  regression/goto-analyzer/intervals_03/test.desc
  regression/goto-analyzer/intervals_04/test.desc
  regression/goto-analyzer/intervals_05/test.desc
  regression/goto-analyzer/intervals_06/test.desc
  regression/goto-analyzer/intervals_07/test.desc
  regression/goto-analyzer/intervals_08/test.desc
  regression/goto-analyzer/intervals_09/test.desc
  regression/goto-analyzer/intervals_10/test.desc
  regression/goto-analyzer/intervals_11/test.desc
  regression/strings/test_index_of/test.desc
  regression/strings/test_int/test.desc
Labels: bugfix

#2199 Static simplification should not alter symbol types
  src/goto-analyzer/static_simplifier.cpp
  src/goto-programs/remove_returns.cpp
Labels: bugfix

#2197 Fix help output of --generate-function-body-options
  src/goto-programs/generate_function_bodies.h
Labels: bugfix

#2191 Java: make null-pointer and similar checks fatal
  regression/cbmc-java/NullPointer3/test.desc
  regression/cbmc-java/repeated_guards/A.class
  regression/cbmc-java/repeated_guards/B.class
  regression/cbmc-java/repeated_guards/Test.class
  regression/cbmc-java/repeated_guards/Test.java
  regression/cbmc-java/repeated_guards/test_arraybounds.desc
  regression/cbmc-java/repeated_guards/test_arraycreation.desc
  regression/cbmc-java/repeated_guards/test_assertion.desc
  regression/cbmc-java/repeated_guards/test_classcast.desc
  regression/cbmc-java/repeated_guards/test_divbyzero.desc
  regression/cbmc-java/repeated_guards/test_nullderef.desc
  regression/jbmc-strings/long_string/Test.class
  regression/jbmc-strings/long_string/Test.java
  src/goto-instrument/cover.cpp
  src/java_bytecode/java_bytecode_instrument.cpp
  src/util/std_code.cpp
  src/util/std_code.h
Labels: Java Front End

#2209 Travis: remove g++ build on OS X
  .travis.yml
Labels: cleanup

#2208 remove basic_blocks and goto_program_irep
  src/goto-programs/Makefile
  src/goto-programs/basic_blocks.cpp
  src/goto-programs/basic_blocks.h
  src/goto-programs/goto_program_irep.cpp
  src/goto-programs/goto_program_irep.h
  src/util/irep_ids.def
Labels: cleanup

#2207 remove (pre-SMT-LIB) CVC interface
  src/cbmc/cbmc_solvers.cpp
  src/solvers/Makefile
  src/solvers/cvc/cvc_conv.cpp
  src/solvers/cvc/cvc_conv.h
  src/solvers/cvc/cvc_dec.cpp
  src/solvers/cvc/cvc_dec.h
Labels: cleanup

#2211 Travis/OSX follow-up cleanup: remove unnecessary environment variables
  .travis.yml
Labels: cleanup

#2210 Verbosity parsing/handling cleanup
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/janalyzer/janalyzer_parse_options.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/clobber/clobber_parse_options.cpp
  src/clobber/clobber_parse_options.h
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-cc/armcc_mode.cpp
  src/goto-cc/as_mode.cpp
  src/goto-cc/cw_mode.cpp
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-cc/ms_cl_mode.cpp
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-diff/goto_diff_parse_options.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/util/message.cpp
  src/util/message.h
Labels: cleanup

#2214 Remove memory_limit and substitute
  src/util/Makefile
  src/util/memory_limit.cpp
  src/util/memory_limit.h
  src/util/substitute.cpp
  src/util/substitute.h
Labels: cleanup

#2222 C front-end: fallthrough attribute, variable aliases
  regression/ansi-c/gcc_attributes12/main.c
  regression/ansi-c/gcc_attributes12/test.desc
  regression/ansi-c/gcc_attributes13/main.c
  regression/ansi-c/gcc_attributes13/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
Labels: C Front End

#2244 fix ordering problem in solvers/Makefile
  src/common
  src/config.inc
  src/solvers/Makefile
Labels: Build, bugfix

#2241 goto-cc: add separate path for ld
  src/goto-cc/Makefile
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/gcc_mode.h
  src/goto-cc/goto_cc_main.cpp
  src/goto-cc/goto_cc_mode.cpp
  src/goto-cc/hybrid_binary.cpp
  src/goto-cc/hybrid_binary.h
  src/goto-cc/ld_mode.cpp
  src/goto-cc/ld_mode.h
  src/goto-cc/linker_script_merge.cpp
  src/goto-cc/linker_script_merge.h
Labels: cleanup

#2242 remove a warning about section names
  src/ansi-c/c_typecheck_base.cpp
Labels: C Front End

#2201 Remove incomplete type constructors
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_parse_tree.h
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  jbmc/unit/java_bytecode/java_types/generic_type_index.cpp
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/cpp/parse.cpp
  src/goto-programs/remove_virtual_functions.cpp
  src/goto-programs/string_instrumentation.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/util/std_types.h
Labels: cleanup

#2251 Cleanup of uses of get_new_name
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/accelerate/sat_path_enumerator.cpp
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_dead.cpp
  src/goto-symex/symex_decl.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/value_set_dereference.cpp
Labels: cleanup
