Repository diffblue/cbmc, pull requests merged in 2018-10, with the labels that each got.

#3076 struct_typet::baset: no need for cast to symbol_type
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  src/goto-programs/class_hierarchy.cpp
Labels: Java Front End, cleanup

#3074 Inline copy_to_operands
  src/util/expr.cpp
  src/util/expr.h
Labels: enhancement

#2775 Add documentation on `remove-instanceof` [DOC-25]
  jbmc/src/java_bytecode/README.md
  jbmc/src/java_bytecode/remove_instanceof.h
Labels: documentation

#3077 allow binary arithmetic of a vector type and a scalar type
  regression/cbmc/gcc_vector1/main.c
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/remove_vector.cpp
Labels: C Front End, bugfix

#3088 remove typet::subtypes()
  src/util/type.cpp
  src/util/type.h
Labels: cleanup

#3090 added backtrace output on the Mac
  src/util/invariant.cpp
Labels: enhancement

#3089 simple test for mismatching return types accross compilation units
  regression/cbmc/Linking7/return_type.desc
  regression/cbmc/Linking7/return_type1.c
  regression/cbmc/Linking7/return_type2.c
  src/goto-programs/remove_returns.cpp
Labels: Tests, bugfix

#3086 bugfix: use symbol_type for type symbol
  src/pointer-analysis/value_set_analysis_fi.cpp
  src/pointer-analysis/value_set_analysis_fivr.cpp
  src/pointer-analysis/value_set_analysis_fivrns.cpp
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/boolbv_map.cpp
  src/solvers/flattening/boolbv_update.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: bugfix

#3098 simplifier: sum and mul cleanup
  src/util/fixedbv.cpp
  src/util/simplify_expr_int.cpp
Labels: cleanup

#3096 introduce integer2bv and bv2integer
  jbmc/src/java_bytecode/java_bytecode_concurrency_instrumentation.cpp
  src/ansi-c/expr2c.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/util/arith_tools.cpp
  src/util/bv_arithmetic.cpp
  src/util/expr.cpp
  src/util/fixedbv.cpp
  src/util/ieee_float.cpp
  src/util/mp_arith.cpp
  src/util/mp_arith.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#3060 C++: use struct tag instead of symbol_type
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_exception_id.cpp
  src/cpp/cpp_instantiate_template.cpp
  src/cpp/cpp_is_pod.cpp
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_bases.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_virtual_table.cpp
Labels: C++ Front End, cleanup

#3073 deprecates exprt::move_to_operands(...)
  src/util/expr.h
Labels: cleanup, documentation

#3104 remove bitwise_neg(mp_integer)
  src/goto-programs/interpreter_evaluate.cpp
  src/util/mp_arith.cpp
  src/util/mp_arith.h
Labels: cleanup

#3080 added code_blockt::statements(), which is a vector of codet
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/simple_method_stubbing.cpp
  src/ansi-c/expr2c.cpp
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_typecheck_destructor.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/goto_convert.cpp
  src/jsil/jsil_parse_tree.cpp
  src/util/format_expr.cpp
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#3106 boolbvt::convert_constant is now independent of bitvector representation
  src/solvers/flattening/boolbv_constant.cpp
  src/util/arith_tools.cpp
  src/util/arith_tools.h
  src/util/simplify_expr.cpp
Labels: cleanup

#3067 use code_blockt::add and ::move for adding a statement
  jbmc/src/java_bytecode/java_bytecode_concurrency_instrumentation.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  jbmc/src/java_bytecode/java_bytecode_instrument.h
  jbmc/src/java_bytecode/java_entry_point.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_static_initializers.cpp
  jbmc/src/java_bytecode/remove_java_new.cpp
  jbmc/src/java_bytecode/simple_method_stubbing.cpp
  src/ansi-c/ansi_c_entry_point.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_destructor.cpp
  src/goto-instrument/goto_program2code.cpp
  src/jsil/jsil_entry_point.cpp
  src/linking/static_lifetime_init.cpp
  src/util/expr.h
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#3105 simplify_exprt::simplify_bitwise is now independent of bitvector representation
  src/util/arith_tools.cpp
  src/util/arith_tools.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#3114 float_type(), double_type() and long_double_type() now return float_typet
  src/ansi-c/gcc_types.cpp
  src/ansi-c/gcc_types.h
  src/util/c_types.cpp
  src/util/c_types.h
Labels: C Front End

#3117 goto-analyzer --simplify must write files in binary mode
  src/goto-analyzer/goto_analyzer_parse_options.cpp
Labels: bugfix

#3125 Remove the __CPROVER_HIDE label when inlining
  src/goto-programs/goto_inline_class.cpp
Labels: bugfix

#3130 static_analysist now passes function identifiers to transform()
  src/analyses/static_analysis.cpp
  src/analyses/static_analysis.h
  src/pointer-analysis/value_set_domain.h
  src/pointer-analysis/value_set_domain_transform.inc
Labels: cleanup

#3131 Modest show_loop_ids cleanup
  src/goto-programs/loop_ids.cpp
  src/goto-programs/loop_ids.h
Labels: cleanup

#3139 Re-try Minisat download (up to two times) in case it fails
  src/Makefile
  src/solvers/CMakeLists.txt
Labels: Build

#3155 Fix typo in simplify_byte_extract
  jbmc/unit/util/simplify_expr.cpp
  src/util/simplify_expr.cpp
  unit/Makefile
  unit/util/simplify_expr.cpp
Labels: bugfix

#3160 type_with_subtype constructor
  src/util/std_types.h
  src/util/type.h
Labels: cleanup

#3163 add 'override' in cpp_typecheckt
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_expr.cpp
Labels: C++ Front End, cleanup

#3164 print disjuncts in Gentzen sequent separately
  regression/cbmc/show-vcc/main.c
  regression/cbmc/show-vcc/test.desc
  src/goto-symex/show_vcc.cpp
Labels: enhancement

#3169 c_bool_typet: Remove unused default constructor
  src/util/std_types.h
Labels: cleanup

#3173 Add sources for libstdc++6 >= 4.9
  .travis.yml
Labels: Build, bugfix

#3172 Make maven invocations quiet
  jbmc/CMakeLists.txt
  jbmc/src/java_bytecode/library/Makefile
Labels: Build

#3174 Travis: Make linter and clang-format failures fatal
  .github/pull_request_template.md
  .travis.yml
Labels: Build

#3177 Use is_not_zero in simplifier
  src/util/simplify_expr.cpp
Labels: cleanup

#3166 mstreamt manipulators are now static
  src/cbmc/all_properties.cpp
  src/cbmc/bmc.cpp
  src/goto-analyzer/static_verifier.cpp
  src/util/message.cpp
  src/util/message.h
Labels: cleanup

#3176 linter: Fix missing comma
  scripts/cpplint.py
Labels: bugfix

#3161 smt2_parser: parse Array sort
  src/solvers/smt2/smt2_parser.cpp
Labels: Solvers

#3175 Fix documentation formatting
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  src/goto-programs/remove_virtual_functions.cpp
  src/util/fresh_symbol.cpp
Labels: documentation

#3165 use a separate message for show_goto_functions() for the console
  src/goto-programs/goto_functions.cpp
  src/goto-programs/goto_functions.h
  src/goto-programs/goto_model.h
  src/goto-programs/show_goto_functions.cpp
  src/goto-programs/show_goto_functions_json.cpp
  src/goto-programs/show_goto_functions_xml.cpp
Labels: enhancement

#3195 Goto trace colors
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
Labels: enhancement

#3197 fix ACSL unicode operators
  regression/cbmc/ACSL/operators.c
  regression/cbmc/ACSL/operators.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
Labels: C Front End, bugfix

#3103 bitwise_or, _and, _xor can now do arbitrary widths
  src/util/mp_arith.cpp
Labels: enhancement, work in progress

#3202 Add contracts directory to regression tests run via CMake
  regression/CMakeLists.txt
Labels: Tests, bugfix

#3109 switch bv2integer and integer2bv to irep_idt
  src/ansi-c/expr2c.cpp
  src/ansi-c/literals/convert_float_literal.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/solvers/flattening/boolbv_constant.cpp
  src/solvers/lowering/popcount.cpp
  src/util/arith_tools.cpp
  src/util/arith_tools.h
  src/util/bv_arithmetic.cpp
  src/util/expr.cpp
  src/util/fixedbv.cpp
  src/util/ieee_float.cpp
  src/util/json_expr.cpp
  src/util/mp_arith.cpp
  src/util/mp_arith.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#3205 values in goto-trace outputs are now done independent of bvrep
  src/goto-programs/goto_trace.cpp
Labels: cleanup

#2830 use code_blockt::statements() where appropriate
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_code.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/goto_program2code.cpp
Labels: cleanup

#3209 show-vcc: colors
  src/goto-symex/show_vcc.cpp
Labels: enhancement

#2876 Travis: Use clang-6.0 and mark all builds as sudo: false
  .travis.yml
Labels: Build

#3214 comments on future replacements of util/file_util.h functions
  src/util/file_util.h
Labels: documentation

#3213 static_show_domain doesn't determine SAFE/UNSAFE
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/static_show_domain.cpp
  src/goto-analyzer/static_show_domain.h
Labels: Static Analyses, cleanup

#3217 Fix is_bmp_code_point
  jbmc/src/java_bytecode/character_refine_preprocess.cpp
Labels: bugfix

#3235 coding style: encourage documenting interfaces in the header file
  CODING_STANDARD.md
Labels: documentation

#3230 goto-cc: show error line
  regression/ansi-c/const1/const-array.desc
  regression/ansi-c/const1/const-member.desc
  src/util/cout_message.cpp
  src/util/source_location.cpp
  src/util/source_location.h
Labels: C Front End, C++ Front End, enhancement

#3244 move CPROVER manual source into git repo
  doc/cprover-manual/api.md
  doc/cprover-manual/assumptions.md
  doc/cprover-manual/cbmc-assertions.md
  doc/cprover-manual/cbmc-tutorial.md
  doc/cprover-manual/cbmc-unwinding.md
  doc/cprover-manual/goto-cc-variants.md
  doc/cprover-manual/goto-cc.md
  doc/cprover-manual/index.md
  doc/cprover-manual/installation.md
  doc/cprover-manual/introduction.md
  doc/cprover-manual/modeling-assumptions.md
  doc/cprover-manual/modeling-floating-point.md
  doc/cprover-manual/modeling-nondeterminism.md
  doc/cprover-manual/modeling-pointers.md
  doc/cprover-manual/test-suite.md
  doc/cprover-manual/visual-studio.md
Labels: documentation

#3183 Evaluating sizeof over __CPROVER_bool requires special cases
  regression/ansi-c/cprover_bool1/main.c
  regression/ansi-c/cprover_bool1/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/padding.cpp
  src/util/pointer_offset_size.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_struct.cpp
Labels: C Front End, bugfix

#3171 Use CPROVER_PREFIX macro instead of hardcoded __CPROVER_ string
  jbmc/src/java_bytecode/java_bytecode_internal_additions.cpp
  jbmc/unit/java_bytecode/java_object_factory/gen_nondet_string_init.cpp
  scripts/cpplint.py
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/escape_analysis.cpp
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/cprover_library.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/scanner.l
  src/cpp/cpp_convert_type.cpp
  src/cpp/cpp_internal_additions.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-instrument/cover_instrument_other.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-instrument/model_argc_argv.cpp
  src/goto-instrument/thread_instrumentation.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/read_bin_goto_object.cpp
  src/goto-programs/slice_global_inits.cpp
  src/jsil/jsil_internal_additions.cpp
  src/linking/static_lifetime_init.cpp
  src/solvers/flattening/boolbv_index.cpp
  src/util/cprover_prefix.h
  unit/path_strategies.cpp
Labels: cleanup

#3184 C++ bool is at least one byte wide
  regression/cpp/cprover_bool1/main.cpp
  regression/cpp/cprover_bool1/test.desc
  src/cpp/cpp_convert_type.cpp
  src/cpp/cpp_type2name.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_type.cpp
  src/cpp/expr2cpp.cpp
  src/cpp/parse.cpp
Labels: C++ Front End, Do not merge, bugfix

#3203 Remove unused includes from regression tests
  regression/cbmc/Endianness6/main.c
  regression/cbmc/Function_Pointer13/main.c
  regression/cbmc/Variadic1/main.c
  regression/cbmc/byte_update1/main.c
  regression/cbmc/byte_update3/main.c
  regression/cbmc/byte_update4/main.c
  regression/cbmc/byte_update5/main.c
  regression/cbmc/complex1/main.c
  regression/cbmc/dynamic_sizeof1/main.c
  regression/cbmc/pointer-extra-checks/main.c
  regression/cbmc/va_list3/main.c
Labels: Tests, cleanup

#2161 Handle empty structs in the back-end (and a number of induced fixes)
  regression/cbmc/Empty_struct2/main.c
  regression/cbmc/Empty_struct2/test.desc
  src/pointer-analysis/value_set_dereference.cpp
  src/solvers/flattening/pointer_logic.cpp
  src/solvers/flattening/pointer_logic.h
  src/util/pointer_offset_size.cpp
  src/util/simplify_expr.cpp
Labels: bugfix

#3135 Include pointer offset in counterexample output
  regression/cbmc/trace_address_arithmetic1/main.c
  regression/cbmc/trace_address_arithmetic1/test.desc
  src/solvers/flattening/pointer_logic.cpp
Labels: bugfix
