Repository diffblue/cbmc, pull requests merged in 2018-12, with the labels that each got.

#3483 fix memcpy overlap check
  regression/cbmc-library/memcpy-02/memcpy1.c
  regression/cbmc-library/memcpy-02/memcpy1.desc
  regression/cbmc-library/memcpy-02/memcpy2.c
  regression/cbmc-library/memcpy-02/memcpy2.desc
  regression/cbmc-library/memcpy-02/memcpy3.c
  regression/cbmc-library/memcpy-02/memcpy3.desc
  regression/cbmc-library/memcpy-02/memcpy4.c
  regression/cbmc-library/memcpy-02/memcpy4.desc
  scripts/delete_failing_smt2_solver_tests
  src/ansi-c/library/string.c
Labels: bugfix

#3491 Refactoring: use value_is_zero_string
  src/util/json_expr.cpp
Labels: cleanup

#3487 Remove deprecated exprt::make_false
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/unwind.cpp
  src/goto-symex/memory_model_tso.cpp
  src/goto-symex/symex_goto.cpp
  src/jsil/parser.y
  src/solvers/flattening/boolbv_quantifier.cpp
  src/util/expr.cpp
  src/util/expr.h
Labels: cleanup

#3489 Fix typo: phtread_join -> pthread_join
  src/ansi-c/library/pthread_lib.c
Labels: bugfix

#3503 SMT2: get-assignment
  regression/smt2_solver/get-assignment/get-assignment1.desc
  regression/smt2_solver/get-assignment/get-assignment1.smt2
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
  src/solvers/smt2/smt2_solver.cpp
  src/solvers/smt2/smt2_tokenizer.cpp
  src/solvers/smt2/smt2_tokenizer.h
Labels: enhancement

#3509 Remove unnecessary duplicate hiding
  src/util/std_expr.h
Labels: cleanup

#3506 Inline side_effect_exprt* constructors
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#3508 Remove unnecessary "explicit"
  src/util/std_code.h
  src/util/std_expr.h
Labels: cleanup

#3515 smt2_solver: implement get-model
  regression/smt2_solver/get-model/get-model1.desc
  regression/smt2_solver/get-model/get-model1.smt2
  src/solvers/smt2/smt2_solver.cpp
Labels: enhancement

#3513 bv_arithmetict: Lift precondition to from_expr's interface
  src/util/bv_arithmetic.cpp
  src/util/bv_arithmetic.h
Labels: cleanup

#3516 Remove unused value_set_dereferencet::get_symbol
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_dereference.h
Labels: cleanup

#3496 Use more specific return type instead of generic codet/exprt (part 2)
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.h
Labels: cleanup

#3497 extractbits_exprt has a single correct operand order
  src/solvers/flattening/boolbv_extractbits.cpp
Labels: cleanup

#3500 Use code_typet::parameters
  src/cpp/cpp_convert_type.cpp
  src/cpp/cpp_typecheck_conversions.cpp
Labels: cleanup

#3485 smt2_solver: quoted symbol fix
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_format.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_tokenizer.cpp
  src/solvers/smt2/smt2_tokenizer.h
  src/util/irep_ids.def
Labels: bugfix

#3512 Remove unused code_ifthenelset object
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
Labels: cleanup

#3393 Class and function documentation for goto-symex-target [DOC-79]
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: Needs rebase, documentation

#3399 DOC-70: Description of `rd_range_domaint` of reaching_definitions.h(cpp) module.
  src/analyses/reaching_definitions.cpp
  src/analyses/reaching_definitions.h
Labels: documentation

#3521 smt2_solver: arrays
  regression/smt2_solver/arrays/arrays1.desc
  regression/smt2_solver/arrays/arrays1.smt2
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_format.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_solver.cpp
Labels: enhancement

#3490 Remove deprecated exprt::make_true
  src/analyses/goto_rw.h
  src/analyses/interval_domain.cpp
  src/goto-symex/slice_by_trace.cpp
  src/jsil/parser.y
  src/util/expr.cpp
  src/util/expr.h
  src/util/guard.cpp
  src/util/guard.h
Labels: cleanup

#3339 Remove unused messaget parameter from static_verifier_text [blocks: #2310]
  src/goto-analyzer/static_verifier.cpp
Labels: blocker, cleanup

#3548 smt2 parser: fix sign extension
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_parser.cpp
Labels: bugfix

#3550 smt2 solver: constants
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_format.cpp
  src/solvers/smt2/smt2_solver.cpp
Labels: enhancement

#3552 smt2 backend: fix floating-point values
  regression/cbmc/hex_trace/main.c
  regression/cbmc/hex_trace/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/solvers/floatbv/float_bv.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: bugfix

#3415 Avoid shadowing of variables (several instances) [blocks: #2310]
  src/goto-cc/linker_script_merge.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-instrument/accelerate/accelerate.h
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/accelerate/acceleration_utils.h
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.h
  src/goto-instrument/concurrency.cpp
  src/goto-instrument/document_properties.cpp
  src/goto-instrument/dot.cpp
  src/goto-instrument/nondet_static.cpp
  src/goto-instrument/thread_instrumentation.cpp
  src/goto-instrument/unwind.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-instrument/wmm/goto2graph.h
  src/goto-instrument/wmm/instrumenter_strategies.cpp
  src/goto-instrument/wmm/shared_buffers.cpp
  src/goto-instrument/wmm/shared_buffers.h
  src/goto-instrument/wmm/weak_memory.cpp
Labels: blocker, cleanup

#3556 Remove refs to obsolete solver modules
  CODEOWNERS
  doc/man/cbmc.1
  doc/slides/cprover-overview-latex-beamer/cprover-overview-slides.tex
  jbmc/src/jbmc/jbmc_parse_options.h
  scripts/vpath-setup.sh
  src/solvers/README.md
  src/solvers/cvc/module_dependencies.txt
Labels: cleanup

#3573 Fix typos
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_goto.cpp
Labels: cleanup, documentation

#3576 smt2 parser: fix the two error messages for unknown symbols
  src/solvers/smt2/smt2_parser.cpp
Labels: Solvers

#3582 smt2 backend: additional passing tests
  scripts/delete_failing_smt2_solver_tests
Labels: SMT Backend Interface, Tests

#3353 Avoid warning about unsigned/enum type mix in conditional expression [blocks: #2310]
  src/goto-diff/change_impact.cpp
Labels: blocker, cleanup

#3557 Move cbmc_solvers as solver_factory to new goto-checker module [blocks: 3564, 3565]
  CMakeLists.txt
  jbmc/src/jbmc/CMakeLists.txt
  jbmc/src/jbmc/Makefile
  jbmc/src/jbmc/module_dependencies.txt
  jbmc/unit/CMakeLists.txt
  jbmc/unit/Makefile
  src/CMakeLists.txt
  src/Makefile
  src/cbmc/CMakeLists.txt
  src/cbmc/Makefile
  src/cbmc/bmc.cpp
  src/cbmc/cbmc_parse_options.h
  src/cbmc/module_dependencies.txt
  src/goto-checker/CMakeLists.txt
  src/goto-checker/Makefile
  src/goto-checker/module_dependencies.txt
  src/goto-checker/solver_factory.cpp
  src/goto-checker/solver_factory.h
  unit/CMakeLists.txt
  unit/Makefile
  unit/module_dependencies.txt
  unit/path_strategies.cpp
Labels: Goto-checker, blocker

#3591 Unit test of expr2bits/bits2expr [blocks: #3592]
  unit/util/simplify_expr.cpp
Labels: blocker

#3593 Fix binary value string in XML representation of expressions
  src/util/xml_expr.cpp
  unit/Makefile
  unit/util/xml_expr.cpp
Labels: bugfix

#3594 format_{expr,type}: Beautify array and pointer output
  jbmc/regression/jbmc/simplify-classid-of-interface/test_no_simplify_vccs.desc
  src/util/format_expr.cpp
  src/util/format_type.cpp
Labels: cleanup

#3592 Fix simplify_extractbit and simplify_extractbits
  src/util/simplify_expr_int.cpp
  src/util/std_expr.h
  unit/util/simplify_expr.cpp
Labels: bugfix

#3590 Use string_constantt's API
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  src/analyses/custom_bitvector_analysis.cpp
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/c_storage_spec.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/literals/convert_string_literal.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_static_assert.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_instrumentation.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/solvers/refinement/string_constraint_generator_constants.cpp
  src/solvers/refinement/string_constraint_generator_main.cpp
  src/util/format_constant.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/string_constant.cpp
  src/util/string_constant.h
Labels: cleanup

#3409 Move big-int unit test to unit/ folder and make it a CATCH-style test [blocks: #2452]
  .gitignore
  CMakeLists.txt
  src/big-int/CMakeLists.txt
  src/big-int/bigint-test.cc
  src/big-int/makefile
  src/big-int/number.tst
  unit/Makefile
  unit/big-int/big-int.cpp
  unit/big-int/module_dependencies.txt
  unit/big-int/number.tst
Labels: Tests, blocker

#3342 Refactor show_program [blocks: #2310]
  src/goto-symex/show_program.cpp
Labels: blocker, cleanup

#3595 Make __CPROVER_allocated_memory work with non-POD type objects
  regression/cbmc/union12/main.c
  regression/cbmc/union12/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/analyses/goto_check.cpp
Labels: bugfix

#3366 Add missing member initializers of string_constraintst-typed value [blocks: #2310]
  src/solvers/refinement/string_constraint_generator_main.cpp
  src/solvers/refinement/string_constraint_generator_testing.cpp
  src/solvers/refinement/string_constraint_generator_valueof.cpp
Labels: blocker, bugfix

#2220 Skip phi assignment if one of the merged states has an uninitialised object [blocks: #35, #2574, #3486]
  regression/cbmc-concurrency/thread_local2/main.c
  regression/cbmc-concurrency/thread_local2/test.desc
  regression/cbmc/extern3/main.c
  regression/cbmc/extern3/test.desc
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_goto.cpp
Labels: blocker, bugfix

#3470 irept: use single map for all named sub-nodes
  src/ansi-c/README.md
  src/cpp/cpp_type2name.cpp
  src/util/README.md
  src/util/irep.cpp
  src/util/irep.h
  src/util/irep_hash_container.cpp
  src/util/irep_serialization.cpp
  src/util/json_irep.cpp
  src/util/lispirep.cpp
  src/util/merge_irep.cpp
  src/util/xml_irep.cpp
  unit/util/irep.cpp
Labels: enhancement

#3606 irept-related fixes [blocks: #2035]
  src/util/format_expr.cpp
  src/util/irep_hash_container.cpp
  src/util/merge_irep.cpp
Labels: blocker, bugfix

#3588 Improve solver factory
  src/goto-checker/solver_factory.cpp
  src/goto-checker/solver_factory.h
Labels: cleanup

#3608 Add missing virtual destructor [blocks: #2310]
  src/goto-diff/goto_diff.h
Labels: blocker, bugfix

#3609 Follow-up: Remove non-reference const in declarations [blocks: #2310]
  src/cbmc/symex_bmc.cpp
  src/cbmc/symex_bmc.h
  src/goto-symex/symex_function_call.cpp
Labels: blocker, cleanup

#3613 Remove unused local variables or fix code to use them [blocks: #2310]
  jbmc/unit/java_bytecode/goto_program_generics/mutually_recursive_generics.cpp
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_invoke_dynamic.cpp
  jbmc/unit/solvers/refinement/string_constraint_instantiation/instantiate_not_contains.cpp
  src/goto-programs/goto_inline_class.cpp
  unit/util/range.cpp
Labels: blocker, bugfix

#3611 Add standard file headers
  unit/util/expr_cast/expr_cast.cpp
  unit/util/expr_cast/expr_undefined_casts.cpp
  unit/util/string_utils/split_string.cpp
  unit/util/string_utils/strip_string.cpp
  unit/util/symbol.cpp
Labels: cleanup

#3612 Use CATCH's REQUIRE_THROWS_AS [blocks: #2310]
  unit/goto-programs/goto_model_function_type_consistency.cpp
  unit/goto-programs/goto_program_assume.cpp
  unit/goto-programs/goto_program_dead.cpp
  unit/goto-programs/goto_program_declaration.cpp
  unit/goto-programs/goto_program_function_call.cpp
  unit/goto-programs/goto_program_goto_target.cpp
  unit/goto-programs/goto_program_symbol_type_table_consistency.cpp
  unit/goto-programs/goto_program_table_consistency.cpp
  unit/goto-symex/ssa_equation.cpp
Labels: Tests, blocker, cleanup

#3617 Actually use the parameter of set_is_stub [blocks: #2310]
  jbmc/src/java_bytecode/java_types.h
Labels: blocker, bugfix

#3621 goto_symex: use ranged for
  src/goto-symex/goto_symex_state.cpp
Labels: cleanup

#3622 use ec2 ubuntu mirror
  buildspec.yml
Labels: Build

#3635 remove ID_class type
  src/goto-symex/goto_symex_state.cpp
Labels: cleanup

#3587 Use rvalue constructor when building a concatenation_exprt
  src/solvers/floatbv/float_bv.cpp
  src/solvers/lowering/byte_operators.cpp
  src/solvers/smt2/smt2_parser.cpp
Labels: cleanup

#3632 Fix type mismatch between value at call site and declaration [blocks: #2310]
  unit/solvers/refinement/string_constraint_generator_valueof/calculate_max_string_length.cpp
Labels: blocker, bugfix

#3615 Remove names of unused parameters [blocks: #2310]
  src/solvers/smt2/smt2_solver.cpp
Labels: blocker, cleanup

#3644 type2name cleanup
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/type2name.cpp
  src/ansi-c/type2name.h
Labels: C Front End, cleanup

#3638 smt2 backend: member operator for non-byte offsets
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#3624 Mark failing tests KNOWNBUG [blocks: #2310, #3627]
  jbmc/regression/jbmc-concurrency/anonymous-java.lang.thread/test.desc
  jbmc/regression/jbmc-concurrency/anonymous-java.lang.thread/test2.desc
  jbmc/regression/jbmc-concurrency/explicit-thread-blocks/test.desc
  jbmc/regression/jbmc-concurrency/explicit-thread-blocks/test2.desc
  jbmc/regression/jbmc-concurrency/get-current-thread/test.desc
  jbmc/regression/jbmc-concurrency/get-current-thread/test4.desc
  jbmc/regression/jbmc-concurrency/get-current-thread/test5.desc
  jbmc/regression/jbmc-concurrency/get-current-thread/test6.desc
  jbmc/regression/jbmc-concurrency/java-lang-runnable/test.desc
  jbmc/regression/jbmc-concurrency/java-lang-runnable/test2.desc
  jbmc/regression/jbmc-concurrency/java-lang-runnable/test3.desc
  jbmc/regression/jbmc-concurrency/java-lang-runnable/test4.desc
  jbmc/regression/jbmc-concurrency/java-lang-thread/test.desc
  jbmc/regression/jbmc-concurrency/java-lang-thread/test2.desc
  jbmc/regression/jbmc-concurrency/java-lang-thread/test3.desc
  jbmc/regression/jbmc-concurrency/java-lang-thread/test4.desc
  jbmc/regression/jbmc-concurrency/several-threads/test.desc
  jbmc/regression/jbmc-concurrency/several-threads/test2.desc
  jbmc/regression/jbmc-concurrency/several-threads/test3.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks/test1.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks/test2.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks/test3.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks/test_sync.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks/test_sync_baseline.desc
  jbmc/regression/jbmc-concurrency/synchronized-method-illegal-state/test.desc
  jbmc/regression/jbmc-concurrency/synchronized-methods/test1.desc
  jbmc/regression/jbmc-concurrency/synchronized-methods/test2.desc
  jbmc/regression/jbmc-concurrency/synchronized-methods/test3.desc
  jbmc/regression/jbmc-concurrency/synchronized-methods/test_sync.desc
  jbmc/regression/jbmc-concurrency/synchronized-methods/test_sync_baseline.desc
  jbmc/regression/jbmc-concurrency/synchronized/test.desc
  jbmc/regression/jbmc/static_init1/test1.desc
  jbmc/regression/jbmc/static_init2/test1.desc
  jbmc/regression/jbmc/static_init_order/test3.desc
  jbmc/regression/jbmc/static_init_order/test4.desc
  regression/ansi-c/const1/const-array.desc
  regression/ansi-c/const1/const-member.desc
  regression/ansi-c/cprover_bool1/test.desc
Labels: Tests, blocker

#3646 SMT2: convert struct_tag and union_tag types
  src/solvers/smt2/smt2_conv.cpp
Labels: enhancement
