Repository diffblue/cbmc, pull requests merged in 2018-09, with the labels that each got.

#2838 remove unused 'init' statement
  src/analyses/invariant_set.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/goto-programs/goto_convert.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivrns.cpp
  src/util/irep_ids.def
Labels: cleanup

#2840 two additional checks on array subtypes
  src/ansi-c/c_typecheck_type.cpp
Labels: C Front End, enhancement

#2868 smt2_dec now uses run() instead of system()
  src/solvers/smt2/smt2_dec.cpp
  src/solvers/smt2/smt2_dec.h
Labels: cleanup

#2878 smt2_dect now uses temporary_filet
  src/solvers/smt2/smt2_dec.cpp
  src/solvers/smt2/smt2_dec.h
Labels: cleanup

#2718 Central implementation of syntactic equality of instructions and goto programs
  jbmc/src/jdiff/java_syntactic_diff.cpp
  src/goto-diff/syntactic_diff.cpp
  src/goto-diff/unified_diff.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_program.h
Labels: cleanup

#2873 Make explicit that the Lal-Reps sequentialization is incomplete
  src/goto-instrument/concurrency.cpp
Labels: cleanup

#2418 stack_depth takes a signed int as argument
  regression/goto-instrument/stack-depth1/fails.desc
  regression/goto-instrument/stack-depth1/main.c
  regression/goto-instrument/stack-depth1/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/stack_depth.cpp
  src/goto-instrument/stack_depth.h
Labels: bugfix

#2870 split up remove_function_pointerst::remove_function_pointer
  src/goto-programs/remove_function_pointers.cpp
Labels: cleanup

#2791 Briefly document interval analysis
  src/analyses/README.md
  src/analyses/interval_analysis.cpp
Labels: documentation

#2860 remove unused member_exprt::symbol()
  jbmc/unit/java-testing-utils/require_goto_statements.cpp
  jbmc/unit/java-testing-utils/require_goto_statements.h
  jbmc/unit/java_bytecode/goto_program_generics/generic_bases_test.cpp
  jbmc/unit/java_bytecode/goto_program_generics/generic_parameters_test.cpp
  jbmc/unit/java_bytecode/goto_program_generics/mutually_recursive_generics.cpp
  src/util/std_expr.h
Labels: cleanup

#2854 added a test for the precision of the value sets on unions
  regression/cbmc/union10/union_list2.c
  regression/cbmc/union10/union_list2.desc
Labels: Tests, bug

#2703 Cleanup error handling of cbmc/ folder
  src/cbmc/bmc.cpp
  src/cbmc/bmc_cover.cpp
  src/cbmc/cbmc_main.cpp
  src/cbmc/cbmc_solvers.cpp
  src/cbmc/cbmc_solvers.h
  src/cbmc/fault_localization.cpp
  src/cbmc/symex_coverage.cpp
  src/util/Makefile
  src/util/exception_utils.cpp
  src/util/exception_utils.h
  src/util/parse_options.cpp
Labels: Do not merge

#2850 Use CL version to determine target
  regression/goto-cl/version/main.c
  regression/goto-cl/version/version.desc
  src/goto-cc/Makefile
  src/goto-cc/ms_cl_mode.cpp
  src/goto-cc/ms_cl_version.cpp
  src/goto-cc/ms_cl_version.h
Labels: C Front End, enhancement

#2894 linker: non-recursive version of get_symbols
  src/linking/remove_internal_symbols.cpp
Labels: enhancement

#2893 only do bitvector analysis when used
  src/analyses/goto_check.cpp
Labels: enhancement

#2204 remove lhs_object from goto_trace_stept
  regression/cbmc/trace-values/trace-values.c
  regression/cbmc/trace-values/trace-values.desc
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/json_goto_trace.cpp
  src/goto-programs/vcd_goto_trace.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/goto-symex/build_goto_trace.cpp
Labels: cleanup

#2802 DOC-43: Documentation of GOTO model (de)serialisation.
  src/goto-programs/README.md
  src/util/README.md
Labels: documentation

#2901 Unit tests: use null_message_handler from testing utils
  unit/analyses/ai/ai.cpp
  unit/analyses/constant_propagator.cpp
  unit/path_strategies.cpp
Labels: cleanup

#2900 Makefiles: Add missing dependency tracking for smt2_solver
  src/solvers/Makefile
Labels: Build, bugfix

#2903 update Solaris instructions
  COMPILING.md
Labels: documentation

#2697 Introduce union tag type
  src/ansi-c/c_typecheck_type.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_type.cpp
  src/goto-symex/goto_symex_state.cpp
Labels: C Front End, cleanup

#2915 rewrite_union no longer needs namespace
  src/cpp/cpp_typecheck_compound_type.cpp
  src/goto-symex/rewrite_union.cpp
  src/goto-symex/rewrite_union.h
Labels: cleanup

#2924 Test for memcpy with struct pointers
  regression/cbmc/memcpy-struct-ptr/main.c
  regression/cbmc/memcpy-struct-ptr/test.desc
Labels: Tests

#2943 remove dereference checks during symex
  src/goto-symex/symex_dereference_state.cpp
  src/goto-symex/symex_dereference_state.h
  src/pointer-analysis/dereference_callback.h
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_dereference.h
Labels: Symbolic Execution, cleanup

#2947 Add brief documentation of overlay classes
  jbmc/regression/jbmc/overlay-class/annotations/org/cprover/IgnoredMethodImplementation.class
  jbmc/regression/jbmc/overlay-class/annotations/org/cprover/IgnoredMethodImplementation.java
  jbmc/regression/jbmc/overlay-class/annotations/org/cprover/OverlayClassImplementation.java
  jbmc/regression/jbmc/overlay-class/annotations/org/cprover/OverlayMethodImplementation.java
  jbmc/regression/jbmc/overlay-class/ignored-method/Test.class
  jbmc/regression/jbmc/overlay-class/ignored-method/Test.java
  jbmc/regression/jbmc/overlay-class/ignored-test.desc
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_class_loader.cpp
Labels: documentation

#2965 new interface for read_goto_binary()
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/read_goto_binary.cpp
  src/goto-programs/read_goto_binary.h
Labels: C Front End, cleanup

#2823 Add typet and symbol_typet documentation to util README [DOC-12]
  src/util/README.md
Labels: documentation

#2820 Correct incomplete_array_typet [DOC-12]
  src/util/std_types.h
Labels: bugfix

#2821 Deprecate nil_typet [DOC-12]
  src/util/std_types.h
Labels: cleanup

#2877 unit test Makefiles: add missing source files
  CMakeLists.txt
  jbmc/regression/jbmc-generics/Makefile
  jbmc/regression/strings-smoke-tests/Makefile
  jbmc/unit/Makefile
  jbmc/unit/java_bytecode/expr2java.cpp
  src/ansi-c/Makefile
  src/cpp/Makefile
  src/util/format_expr.cpp
  unit/.gitignore
  unit/CMakeLists.txt
  unit/Makefile
  unit/catch_example.cpp
  unit/miniBDD.cpp
  unit/solvers/miniBDD/miniBDD.cpp
  unit/solvers/miniBDD/module_dependencies.txt
Labels: Build, bugfix

#2982 Do not use outdated *-mod.gb file
  regression/contracts/chain.sh
  regression/goto-instrument/chain.sh
Labels: Tests, bugfix

#2986 Workaround for Google Cloud SDK packaging problem
  .travis.yml
Labels: Build, bugfix

#2959 Cleanup error handling in solvers/miniBDD
  src/solvers/miniBDD/miniBDD.cpp
  src/solvers/miniBDD/miniBDD.inc
Labels: Needs rebase

#2988 Improve typing in cpp_typecheckt::reference_binding
  src/cpp/cpp_typecheck_conversions.cpp
Labels: C++ Front End, cleanup

#2966 ranged for over components and parameters
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/expr2c.cpp
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_destructor.cpp
  src/cpp/cpp_is_pod.cpp
  src/cpp/cpp_typecheck_bases.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/expr2cpp.cpp
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/boolbv_member.cpp
  src/solvers/flattening/boolbv_update.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/util/endianness_map.cpp
  src/util/expr_initializer.cpp
  src/util/find_symbols.cpp
  src/util/pointer_offset_size.cpp
  src/util/rename_symbol.cpp
  src/util/replace_symbol.cpp
  src/util/std_types.cpp
Labels: cleanup

#2989 Restrict signature of prop_conv_solvert::literal to only supported type
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/prop/prop_conv.cpp
  src/solvers/prop/prop_conv.h
Labels: cleanup

#2200 Fix replace_symbolt for non-lvalues
  src/util/replace_symbol.cpp
  unit/util/replace_symbol.cpp
Labels: bugfix

#2928 fix for const-ness of array members
  regression/ansi-c/const1/array-of-const.c
  regression/ansi-c/const1/array-of-const.desc
  regression/ansi-c/const1/const-array.c
  regression/ansi-c/const1/const-array.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, bugfix

#2927 fix for const-nesss of member expressions
  regression/ansi-c/const1/const-field.c
  regression/ansi-c/const1/const-field.desc
  regression/ansi-c/const1/const-member.c
  regression/ansi-c/const1/const-member.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, bugfix

#2994 move to C++ tests from regression/cbmc to regression/cbmc-cpp
  regression/cbmc-cpp/cpp1/main.cpp
  regression/cbmc-cpp/cpp1/test.desc
  regression/cbmc-cpp/cpp2/main.cpp
  regression/cbmc-cpp/cpp2/test.desc
Labels: Tests, cleanup

#2993 Fix enum compound assignments
  regression/cbmc/enum6/test.desc
  src/goto-programs/goto_convert_side_effect.cpp
  src/util/simplify_expr_floatbv.cpp
Labels: bugfix

#2990 Doc/goto program methods
  src/goto-programs/goto_program.h
Labels: documentation

#2992 remove optiont to store subtypes in a named sub-irep
  src/util/type.h
Labels: cleanup

#2980 goto-cc no longer uses language_uit
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
  src/goto-cc/linker_script_merge.cpp
  src/goto-cc/linker_script_merge.h
  src/goto-programs/initialize_goto_model.cpp
  src/util/cout_message.h
Labels: cleanup

#2991 cleanup accesses to subtype() and subtypes()
  src/util/mathematical_types.h
  src/util/type.h
Labels: cleanup

#2926 Use struct tags
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/goto-instrument/dump_c.cpp
  src/util/expr_initializer.cpp
  src/util/std_types.cpp
Labels: C Front End

#2434 Do not artificially separate message handler and uit
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jdiff/java_syntactic_diff.h
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/unit/solvers/refinement/string_constraint_instantiation/instantiate_not_contains.cpp
  src/cbmc/all_properties.cpp
  src/cbmc/bmc.cpp
  src/cbmc/bmc.h
  src/cbmc/bmc_cover.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_solvers.cpp
  src/cbmc/cbmc_solvers.h
  src/cbmc/fault_localization.cpp
  src/goto-diff/goto_diff.h
  src/goto-diff/goto_diff_base.cpp
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-diff/syntactic_diff.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/class_hierarchy.cpp
  src/goto-programs/class_hierarchy.h
  src/goto-programs/show_symbol_table.cpp
  src/goto-symex/show_vcc.cpp
  src/goto-symex/show_vcc.h
  src/solvers/refinement/bv_refinement.h
  src/solvers/refinement/bv_refinement_loop.cpp
  src/solvers/refinement/string_refinement_util.h
  src/util/message.h
  src/util/ui_message.cpp
  src/util/ui_message.h
  unit/analyses/ai/ai_simplify_lhs.cpp
  unit/path_strategies.cpp
Labels: cleanup

#2998 format(type) additions
  src/util/format_type.cpp
Labels: enhancement

#3010 constant_exprt constructor
  src/goto-cc/linker_script_merge.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/pointer_logic.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/arith_tools.cpp
  src/util/bv_arithmetic.cpp
  src/util/fixedbv.cpp
  src/util/ieee_float.cpp
  src/util/json_expr.cpp
  src/util/rational_tools.cpp
  src/util/simplify_expr_int.cpp
  src/util/std_expr.h
  src/util/xml_expr.cpp
Labels: cleanup

#3016 API change: from_integer for negative naturals
  src/util/arith_tools.cpp
Labels: cleanup

#3017 nullary and ternary expressions
  src/ansi-c/ansi_c_declaration.h
  src/solvers/smt2/smt2_conv.h
  src/util/byte_operators.h
  src/util/std_expr.h
  src/util/string_constant.cpp
  src/util/string_constant.h
Labels: cleanup

#2851 better precision of value_set on unions
  regression/cbmc/union11/union_list.c
  regression/cbmc/union11/union_list.desc
  src/pointer-analysis/value_set.cpp
  src/util/simplify_expr_struct.cpp
Labels: enhancement

#3024 remove symbol_type support from C front-end
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/padding.cpp
Labels: cleanup

#2806 First draft of background concepts section.
  doc/architectural/background-concepts.md
Labels: documentation

#3028 Move contents of goto_program_template.cpp to goto_program.cpp
  src/goto-programs/Makefile
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_program_template.cpp
Labels: cleanup

#3023 forall/exists take a Boolean as second operand
  regression/cbmc/Quantifiers1/main.c
  src/ansi-c/c_typecheck_expr.cpp
Labels: bugfix

#2979 check for side effects in quantifiers
  regression/cbmc/Quantifiers1/quantifier-with-side-effect.c
  regression/cbmc/Quantifiers1/quantifier-with-side-effect.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/goto_clean_expr.cpp
Labels: bugfix

#3015 Console colors
  src/cbmc/all_properties.cpp
  src/cbmc/bmc.cpp
  src/goto-analyzer/static_verifier.cpp
  src/util/cout_message.cpp
  src/util/cout_message.h
  src/util/message.h
  src/util/ui_message.cpp
  src/util/ui_message.h
Labels: enhancement

#3056 Revert "Workaround for Google Cloud SDK packaging problem"
  .travis.yml
Labels: Build, cleanup

#3061 bugfix: missing eom
  src/solvers/flattening/boolbv_with.cpp
Labels: bugfix

#2997 better location for compound members
  regression/ansi-c/Incomplete_Type1/incomplete_component.c
  regression/ansi-c/Incomplete_Type1/incomplete_component.desc
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/parser.y
Labels: C Front End, enhancement

#3063 cpp_scopet::lookup methods now return an id set
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_instantiate_template.cpp
  src/cpp/cpp_scope.cpp
  src/cpp/cpp_scope.h
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_template.cpp
  src/cpp/cpp_typecheck_using.cpp
Labels: C++ Front End, cleanup

#3066 C++ front-end: use ranged for
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_id.cpp
  src/cpp/cpp_instantiate_template.cpp
  src/cpp/cpp_language.cpp
  src/cpp/cpp_scope.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_fargs.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/template_map.cpp
Labels: C++ Front End, cleanup

#2137 use optional for unknown pointer offset sizes
  src/analyses/goto_rw.cpp
  src/analyses/reaching_definitions.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/padding.cpp
  src/ansi-c/type2name.cpp
  src/goto-instrument/alignment_checks.cpp
  src/goto-instrument/count_eloc.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/goto-programs/vcd_goto_trace.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_goto.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_index.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/flatten_byte_operators.cpp
  src/solvers/flattening/pointer_logic.cpp
  src/solvers/lowering/popcount.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/endianness_map.cpp
  src/util/expr_initializer.cpp
  src/util/pointer_offset_size.cpp
  src/util/pointer_offset_size.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
Labels: cleanup
