Repository diffblue/cbmc, pull requests merged in 2018-07, with the labels that each got.

#2496 unzip is needed on Debian, plus say how to build jbmc on Windows
  COMPILING.md
Labels: Build, documentation

#2471 Do not unnecessarily mark local variables static
  jbmc/src/java_bytecode/expr2java.h
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
  jbmc/src/java_bytecode/load_method_by_regex.cpp
Labels: cleanup

#2490 Evaluate expressions that delimit GCC switch/case ranges
  regression/cbmc/gcc_switch_case_range2/main.c
  regression/cbmc/gcc_switch_case_range2/test.desc
  src/ansi-c/c_typecheck_code.cpp
Labels: C Front End, bugfix

#2513 Regression test clean target and test.pl fix
  jbmc/regression/jbmc-strings/Makefile
  jbmc/regression/jbmc/Makefile
  regression/cbmc/Makefile
  regression/goto-gcc/Makefile
  regression/invariants/Makefile
  regression/test.pl
Labels: Build, bugfix, cleanup

#2500 move version.h to util/
  CMakeLists.txt
  jbmc/src/janalyzer/CMakeLists.txt
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/jbmc/CMakeLists.txt
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jdiff/CMakeLists.txt
  jbmc/src/jdiff/jdiff_parse_options.cpp
  src/cbmc/CMakeLists.txt
  src/cbmc/Makefile
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_solvers.cpp
  src/clobber/CMakeLists.txt
  src/clobber/clobber_parse_options.cpp
  src/common
  src/goto-analyzer/CMakeLists.txt
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-cc/CMakeLists.txt
  src/goto-cc/Makefile
  src/goto-cc/as_mode.cpp
  src/goto-cc/compile.cpp
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/goto_cc_mode.cpp
  src/goto-diff/CMakeLists.txt
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-instrument/CMakeLists.txt
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/memory-models/CMakeLists.txt
  src/memory-models/mmcc_parse_options.cpp
  src/util/CMakeLists.txt
  src/util/Makefile
Labels: Build

#2493 [TG-3694] Parse and store inner class information
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_parse_tree.h
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/unit/Makefile
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsAnonymousClass$1.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsAnonymousClass$2.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsAnonymousClass$3.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsAnonymousClass$4.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsAnonymousClass$InnerInterface.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsAnonymousClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsLocalClass$1LocalClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/ContainsLocalClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClasses$DefaultInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClasses$PrivateInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClasses$ProtectedInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClasses$PublicInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClasses.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClasses.java
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDeeplyNested$SinglyNestedClass$DefaultDoublyNestedInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDeeplyNested$SinglyNestedClass$PrivateDoublyNestedInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDeeplyNested$SinglyNestedClass$ProtectedDoublyNestedInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDeeplyNested$SinglyNestedClass$PublicDoublyNestedInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDeeplyNested$SinglyNestedClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDeeplyNested.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDefault$DefaultInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDefault$PrivateInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDefault$ProtectedInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDefault$PublicInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/InnerClassesDefault.class
  jbmc/unit/java_bytecode/java_bytecode_parser/parse_java_attributes.cpp
  src/util/irep_ids.def
Labels: In progress

#2383 Set BUILD_ENV via make variable instead of patching via sed
  appveyor.yml
  buildspec-windows.yml
Labels: cleanup

#2443 Remove unused parameter from rDeclarator
  src/cpp/parse.cpp
Labels: C++ Front End, cleanup

#2449 Clean up unused template instantiation symbols
  regression/cpp/Decltype3/test.desc
  regression/cpp/Template_Instantiation4/test.desc
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck.h
Labels: C++ Front End, bugfix

#2517 Captures static inner class information
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_parse_tree.h
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$1.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$1LocalClassInNonStatic.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$1LocalClassInStatic.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$2.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$PublicNonStaticInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$PublicStaticInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass$SomeInterface.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass.class
  jbmc/unit/java_bytecode/java_bytecode_parser/StaticInnerClass.java
  jbmc/unit/java_bytecode/java_bytecode_parser/parse_java_attributes.cpp
Labels: Do not merge

#2532 Regression test should succeed even if char is an unsigned type
  regression/cbmc-cover/branch3/main.c
Labels: Build, bugfix

#2538 Use to_ulong instead of the deprecated integer2ulong
  src/util/mp_arith.cpp
Labels: cleanup

#2530 Fix tests that are only correct on little-endian architectures
  regression/cbmc/byte_update2/test.desc
  regression/cbmc/byte_update3/test.desc
  regression/cbmc/byte_update4/test.desc
  regression/cbmc/byte_update5/test.desc
  regression/cbmc/byte_update6/test.desc
  regression/cbmc/byte_update7/test.desc
  regression/cbmc/byte_update8/test.desc
Labels: Build, bugfix

#2544 Remove unused parameter from value_set_fivrt::flatten_rec
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivr.h
Labels: cleanup

#2464 Remove unused parameters message_handler, ns
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/static_show_domain.cpp
  src/goto-analyzer/static_show_domain.h
  src/goto-analyzer/unreachable_instructions.cpp
  src/goto-analyzer/unreachable_instructions.h
Labels: cleanup

#2440 Remove unused parameter from list_calls_and_arguments
  src/goto-instrument/call_sequences.cpp
Labels: cleanup

#2439 Remove unused and inconsistent pointer_object_has_type
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/solvers/smt2/smt2_conv.cpp
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: bugfix, cleanup

#2448 Fix delayed method body conversion for templates
  regression/cpp/Function_Overloading2/main.cpp
  regression/cpp/Function_Overloading2/test.desc
  regression/cpp/Template_Instantiation5/test.desc
  regression/systemc/BitvectorSc1/test.desc
  regression/systemc/BitvectorSc2/test.desc
  regression/systemc/EqualOp1/test.desc
  regression/systemc/EqualOp2/test.desc
  regression/systemc/EqualOp3/test.desc
  regression/systemc/FunTempl1/test.desc
  regression/systemc/SimpleSc1/test.desc
  regression/systemc/Template1/test.desc
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_instantiate_template.cpp
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_declaration.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_method_bodies.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_resolve.h
Labels: C++ Front End, bugfix

#2450 Name resolution may require further template instantiation
  regression/cpp/Template_Instantiation3/test.desc
  regression/systemc/Array3/test.desc
  src/cpp/cpp_typecheck_resolve.cpp
Labels: C++ Front End, bugfix

#2550 Use type-consistent unsigned value for unreachable return statement
  src/goto-cc/goto_cc_cmdline.cpp
Labels: cleanup

#2420 Fix invariant: value must be strictly positive
  src/solvers/refinement/string_constraint_generator_format.cpp
Labels: bugfix

#2533 utf8 to utf16 conversion must use native endianness
  jbmc/src/java_bytecode/java_string_literals.cpp
  src/util/unicode.h
Labels: Java Front End, bugfix

#2535 Use architecture-specific compiler flags to configure bit width during preprocessing
  src/ansi-c/c_preprocess.cpp
Labels: C Front End, bugfix

#2539 Mark integer constants as unsigned when lhs is unsigned
  jbmc/src/java_bytecode/java_utils.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/literals/unescape_string.cpp
  src/goto-cc/gcc_mode.cpp
  src/solvers/refinement/string_constraint_generator_testing.cpp
  src/util/simplify_expr.cpp
  src/util/unicode.cpp
Labels: cleanup

#2531 Fix copy&paste error in C library
  src/ansi-c/library/inet.c
Labels: C Front End, bugfix

#2553 Partial revert of #1898 (always_inline support, second attempt)
  regression/ansi-c/always_inline1/test.desc
  regression/ansi-c/always_inline2/main.c
  regression/ansi-c/always_inline2/test.desc
  regression/ansi-c/always_inline3/main.c
  regression/ansi-c/always_inline3/test.desc
  regression/ansi-c/always_inline4/main.c
  regression/ansi-c/always_inline4/test.desc
  regression/ansi-c/always_inline5/main.c
  regression/ansi-c/always_inline5/test.desc
  regression/ansi-c/always_inline6/main.c
  regression/ansi-c/always_inline6/test.desc
  regression/ansi-c/always_inline7/main.c
  regression/ansi-c/always_inline7/test.desc
  regression/ansi-c/always_inline8/main.c
  regression/ansi-c/always_inline8/test.desc
  regression/ansi-c/always_inline9/main.c
  regression/ansi-c/always_inline9/test.desc
  regression/cbmc/always_inline1/main.c
  regression/cbmc/always_inline1/test.desc
  regression/cbmc/always_inline2/main.c
  regression/cbmc/always_inline2/test.desc
  regression/cbmc/always_inline3/main.c
  regression/cbmc/always_inline3/test.desc
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/ansi_c_declaration.cpp
  src/ansi-c/ansi_c_declaration.h
  src/ansi-c/c_storage_spec.cpp
  src/ansi-c/c_storage_spec.h
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
  src/util/irep_ids.def
  src/util/replace_symbol.cpp
Labels: C Front End, bug, bugfix

#2425 Add missing virtual destructor
  src/goto-instrument/rw_set.h
  src/pointer-analysis/value_set.h
  src/util/endianness_map.h
Labels: bugfix

#2435 Change index variable name, simplify code
  src/goto-programs/goto_convert.cpp
Labels: cleanup

#2429 Set little_endian in the same way that boolbv_byte_extract already does
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_byte_update.cpp
  src/solvers/flattening/flatten_byte_operators.cpp
Labels: cleanup

#2542 String refinement: remove unused parameters
  src/solvers/refinement/string_builtin_function.h
  src/solvers/refinement/string_constraint_generator.h
  src/solvers/refinement/string_constraint_generator_insert.cpp
  src/solvers/refinement/string_constraint_generator_valueof.cpp
  src/solvers/refinement/string_refinement.cpp
  src/solvers/refinement/string_refinement.h
Labels: String solver, cleanup

#2565 Cleanup of float_bvt
  src/solvers/floatbv/float_bv.h
Labels: cleanup

#2563 Remove unused interface
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.h
  src/goto-instrument/accelerate/enumerating_loop_acceleration.h
  src/goto-instrument/accelerate/loop_acceleration.h
  src/goto-instrument/accelerate/polynomial_accelerator.h
  src/goto-instrument/accelerate/sat_path_enumerator.h
Labels: cleanup

#2460 Visual Studio: silence warnings about local variables assigned-but-not-used
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
Labels: Java Front End, cleanup

#2567 Fix MCDC coverage instrumentation
  regression/cbmc-cover/built-ins7/test.desc
  regression/cbmc-cover/mcdc1/test.desc
  regression/cbmc-cover/mcdc10/test.desc
  regression/cbmc-cover/mcdc11/test.desc
  regression/cbmc-cover/mcdc12/test.desc
  regression/cbmc-cover/mcdc13/test.desc
  regression/cbmc-cover/mcdc14/test.desc
  regression/cbmc-cover/mcdc2/test.desc
  regression/cbmc-cover/mcdc3/test.desc
  regression/cbmc-cover/mcdc4/test.desc
  regression/cbmc-cover/mcdc5/test.desc
  regression/cbmc-cover/mcdc6/test.desc
  regression/cbmc-cover/mcdc7/test.desc
  regression/cbmc-cover/mcdc8/test.desc
  regression/cbmc-cover/mcdc9/test.desc
  src/goto-instrument/cover_instrument_mcdc.cpp
Labels: bugfix

#2568 Document proposed best practice for unused parameters
  CODING_STANDARD.md
Labels: documentation

#2541 Use std::string(N, ' ') instead of static locals
  src/solvers/refinement/string_refinement.cpp
Labels: String solver, cleanup

#2566 (interval_)sparse_arrayt: Remove unnecessary use of "virtual" and further cleanup
  src/solvers/refinement/string_refinement.cpp
  src/solvers/refinement/string_refinement_util.cpp
  src/solvers/refinement/string_refinement_util.h
  unit/solvers/refinement/string_refinement/sparse_array.cpp
Labels: String solver, cleanup

#2564 Cleanup java_bytecode_parse_treet: all members are public, no virtual tables required
  jbmc/src/java_bytecode/java_bytecode_parse_tree.h
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
  jbmc/src/java_bytecode/java_bytecode_parser.h
Labels: Do not merge, Java Front End, cleanup

#2560 Support Visual Studio's __forceinline
  regression/ansi-c/forceinline1/main.i
  regression/ansi-c/forceinline1/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
  src/cpp/parse.cpp
Labels: C Front End, bugfix

#2528 goto-gcc: run original compiler even when output is /dev/null
  regression/goto-gcc/dev_null1/main.c
  regression/goto-gcc/dev_null1/test.desc
  src/goto-cc/gcc_mode.cpp
Labels: bugfix

#2495 the jbmc tests now work on Windows
  appveyor.yml
  buildspec-windows.yml
  jbmc/regression/jbmc-cover/generics/test.desc
Labels: Build, Do not merge

#2546 goto-instrument/wmm: Use int for bit vector of Booleans
  src/goto-instrument/wmm/abstract_event.h
Labels: cleanup

#2545 Avoid unncessary signed/unsigned conversion
  src/goto-instrument/accelerate/polynomial.cpp
Labels: cleanup

#2507 Leave typecasts on variables on stack
  jbmc/regression/jbmc/stack_var12/stack_typecast.class
  jbmc/regression/jbmc/stack_var12/stack_typecast.j
  jbmc/regression/jbmc/stack_var12/test.desc
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
Labels: Do not merge

#2590 Use irep id defs for all #comments
  src/ansi-c/c_typecheck_expr.cpp
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_declaration.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_fargs.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_dereference_state.cpp
  src/pointer-analysis/goto_program_dereference.cpp
  src/solvers/flattening/pointer_logic.cpp
  src/util/irep_ids.def
Labels: cleanup

#2543 Explicit unsigned -> uint16_t casts to avoid conversion warnings
  jbmc/src/java_bytecode/expr2java.cpp
  jbmc/src/java_bytecode/java_string_literals.cpp
  src/ansi-c/literals/convert_string_literal.cpp
  src/ansi-c/literals/unescape_string.cpp
  src/ansi-c/scanner.l
  src/solvers/refinement/string_constraint_generator_format.cpp
  src/util/file_util.cpp
  src/util/unicode.cpp
  src/util/unicode.h
  unit/CMakeLists.txt
  unit/Makefile
  unit/util/unicode.cpp
Labels: cleanup

#2497 avoid non-termination of simplify_exprt::simplify_byte_extract(array_of(...))
  jbmc/regression/jbmc/simplify_expr_termination/test.class
  jbmc/regression/jbmc/simplify_expr_termination/test.desc
  jbmc/regression/jbmc/simplify_expr_termination/test.java
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_struct.cpp
Labels: bugfix

#2491 mark various 'partial constructors' as deprecated
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-programs/remove_function_pointers.cpp
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#2621 instructions for Amazon Linux
  COMPILING.md
Labels: Build, documentation

#2529 Do not (unnecessarily) require preprocessing for fixed 32/64 bit regression tests
  .travis.yml
  regression/cbmc/Float24/main.i
  regression/cbmc/Float24/test.desc
  regression/cbmc/Malloc15/main.i
  regression/cbmc/Malloc15/test.desc
  regression/cbmc/Malloc16/main.i
  regression/cbmc/Malloc16/test.desc
  regression/cbmc/Pointer_Arithmetic12/main.i
  regression/cbmc/Pointer_Arithmetic12/test.desc
  regression/cbmc/Pointer_array4/main.i
  regression/cbmc/Pointer_array4/test.desc
  regression/cbmc/Pointer_byte_extract5/main.i
  regression/cbmc/Pointer_byte_extract5/no-simplify.desc
  regression/cbmc/Pointer_byte_extract5/test.desc
  regression/cbmc/Pointer_byte_extract8/main.i
  regression/cbmc/Pointer_byte_extract8/test.desc
  regression/cbmc/Struct_Padding1/main.i
  regression/cbmc/Struct_Padding1/test.desc
  regression/cbmc/Visual_Studio_Types1/main.c
  regression/cbmc/Visual_Studio_Types1/main.i
  regression/cbmc/Visual_Studio_Types1/test.desc
  regression/cbmc/Visual_Studio_Types2/main.c
  regression/cbmc/Visual_Studio_Types2/main.i
  regression/cbmc/Visual_Studio_Types2/test.desc
  regression/cbmc/address_space_size_limit2/test.desc
  regression/cbmc/address_space_size_limit2/test.i
  regression/cbmc/address_space_size_limit3/main.i
  regression/cbmc/address_space_size_limit3/test.desc
Labels: Build, cleanup

#2627 remove bitvector and bitvector_u rules
  src/ansi-c/scanner.l
Labels: C Front End, cleanup

#2606 two further Visual Studio CL options
  src/goto-cc/ms_cl_cmdline.cpp
Labels: C Front End

#2423 Convert to signed type to make negation meaningful
  src/solvers/floatbv/float_approximation.cpp
  unit/CMakeLists.txt
  unit/Makefile
  unit/float_utils.cpp
  unit/solvers/floatbv/float_utils.cpp
  unit/solvers/floatbv/module_dependencies.txt
Labels: bugfix

#2630 fix flattening of ID_invalid_pointer
  regression/cbmc/Malloc23/test.desc
  regression/cbmc/bounds_check1/test.desc
  regression/cbmc/memcpy1/test.desc
  regression/cbmc/memory_allocation1/test.desc
  src/analyses/goto_check.cpp
  src/solvers/flattening/bv_pointers.cpp
Labels: Solvers, bugfix

#2608 added support for _int64 keyword
  regression/ansi-c/VS_extensions1/main.c
  src/ansi-c/scanner.l
Labels: C Front End, enhancement

#2628 ansi-c: clang extensions
  regression/ansi-c/gcc_float_types1/main.c
  regression/ansi-c/gcc_float_types1/test.desc
  src/ansi-c/ansi_c_declaration.cpp
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/gcc_builtin_headers_ia32.h
  src/ansi-c/get-gcc-builtins.sh
  src/ansi-c/scanner.l
  src/cpp/cpp_convert_type.cpp
  src/cpp/cpp_internal_additions.cpp
  src/cpp/parse.cpp
  src/goto-cc/gcc_mode.cpp
  src/util/config.cpp
  src/util/config.h
Labels: C Front End, bugfix

#2602 __CPROVER_r_ok and __CPROVER_w_ok preconditions
  doc/cbmc-user-manual.md
  regression/cbmc/memcpy1/test.desc
  regression/cbmc/memset1/test.desc
  regression/cbmc/memset3/test.desc
  src/analyses/goto_check.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/expr2c.cpp
  src/ansi-c/library/cprover.h
  src/ansi-c/library/string.c
  src/util/irep_ids.def
Labels: C Front End, enhancement
