Repository diffblue/cbmc, pull requests merged in 2018-04, with the labels that each got.

#1990 [SV-COMP'18 1/19] Include missing header
  src/memory-models/mm2cpp.cpp
Labels: bugfix

#2015 smt2_solver.{o,d} should be removed by "make clean"
  src/common
  src/solvers/Makefile
Labels: bugfix

#2085 Use from_{expr,type} matching the language of the expression/type
  src/analyses/constant_propagator.cpp
  src/analyses/goto_check.cpp
  src/analyses/goto_rw.cpp
  src/analyses/invariant_set.cpp
  src/analyses/local_may_alias.cpp
  src/cbmc/bmc.cpp
  src/cbmc/show_vcc.cpp
  src/goto-cc/compile.cpp
  src/goto-instrument/cover_instrument_condition.cpp
  src/goto-instrument/cover_instrument_decision.cpp
  src/goto-instrument/cover_instrument_mcdc.cpp
  src/goto-instrument/cover_instrument_other.cpp
  src/goto-instrument/dot.cpp
  src/goto-instrument/rw_set.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/goto-symex/slice_by_trace.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_target_equation.cpp
  src/pointer-analysis/dereference.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivrns.cpp
  unit/java_bytecode/java_object_factory/gen_nondet_string_init.cpp
  unit/java_bytecode/java_string_library_preprocess/convert_exprt_to_string_exprt.cpp
  unit/miniBDD.cpp
  unit/solvers/refinement/string_constraint_instantiation/instantiate_not_contains.cpp
Labels: cleanup

#1244 goto-gcc: Add @<file> arguments to the original command line
  regression/goto-gcc/at_files/args
  regression/goto-gcc/at_files/main.c
  regression/goto-gcc/at_files/other.c
  regression/goto-gcc/at_files/test.desc
  src/goto-cc/gcc_cmdline.cpp
  src/goto-cc/gcc_cmdline.h
Labels: bugfix

#2003 [SV-COMP'18 14/19] Fixing member offset computation in presence of bitfields.
  regression/cbmc/Bitfields3/main.c
  regression/cbmc/Bitfields3/test.desc
  src/ansi-c/padding.cpp
  src/util/pointer_offset_size.cpp
Labels: C Front End, bugfix

#1988 Add support for CaDiCaL
  scripts/cadical-patch
  src/Makefile
  src/common
  src/config.inc
  src/solvers/Makefile
  src/solvers/sat/satcheck.h
  src/solvers/sat/satcheck_cadical.cpp
  src/solvers/sat/satcheck_cadical.h
Labels: Solvers

#2114 Ensure consistent type renaming of heap objects of dynamic size
  regression/cbmc-concurrency/malloc2/main.c
  regression/cbmc-concurrency/malloc2/test.desc
  src/ansi-c/c_typecheck_type.cpp
  src/goto-symex/symex_builtin_functions.cpp
Labels: bugfix

#2073 Reset namespace after symbolic execution
  src/goto-symex/symex_main.cpp
Labels: bugfix

#2136 remove two unused hooks in bmct
  src/cbmc/bmc.cpp
  src/cbmc/bmc.h
Labels: cleanup

#2135 remove support for SMT1
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_solvers.cpp
  src/cbmc/cbmc_solvers.h
  src/solvers/Makefile
  src/solvers/smt1/smt1_conv.cpp
  src/solvers/smt1/smt1_conv.h
  src/solvers/smt1/smt1_dec.cpp
  src/solvers/smt1/smt1_dec.h
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
  src/solvers/smt2/smt2_dec.cpp
Labels: cleanup
