Repository diffblue/cbmc, pull requests merged in 2018-11, with the labels that each got.

#3253 Do not use exprt::move_to_operands as it is marked as deprecated
  src/util/expr.cpp
Labels: cleanup

#3269 results now include line number
  jbmc/regression/jbmc/catch1/test.desc
  jbmc/regression/jbmc/temp_stack_variable_packing/test.desc
  regression/cbmc/Array_operations1/test.desc
  regression/cbmc/Function5/test.desc
  regression/cbmc/Multi_Dimensional_Array6/test.desc
  regression/cbmc/Multiple_Properties1/test.desc
  regression/cbmc/Overflow_Addition1/test.desc
  regression/cbmc/Overflow_Leftshift1/test.desc
  regression/cbmc/Quantifiers-assertion/test.desc
  regression/cbmc/Quantifiers-assignment/test.desc
  regression/cbmc/Quantifiers-copy/test.desc
  regression/cbmc/Quantifiers-if/test.desc
  regression/cbmc/Quantifiers-initialisation/test.desc
  regression/cbmc/Quantifiers-initialisation2/test.desc
  regression/cbmc/Quantifiers-not-exists/test.desc
  regression/cbmc/Quantifiers-not/test.desc
  regression/cbmc/Quantifiers-two-dimension-array/test.desc
  regression/cbmc/Quantifiers-type/test.desc
  regression/cbmc/Undefined_Shift1/test.desc
  regression/cbmc/fgets1/test.desc
  regression/cbmc/gcc_bswap1/test.desc
  regression/cbmc/goto4/test.desc
  regression/cbmc/memcpy1/test.desc
  regression/cbmc/memory_allocation1/test.desc
  regression/cbmc/memset1/test.desc
  regression/cbmc/memset3/test.desc
  regression/cbmc/pipe1/test.desc
  regression/cbmc/pointer-extra-checks/test.desc
  regression/cbmc/read1/test.desc
  regression/cbmc/return2/test.desc
  regression/cbmc/strcat1/test.desc
  regression/contracts/function_check_04/test.desc
  regression/contracts/invar_check_04/test.desc
  regression/goto-instrument/generate-function-body-assert-false-assume-false/test.desc
  regression/goto-instrument/generate-function-body-assert-false/test.desc
  regression/goto-instrument/generate-function-body-complex-struct/test.desc
  regression/goto-instrument/generate-function-body-const-pointer-to-non-const/test.desc
  regression/goto-instrument/generate-function-body-havoc-globals/test.desc
  regression/goto-instrument/generate-function-body-havoc-params/test.desc
  regression/goto-instrument/generate-function-body-pointer-to-pointer-to-const/test.desc
  regression/goto-instrument/generate-function-body-struct-with-const-member/test.desc
  regression/goto-instrument/generate-function-body-union-with-const-member/test.desc
  regression/goto-instrument/generate-function-body/test.desc
  src/cbmc/all_properties.cpp
Labels: enhancement

#3266 Use add_to_operands
  src/util/expr_initializer.cpp
  src/util/guard.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_int.cpp
  src/util/std_code.h
  src/util/std_expr.h
  src/util/string_expr.h
Labels: cleanup

#3233 SMT2 backend testing
  .travis.yml
  buildspec.yml
  regression/cbmc/Makefile
  scripts/delete_failing_smt2_solver_tests
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/cbmc/cbmc_solvers.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
  src/solvers/smt2/smt2_dec.cpp
Labels: SMT Backend Interface

#3270 coding guidelines: prefer using instead of typedef
  CODING_STANDARD.md
Labels: documentation

#3107 Bitvectors are now hexadecimal
  regression/invariants/invariant-irep-diagnostic/test.desc
  src/solvers/flattening/boolbv_constant.cpp
  src/util/arith_tools.cpp
Labels: enhancement

#3272 Spell out review-within-two-weeks rule for Code Owners
  CODEOWNERS
Labels: documentation

#3275 Return converted code by value for consistency
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
Labels: cleanup

#3264 avoid direct access to exprt::opX
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/symex_dead.cpp
  src/goto-symex/symex_decl.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_goto.cpp
  src/util/config.cpp
  src/util/expr_util.cpp
  src/util/json_expr.cpp
  src/util/ssa_expr.cpp
  src/util/std_code.cpp
Labels: cleanup

#3273 Use typecast_exprt::conditional_cast
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  src/pointer-analysis/pointer_offset_sum.cpp
  src/solvers/flattening/functions.cpp
Labels: cleanup

#3259 Allocate nondet char array
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  jbmc/unit/java_bytecode/java_object_factory/gen_nondet_string_init.cpp
Labels: bugfix

#3236 added cond_exprt
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_cond.cpp
  src/util/std_expr.h
Labels: cleanup

#3267 Type the operand of code_declt
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  src/analyses/constant_propagator.cpp
  src/analyses/locals.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_util.cpp
  src/cpp/cpp_util.h
  src/goto-diff/change_impact.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.h
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/full_slicer.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-symex/symex_decl.cpp
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#3242 refactoring: factor out analysis in goto-analyzer
  src/goto-analyzer/static_verifier.cpp
Labels: Static Analyses, cleanup

#3265 code_deadt operand is now typed
  jbmc/src/java_bytecode/remove_exceptions.cpp
  src/analyses/constant_propagator.cpp
  src/analyses/reaching_definitions.cpp
  src/goto-diff/change_impact.cpp
  src/goto-instrument/full_slicer.cpp
  src/goto-symex/symex_dead.cpp
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#3279 Simplify and modernise array-is-uniform code
  regression/cbmc/uniform_array1/main.c
  regression/cbmc/uniform_array1/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/solvers/flattening/boolbv_index.cpp
Labels: cleanup

#3158 Clean out opensmt
  src/cbmc/cbmc_parse_options.h
Labels: SMT Backend Interface, Solvers, enhancement

#3277 C front-end: cleanup label statement type checking
  regression/cbmc/nested_label1/main.c
  regression/cbmc/nested_label1/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/ansi-c/c_typecheck_code.cpp
Labels: C Front End, cleanup

#2494 Remove dead code: byte_extract_(big|little)_endian
  src/util/byte_operators.h
Labels: cleanup

#3278 Replace uses of codet::move by codet::add(std::move(...)) [blocks: #2310]
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  jbmc/src/java_bytecode/java_entry_point.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_static_initializers.cpp
  jbmc/src/java_bytecode/remove_java_new.cpp
  src/ansi-c/ansi_c_entry_point.cpp
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/cpp/cpp_constructor.cpp
  src/util/nondet.cpp
  src/util/std_code.h
Labels: blocker, cleanup

#3276 introduce 'called_function' into goto traces [blocks: #3126]
  regression/cbmc/trace_show_function_calls/test.desc
  src/cbmc/symex_bmc.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/json_goto_trace.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/show_program.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: blocker, cleanup

#3290 Move flatten_byte_* to lowering [blocks: #2068, #2501]
  src/solvers/Makefile
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_equality.cpp
  src/solvers/flattening/flatten_byte_operators.h
  src/solvers/lowering/byte_operators.cpp
  src/solvers/lowering/expr_lowering.h
  src/solvers/lowering/flatten_byte_extract_exceptions.h
  src/solvers/smt2/smt2_conv.cpp
Labels: blocker, cleanup

#3284 smt2 bit vector fix [blocks: any PR adding CBMC tests]
  .travis.yml
  buildspec.yml
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_conv.cpp
Labels: blocker, bugfix

#3194 goto traces now show pretty function names
  jbmc/regression/jbmc/NullPointer1/test.desc
  jbmc/regression/jbmc/NullPointer2/test.desc
  jbmc/regression/jbmc/NullPointer4/test.desc
  src/goto-programs/goto_trace.cpp
Labels: enhancement

#3295 Exclude doc/cprover-manual from Doxygen input [blocks: #3258]
  src/doxyfile
Labels: blocker

#3245 Move Travis jobs using clang 6.0 to clang 7
  .travis.yml
Labels: Build

#3051 Use numeric_cast_v<std::size_t> instead of deprecated integer2size_t [blocks: #2310]
  src/analyses/goto_rw.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/padding.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/goto-programs/remove_const_function_pointers.cpp
  src/goto-programs/remove_vector.cpp
  src/goto-programs/vcd_goto_trace.cpp
  src/solvers/flattening/boolbv_byte_update.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/boolbv_index.cpp
  src/solvers/flattening/boolbv_shift.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/lowering/byte_operators.cpp
  src/solvers/lowering/popcount.cpp
  src/solvers/qbf/qbf_qube_core.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/endianness_map.cpp
  src/util/ieee_float.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_floatbv.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_struct.cpp
Labels: blocker

#3289 Add source locations to compound blocks
  src/goto-instrument/goto_program2code.cpp
  src/goto-instrument/goto_program2code.h
  unit/Makefile
  unit/compound_block_locations.cpp
  unit/compound_block_locations.h
  unit/module_dependencies.txt
Labels: Needs rebase

#3288 simplify the remove_exceptions API
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/java_bytecode/remove_exceptions.cpp
  jbmc/src/java_bytecode/remove_exceptions.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.cpp
Labels: cleanup

#3123 Skeleton for well-formedness checking of goto models [blocks: #3118, #3147, #3188, #3191, #3187, #3193]
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-programs/goto_function.h
  src/goto-programs/goto_functions.h
  src/goto-programs/goto_model.h
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_program.h
  src/goto-programs/initialize_goto_model.cpp
  src/util/Makefile
  src/util/exception_utils.cpp
  src/util/exception_utils.h
  src/util/expr.h
  src/util/std_code.h
  src/util/std_expr.h
  src/util/std_types.h
  src/util/symbol_table.h
  src/util/type.h
  src/util/validate.h
  src/util/validate_code.cpp
  src/util/validate_code.h
  src/util/validate_expressions.cpp
  src/util/validate_expressions.h
  src/util/validate_helpers.h
  src/util/validate_types.cpp
  src/util/validate_types.h
  src/util/validation_interface.h
  src/util/validation_mode.h
Labels: blocker

#3305 to_bitvector_type must not be used on enum types
  regression/cbmc/enum7/main.c
  regression/cbmc/enum7/test.desc
  src/util/simplify_expr.cpp
Labels: bugfix

#3308 show-properties: do not skip functions marked for inlining
  regression/cbmc/show_properties1/main.c
  regression/cbmc/show_properties1/test.desc
  src/goto-programs/show_properties.cpp
Labels: bugfix

#3286 Use irept instead of symbol_exprt in java_lambda_method_handlest [blocks: #2310]
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/unit/java-testing-utils/require_type.cpp
Labels: blocker, bugfix, cleanup

#3316 Rename result to result_expr to avoid shadowing [blocks: #2310]
  src/util/simplify_expr_array.cpp
Labels: blocker, cleanup

#3315 Remove repeated declaration [blocks: #2310]
  src/util/simplify_expr.cpp
Labels: blocker, cleanup

#3314 show_vcc no longer requires a namespace [blocks: #2310]
  src/cbmc/bmc.cpp
  src/goto-symex/show_vcc.cpp
  src/goto-symex/show_vcc.h
Labels: blocker, cleanup

#3312 Do not shadow local variables solvers, pc [blocks: #2310]
  unit/path_strategies.cpp
Labels: blocker, cleanup

#3311 Do not shadow local variable type [blocks: #2310]
  src/util/simplify_expr_pointer.cpp
Labels: blocker, cleanup

#3310 Remove unused left-hand side e2 [blocks: #2310]
  unit/util/irep.cpp
Labels: blocker, cleanup

#3317 Remove unused parameter message_handler from static_lifetime_init [blocks: #2310]
  src/ansi-c/ansi_c_entry_point.cpp
  src/linking/static_lifetime_init.cpp
  src/linking/static_lifetime_init.h
Labels: blocker, cleanup

#3318 Remove stray backslash [blocks: #2310]
  unit/analyses/ai/ai_simplify_lhs.cpp
Labels: blocker, cleanup

#3309 Escape backslash in string representing Windows path [blocks: #2310]
  unit/util/file_util.cpp
Labels: blocker, bugfix

#3313 Avoid warning about result_fd being possibly uninitialized [blocks: #2310]
  src/util/run.cpp
Labels: blocker

#3322 Renamed shadowing call_graph_from_goto_functions [blocks: #2310]
  unit/analyses/call_graph.cpp
Labels: blocker, cleanup

#3324 Rename shadowing variable line [blocks: #2310]
  src/util/cout_message.cpp
Labels: blocker, cleanup

#3323 Rename parameter hiding class member [blocks: #2310]
  src/util/xml.cpp
  src/util/xml.h
Labels: blocker, cleanup

#3325 Do not shadow local variable l [blocks: #2310]
  src/util/expr.cpp
Labels: blocker, cleanup

#3326 Do not use arbitrarily bounded integer types [blocks: #2310]
  scripts/expected_doxygen_warnings.txt
  src/util/nondet.cpp
  src/util/nondet.h
Labels: blocker

#3333 Add missing virtual destructor [blocks: #2310]
  src/util/invariant.h
Labels: blocker, bugfix

#3335 Cleanup file_util.cpp
  src/util/file_util.cpp
Labels: cleanup

#3334 Rename shadowing local "mode" to gcc_attr_mode [blocks: #2310]
  src/ansi-c/c_typecheck_type.cpp
Labels: blocker, cleanup

#3328 Do not shadow s, symbol [blocks: #2310]
  src/linking/remove_internal_symbols.cpp
Labels: blocker, cleanup

#3327 Rename mstream parameter to avoid shadowing [blocks: #2310]
  src/util/message.cpp
Labels: blocker, cleanup

#3331 Rename parameters of div_and_round [blocks: #2310]
  src/util/ieee_float.cpp
  src/util/ieee_float.h
Labels: blocker, cleanup

#3330 Remove unused parameters from reaching definitions transformers [blocks: #2310]
  src/analyses/reaching_definitions.cpp
  src/analyses/reaching_definitions.h
Labels: blocker, cleanup

#3320 Do not shadow local variables in symbol_table test [blocks: #2310]
  unit/util/symbol_table.cpp
Labels: blocker, cleanup

#3343 Do not repeatedly define "value" [blocks: #2310]
  src/ansi-c/expr2c.cpp
Labels: blocker, cleanup

#3341 show_goto_stack_trace: remove unused parameter and make static [blocks: #2310]
  src/goto-programs/goto_trace.cpp
Labels: blocker, cleanup

#3340 Do not shadow size variable [blocks: #2310]
  src/goto-symex/symex_builtin_functions.cpp
Labels: blocker, cleanup

#2470 Silence warnings about unused parameters [blocks: #2310]
  jbmc/src/java_bytecode/character_refine_preprocess.cpp
  jbmc/src/java_bytecode/java_bytecode_concurrency_instrumentation.cpp
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_bytecode_typecheck.cpp
  jbmc/src/java_bytecode/java_enum_static_init_unwind_handler.cpp
  jbmc/src/java_bytecode/java_local_variable_table.cpp
  jbmc/src/java_bytecode/select_pointer_type.cpp
  src/analyses/ai_domain.h
  src/analyses/constant_propagator.cpp
  src/analyses/local_may_alias.cpp
  src/analyses/uncaught_exceptions_analysis.cpp
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-cc/hybrid_binary.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/accelerate/scratch_program.cpp
  src/goto-instrument/cover_basic_blocks.h
  src/goto-instrument/cover_filter.cpp
  src/goto-instrument/full_slicer_class.h
  src/goto-instrument/rw_set.h
  src/goto-instrument/wmm/data_dp.cpp
  src/goto-instrument/wmm/instrumenter_strategies.cpp
  src/goto-instrument/wmm/shared_buffers.cpp
  src/goto-programs/osx_fat_reader.cpp
  src/langapi/language.cpp
  src/langapi/language.h
  src/pointer-analysis/value_set.h
  src/util/memory_info.cpp
  src/util/signal_catcher.cpp
  src/util/tempdir.cpp
  src/util/timestamper.cpp
Labels: blocker, cleanup

#3349 Do not shadow "it" [blocks: #2310]
  src/analyses/goto_check.cpp
Labels: blocker, cleanup

#3355 Do not shadow parameter "lhs"
  src/goto-programs/builtin_functions.cpp
Labels: blocker, cleanup

#3367 Explicitly compare to zero to avoid Visual Studio warning [blocks: #2310]
  src/util/small_shared_two_way_ptr.h
Labels: blocker, cleanup

#3363 Use Boolean operators compute xor, or, and over bool [blocks: #2310]
  src/util/mp_arith.cpp
  src/util/simplify_expr_int.cpp
Labels: blocker, cleanup

#3361 Do not shadow source_location [blocks: #2310]
  src/ansi-c/c_typecheck_type.cpp
Labels: blocker, cleanup

#3360 Do not shadow "type" function parameter [blocks: #2310]
  src/ansi-c/c_typecheck_type.cpp
Labels: blocker, cleanup

#3358 Do not shadow the class member return_type [blocks: #2310]
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_type.cpp
Labels: blocker, cleanup

#3348 Do not shadow "code" local variable [blocks: #2310]
  src/analyses/reaching_definitions.cpp
Labels: blocker, cleanup

#3354 Avoid shadowing in custom bitvector analysis [blocks: #2310]
  src/analyses/custom_bitvector_analysis.cpp
Labels: blocker, cleanup

#3351 Value sets: avoid shadowing [blocks: #2310]
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fivr.cpp
Labels: blocker, cleanup

#3346 Remove unused parameter address_map [blocks: #2310]
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
Labels: blocker, cleanup

#3356 Do not shadow raw_ptr, use_count
  src/util/sharing_map.h
Labels: blocker, cleanup

#3347 Avoid shadowing in escape analysis [blocks: #2310]
  src/analyses/escape_analysis.cpp
Labels: blocker, cleanup

#3345 Remove duplicate definition of "root_object" [blocks: #2310]
  src/pointer-analysis/value_set_dereference.cpp
Labels: blocker, cleanup

#3337 Remove unused parameter tmp_var_type from save_stack_entries [blocks: #2310]
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
Labels: blocker, cleanup

#3336 fix a run() variant on non-Windows OSs [blocks: #2310]
  src/util/run.cpp
  src/util/run.h
Labels: blocker, bugfix

#3350 Rename non-descriptive class member t to current_target [blocks: #2310]
  src/analyses/goto_check.cpp
Labels: blocker, cleanup

#3369 jsil: replace err_location by error().source_location
  src/jsil/jsil_typecheck.cpp
Labels: cleanup

#3370 cpp: replace err_location by error().source_location
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_initializer.cpp
Labels: cleanup

#3375 Do not shadow "i" multiple times [blocks: #2310]
  src/goto-programs/read_bin_goto_object.cpp
Labels: blocker, cleanup

#3368 Remove unused parameter array_component_element_type_name [blocks: #2310]
  jbmc/unit/java-testing-utils/load_java_class.cpp
  jbmc/unit/java-testing-utils/require_goto_statements.cpp
  jbmc/unit/java-testing-utils/require_goto_statements.h
  jbmc/unit/java_bytecode/goto_program_generics/generic_parameters_test.cpp
Labels: blocker, cleanup

#3352 Do not shadow the "result" variable and fix one use of it [blocks: #2310]
  unit/util/symbol_table.cpp
Labels: blocker, bugfix

#3379 Inline single use of compute_address_taken_in_symbols [blocks: #2310]
  src/goto-programs/remove_function_pointers.cpp
Labels: blocker, cleanup

#3376 Do not shadow parameter is_virtual [blocks: #2310]
  src/cpp/cpp_typecheck_bases.cpp
Labels: blocker, cleanup

#3372 Do not shadow class member "symbol_table" [blocks: #2310]
  src/goto-programs/lazy_goto_model.cpp
Labels: blocker, cleanup

#3377 Do not shadow "resolved" [blocks: #2310]
  src/goto-programs/remove_const_function_pointers.cpp
Labels: blocker, cleanup

#3378 Make messaget a member [blocks: #2310]
  src/goto-programs/remove_function_pointers.cpp
Labels: blocker, cleanup

#3373 Avoid implicit conversion to bool and actually use return value [blocks: #2310]
  src/goto-programs/osx_fat_reader.cpp
  src/goto-programs/read_goto_binary.cpp
Labels: blocker, bugfix

#2794 Adds summary for remove_exceptions [DOC-84]
  jbmc/src/java_bytecode/README.md
Labels: documentation

#3374 Avoid shadowing "symbol" [blocks: #2310]
  src/cpp/cpp_typecheck.cpp
Labels: blocker, cleanup

#3394 Fix Doxygen warnings in goto-programs/ folder
  scripts/expected_doxygen_warnings.txt
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_model.h
  src/goto-programs/goto_program.h
  src/goto-programs/goto_trace.cpp
  src/goto-programs/rebuild_goto_start_function.cpp
  src/goto-programs/resolve_inherited_component.cpp
Labels: documentation

#3365 Remove symbol generator from add_axioms_for_* that do not use it
  src/solvers/README.md
  src/solvers/refinement/string_constraint_generator.h
  src/solvers/refinement/string_constraint_generator_code_points.cpp
  src/solvers/refinement/string_constraint_generator_concat.cpp
  src/solvers/refinement/string_constraint_generator_constants.cpp
  src/solvers/refinement/string_constraint_generator_float.cpp
  src/solvers/refinement/string_constraint_generator_main.cpp
Labels: blocker, cleanup

#3362 Avoid default no-ops, force derived classes to override [blocks: #2310]
  src/util/cout_message.h
  src/util/message.h
Labels: blocker, cleanup

#3408 Add author information to big-int implementation file [blocks: #2452]
  src/big-int/bigint-func.cc
Labels: blocker, bugfix

#3338 Avoid shadowing index_expr and fix type cast [blocks: #2310]
  src/pointer-analysis/value_set.cpp
Labels: blocker, bugfix

#3410 remove typecheckt::err_location(...)
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/util/typecheck.h
Labels: C Front End, cleanup

#3398 Small expansion to analyses/README.md
  src/analyses/README.md
Labels: documentation

#3400 Briefly document escape analysis
  src/analyses/README.md
Labels: documentation

#3364 String refinement: Remove generator parameter where unused [blocks: #2310]
  scripts/expected_doxygen_warnings.txt
  src/solvers/README.md
  src/solvers/refinement/string_builtin_function.cpp
  src/solvers/refinement/string_constraint_generator.h
  src/solvers/refinement/string_constraint_generator_float.cpp
  src/solvers/refinement/string_constraint_generator_format.cpp
  src/solvers/refinement/string_constraint_generator_insert.cpp
  src/solvers/refinement/string_constraint_generator_main.cpp
  src/solvers/refinement/string_constraint_generator_valueof.cpp
  src/solvers/refinement/string_refinement.cpp
Labels: blocker, cleanup

#3412 Replace assert by DATA_INVARIANT [blocks: #2548]
  src/goto-analyzer/taint_analysis.cpp
Labels: blocker, cleanup

#3402 [DOC-127] Doc/compilation and development
  doc/architectural/compilation-and-development.md
Labels: documentation

#3386 Add documentation to `lazy_goto_modelt`
  src/goto-programs/lazy_goto_model.cpp
  src/goto-programs/lazy_goto_model.h
  src/langapi/language.h
Labels: documentation

#3385 Document namespace and symbol table files.
  src/util/namespace.cpp
  src/util/namespace.h
  src/util/symbol.cpp
  src/util/symbol.h
  src/util/symbol_table.cpp
  src/util/symbol_table.h
  src/util/symbol_table_base.cpp
  src/util/symbol_table_base.h
Labels: documentation

#3419 Remove unnecessary assertion about using 0-size objects
  regression/cbmc/void_pointer4/main.c
  regression/cbmc/void_pointer4/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/util/std_expr.cpp
Labels: bugfix

#3416 Avoid shadowing of variables (several instances, part 2) [blocks: #2310]
  src/cpp/cpp_is_pod.cpp
  src/cpp/cpp_scope.cpp
  src/cpp/cpp_scope.h
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_enum_type.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_template.cpp
  src/cpp/parse.cpp
  src/goto-programs/goto_inline_class.cpp
Labels: blocker, cleanup

#3411 Disable clang-format for imported miniz code [blocks: #2548]
  jbmc/src/miniz/miniz.cpp
Labels: blocker, cleanup

#3424 Silence #if/#elif warnings originating from Windows header files [blocks: #2310]
  src/util/run.cpp
Labels: blocker, cleanup

#3389 Fix Doxygen warnings in ansi-c/ folder
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/expr2c.cpp
Labels: documentation

#3382 Document pointer type selection interface [DOC-113]
  jbmc/src/java_bytecode/README.md
  jbmc/src/java_bytecode/select_pointer_type.cpp
  jbmc/src/java_bytecode/select_pointer_type.h
  scripts/expected_doxygen_warnings.txt
Labels: documentation

#3387 Initial overview for class messaget.
  src/util/message.h
Labels: documentation

#3391 Document generics substitution [DOC-114]
  jbmc/src/java_bytecode/README.md
  jbmc/src/java_bytecode/select_pointer_type.cpp
Labels: documentation

#3397 Add documentation for global-may-alias analysis.
  src/analyses/README.md
  src/analyses/global_may_alias.cpp
  src/analyses/global_may_alias.h
Labels: documentation

#3401 Briefly document dominator analysis
  src/analyses/README.md
Labels: documentation

#3406 Documentation: overview of java concurrency instrumentation
  jbmc/src/java_bytecode/README.md
Labels: documentation

#3404 Add JBMC user manual [DOC-9]
  doc/cprover-manual/jbmc-user-manual.md
Labels: documentation

#3215 Show abstract states in program source code
  regression/goto-analyzer/show-on-source/main.c
  regression/goto-analyzer/show-on-source/main.desc
  src/goto-analyzer/Makefile
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-analyzer/show_on_source.cpp
  src/goto-analyzer/show_on_source.h
Labels: Static Analyses, enhancement

#3298 Online user manual fixes
  doc/cprover-manual/binsearch.c
  doc/cprover-manual/cbmc-tutorial.md
  doc/cprover-manual/file1.c
  doc/cprover-manual/index.md
  doc/cprover-manual/installation.md
  doc/cprover-manual/lock-example.c
  doc/cprover-manual/properties.md
Labels: documentation

#3405 Document remove asm
  src/goto-programs/remove_asm.cpp
  src/goto-programs/remove_asm.h
Labels: documentation

#3396 [Documentation] The BMC algorithm.
  doc/architectural/background-concepts.md
Labels: documentation

#3392 Basic placeholder information about cprover printing.
  src/util/README.md
Labels: documentation

#3440 smt2_solver: SMT2-specific message output
  regression/smt2_solver/function-applications/function-application2.desc
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_solver.cpp
Labels: bugfix

#3460 SMT2-backend fix: constants
  scripts/delete_failing_smt2_solver_tests
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#3251 Recursive nondet init of pointers to structs [blocks: #3443]
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/convert_java_nondet.cpp
  jbmc/src/java_bytecode/convert_java_nondet.h
  jbmc/src/java_bytecode/java_bytecode_language.h
  jbmc/src/java_bytecode/java_entry_point.cpp
  jbmc/src/java_bytecode/java_entry_point.h
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_object_factory.h
  jbmc/src/java_bytecode/java_object_factory_parameters.cpp
  jbmc/src/java_bytecode/java_object_factory_parameters.h
  jbmc/src/java_bytecode/java_static_initializers.cpp
  jbmc/src/java_bytecode/java_static_initializers.h
  jbmc/src/java_bytecode/simple_method_stubbing.cpp
  jbmc/src/java_bytecode/simple_method_stubbing.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  jbmc/unit/java_bytecode/java_object_factory/gen_nondet_string_init.cpp
  jbmc/unit/java_bytecode/java_replace_nondet/replace_nondet.cpp
  regression/cbmc/pointer-function-parameters-struct-mutual-recursion/main.c
  regression/cbmc/pointer-function-parameters-struct-mutual-recursion/test.desc
  regression/cbmc/pointer-function-parameters-struct-non-recursive/main.c
  regression/cbmc/pointer-function-parameters-struct-non-recursive/test.desc
  regression/cbmc/pointer-function-parameters-struct-simple-recursion-2/main.c
  regression/cbmc/pointer-function-parameters-struct-simple-recursion-2/test.desc
  regression/cbmc/pointer-function-parameters-struct-simple-recursion-3/main.c
  regression/cbmc/pointer-function-parameters-struct-simple-recursion-3/test.desc
  regression/cbmc/pointer-function-parameters-struct-simple-recursion/main.c
  regression/cbmc/pointer-function-parameters-struct-simple-recursion/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/ansi-c/Makefile
  src/ansi-c/ansi_c_entry_point.cpp
  src/ansi-c/ansi_c_entry_point.h
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/ansi_c_language.h
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/ansi-c/c_nondet_symbol_factory.h
  src/ansi-c/c_object_factory_parameters.cpp
  src/ansi-c/c_object_factory_parameters.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/cpp/cpp_language.cpp
  src/cpp/cpp_language.h
  src/goto-cc/compile.cpp
  src/goto-programs/initialize_goto_model.cpp
  src/langapi/language_file.cpp
  src/util/Makefile
  src/util/nondet_bool.h
  src/util/object_factory_parameters.cpp
  src/util/object_factory_parameters.h
Labels: blocker

#3461 SMT2 solver: implement get-value
  scripts/delete_failing_smt2_solver_tests
  src/solvers/Makefile
  src/solvers/smt2/smt2_format.cpp
  src/solvers/smt2/smt2_format.h
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
  src/solvers/smt2/smt2_solver.cpp
Labels: enhancement

#3476 smt2_solver: use smt2_format instead of .pretty()
  src/solvers/smt2/smt2_solver.cpp
Labels: enhancement

#3458 added --compact-trace option [blocks: #3459]
  regression/cbmc/compact-trace/main.c
  regression/cbmc/compact-trace/test.desc
  scripts/delete_failing_smt2_solver_tests
  src/cbmc/cbmc_parse_options.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
Labels: blocker, enhancement

#2786 Document remove_virtual_functions [DOC-85]
  src/goto-programs/remove_virtual_functions.cpp
  src/goto-programs/remove_virtual_functions.h
Labels: documentation
