Repository diffblue/cbmc, pull requests merged in 2018-03, with the labels that each got.

#1892 remove OPERANDS_IN_GETSUB define, which is now simply the only option
  src/util/expr.h
  src/util/irep_ids.def
Labels: cleanup

#1800 Fix process_array_expr to take into account pointer offset
  regression/cbmc-from-CVS/Array_operations1/main.c
  regression/cbmc/Array_operations1/main.c
  regression/cbmc/Array_operations1/test.desc
  regression/cbmc/memcpy2/main.c
  regression/cbmc/memcpy2/test.desc
  regression/cbmc/memcpy3/main.c
  regression/cbmc/memcpy3/test.desc
  src/goto-programs/builtin_functions.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_other.cpp
  src/pointer-analysis/value_set_dereference.cpp
Labels: bugfix

#1888 Linker-script processing fixes
  src/goto-cc/compile.cpp
  src/goto-cc/dist-linux
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-cc/linker_script_merge.h
Labels: bugfix

#1772 Bounds checks in fgets, read
  regression/cbmc/fgets1/test.desc
  regression/cbmc/read1/main.c
  regression/cbmc/read1/test.desc
  src/ansi-c/library/stdio.c
  src/ansi-c/library/unistd.c
Labels: C Front End, bugfix

#1363 test for signature conflict with undeclared function
  regression/cbmc/return6/f_def.c
  regression/cbmc/return6/main.c
  regression/cbmc/return6/test.desc
  src/linking/linking.cpp
Labels: C Front End, bugfix

#1891 remove exprt::negate, sum, mul, subtract (deprecated since 2011)
  src/util/expr.cpp
  src/util/expr.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#1910 on-demand definitions for compiler-built-in functions
  src/ansi-c/CMakeLists.txt
  src/ansi-c/Makefile
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_internal_additions.h
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/builtin_factory.h
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/clang_builtin_headers.h
  src/ansi-c/gcc_builtin_headers_generic.h
  src/ansi-c/gcc_builtin_headers_types.h
  src/cpp/cpp_internal_additions.cpp
Labels: C Front End, enhancement

#1893 Expression printer
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/boolbv_equality.cpp
  src/solvers/prop/bdd_expr.cpp
  src/solvers/qbf/qbf_bdd_core.cpp
  src/solvers/refinement/refine_arrays.cpp
  src/solvers/refinement/string_constraint.h
  src/solvers/refinement/string_refinement.cpp
  src/solvers/smt1/smt1_conv.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/Makefile
  src/util/expr.cpp
  src/util/expr.h
  src/util/format.h
  src/util/format_expr.cpp
  src/util/format_expr.h
  src/util/format_type.cpp
  src/util/format_type.h
  src/util/simplify_expr.cpp
  src/util/type.h
  unit/solvers/refinement/string_constraint_instantiation/instantiate_not_contains.cpp
Labels: cleanup, enhancement

#1926 goto-analyzer (un)reachable-functions: build valid json output
  regression/goto-analyzer/reachable-functions-basic-json/test.desc
  regression/goto-analyzer/unreachable-functions-basic-json/test.desc
  src/goto-analyzer/unreachable_instructions.cpp
Labels: bugfix

#1952 move CPROVER built-in functions into the factory
  src/ansi-c/CMakeLists.txt
  src/ansi-c/Makefile
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_internal_additions.h
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/windows_builtin_headers.h
Labels: C Front End, enhancement
