Repository diffblue/cbmc, pull requests merged in 2019-02, with the labels that each got.

#3796 Stop-on-fail verifier [blocks: 3968]
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/goto-checker/README.md
  src/goto-checker/stop_on_fail_verifier.h
Labels: Goto-checker, blocker

#3968 Add cover goals verifier [blocks: 3969]
  jbmc/unit/Makefile
  regression/cbmc-cover/assertion1/test.desc
  src/cbmc/Makefile
  src/cbmc/c_test_input_generator.cpp
  src/cbmc/c_test_input_generator.h
  src/cbmc/cbmc_parse_options.cpp
  src/goto-checker/Makefile
  src/goto-checker/README.md
  src/goto-checker/cover_goals_report_util.cpp
  src/goto-checker/cover_goals_report_util.h
  src/goto-checker/cover_goals_verifier_with_trace_storage.h
  src/goto-checker/goto_trace_storage.cpp
  src/goto-checker/goto_trace_storage.h
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
  unit/Makefile
Labels: Goto-checker, blocker

#3249 Stop propt inheriting from messaget [blocks: #3800]
  src/goto-checker/solver_factory.cpp
  src/solvers/flattening/arrays.cpp
  src/solvers/prop/prop.h
  src/solvers/qbf/qbf_quantor.cpp
  src/solvers/qbf/qbf_qube.cpp
  src/solvers/qbf/qbf_qube_core.cpp
  src/solvers/qbf/qbf_skizzo.cpp
  src/solvers/sat/dimacs_cnf.cpp
  src/solvers/sat/dimacs_cnf.h
  src/solvers/sat/pbs_dimacs_cnf.cpp
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/sat/satcheck_minisat2.h
  src/solvers/smt2/smt2_solver.cpp
Labels: Solvers, blocker, cleanup

#4006 xml_expr binary fix
  src/goto-programs/xml_expr.cpp
  unit/goto-programs/xml_expr.cpp
Labels: bugfix

#4022 Include tags in type-to-identifier conversion
  regression/ansi-c/anonymous_union1/main.c
  regression/ansi-c/anonymous_union1/test.desc
  src/ansi-c/type2name.cpp
Labels: C Front End, bugfix

#4024 replication_exprt now gets a constant_exprt
  src/util/std_expr.h
Labels: cleanup

#4045 goto-cc: do not restrict parsing from stdin to C source code
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
Labels: bugfix

#4035 irep2name: return std::string by value
  src/cpp/cpp_type2name.cpp
Labels: cleanup

#4032 expr2c: Output the declarator with __int128-typed objects
  src/ansi-c/expr2c.cpp
Labels: C Front End, bugfix

#4052 Cleanup use of messaget in unit tests [blocks: #3800]
  jbmc/unit/solvers/strings/string_refinement/string_symbol_resolution.cpp
  unit/analyses/dependence_graph.cpp
  unit/util/message.cpp
Labels: blocker, cleanup

#4058 remove base_type_eq and type_eq: C/C++ edition
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/cpp/cpp_typecheck_expr.cpp
Labels: C Front End, C++ Front End, cleanup

#4027 move two builds from Travis to codebuild
  .travis.yml
  buildspec-linux-clang.yml
  buildspec-linux-cmake-gcc.yml
Labels: Build

#4060 Simplify index_exprt over vectors [blocks: #2068]
  src/util/simplify_expr_array.cpp
Labels: blocker, enhancement

#4025 use goto_programt::make_X() to create instructions [blocks: #4030]
  src/analyses/flow_insensitive_analysis.cpp
  src/analyses/goto_check.cpp
  src/goto-instrument/havoc_loops.cpp
  src/goto-instrument/loop_utils.cpp
Labels: blocker, cleanup

#4037 invariant set to_string: remove unused second parameter
  src/analyses/invariant_set.cpp
  src/analyses/invariant_set.h
  src/analyses/invariant_set_domain.h
Labels: cleanup

#4034 get_code: return std::string by value
  src/goto-instrument/document_properties.cpp
Labels: cleanup

#4033 value_set*: remove unused second parameter of add_var
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fi.h
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivr.h
  src/pointer-analysis/value_set_fivrns.cpp
  src/pointer-analysis/value_set_fivrns.h
Labels: cleanup

#4040 Remove trivial assertion
  jbmc/src/java_bytecode/java_entry_point.cpp
Labels: Java Front End, cleanup

#4046 character_refine_preprocesst isn't a messaget [blocks: #3800]
  jbmc/src/java_bytecode/character_refine_preprocess.h
Labels: blocker, cleanup

#4059 with_exprt need only have an odd number of operands [blocks: #2068]
  src/util/std_expr.h
Labels: blocker, bugfix

#4017 Store goto_symex::\guard in a single place [blocks: #3619]
  src/goto-symex/auto_objects.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/renaming_level.cpp
  src/goto-symex/symex_goto.cpp
Labels: Symbolic Execution, blocker, cleanup

#4068 simplify_function_application: do not assume that a symbol always has a value
  jbmc/regression/jbmc-strings/StartsWithConstantEvalution/RefineStrings.class
  jbmc/regression/jbmc-strings/StartsWithConstantEvalution/RefineStrings.java
  src/util/simplify_expr.cpp
Labels: bugfix

#4044 Require a message handler when constructing a propt [blocks: #3800]
  jbmc/unit/solvers/strings/string_constraint_instantiation/instantiate_not_contains.cpp
  src/goto-instrument/accelerate/scratch_program.h
  src/solvers/flattening/bv_minimize.h
  src/solvers/prop/prop.h
  src/solvers/qbf/qbf_quantor.cpp
  src/solvers/qbf/qbf_quantor.h
  src/solvers/qbf/qbf_qube.cpp
  src/solvers/qbf/qbf_qube.h
  src/solvers/qbf/qbf_qube_core.cpp
  src/solvers/qbf/qbf_qube_core.h
  src/solvers/qbf/qbf_skizzo.cpp
  src/solvers/qbf/qbf_skizzo.h
  src/solvers/qbf/qdimacs_cnf.h
  src/solvers/qbf/qdimacs_core.h
  src/solvers/refinement/refine_arrays.cpp
  src/solvers/sat/cnf.h
  src/solvers/sat/cnf_clause_list.h
  src/solvers/sat/dimacs_cnf.cpp
  src/solvers/sat/dimacs_cnf.h
  src/solvers/sat/pbs_dimacs_cnf.h
  src/solvers/sat/satcheck_glucose.cpp
  src/solvers/sat/satcheck_glucose.h
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/sat/satcheck_minisat2.h
  src/solvers/strings/string_constraint.cpp
  src/solvers/strings/string_refinement.cpp
  unit/solvers/bdd/miniBDD/miniBDD.cpp
  unit/solvers/floatbv/float_utils.cpp
Labels: blocker, cleanup

#3824 Remove language_uit as it is no longer used
  doc/architectural/code-walkthrough.md
  src/langapi/Makefile
  src/langapi/README.md
  src/langapi/language_ui.cpp
  src/langapi/language_ui.h
  unit/compound_block_locations.cpp
  unit/path_strategies.cpp
Labels: cleanup

#4069 String refinement must not rely on input equations to be simplified
  jbmc/regression/strings-smoke-tests/java_starts_with/test-no-simplify.desc
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_refinement.cpp
Labels: String solver, bugfix

#3969 Single-path symex checker [blocks: #3976]
  jbmc/src/java_bytecode/java_single_path_symex_checker.h
  jbmc/src/java_bytecode/java_single_path_symex_only_checker.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/goto-checker/Makefile
  src/goto-checker/bmc_util.cpp
  src/goto-checker/bmc_util.h
  src/goto-checker/goto_symex_property_decider.cpp
  src/goto-checker/goto_symex_property_decider.h
  src/goto-checker/multi_path_symex_checker.cpp
  src/goto-checker/multi_path_symex_checker.h
  src/goto-checker/multi_path_symex_only_checker.cpp
  src/goto-checker/multi_path_symex_only_checker.h
  src/goto-checker/single_path_symex_checker.cpp
  src/goto-checker/single_path_symex_checker.h
  src/goto-checker/single_path_symex_only_checker.cpp
  src/goto-checker/single_path_symex_only_checker.h
  src/goto-checker/solver_factory.cpp
Labels: Goto-checker, blocker

#4072 simplify_with also applies to vectors
  src/util/simplify_expr.cpp
Labels: enhancement

#4018 Break goto_symex_state into more manageable bits
  src/goto-checker/symex_bmc.cpp
  src/goto-checker/symex_bmc.h
  src/goto-symex/goto_symex.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/postcondition.cpp
  src/goto-symex/precondition.cpp
  src/goto-symex/renaming_level.cpp
  src/goto-symex/renaming_level.h
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_start_thread.cpp
Labels: Symbolic Execution, cleanup

#4074 Fix use of binary irep in smt2_conv
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
Labels: SMT Backend Interface, bugfix

#4086 Move forgotten line that documents cbmc version
  src/goto-programs/README.md
Labels: documentation

#3976 Run CBMC regression tests with --paths lifo in CI
  .travis.yml
  buildspec-windows.yml
  buildspec.yml
  regression/cbmc/CMakeLists.txt
  regression/cbmc/Failing_Assert1/test.desc
  regression/cbmc/Makefile
  regression/cbmc/Multi_Dimensional_Array6/test.desc
  regression/cbmc/address_space_size_limit1/test.desc
  regression/cbmc/array-tests/test.desc
Labels: Tests

#4087 Document partial_order_concurrency [DOC-140]
  src/goto-symex/README.md
  src/goto-symex/partial_order_concurrency.h
Labels: documentation

#3403 Add high-level documentation about Java traces [DOC-128]
  src/goto-programs/README.md
Labels: documentation

#4101 Avoid deprecated symbol_exprt default construction in unit test [blocks: #3768]
  unit/util/expr_cast/expr_cast.cpp
Labels: blocker, cleanup

#4026 use instructiont::get_condition()
  src/analyses/constant_propagator.cpp
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/flow_insensitive_analysis.cpp
  src/analyses/interval_domain.cpp
  src/analyses/invariant_propagation.cpp
  src/analyses/invariant_set_domain.cpp
  src/analyses/local_safe_pointers.cpp
  src/analyses/static_analysis.cpp
  src/goto-programs/cfg.h
  src/goto-programs/goto_program.h
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
Labels: cleanup

#4090 Document java trace in depth
  jbmc/src/java_bytecode/README.md
  src/goto-programs/README.md
Labels: documentation

#4085 Update adjust_float_expressions documentation [DOC-153]
  src/goto-programs/adjust_float_expressions.cpp
  src/goto-programs/adjust_float_expressions.h
Labels: documentation

#4094 Tidy up value set analysis
  src/pointer-analysis/value_set_analysis.h
  src/pointer-analysis/value_set_domain.h
  src/pointer-analysis/value_set_domain_transform.inc
Labels: cleanup

#4089 Document value-set analysis
  src/pointer-analysis/README.md
  src/pointer-analysis/value_set_analysis.h
  src/pointer-analysis/value_set_domain.h
Labels: documentation

#4091 Add description of return removal
  src/goto-programs/remove_returns.cpp
  src/goto-programs/remove_returns.h
Labels: documentation

#4093 Document ait; first stab at concurrency_aware_ait.
  src/analyses/ai.h
Labels: documentation

#4105 replace exprt::opX by named methods
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/builtin_functions.cpp
  src/solvers/lowering/byte_operators.cpp
  src/util/simplify_expr.cpp
Labels: cleanup

#4061 Fixes to the byte_operator lowering unit test [blocks: #2068, #4062, #4063]
  unit/solvers/lowering/byte_operators.cpp
Labels: Tests, blocker

#4107 use optionalt<exprt> instead of nil_exprt in expr_initializer
  src/util/expr_initializer.cpp
Labels: cleanup

#4092 Clean up smt2_conv [TG-5825]
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: cleanup

#4112 goto-link regression test: Set the executable bit after copying
  regression/goto-cl/Makefile
Labels: Build, Tests

#4113 String refinement: Do not fail if the solver returns a negative string length [blocks: #2574]
  src/solvers/strings/string_refinement.cpp
Labels: blocker, bugfix

#4062 byte_extract lowering: lower newly introduced byte_extract expressions [depends-on: #4061, blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker, bugfix

#4102 Remove void_typet
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  jbmc/src/java_bytecode/java_bytecode_internal_additions.cpp
  jbmc/src/java_bytecode/java_entry_point.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_pointer_casts.cpp
  jbmc/src/java_bytecode/java_static_initializers.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  jbmc/src/java_bytecode/java_types.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/src/java_bytecode/remove_exceptions.cpp
  jbmc/src/java_bytecode/simple_method_stubbing.cpp
  jbmc/unit/java_bytecode/java_bytecode_parser/parse_java_annotations.cpp
  regression/invariants/driver.cpp
  src/ansi-c/ansi_c_entry_point.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/parser_static.inc
  src/assembler/remove_asm.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_function.cpp
  src/goto-instrument/generate_function_bodies.cpp
  src/jsil/parser.y
  src/solvers/flattening/bv_pointers.cpp
  src/util/c_types.cpp
  src/util/c_types.h
  src/util/std_types.h
  unit/analyses/ai/ai.cpp
  unit/analyses/constant_propagator.cpp
Labels: cleanup

#4055 I/O names must be unique across multiple conversions
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: Symbolic Execution

#4065 Only convert not-yet-converted SSA steps
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: Symbolic Execution

#3991 Replace make_typecast by typecast_exprt or typecast_exprt::conditional_cast [blocks: #3800]
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  src/ansi-c/ansi_c_entry_point.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_initializer.cpp
  src/cpp/cpp_typecheck_static_assert.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/parameter_assignments.cpp
  src/goto-programs/pointer_arithmetic.cpp
  src/goto-programs/printf_formatter.cpp
  src/goto-programs/remove_function_pointers.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_abstraction.h
  src/goto-programs/string_instrumentation.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_other.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivrns.cpp
  src/solvers/flattening/arrays.cpp
Labels: blocker, cleanup

#4096 Document SAT API.
  src/solvers/README.md
  src/solvers/sat/cnf.h
Labels: documentation

#4106 codet API
  src/cpp/cpp_typecheck_initializer.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/rw_set.cpp
  src/goto-programs/goto_convert.cpp
  src/jsil/jsil_typecheck.cpp
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/value_set.cpp
  src/util/std_code.h
Labels: cleanup

#4080 Clean-up and document symex_function_call [DOC-150]
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_main.cpp
Labels: cleanup, documentation

#4122 byte_extract lowering: Fail when we _don't_ have a constant [blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker, bugfix

#4128 Remove unused goto_convertt::convert_init
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_class.h
Labels: cleanup

#4133 GraphML witness: consistently use function_id
  src/goto-programs/graphml_witness.cpp
Labels: cleanup

#3967 Added basic block source lines to source_locationt
  jbmc/regression/jdiff/java-properties/test.desc
  jbmc/src/jbmc/Makefile
  jbmc/src/jdiff/Makefile
  jbmc/unit/Makefile
  regression/cbmc-cover/block-coverage-report1/main.c
  regression/cbmc-cover/block-coverage-report1/test.desc
  regression/cbmc-cover/block-coverage-report2/main.c
  regression/cbmc-cover/block-coverage-report2/test.desc
  regression/cbmc-cover/block-coverage-report3/main.c
  regression/cbmc-cover/block-coverage-report3/test.desc
  regression/cbmc-cover/block-coverage-report4/main.c
  regression/cbmc-cover/block-coverage-report4/test.desc
  regression/cbmc-cover/location1/test.desc
  regression/cbmc-cover/location11/test.desc
  regression/cbmc-cover/location12/test.desc
  regression/cbmc-cover/location13/test.desc
  regression/cbmc-cover/location14/test.desc
  regression/cbmc-cover/location15/test.desc
  regression/cbmc-cover/location16/test.desc
  regression/cbmc-cover/simple_assert/test.desc
  src/cbmc/Makefile
  src/goto-diff/Makefile
  src/goto-instrument/Makefile
  src/goto-instrument/cover_basic_blocks.cpp
  src/goto-instrument/cover_basic_blocks.h
  src/goto-instrument/cover_instrument_location.cpp
  src/goto-instrument/source_lines.cpp
  src/goto-instrument/source_lines.h
  src/util/irep_ids.def
  src/util/source_location.h
  unit/Makefile
Labels: Do not merge

#4126 Object factory: ensure generated assignments are exactly type-consistent [blocks: #3966]
  jbmc/src/java_bytecode/java_object_factory.cpp
Labels: blocker, bugfix

#4136 SMT2 conversion: permit single-operand concatenation [blocks: #2574]
  src/solvers/smt2/smt2_conv.cpp
Labels: blocker, bugfix

#4134 Use type information to detect implicit function declaration
  src/goto-programs/builtin_functions.cpp
  src/linking/linking.cpp
Labels: cleanup

#3994 C front-end: support storage class and attributes for aggregate objects
  regression/ansi-c/gcc_attributes14/main.c
  regression/ansi-c/gcc_attributes14/test.desc
  src/ansi-c/parser.y
Labels: C Front End, bugfix

#4140 Remove unused constructor
  src/goto-symex/goto_symex_state.h
Labels: cleanup

#4139 use instructiont::make_goto variant that takes a guard
  jbmc/src/java_bytecode/remove_exceptions.cpp
  src/goto-analyzer/taint_analysis.cpp
  src/goto-instrument/branch.cpp
  src/goto-instrument/interrupt.cpp
  src/goto-instrument/unwind.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_function_call.cpp
  src/goto-programs/string_instrumentation.cpp
  unit/goto-programs/goto_program_goto_target.cpp
Labels: cleanup

#4138 move patternt into header file
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/pattern.h
Labels: Java Front End

#4142 from_integer can no longer return nil_exprt
  src/analyses/goto_check.cpp
  src/solvers/flattening/boolbv_index.cpp
  src/util/expr_util.cpp
  src/util/pointer_predicates.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_int.cpp
Labels: cleanup

#4141 Remove unnecessary "explicit"
  src/goto-symex/path_storage.h
Labels: cleanup

#4048 Do not remove LHS typecasts in goto-program conversion [blocks: #3800]
  src/goto-programs/goto_convert.cpp
Labels: blocker

#4147 bugfix: must do .update() after remove_returns
  src/goto-instrument/goto_instrument_parse_options.cpp
Labels: bug, bugfix

#4001 Use goto_programt::make_X factories in remove_returns
  src/goto-programs/goto_program.h
  src/goto-programs/remove_returns.cpp
Labels: cleanup

#4148 introduce code_gcc_switch_case_ranget
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/cpp/parse.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_class.h
  src/util/std_code.h
Labels: C Front End, C++ Front End, cleanup

#4149 introduce gcc_asm_gcct
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/assembler/remove_asm.cpp
  src/cpp/parse.cpp
  src/util/std_code.h
Labels: C Front End, C++ Front End, cleanup

#4152 introduce a ranged for
  src/ansi-c/c_typecheck_code.cpp
Labels: C Front End, cleanup

#4146 initialize three members of instructiont
  src/goto-programs/goto_program.h
Labels: bug, bugfix

#4132 fresh symbols: Only use source_locationt's get_function() for user output
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/ansi-c/c_nondet_symbol_factory.h
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/generate_function_bodies.cpp
  src/goto-instrument/wmm/abstract_event.h
  src/goto-instrument/wmm/event_graph.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-instrument/wmm/goto2graph.h
  src/goto-programs/remove_function_pointers.cpp
  src/goto-programs/remove_function_pointers.h
Labels: cleanup

#4166 Put current goto binary version in a single place
  src/goto-programs/read_bin_goto_object.cpp
  src/goto-programs/write_goto_binary.cpp
Labels: cleanup

#4163 irept deserialisation: avoid unnecessary construct/destruct
  src/goto-programs/read_bin_goto_object.cpp
  src/util/irep_serialization.cpp
  src/util/irep_serialization.h
Labels: Performance Optimisations

#4162 Correctly truncate error traces
  regression/cbmc/multiple-goto-traces/main.c
  regression/cbmc/multiple-goto-traces/test.desc
  src/goto-checker/all_properties_verifier_with_trace_storage.h
  src/goto-checker/bmc_util.cpp
  src/goto-checker/bmc_util.h
  src/goto-checker/cover_goals_verifier_with_trace_storage.h
  src/goto-checker/goto_trace_provider.h
  src/goto-checker/multi_path_symex_checker.cpp
  src/goto-checker/multi_path_symex_checker.h
  src/goto-checker/report_util.cpp
  src/goto-checker/single_path_symex_checker.cpp
  src/goto-checker/single_path_symex_checker.h
  src/goto-checker/stop_on_fail_verifier.h
Labels: bugfix

#4165 Use modern API to access parametert's identifier and base name
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_fargs.cpp
  src/cpp/cpp_typecheck_function.cpp
  src/cpp/cpp_typecheck_initializer.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_type.cpp
Labels: C++ Front End, cleanup

#4097 Clean and document symex-dereference
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_dereference_state.cpp
  src/goto-symex/symex_dereference_state.h
  src/goto-symex/symex_other.cpp
  src/pointer-analysis/dereference_callback.h
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/goto_program_dereference.h
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_dereference.h
Labels: cleanup

#3966 Reinstate limited symex renaming [blocks: #4164]
  regression/cbmc/vla1/main.c
  regression/cbmc/vla1/program-only.desc
  regression/cbmc/vla1/test.desc
  src/ansi-c/c_typecheck_type.cpp
  src/goto-symex/goto_symex_state.cpp
Labels: Symbolic Execution, blocker

#4155 merge_irept: insert once and then const_cast to edit in place
  src/util/merge_irep.cpp
Labels: Performance Optimisations

#4137 Java frontend: get qualified generic types of static fields
  jbmc/regression/jbmc/generic_static_field/Test.class
  jbmc/regression/jbmc/generic_static_field/Test.java
  jbmc/regression/jbmc/generic_static_field/test.desc
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
Labels: Java Front End

#3890 symex: source is not optional
  src/goto-instrument/accelerate/scratch_program.cpp
  src/goto-instrument/accelerate/scratch_program.h
  src/goto-symex/goto_symex.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  unit/goto-symex/ssa_equation.cpp
Labels: bugfix

#4144 avoid accesses to instructiont::guard
  src/analyses/constant_propagator.cpp
  src/analyses/dirty.cpp
  src/analyses/goto_check.cpp
  src/analyses/goto_rw.cpp
  src/analyses/local_cfg.cpp
  src/goto-analyzer/static_verifier.cpp
  src/goto-analyzer/taint_analysis.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/accelerate/all_paths_enumerator.cpp
  src/goto-instrument/accelerate/cone_of_influence.cpp
  src/goto-instrument/branch.cpp
  src/goto-programs/adjust_float_expressions.cpp
  src/goto-programs/compute_called_functions.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_program.h
  src/goto-programs/goto_trace.cpp
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/instrument_preconditions.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/remove_complex.cpp
  src/goto-programs/remove_skip.cpp
  src/goto-programs/remove_vector.cpp
  src/goto-programs/rewrite_union.cpp
  src/goto-programs/show_properties.cpp
  src/goto-programs/slice_global_inits.cpp
  src/goto-programs/string_abstraction.cpp
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/value_set_domain.h
Labels: cleanup

#4175 Return statements always have one operand
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  jbmc/src/java_bytecode/java_bytecode_typecheck_code.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/parser.y
  src/cpp/parse.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fi.h
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivr.h
  src/pointer-analysis/value_set_fivrns.cpp
  src/pointer-analysis/value_set_fivrns.h
  src/util/std_code.h
Labels: cleanup

#4177 Deprecate old instructiont API
  src/goto-programs/goto_program.h
Labels: documentation

#4063 byte_extract lowering: ensure type consistency [blocks: #2068]
  regression/cbmc/Pointer_byte_extract3/test.desc
  regression/cbmc/Pointer_byte_extract7/test.desc
  regression/cbmc/equality_through_union1/test.desc
  regression/cbmc/equality_through_union2/test.desc
  regression/cbmc/equality_through_union3/test.desc
  regression/cbmc/gcc_vector1/test.desc
  regression/cbmc/trace_address_arithmetic1/test.desc
  regression/cbmc/union11/union_list.desc
  regression/cbmc/union8/test.desc
  src/solvers/lowering/byte_operators.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker, bugfix

#4123 byte_extract lowering over arrays: fix bits vs bytes error [blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker, bugfix

#4189 use instructiont::make_X in remove_virtual_functions
  src/goto-programs/remove_virtual_functions.cpp
Labels: cleanup

#4124 Byte extract lowering for vectors and array cleanup [blocks: #2068, #4187]
  src/solvers/lowering/byte_operators.cpp
  src/solvers/lowering/flatten_byte_extract_exceptions.h
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker, bugfix

#4191 byte_extract lowering of pointers [blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker

#4194 Add missing include
  src/util/sharing_map.h
Labels: Build, bugfix

#4193 ssa_exprt::get_object_name: add fast path
  src/util/ssa_expr.h
Labels: Performance Optimisations

#4186 byte_extract lowering of string constants [blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker

#4209 Add tests for overflows
  regression/cbmc/Overflow_Addition2/main.c
  regression/cbmc/Overflow_Addition2/test.desc
  regression/cbmc/Overflow_Addition3/main.c
  regression/cbmc/Overflow_Addition3/test.desc
  regression/cbmc/Overflow_Addition4/main.c
  regression/cbmc/Overflow_Addition4/test.desc
Labels: Tests, bug

#4211 expr2bits needs to handle pointer case
  regression/cbmc/assigning_nullpointers_should_not_crash_symex/main.c
  regression/cbmc/assigning_nullpointers_should_not_crash_symex/test.desc
  src/util/simplify_expr.cpp
Labels: bugfix

#4190 Array logic: support with_exprt with multiple updates [blocks: #2068]
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/arrays.h
Labels: blocker, bugfix

#4219 Fix revert-slice bug
  src/goto-symex/slice.cpp
Labels: bugfix

#4220 Do not copy on initialization
  src/goto-checker/single_path_symex_checker.cpp
Labels: cleanup

#4222 Add missing JSON trace output to the C test input generator
  src/cbmc/c_test_input_generator.cpp
Labels: bugfix

#4224 Clarify trace storage property ID mapping
  src/goto-checker/goto_trace_storage.h
Labels: documentation

#3931 C++ parser: use optionalt<codet> to avoid deprecated codet constructor [blocks: #3800]
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/parse.cpp
Labels: C++ Front End, blocker, cleanup

#3110 introduce to_dstring
  src/util/dstring.cpp
  src/util/dstring.h
  src/util/irep.cpp
  src/util/magic.h
Labels: enhancement

#4204 add missing const qualifiers
  jbmc/src/java_bytecode/remove_exceptions.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-programs/parameter_assignments.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_instrumentation.cpp
Labels: cleanup

#4229 Code cleanup of byte_extract lowering of arrays, vectors [blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
Labels: blocker, cleanup

#4227 Byte-operator lowering: do not generate type casts to compound types [blocks: #2068]
  regression/cbmc/Pointer_byte_extract3/test.desc
  regression/cbmc/Pointer_byte_extract7/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: blocker, bugfix

#4228 byte_extract lowering for complex_typet [blocks: #2068]
  src/solvers/lowering/byte_operators.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  unit/solvers/lowering/byte_operators.cpp
Labels: blocker

#3988 Refactoring in goto_symex
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/renaming_level.cpp
  src/goto-symex/renaming_level.h
  src/goto-symex/symex_dead.cpp
  src/goto-symex/symex_decl.cpp
  src/goto-symex/symex_start_thread.cpp
  src/pointer-analysis/add_failed_symbols.cpp
  src/pointer-analysis/add_failed_symbols.h
  src/pointer-analysis/value_set.cpp
Labels: Symbolic Execution

#4214 Remove broken-smt-backend tag from passing tests
  regression/cbmc/Anonymous_Struct3/test.desc
  regression/cbmc/Float13/test.desc
  regression/cbmc/Promotion3/test.desc
  regression/cbmc/Quantifiers-assertion/test.desc
  regression/cbmc/Union_Initialization1/test.desc
  regression/cbmc/array-tests/test.desc
  regression/cbmc/graphml_witness1/test.desc
  regression/cbmc/union6/test.desc
  regression/cbmc/variable-access-to-constant-array/test.desc
Labels: SMT Backend Interface, Tests

#3970 Integrate fault localizer into goto checker [blocks: 4215]
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-checker/Makefile
  src/goto-checker/all_properties_verifier_with_fault_localization.h
  src/goto-checker/bmc_util.cpp
  src/goto-checker/bmc_util.h
  src/goto-checker/fault_localization_provider.h
  src/goto-checker/goto_symex_fault_localizer.cpp
  src/goto-checker/goto_symex_fault_localizer.h
  src/goto-checker/goto_symex_property_decider.cpp
  src/goto-checker/goto_trace_storage.cpp
  src/goto-checker/multi_path_symex_checker.cpp
  src/goto-checker/multi_path_symex_checker.h
  src/goto-checker/report_util.cpp
  src/goto-checker/report_util.h
  src/goto-checker/stop_on_fail_verifier_with_fault_localization.h
  src/goto-programs/goto_trace.h
Labels: Goto-checker, blocker

#4235 remove to_integer(const exprt &, ...)
  src/util/arith_tools.cpp
  src/util/arith_tools.h
Labels: cleanup

#4242 symex_allocate: only use alloc_size when set
  regression/cbmc/Malloc25/main.c
  regression/cbmc/Malloc25/test.desc
  src/goto-symex/symex_builtin_functions.cpp
Labels: Symbolic Execution, bugfix

#4236 remove two unused includes from util/mp_arith.h
  jbmc/src/java_bytecode/expr2java.h
  src/util/arith_tools.h
  src/util/mp_arith.h
Labels: cleanup

#4243 Remove deprecated irept::get_unsigned_int
  src/util/expr.h
  src/util/irep.cpp
  src/util/irep.h
  src/util/message.h
  src/util/type.h
Labels: cleanup

#4247 Document to_integer
  src/util/arith_tools.h
Labels: documentation

#4240 Use byte_update_exprt constructor
  src/goto-symex/symex_assign.cpp
Labels: cleanup

#4198 Ensure String literals that are only used as classids are initialised
  jbmc/regression/jbmc-strings/ClassName/test.class
  jbmc/regression/jbmc-strings/ClassName/test.desc
  jbmc/regression/jbmc-strings/ClassName/test.java
  jbmc/src/java_bytecode/java_entry_point.cpp
Labels: Java Front End

#4246 Avoid json.h include in message.h
  src/util/message.cpp
  src/util/message.h
Labels: cleanup

#4212 added test for undeclared functions
  regression/ansi-c/undeclared_function/fileA.c
  regression/ansi-c/undeclared_function/fileB.c
  regression/ansi-c/undeclared_function/undeclared_function1.desc
  src/goto-cc/armcc_mode.cpp
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
  src/goto-cc/cw_mode.cpp
  src/goto-cc/gcc_cmdline.cpp
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/ld_cmdline.cpp
  src/goto-cc/ld_mode.cpp
  src/goto-cc/ms_cl_cmdline.cpp
  src/goto-cc/ms_cl_mode.cpp
Labels: C Front End, Tests, bug

#4244 Remove unused includes list, functional from expr.h
  src/ansi-c/ansi_c_convert_type.h
  src/assembler/assembler_parser.cpp
  src/assembler/assembler_parser.h
  src/cbmc/all_properties.cpp
  src/cbmc/all_properties_class.h
  src/cbmc/bmc_cover.cpp
  src/solvers/flattening/arrays.h
  src/solvers/prop/cover_goals.cpp
  src/solvers/prop/cover_goals.h
  src/util/expr.h
Labels: cleanup

#4232 Fix array constraints for with_exprt with >3 operands [blocks: #2068]
  regression/cbmc/array_constraints1/main.c
  regression/cbmc/array_constraints1/test.desc
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/arrays.h
Labels: blocker, bugfix

#4207 Store identifiers of parameters in goto_functiont::parameter_identifiers [blocks: #4167]
  src/goto-instrument/generate_function_bodies.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_function.h
  src/goto-programs/goto_functions.h
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/read_bin_goto_object.cpp
  src/goto-programs/string_abstraction.cpp
Labels: blocker

#4225 Use correct function ID for return from function without body
  regression/cbmc/function-return-no-body1/main.c
  regression/cbmc/function-return-no-body1/test.desc
  src/goto-programs/json_goto_trace.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: bugfix

#4223 Get_all_property_ids should only return failed properties
  regression/cbmc-cover/branch-loop1/main.c
  regression/cbmc-cover/branch-loop1/test.desc
  src/cbmc/c_test_input_generator.cpp
  src/goto-checker/goto_trace_storage.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/goto_trace.h
Labels: bugfix

#4226 Fix C enum output
  regression/cbmc/enum-trace1/main.c
  regression/cbmc/enum-trace1/test_json.desc
  regression/cbmc/enum-trace1/test_xml.desc
  src/goto-programs/json_expr.cpp
  src/goto-programs/xml_expr.cpp
Labels: bugfix

#4241 Counterexamples: show strings, not address-of-character
  regression/cbmc/trace-strings/main.c
  regression/cbmc/trace-strings/test.desc
  src/solvers/flattening/pointer_logic.cpp
  src/util/simplify_expr.cpp
Labels: bugfix

#4255 Fix exit/signal specifications in enum-trace1 [blocks: #4253]
  regression/cbmc-cover/branch-loop1/test.desc
  regression/cbmc/enum-trace1/test_json.desc
  regression/cbmc/enum-trace1/test_xml.desc
  regression/cbmc/function-return-no-body1/test.desc
Labels: blocker, bugfix

#4245 Do not use has_prefix in source_location.h
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_bytecode_typecheck_expr.cpp
  jbmc/src/java_bytecode/java_class_loader_base.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/load_method_by_regex.cpp
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/c_preprocess.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/expr2c.cpp
  src/goto-cc/compile.cpp
  src/goto-harness/function_call_harness_generator.cpp
  src/goto-instrument/cover_filter.cpp
  src/goto-instrument/nondet_static.cpp
  src/goto-instrument/race_check.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/remove_virtual_functions.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_function_call.cpp
  src/pointer-analysis/value_set.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/source_location.cpp
  src/util/source_location.h
  unit/analyses/constant_propagator.cpp
Labels: cleanup

#4252 Use goto_functiont::parameter_identifiers instead of looking at the type [blocks: #4167]
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/generate_function_bodies.cpp
  src/goto-programs/goto_function.cpp
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/goto_inline_class.h
  src/goto-programs/interpreter.cpp
  src/goto-symex/symex_function_call.cpp
Labels: blocker

#4256 Take __CPROVER_allocated_memory regions into account for --bounds-check
  regression/cbmc/memory_allocation2/main.c
  regression/cbmc/memory_allocation2/test.desc
  src/analyses/goto_check.cpp
Labels: bugfix

#4263 use instructiont::transform
  src/goto-programs/adjust_float_expressions.cpp
  src/goto-programs/remove_complex.cpp
  src/goto-programs/remove_vector.cpp
Labels: cleanup

#4265 function identifier in trace is wrong when function has no body
  regression/cbmc/trace_show_function_calls/main.c
  regression/cbmc/trace_show_function_calls/test.desc
Labels: Tests, bug

#3478 add replace_all documentation
  src/util/string_utils.cpp
Labels: documentation

#4274 Use ranged-for to iterate over value_sett:valuest
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_analysis.cpp
Labels: cleanup

#4269 Add a definition of alloca [blocks: #4270]
  src/ansi-c/library/stdlib.c
Labels: blocker

#4273 Remove replace_all string utility
  src/util/string_utils.cpp
  src/util/string_utils.h
Labels: cleanup

#2033 Use propt::lcnf instead of propt::l_set_to{true,false}
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_utils.cpp
Labels: cleanup

#4271 pthread_cond_wait may return spuriously
  regression/cbmc-library/CMakeLists.txt
  regression/cbmc-library/Makefile
  regression/cbmc-library/pthread_barrier_destroy-01/test.desc
  regression/cbmc-library/pthread_barrier_init-01/test.desc
  regression/cbmc-library/pthread_barrier_wait-01/test.desc
  regression/cbmc-library/pthread_cancel-01/test.desc
  regression/cbmc-library/pthread_cond_broadcast-01/test.desc
  regression/cbmc-library/pthread_cond_init-01/test.desc
  regression/cbmc-library/pthread_cond_signal-01/test.desc
  regression/cbmc-library/pthread_cond_wait-01/main.c
  regression/cbmc-library/pthread_cond_wait-01/test.desc
  regression/cbmc-library/pthread_create-01/test.desc
  regression/cbmc-library/pthread_exit-01/test.desc
  regression/cbmc-library/pthread_join-01/test.desc
  regression/cbmc-library/pthread_mutex_destroy-01/test.desc
  regression/cbmc-library/pthread_mutex_init-01/test.desc
  regression/cbmc-library/pthread_mutex_lock-01/test.desc
  regression/cbmc-library/pthread_mutex_trylock-01/test.desc
  regression/cbmc-library/pthread_mutex_unlock-01/test.desc
  regression/cbmc-library/pthread_mutexattr_settype-01/test.desc
  regression/cbmc-library/pthread_rwlock_destroy-01/test.desc
  regression/cbmc-library/pthread_rwlock_init-01/test.desc
  regression/cbmc-library/pthread_rwlock_rdlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_tryrdlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_trywrlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_unlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_wrlock-01/test.desc
  regression/cbmc-library/pthread_spin_lock-01/test.desc
  regression/cbmc-library/pthread_spin_trylock-01/test.desc
  regression/cbmc-library/pthread_spin_unlock-01/test.desc
  src/ansi-c/library/pthread_lib.c
Labels: C Front End

#4278 Enable cbmc-concurrency regression tests by default
  regression/CMakeLists.txt
  regression/Makefile
  regression/cbmc-concurrency/CMakeLists.txt
  regression/cbmc-concurrency/Makefile
  regression/cbmc-concurrency/atomic_section_sc6/test.desc
  regression/cbmc-concurrency/conditional_spawn1/test.desc
  regression/cbmc-concurrency/deadlock1/test.desc
  regression/cbmc-concurrency/deadlock2/test.desc
  regression/cbmc-concurrency/malloc1/main.c
  regression/cbmc-concurrency/malloc2/main.c
  regression/cbmc-concurrency/memory_barrier1/test.desc
  regression/cbmc-concurrency/memory_barrier2/main.c
  regression/cbmc-concurrency/memory_barrier2/test.desc
  regression/cbmc-concurrency/mutex2/test.desc
  regression/cbmc-concurrency/norace_array1/test.desc
  regression/cbmc-concurrency/norace_array2/test.desc
  regression/cbmc-concurrency/norace_scalar1/test.desc
  regression/cbmc-concurrency/norace_struct1/test.desc
  regression/cbmc-concurrency/pthread_create_tso1/test.desc
  regression/cbmc-concurrency/pthread_join1/test.desc
  regression/cbmc-concurrency/pthread_join2/test.desc
  regression/cbmc-concurrency/sc6/test.desc
  regression/cbmc-concurrency/svcomp13_fib_bench_longer_safe/test.desc
  regression/cbmc-concurrency/svcomp13_fib_bench_longer_unsafe/test.desc
  regression/cbmc-concurrency/thread_chain_posix1/test.desc
  regression/cbmc-concurrency/thread_chain_posix2/test.desc
  regression/cbmc-concurrency/thread_chain_posix3/test.desc
  regression/cbmc-concurrency/thread_local1/test.desc
  regression/cbmc-concurrency/trace1/test.desc
  regression/cbmc-concurrency/uf_with_threads1/test.desc
  src/goto-programs/builtin_functions.cpp
Labels: Tests, bugfix

#4283 C library: Do not require stdin, stdout, stderr to be initialised
  regression/cbmc-library/fileno-01/main.c
  regression/cbmc-library/fileno-01/test.desc
  regression/cbmc-library/fprintf-01/main.c
  regression/cbmc-library/fprintf-01/test.desc
  src/ansi-c/library/stdio.c
Labels: C Front End, bugfix

#3996 Split the rename function according to the level and pass expression by copy instead of reference
  src/goto-instrument/accelerate/scratch_program.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_dead.cpp
  src/goto-symex/symex_decl.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_dereference_state.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_start_thread.cpp
Labels: Symbolic Execution

#3770 Move promotion rule application to C front-end [blocks: #3725, #3800]
  regression/cbmc/Overflow_Addition3/test.desc
  regression/cbmc/complex1/main.c
  regression/cbmc/enum8/main.c
  regression/cbmc/enum8/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/goto_convert_side_effect.cpp
Labels: blocker, bugfix, cleanup

#4298 Add missing include file [blocks: #4056]
  regression/cbmc-cover/built-ins2/main.c
Labels: blocker

#4264 remove symbol_typet [blocks: #4056]
  src/analyses/invariant_propagation.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/expr2c.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/cpp/cpp_typecheck_template.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-instrument/nondet_volatile.cpp
  src/goto-programs/destructor.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/json_expr.cpp
  src/goto-programs/xml_expr.cpp
  src/goto-symex/goto_symex_state.cpp
  src/linking/linking.cpp
  src/pointer-analysis/value_set_analysis_fi.cpp
  src/pointer-analysis/value_set_analysis_fivr.cpp
  src/pointer-analysis/value_set_analysis_fivrns.cpp
  src/solvers/flattening/boolbv_width.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/README.md
  src/util/base_type.cpp
  src/util/endianness_map.cpp
  src/util/expr_initializer.cpp
  src/util/find_symbols.cpp
  src/util/format_type.cpp
  src/util/irep_ids.def
  src/util/namespace.cpp
  src/util/namespace.h
  src/util/pointer_offset_size.cpp
  src/util/rename_symbol.cpp
  src/util/std_types.cpp
  src/util/std_types.h
  src/util/type_eq.cpp
Labels: blocker, bugfix, cleanup

#4303 Deprecate link_to_library(goto_functions, symbol_table, ...) [blocks: #4296]
  src/goto-programs/link_to_library.cpp
  src/goto-programs/link_to_library.h
Labels: blocker
