Repository diffblue/cbmc, pull requests merged in 2019-09, with the labels that each got.

#5024 fix accesses to exprt::opX() in statement-list/
  src/statement-list/converters/expr2statement_list.cpp
Labels: cleanup

#5026 fix accesses to exprt::opX() in goto-programs/
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/goto-programs/pointer_arithmetic.cpp
  src/goto-programs/printf_formatter.cpp
  src/goto-programs/remove_complex.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_instrumentation.cpp
  src/goto-programs/wp.cpp
Labels: cleanup

#5015 further typing in the simplifier
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_if.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#5075 Fix accesses to exprt::opX() in jbmc/
  jbmc/src/java_bytecode/java_bytecode_concurrency_instrumentation.cpp
  jbmc/src/java_bytecode/java_expr.h
  jbmc/src/java_bytecode/java_trace_validation.cpp
  jbmc/unit/java-testing-utils/require_goto_statements.cpp
  jbmc/unit/java_bytecode/goto-programs/remove_virtual_functions_without_fallback.cpp
  jbmc/unit/java_bytecode/java_bytecode_instrument/virtual_call_null_checks.cpp
  jbmc/unit/pointer-analysis/custom_value_set_analysis.cpp
  jbmc/unit/solvers/strings/string_refinement/dependency_graph.cpp
  jbmc/unit/util/expr_iterator.cpp
Labels: cleanup

#4368 struct_exprt API [do not merge before 2019-07-12]
  src/util/std_expr.h
  src/util/string_expr.h
Labels: cleanup

#5081 Add unit tests for get_user_specified_clinit_body
  jbmc/unit/java_bytecode/java_static_initializers/java_static_initializers.cpp
  jbmc/unit/java_bytecode/java_static_initializers/module_dependencies.txt
  unit/testing-utils/expr_query.h
Labels: Tests

#5079 [TG-9218] Fix parsing of escaped characters in json
  jbmc/regression/jbmc/deterministic_assignments_json/StaticValues.class
  jbmc/regression/jbmc/deterministic_assignments_json/StaticValues.java
  jbmc/regression/jbmc/deterministic_assignments_json/clinit-state.json
  jbmc/regression/jbmc/deterministic_assignments_json/test_new_line_char_fail.desc
  jbmc/regression/jbmc/deterministic_assignments_json/test_new_line_char_pass.desc
  src/json/scanner.l
  unit/json/json_parser.cpp
Labels: QA reviewed

#5073 [TG-9299] Fix crash in case of user provided clinit for a clinit which is not in the symbol table
  jbmc/src/java_bytecode/assignments_from_json.cpp
  jbmc/src/java_bytecode/java_static_initializers.cpp
  jbmc/unit/java_bytecode/java_static_initializers/java_static_initializers.cpp
Labels: Java Front End, bugfix, dependent - do not merge

#5102 Fix build dependencies of symtab2gb
  src/Makefile
Labels: Build, bugfix
