Repository diffblue/cbmc, pull requests merged in 2019-06, with the labels that each got.

#4713 Byte-update lowering: fixup invariant for array-comprehension
  regression/cbmc/byte_update12/main.c
  regression/cbmc/byte_update12/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#4741 C front-end: Typecheck bitnand
  regression/cbmc/atomic_fetch_X-1/main.c
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, bugfix

#4742 Byte-update lowering: array comprehension must consider offset
  regression/cbmc-library/memcpy-05/main.c
  regression/cbmc-library/memcpy-05/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#4743 added virtual destructor to statement_list_parse_treet::functiont
  src/statement-list/statement_list_parse_tree.h
Labels: bugfix

#4740 Travis clang-format, cpplint: Use the merge base
  .travis.yml
  scripts/travis_lint.sh
Labels: Build, bugfix

#4718 Add CI compilation with clang++-3.8
  buildspec-linux-clang-3.8.yml
Labels: Do not merge

#4735 Clean-up symex assignments
  src/goto-symex/goto_symex.h
  src/goto-symex/ssa_step.cpp
  src/goto-symex/ssa_step.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_target_equation.cpp
  src/solvers/prop/bdd_expr.cpp
  src/util/expr_util.cpp
  src/util/expr_util.h
Labels: Symbolic Execution, cleanup

#4734 Differentiate OSX fat binaries from Java class files
  src/goto-programs/osx_fat_reader.cpp
  src/goto-programs/osx_fat_reader.h
  src/goto-programs/read_goto_binary.cpp
  unit/Makefile
  unit/goto-programs/Hello.class
  unit/goto-programs/hello_fat
  unit/goto-programs/osx_fat_reader.cpp
  unit/osx_fat_reader.cpp
Labels: Needs rebase

#4748 goto-analyzer uses goto-checker
  src/Makefile
Labels: Build

#4732 introduce simplify_exprt::resultt
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
Labels: RFC

#4746 switch codebuild from clang 7 to clang 8
  buildspec-linux-clang.yml
  src/solvers/strings/string_builtin_function.h
Labels: Build

#4736 Clean-up ssa-exprt
  src/util/ssa_expr.cpp
  src/util/ssa_expr.h
Labels: cleanup

#4761 Make ssa_exprt unit test more complete
  unit/util/ssa_expr.cpp
Labels: Tests

#4762 Fix is_goto_binary to pass extended Mach-O header to osx_fat_reader
  src/goto-programs/read_goto_binary.cpp
  unit/Makefile
  unit/goto-programs/hello_elf
  unit/goto-programs/hello_elf_with_gbf
  unit/goto-programs/hello_fat_macho
  unit/goto-programs/hello_fat_macho_with_gbf
  unit/goto-programs/is_goto_binary.cpp
  unit/goto-programs/osx_fat_reader.cpp
Labels: bugfix

#4759 Do not try to generate void objects
  regression/goto-instrument/generate-function-body-void/main.c
  regression/goto-instrument/generate-function-body-void/test.desc
  src/ansi-c/c_nondet_symbol_factory.cpp
Labels: bugfix

#4764 fix for arraylength
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
Labels: Java Front End, bugfix

#4769 deprecate java_is_array_type
  jbmc/src/java_bytecode/java_utils.h
Labels: cleanup

#4773 Remove use of deprecated get_value_set
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  unit/pointer-analysis/value_set.cpp
Labels: cleanup

#4775 Remove use of deprecated get_value_set function
  src/pointer-analysis/value_set_dereference.cpp
Labels: cleanup

#4786 Move string_format functions into builtin_functions
  src/solvers/Makefile
  src/solvers/strings/string_constraint_generator_format.cpp
  src/solvers/strings/string_format_builtin_function.cpp
Labels: cleanup

#4774 Unit-test try_evaluate_pointer_comparison and bugfix
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_goto.cpp
  unit/Makefile
  unit/goto-symex/try_evaluate_pointer_comparisons.cpp
Labels: Symbolic Execution, Tests, bugfix

#4776 Document field sensitivity class
  doc/architectural/background-concepts.md
  src/goto-symex/field_sensitivity.h
Labels: Symbolic Execution, documentation

#4794 Use format instead of from_expr in value_sett::output
  src/pointer-analysis/module_dependencies.txt
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set.h
Labels: cleanup

#4801 introduce BC_* macros
  jbmc/src/java_bytecode/bytecode_info.h
Labels: Java Front End

#4804 fix result type of instanceof
  jbmc/src/java_bytecode/bytecode_info.cpp
Labels: Java Front End, bugfix

#4803 use BC_ macros instead of string comparison
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
  jbmc/src/java_bytecode/pattern.h
Labels: Java Front End

#4772 C library/free: distinguish invalid pointer from invalid free
  regression/cbmc-library/free-01/main.c
  regression/cbmc-library/free-01/test.desc
  regression/cbmc/alloca1/test.desc
  src/ansi-c/library/stdlib.c
Labels: C Front End

#4810 satcheck_minisat2 assumptions bug fix and unit tests
  src/solvers/sat/satcheck_minisat2.cpp
  unit/Makefile
  unit/solvers/sat/module_dependencies.txt
  unit/solvers/sat/satcheck_minisat2.cpp
Labels: Tests, bugfix

#4816 Fix indentation in value_sett output
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#4800 Extract string_concatenation_builtin_function in own file [TG-8152]
  src/solvers/Makefile
  src/solvers/strings/string_builtin_function.cpp
  src/solvers/strings/string_builtin_function.h
  src/solvers/strings/string_concatenation_builtin_function.cpp
  src/solvers/strings/string_concatenation_builtin_function.h
  src/solvers/strings/string_dependencies.cpp
Labels: cleanup

#4815 Make nondet_symbol_exprt constructor take location
  src/goto-symex/path_storage.cpp
  src/goto-symex/path_storage.h
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_clean_expr.cpp
  src/util/std_expr.h
Labels: cleanup

#4819 Bugfix in get_subexpression_at_offset
  src/util/pointer_offset_size.cpp
  unit/util/pointer_offset_size.cpp
Labels: bugfix

#4822 Clean-up pointer offset size
  src/util/pointer_offset_size.cpp
  src/util/pointer_offset_size.h
Labels: cleanup

#4811 Make increase generation a method of symex_level2t
  src/goto-symex/goto_state.cpp
  src/goto-symex/goto_state.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/renaming_level.cpp
  src/goto-symex/renaming_level.h
  src/goto-symex/symex_decl.cpp
  src/pointer-analysis/add_failed_symbols.cpp
  src/pointer-analysis/add_failed_symbols.h
Labels: cleanup

#4812 Move java-assume-inputs-interval to java_object_factory_parameters
  jbmc/src/java_bytecode/java_object_factory_parameters.cpp
  jbmc/src/java_bytecode/java_object_factory_parameters.h
  src/util/object_factory_parameters.cpp
  src/util/object_factory_parameters.h
Labels: cleanup

#4821 Clean-up in pointer logic
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/pointer_logic.cpp
  src/solvers/flattening/pointer_logic.h
Labels: Solvers, cleanup

#4825 Add unit-test for goto symex state assignments
  src/goto-symex/goto_symex_state.cpp
  src/pointer-analysis/value_set.h
  unit/Makefile
  unit/goto-symex/goto_symex_state.cpp
  unit/goto-symex/module_dependencies.txt
Labels: Symbolic Execution, Tests, cleanup

#4830 simplifier cleanup
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
Labels: cleanup

#4831 simplify_byte_extract and simplify_byte_update now have new interface
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
Labels: cleanup

#4827 Refactor and unit test symex_assign_symbol
  src/goto-symex/goto_symex.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_assign.h
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_start_thread.cpp
  unit/Makefile
  unit/goto-symex/symex_assign.cpp
Labels: Symbolic Execution, Tests

#4840 Replace use of #ifdef by template parameter in symex_assign
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_assign.h
Labels: Symbolic Execution, cleanup

#4841 Define and use an expr_skeletont class
  src/goto-symex/goto_symex.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_assign.h
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_start_thread.cpp
  unit/goto-symex/symex_assign.cpp
Labels: Symbolic Execution, cleanup

#4653 Remove adjust_if_recursive
  src/solvers/strings/string_refinement.cpp
Labels: Needs TG approval :owl:

#4757 avoid access to exprt::opX()
  src/analyses/constant_propagator.cpp
  src/analyses/goto_check.cpp
  src/analyses/invariant_set.cpp
  src/goto-symex/goto_state.cpp
Labels: cleanup
