Repository diffblue/cbmc, pull requests merged in 2019-07, with the labels that each got.

#4845 Fix full_lhs not being updated in symex_assignt::assign_symbol after rewrite_with_to_field_symbols
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_assign.h
  src/util/optional.h
  unit/goto-symex/symex_assign.cpp
Labels: Symbolic Execution, bugfix

#4856 Cleanup (&fix) simplifier result
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_utils.cpp
Labels: bugfix

#4851 simplifier: new interface for floating-point expressions
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_floatbv.cpp
Labels: cleanup

#4857 Simplifier: new interface for pointer-related simplifications
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#4853 Simplifier: new interface for arithmetic expressions
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#4865 Simplifier: simplify_if new interface
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#4866 Do not store duplicates of inherited static fields in tests for --static-values
  jbmc/regression/jbmc/deterministic_assignments_json/clinit-state.json
  jbmc/regression/jbmc/deterministic_assignments_json/src/main/java/org/cprover/JsonGenerator.java
Labels: Tests

#4870 Fix type of data_ptr in convert_aload/astore and useless typecasts
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_method.cpp
  unit/testing-utils/expr_query.h
Labels: Java Front End, bugfix

#4861 ansi-c: missing eom
  src/ansi-c/c_typecheck_type.cpp
Labels: bugfix

#4878 Fix change propagation in simplify_byte_extract
  src/util/simplify_expr.cpp
Labels: bugfix

#4876 Default initialize class_hierarchy
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_method.cpp
Labels: Needs TG approval :owl:

#4888 better typing in object_descriptor_exprt::root_object()
  src/util/std_expr.cpp
Labels: cleanup

#4873 Avoid unnecessary typecast in java_bytecode_convert_methodt::variable
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_method.cpp
Labels: Java Front End, bugfix

#4881 set the name of bison-generated header file
  src/ansi-c/Makefile
  src/jsil/Makefile
  src/json/Makefile
  src/statement-list/Makefile
  src/xmllang/Makefile
Labels: Build

#4848 Pointer check beautification
  src/analyses/goto_check.cpp
Labels: enhancement

#4901 C front-end: Permit array_of as array initializer
  regression/ansi-c/array_initialization5/main.c
  regression/ansi-c/array_initialization5/test.desc
  src/ansi-c/c_typecheck_initializer.cpp
Labels: C Front End, bugfix

#4872 simplifier: use new interface
  src/util/simplify_expr.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#4874 Simplifier: new interface, final piece [blocks: #4904]
  src/util/Makefile
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_if.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
  src/util/simplify_utils.cpp
Labels: blocker, cleanup

#4900 Null-pointer filtering must handle unknown offsets
  regression/cbmc/null7/main.c
  regression/cbmc/null7/test.desc
  src/goto-symex/symex_goto.cpp
Labels: bugfix

#4902 Value sets: Support bitand/bitor over pointers
  regression/cbmc/Pointer_Arithmetic14/main.c
  regression/cbmc/Pointer_Arithmetic14/test.desc
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#4903 Support OBJECT_SIZE over string constants
  regression/cbmc/String8/main.c
  regression/cbmc/String8/test.desc
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: bugfix

#4898 Factor out charAt() and startsWith() simplification into separate functions
  src/util/simplify_expr.cpp
Labels: Needs rebase

#4922 Fix #include order in util/json.cpp
  src/util/json.cpp
Labels: blocker

#4926 Enable clang-format for Java
  .clang-format
Labels: Build

#4925 Create auxiliary symbols with a different name than symbols in namespace [blocks: #4885]
  src/util/fresh_symbol.cpp
  src/util/fresh_symbol.h
Labels: blocker

#4932 use sorted_symbol_names in show_symbol_table_brief_plain
  src/goto-programs/show_symbol_table.cpp
Labels: cleanup

#4904 simplifier: eliminate casts from bool to number
  jbmc/unit/util/simplify_expr.cpp
  src/util/simplify_expr.cpp
  unit/util/simplify_expr.cpp
Labels: enhancement

#4943 Error message when entry function body cannot be produced [TG-8299]
  jbmc/regression/jbmc/context-include-exclude/test_excluded_entry_point.desc
  jbmc/src/java_bytecode/java_bytecode_language.cpp
Labels: bugfix

#4929 Fix generic_parameter_specialization_map in the presence of non-symmetric generic recursion [TG-7815]
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/README.md
  jbmc/src/java_bytecode/generic_parameter_specialization_map.cpp
  jbmc/src/java_bytecode/generic_parameter_specialization_map.h
  jbmc/src/java_bytecode/generic_parameter_specialization_map_keys.cpp
  jbmc/src/java_bytecode/generic_parameter_specialization_map_keys.h
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/src/java_bytecode/select_pointer_type.cpp
  jbmc/src/java_bytecode/select_pointer_type.h
  jbmc/unit/java-testing-utils/require_type.cpp
  jbmc/unit/java-testing-utils/require_type.h
  jbmc/unit/java_bytecode/goto_program_generics/Bar.class
  jbmc/unit/java_bytecode/goto_program_generics/Foo.class
  jbmc/unit/java_bytecode/goto_program_generics/KeyValue.class
  jbmc/unit/java_bytecode/goto_program_generics/MutuallyRecursiveGenerics.class
  jbmc/unit/java_bytecode/goto_program_generics/MutuallyRecursiveGenerics.java
  jbmc/unit/java_bytecode/goto_program_generics/Outer$Inner.class
  jbmc/unit/java_bytecode/goto_program_generics/Outer.class
  jbmc/unit/java_bytecode/goto_program_generics/Three.class
  jbmc/unit/java_bytecode/goto_program_generics/mutually_recursive_generics.cpp
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/DerivedGenerics.java
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses$GenericInner$GenericInnerInner.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses$GenericInner$ShadowingGenericInner.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses$GenericInner.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses$Inner$InnerInner.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses$Inner.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses$StaticInner.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses.class
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/GenericClassWithInnerClasses.java
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/parse_derived_generic_class.cpp
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/parse_generic_class_with_inner_classes.cpp
  src/util/pointer_offset_size.cpp
  src/util/simplify_expr_int.cpp
Labels: bugfix

#4962 fix exprt::opX accesses in goto-symex
  src/goto-symex/expr_skeleton.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_goto.cpp
Labels: cleanup
