Repository diffblue/cbmc, pull requests merged in 2019-08, with the labels that each got.

#4963 fix exprt::opX accesses in analyses
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/goto_check.cpp
  src/analyses/local_bitvector_analysis.cpp
  src/analyses/local_may_alias.cpp
  src/analyses/local_safe_pointers.cpp
  src/analyses/static_analysis.cpp
  src/analyses/uncaught_exceptions_analysis.cpp
Labels: cleanup

#4935 ACSL quantifiers
  regression/cbmc/ACSL/operators.c
  regression/cbmc/ACSL/quantifier-precedence.c
  regression/cbmc/ACSL/quantifier-precedence.desc
  src/ansi-c/parser.y
Labels: bug, bugfix

#4889 applying functions that aren't symbols
  src/solvers/smt2/smt2_solver.cpp
  src/solvers/strings/string_builtin_function.h
  src/util/mathematical_expr.cpp
  src/util/mathematical_expr.h
Labels: SMT Backend Interface

#4981 fix exprt::opX accesses in simplifier
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
Labels: cleanup

#4934 use optionalt in get_quantifier_var_max/min
  src/solvers/flattening/boolbv_quantifier.cpp
Labels: cleanup

#4969 goto-symex must not lift lets with bound variables
  regression/cbmc/Quantifiers-expr-cleaning/main.c
  regression/cbmc/Quantifiers-expr-cleaning/test.desc
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_main.cpp
Labels: bugfix

#4986 Slicing global inits must not drop depended-on globals
  regression/goto-instrument/slice-global-inits4/main.c
  regression/goto-instrument/slice-global-inits4/test.desc
  src/goto-programs/slice_global_inits.cpp
Labels: bugfix

#4709 Test of dereferencing without an explicit temporary
  regression/cbmc/Pointer_Arithmetic17/main.c
  regression/cbmc/Pointer_Arithmetic17/test.desc
Labels: Tests

#4982 simplifier: new interface for simplify_node
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_if.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
Labels: cleanup

#4983 fix accesses to exprt::opX() in ansi-c/
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/ansi-c/parser.y
  src/util/std_code.h
Labels: cleanup

#4987 Fix accesses to exprt::opX in simplifer
  src/util/simplify_expr.cpp
Labels: Needs rebase, cleanup

#4931 introduce binding_exprt [blocks: #4510]
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/ansi-c/parser.y
  src/solvers/flattening/boolbv_quantifier.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/util/mathematical_expr.h
Labels: blocker, cleanup

#4991 introduce ID_array_comprehension
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/util/irep_ids.def
  src/util/simplify_expr_array.cpp
  src/util/std_expr.h
Labels: cleanup

#4885 [TG-8293] Constant propagation for empty strings and string concatenation [blocks: #4941]
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation04-StringEqual/Main.class
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation04-StringEqual/Main.java
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation04-StringEqual/test.desc
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation05-VerificationFailure/Main.class
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation05-VerificationFailure/Main.java
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation05-VerificationFailure/test1.desc
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation05-VerificationFailure/test2.desc
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation06-2byteChar/Main.class
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation06-2byteChar/Main.java
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation06-2byteChar/test.desc
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation07-NonPrintableChar/Main.class
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation07-NonPrintableChar/Main.java
  jbmc/regression/jbmc-strings/ConstantEvaluationStringConcatenation07-NonPrintableChar/test.desc
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation1/Main.class
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation1/Main.java
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation1/test.desc
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation2/Main.class
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation2/Main.java
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation2/test1.desc
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation2/test2.desc
  jbmc/regression/jbmc-strings/StringBuilderAppendConstantEvaluation2/test3.desc
  jbmc/regression/jbmc-strings/StringBuilderDefaultConstructorConstantEvaluation/Main.class
  jbmc/regression/jbmc-strings/StringBuilderDefaultConstructorConstantEvaluation/Main.java
  jbmc/regression/jbmc-strings/StringBuilderDefaultConstructorConstantEvaluation/test.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation1/Main.class
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation1/Main.java
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation1/test.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation2/Main.class
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation2/Main.java
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation2/test1.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation2/test2.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation2/test3.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation3/Main.class
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation3/Main.java
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation3/test1.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation3/test2.desc
  jbmc/regression/jbmc-strings/StringConcatenationConstantEvaluation3/test3.desc
  jbmc/regression/jbmc-strings/StringDefaultConstructorConstantEvaluation/Main.class
  jbmc/regression/jbmc-strings/StringDefaultConstructorConstantEvaluation/Main.java
  jbmc/regression/jbmc-strings/StringDefaultConstructorConstantEvaluation/test.desc
  jbmc/src/java_bytecode/java_string_literals.cpp
  src/goto-symex/goto_symex.cpp
  src/goto-symex/goto_symex.h
  src/solvers/strings/array_pool.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr.h
  src/util/string_utils.cpp
  src/util/string_utils.h
Labels: blocker

#5000 Refine CPPLINT script to not report __CPROVER_ usage outside of strings
  scripts/cpplint.py
  src/ansi-c/library/cprover.h
  src/cpp/library/cprover.h
Labels: cleanup

#4995 Clean up string constraint generator class
  src/solvers/strings/string_constraint_generator.h
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_dependencies.cpp
  src/solvers/strings/string_dependencies.h
  src/solvers/strings/string_refinement.cpp
Labels: String solver, cleanup

#4990 use simplify_not instead of boolean_negate
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_if.cpp
  src/util/simplify_expr_int.cpp
Labels: cleanup

#5014 type simplify_inequality and auxiliary methods
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#5017 improve typing in binary_relation_exprt::validate
  src/util/std_expr.h
Labels: cleanup

#5020 remove value_set_analysis_fivr and value_set_analysis_fivrns
  src/pointer-analysis/Makefile
  src/pointer-analysis/value_set_analysis_fivr.cpp
  src/pointer-analysis/value_set_analysis_fivrns.cpp
  src/pointer-analysis/value_set_domain_fivr.cpp
  src/pointer-analysis/value_set_domain_fivrns.cpp
  src/pointer-analysis/value_set_fivr.cpp
  src/pointer-analysis/value_set_fivrns.cpp
Labels: Static Analyses, cleanup

#5011 fix exprt::opX accesses in goto-instrument
  src/goto-instrument/accelerate/overflow_instrumenter.cpp
  src/goto-instrument/accelerate/polynomial.cpp
  src/goto-instrument/dot.cpp
  src/goto-instrument/goto_program2code.cpp
Labels: cleanup

#5018 fix exprt::opX accesses in java_bytecode
  jbmc/src/java_bytecode/expr2java.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_pointer_casts.cpp
  jbmc/src/java_bytecode/java_trace_validation.cpp
  jbmc/src/java_bytecode/remove_instanceof.cpp
  jbmc/src/java_bytecode/remove_java_new.cpp
Labels: cleanup

#5016 Handle more formulas than just equations in string solver
  jbmc/unit/solvers/strings/string_refinement/dependency_graph.cpp
  src/solvers/strings/string_dependencies.cpp
  src/solvers/strings/string_dependencies.h
  src/solvers/strings/string_refinement.cpp
  src/solvers/strings/string_refinement.h
  unit/Makefile
  unit/solvers/strings/string_refinement/module_dependencies.txt
  unit/solvers/strings/string_refinement/string_refinement.cpp
Labels: String solver, enhancement

#5040 Fix array length in symex constant string propagation [TG-9048]
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/StringBuilderConstructors01.class
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/StringBuilderConstructors01.java
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-capacity-fail.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-capacity-pass.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-no-arg-fail.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-no-arg-pass.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-string-fail.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-string-pass.desc
  src/goto-symex/goto_symex.cpp
  src/goto-symex/goto_symex.h
Labels: Symbolic Execution, bugfix

#5027 fix accesses to exprt::opX() in pointer-analysis/
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: Static Analyses, cleanup

#5029 fix accesses to exprt::opX() in jsil/
  src/jsil/jsil_convert.cpp
  src/jsil/jsil_typecheck.cpp
Labels: cleanup

#5030 fix accesses to exprt::opX() in unit/
  unit/solvers/strings/string_refinement/substitute_array_list.cpp
  unit/util/interval_constraint.cpp
  unit/util/irep_sharing.cpp
  unit/util/replace_symbol.cpp
Labels: cleanup

#5045 cfg_dominatorst: introduce a public interface [blocks: 5051]
  src/analyses/cfg_dominators.h
  src/analyses/dependence_graph.cpp
  src/analyses/natural_loops.h
  src/goto-instrument/full_slicer.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/cfg.h
Labels: blocker

#5051 cfgt: introduce and use a public interface when interacting with the entry map [blocks: 5049, 5059]
  jbmc/src/java_bytecode/java_local_variable_table.cpp
  src/analyses/cfg_dominators.h
  src/goto-diff/change_impact.cpp
  src/goto-instrument/count_eloc.cpp
  src/goto-instrument/full_slicer.cpp
  src/goto-instrument/points_to.cpp
  src/goto-instrument/reachability_slicer.cpp
  src/goto-programs/cfg.h
Labels: blocker

#5063 Clean-up constraint generation for insert builtin function
  src/solvers/Makefile
  src/solvers/README.md
  src/solvers/strings/string_builtin_function.cpp
  src/solvers/strings/string_builtin_function.h
  src/solvers/strings/string_concatenation_builtin_function.h
  src/solvers/strings/string_constraint_generator.h
  src/solvers/strings/string_constraint_generator_insert.cpp
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_insertion_builtin_function.cpp
  src/solvers/strings/string_insertion_builtin_function.h
Labels: Solvers, cleanup

#5041 [TG-9173] Add build option to enable profiling
  CMakeLists.txt
  doc/architectural/compilation-and-development.md
Labels: Build
