Repository diffblue/cbmc, pull requests merged in 2019-05, with the labels that each got.

#2548 Handle all enum values in switch/case [blocks: #2310]
  CMakeLists.txt
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/miniz/miniz.cpp
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/escape_analysis.cpp
  src/analyses/global_may_alias.cpp
  src/analyses/interval_domain.cpp
  src/analyses/invariant_set_domain.cpp
  src/analyses/local_bitvector_analysis.cpp
  src/analyses/local_cfg.cpp
  src/analyses/local_may_alias.cpp
  src/analyses/local_safe_pointers.cpp
  src/analyses/uncaught_exceptions_analysis.cpp
  src/analyses/uninitialized_domain.cpp
  src/ansi-c/c_typecast.cpp
  src/config.inc
  src/cpp/cpp_id.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/parse.cpp
  src/goto-analyzer/taint_analysis.cpp
  src/goto-cc/compile.cpp
  src/goto-instrument/cover_util.cpp
  src/goto-instrument/points_to.cpp
  src/goto-instrument/show_locations.cpp
  src/goto-programs/format_strings.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/json_goto_trace.h
  src/goto-programs/show_symbol_table.cpp
  src/goto-programs/string_instrumentation.cpp
  src/goto-programs/vcd_goto_trace.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/goto-symex/slice.cpp
  src/goto-symex/ssa_step.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/show_value_sets.cpp
  src/pointer-analysis/value_set_domain.h
  src/pointer-analysis/value_set_domain_fi.cpp
  src/pointer-analysis/value_set_domain_fivr.cpp
  src/pointer-analysis/value_set_domain_fivrns.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/boolbv_typecast.cpp
  src/solvers/floatbv/float_utils.h
  src/solvers/prop/cover_goals.cpp
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/prop/prop_minimize.cpp
  src/solvers/qbf/qdimacs_cnf.cpp
  src/solvers/refinement/bv_refinement_loop.cpp
  src/solvers/refinement/refine_arrays.cpp
  src/solvers/smt2/smt2_dec.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2irep.cpp
  src/solvers/strings/string_constraint_generator_format.cpp
  src/util/byte_operators.cpp
  src/util/config.cpp
  src/util/ieee_float.cpp
Labels: blocker

#4595 field_sensitivityt::apply does not take a reference
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/field_sensitivity.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_dereference.cpp
Labels: Symbolic Execution, cleanup

#4597 use optional for json file name
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  src/goto-analyzer/taint_analysis.cpp
  src/goto-analyzer/taint_analysis.h
Labels: cleanup

#4563 Export-function-local-symbols name mangling: rename initial values
  regression/Makefile
  regression/goto-cc-file-local/Makefile
  regression/goto-cc-file-local/chain.sh
  regression/goto-cc-file-local/function-pointer/main.c
  regression/goto-cc-file-local/function-pointer/test.desc
  src/goto-programs/name_mangler.h
  src/util/rename_symbol.h
Labels: bugfix

#4579 instructiont construction
  jbmc/unit/java_bytecode/goto-programs/remove_virtual_functions_without_fallback.cpp
  src/analyses/goto_check.cpp
  src/goto-instrument/unwind.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_function_call.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_instrumentation.cpp
Labels: cleanup

#4598 use apply in cover_util
  regression/cbmc-cover/mcdc1/test.desc
  regression/cbmc-cover/mcdc2/test.desc
  regression/cbmc-cover/mcdc4/test.desc
  regression/cbmc-cover/mcdc5/test.desc
  src/goto-instrument/cover_util.cpp
Labels: cleanup

#4488 Permit selectively disabling generated assertions
  doc/cprover-manual/properties.md
  regression/cbmc/pragma_cprover1/main.c
  regression/cbmc/pragma_cprover1/test.desc
  src/analyses/goto_check.cpp
  src/ansi-c/ansi_c_parser.h
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
Labels: new feature

#4464 Use sharing_mapt to store propagation map
  src/goto-symex/goto_state.cpp
  src/goto-symex/goto_state.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_dead.cpp
  src/goto-symex/symex_goto.cpp
Labels: Needs data, Performance Optimisations, Symbolic Execution

#4620 clean up lower_java_new
  jbmc/src/java_bytecode/remove_java_new.cpp
Labels: Java Front End, cleanup

#4619 expr2java: use .name in case there is no pretty name
  jbmc/src/java_bytecode/expr2java.cpp
Labels: Java Front End

#4618 Java class typet methodt
  jbmc/src/java_bytecode/java_types.h
Labels: Java Front End

#4624 rename add_throws_exceptions
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_types.h
Labels: Java Front End

#4505 Use the sharing map for the renaming level maps
  src/goto-symex/auto_objects.cpp
  src/goto-symex/goto_state.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/renaming_level.cpp
  src/goto-symex/renaming_level.h
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_start_thread.cpp
Labels: Do not merge, Needs data, Performance Optimisations

#4625 update buildspec to include JDK version
  buildspec-linux-clang.yml
  buildspec-linux-cmake-gcc.yml
  buildspec.yml
Labels: Build

#4622 C front-end: Do not lose comments in type checking
  regression/cbmc/pragma_cprover2/main.c
  regression/cbmc/pragma_cprover2/test.desc
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, bugfix

#1992 Enable HASH_CODE by default to avoid repeated hash computation [blocks: #3486]
  src/solvers/smt2/letify.h
  src/solvers/smt2/smt2_conv.h
  src/util/irep.cpp
  src/util/irep.h
  unit/util/irep.cpp
Labels: blocker

#4636 move gcc_version.h/.cpp to ansi-c
  src/ansi-c/Makefile
  src/ansi-c/gcc_version.cpp
  src/ansi-c/gcc_version.h
  src/goto-cc/Makefile
  src/goto-cc/gcc_mode.h
Labels: C Front End

#4646 Default fall-through for function pointer removal
  regression/cbmc/Function_Pointer18/main.c
  regression/cbmc/Function_Pointer18/test.desc
  src/goto-programs/remove_function_pointers.cpp
Labels: bugfix

#4642 Refactoring of symex_assign_symbol
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/postcondition.cpp
  src/goto-symex/precondition.cpp
  src/goto-symex/renaming_level.cpp
  src/goto-symex/renaming_level.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_decl.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_start_thread.cpp
Labels: Symbolic Execution, cleanup

#4627 Fix simplification of pointer-object comparison [blocks: #4628]
  src/util/simplify_expr_pointer.cpp
  unit/util/simplify_expr.cpp
Labels: blocker, bugfix

#4652 Refactor forward_list use in irept
  src/util/forward_list_as_map.h
  src/util/irep.cpp
  src/util/irep.h
  src/util/merge_irep.cpp
Labels: cleanup

#4444 Symex: resolve pointer comparisons using the value-set
  jbmc/regression/jbmc/exception-cleanup/test.desc
  jbmc/regression/jbmc/exception-cleanup/vccs.desc
  regression/cbmc/symex_should_evaluate_simple_pointer_conditions/test.c
  regression/cbmc/symex_should_evaluate_simple_pointer_conditions/test.desc
  src/goto-symex/renaming_level.h
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_dereference.h
Labels: Do not merge

#4629 fix up __float128 and _Float128 support
  regression/ansi-c/gcc_version1/gcc-5.c
  regression/ansi-c/gcc_version1/gcc-7.c
  regression/cbmc/ts18661_typedefs/main.c
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/ansi_c_parser.h
  src/ansi-c/gcc_version.cpp
  src/ansi-c/gcc_version.h
  src/ansi-c/scanner.l
  src/cbmc/cbmc_parse_options.cpp
  src/cpp/cpp_parser.cpp
  src/goto-cc/gcc_mode.cpp
  src/util/config.cpp
  src/util/config.h
Labels: C Front End

#4560 C++ front-end: Declarator to symbol conversion follows C implementation [depends-on: #4559]
  regression/cbmc-cpp/CMakeLists.txt
  regression/cbmc-cpp/Makefile
  regression/cbmc-cpp/gcc_attributes1/main.cpp
  regression/cbmc-cpp/gcc_attributes1/test.desc
  src/cpp/Makefile
  src/cpp/cpp_declarator.h
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_storage_spec.cpp
  src/cpp/cpp_storage_spec.h
  src/cpp/parse.cpp
Labels: C++ Front End, bugfix

#2212 Revert "property_checkert interface"
  src/goto-programs/Makefile
  src/goto-programs/property_checker.cpp
  src/goto-programs/property_checker.h
Labels: cleanup

#4659 Regression test for null-pointer optimisation
  regression/cbmc/null4/main.c
  regression/cbmc/null4/test.desc
Labels: Tests

#4661 smt2 frontend: check the number of types of function arguments
  regression/smt2_solver/function-applications/function-application3.desc
  regression/smt2_solver/function-applications/function-application3.smt2
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
Labels: Solvers, enhancement

#4628 C front-end: type check arguments to built-in functions
  regression/cbmc/r_w_ok4/main.c
  regression/cbmc/r_w_ok4/test.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, bugfix

#4662 Fix compiler warning about polymorphic exception
  src/memory-analyzer/analyze_symbol.cpp
Labels: bugfix

#4663 Fix bug where an item was not added to the delta view of the sharing map
  src/util/sharing_map.h
  unit/util/sharing_map.cpp
Labels: bugfix

#4438 Memory snapshot support for pointers and structs [blocks: #4482]
  regression/CMakeLists.txt
  regression/Makefile
  regression/memory-analyzer/pointer_to_struct_01/test.desc
  regression/snapshot-harness/CMakeLists.txt
  regression/snapshot-harness/Makefile
  regression/snapshot-harness/arrays_01/main.c
  regression/snapshot-harness/arrays_01/test.desc
  regression/snapshot-harness/chain.sh
  regression/snapshot-harness/pointer_01/main.c
  regression/snapshot-harness/pointer_01/test.desc
  regression/snapshot-harness/pointer_02/main.c
  regression/snapshot-harness/pointer_02/test.desc
  regression/snapshot-harness/pointer_03/main.c
  regression/snapshot-harness/pointer_03/test.desc
  regression/snapshot-harness/pointer_04/main.c
  regression/snapshot-harness/pointer_04/test.desc
  regression/snapshot-harness/pointer_05/main.c
  regression/snapshot-harness/pointer_05/test.desc
  regression/snapshot-harness/pointer_06/main.c
  regression/snapshot-harness/pointer_06/test.desc
  regression/snapshot-harness/pointer_to_struct_01/main.c
  regression/snapshot-harness/pointer_to_struct_01/test.desc
  regression/snapshot-harness/structs_01/main.c
  regression/snapshot-harness/structs_01/test.desc
  regression/snapshot-harness/union_01/main.c
  regression/snapshot-harness/union_01/test.desc
  src/goto-harness/memory_snapshot_harness_generator.cpp
  src/goto-harness/memory_snapshot_harness_generator.h
  src/memory-analyzer/analyze_symbol.cpp
  src/memory-analyzer/analyze_symbol.h
  src/memory-analyzer/gdb_api.h
Labels: blocker

#4669 Introduce getters/setters for java class properties
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_entry_point.cpp
  jbmc/src/java_bytecode/java_types.h
Labels: Java Front End, cleanup

#4611 Document and refactor goto check
  src/analyses/goto_check.cpp
Labels: cleanup

#4491 fix sorting in symbol_table_baset::show
  src/goto-programs/show_symbol_table.cpp
  src/util/symbol_table_base.cpp
  src/util/symbol_table_base.h
Labels: bugfix

#4672 Add an API for lambda expressions [blocks: #4651]
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/util/simplify_expr_array.cpp
  src/util/std_expr.h
Labels: blocker

#4673 Record constraints of indexed access to array constants [blocks: #2108]
  regression/cbmc/array-tests/uf-always.c
  regression/cbmc/array-tests/uf-always.desc
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/arrays.h
Labels: blocker, bugfix

#4671 add further == operators for patternt
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/pattern.h
Labels: Java Front End, cleanup

#4239 Move printf to C library and support return values
  doc/cprover-manual/api.md
  regression/cbmc-library/printf-01/main.c
  regression/cbmc-library/printf-01/test.desc
  regression/cbmc/printf1/test.desc
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/library/cprover.h
  src/ansi-c/library/stdio.c
  src/goto-programs/builtin_functions.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_builtin_functions.cpp
Labels: bugfix

#4677 Directly deal with mnemonic suffixes
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
Labels: Java Front End

#4666 Make sure pragmas propagate to all source locations
  regression/cbmc/pragma_cprover2/main.c
  src/analyses/goto_check.cpp
  src/ansi-c/ansi_c_parser.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
  src/util/irep_ids.def
  src/util/source_location.h
Labels: C Front End, bugfix

#4651 Byte-operator lowering: use lambda_exprt for non-constant width
  regression/cbmc-library/memcpy-04/main.c
  regression/cbmc-library/memcpy-04/test.desc
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/arrays.h
  src/solvers/lowering/byte_operators.cpp
Labels: Needs rebase, enhancement

#4686 Fix value-set-based pointer test resolution for non-deterministic pointer values
  regression/cbmc/double_deref/double_deref_with_pointer_arithmetic.desc
  regression/cbmc/double_deref/double_deref_with_pointer_arithmetic_single_alias.desc
  regression/cbmc/null5/main.c
  regression/cbmc/null5/test.desc
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#4688 fix for handling of wchars on windows in getting the directory name [blocks: #4678]
  src/util/file_util.cpp
Labels: blocker, bugfix

#4692 Extract equation_symbol_mapping to its own files
  src/solvers/Makefile
  src/solvers/strings/equation_symbol_mapping.cpp
  src/solvers/strings/equation_symbol_mapping.h
  src/solvers/strings/string_refinement.cpp
  src/solvers/strings/string_refinement_util.cpp
  src/solvers/strings/string_refinement_util.h
Labels: cleanup

#4697 Value-set filtering: gracefully handle pointer arithmetic
  regression/cbmc/Pointer_Arithmetic16/main.c
  regression/cbmc/Pointer_Arithmetic16/test.desc
  src/goto-symex/symex_goto.cpp
Labels: bugfix

#4711 Fix segmentation fault with empty array
  regression/cbmc/array-tests/zero-sized.c
  regression/cbmc/array-tests/zero-sized.desc
  src/solvers/flattening/boolbv_index.cpp
Labels: bugfix

#4710 build_reference_to must consider the offset when returning a null object
  regression/cbmc/null6/main.c
  regression/cbmc/null6/test.desc
  src/pointer-analysis/value_set_dereference.cpp
Labels: bugfix

#4708 fix result type of aaload
  jbmc/src/java_bytecode/bytecode_info.cpp
Labels: Java Front End, bugfix

#4712 Fix unbounded recursion in byte-update lowering of structs
  regression/cbmc/byte_update11/main.c
  regression/cbmc/byte_update11/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#4716 Support va_list types defined via one-element arrays
  regression/cbmc/va_list4/main.c
  regression/cbmc/va_list4/test.desc
  src/goto-programs/builtin_functions.cpp
Labels: enhancement

#4719 rename simplify_inequality_* methods
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#4720 Refactoring simplify_inequality_*
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#4727 Remove duplicate json Makefile entry
  src/cbmc/Makefile
Labels: Build, cleanup

#4715 process_array_expr: abort upon reaching a failed_symbol
  regression/cbmc/void_pointer5/main.c
  regression/cbmc/void_pointer5/test.desc
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_goto.cpp
  src/pointer-analysis/add_failed_symbols.h
Labels: Symbolic Execution, bugfix

#4726 Remove duplicate __builtin_isgreater condition
  src/goto-programs/builtin_functions.cpp
Labels: cleanup

#4722 introduce make_boolean_expr
  src/ansi-c/c_typecheck_expr.cpp
  src/util/expr.h
  src/util/expr_util.cpp
  src/util/expr_util.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_floatbv.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#4691 Remove now-unused bitvector conversion exceptions
  src/goto-symex/equation_conversion_exceptions.h
  src/goto-symex/symex_target_equation.cpp
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_byte_update.cpp
  src/solvers/flattening/boolbv_equality.cpp
  src/solvers/flattening/bv_conversion_exceptions.h
  src/solvers/lowering/byte_operators.cpp
  src/solvers/lowering/flatten_byte_extract_exceptions.h
  src/util/Makefile
  src/util/throw_with_nested.h
  src/util/unwrap_nested_exception.cpp
  src/util/unwrap_nested_exception.h
Labels: cleanup

#4670 sort bytecode_info table by bytecode
  jbmc/src/java_bytecode/bytecode_info.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_bytecode_parse_tree.cpp
  jbmc/src/java_bytecode/java_bytecode_parse_tree.h
  jbmc/src/java_bytecode/java_bytecode_parser.cpp
  jbmc/src/java_bytecode/java_local_variable_table.cpp
  jbmc/unit/java-testing-utils/require_parse_tree.cpp
Labels: Java Front End

#4695 Extract string dependencies into its own files
  jbmc/unit/solvers/strings/string_refinement/dependency_graph.cpp
  src/solvers/Makefile
  src/solvers/strings/string_dependencies.cpp
  src/solvers/strings/string_dependencies.h
  src/solvers/strings/string_refinement.cpp
  src/solvers/strings/string_refinement.h
  src/solvers/strings/string_refinement_util.cpp
  src/solvers/strings/string_refinement_util.h
Labels: cleanup

#4678 Update generate_vcxproj to work with current source tree
  buildspec-windows.yml
  scripts/generate_vcxproj
  scripts/vcxproj.1
Labels: Build, bugfix

#4728 Cast va_list type as needed
  regression/cbmc/va_list2/main.c
  regression/cbmc/va_list2/test.desc
  src/goto-programs/builtin_functions.cpp
Labels: enhancement

#4626 String solver: stop relying on array size
  jbmc/regression/jbmc-strings/literal_length/test.class
  jbmc/regression/jbmc-strings/literal_length/test.desc
  jbmc/regression/jbmc-strings/literal_length/test.java
  jbmc/unit/solvers/strings/string_constraint_instantiation/instantiate_not_contains.cpp
  src/solvers/strings/array_pool.cpp
  src/solvers/strings/array_pool.h
  src/solvers/strings/string_builtin_function.cpp
  src/solvers/strings/string_builtin_function.h
  src/solvers/strings/string_constraint_generator.h
  src/solvers/strings/string_constraint_generator_code_points.cpp
  src/solvers/strings/string_constraint_generator_comparison.cpp
  src/solvers/strings/string_constraint_generator_concat.cpp
  src/solvers/strings/string_constraint_generator_constants.cpp
  src/solvers/strings/string_constraint_generator_float.cpp
  src/solvers/strings/string_constraint_generator_format.cpp
  src/solvers/strings/string_constraint_generator_indexof.cpp
  src/solvers/strings/string_constraint_generator_insert.cpp
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_constraint_generator_testing.cpp
  src/solvers/strings/string_constraint_generator_transformation.cpp
  src/solvers/strings/string_constraint_generator_valueof.cpp
  src/solvers/strings/string_refinement.cpp
  src/util/string_expr.h
Labels: Needs TG approval :owl:

#4739 Revert "Test build of vcxproj files in CI"
  buildspec-msbuild.yml
  buildspec-windows.yml
Labels: Build

#4698 Cleanups in loading of jar files
  jbmc/src/java_bytecode/jar_file.cpp
  jbmc/src/java_bytecode/jar_file.h
  jbmc/src/java_bytecode/jar_pool.cpp
  jbmc/src/java_bytecode/mz_zip_archive.cpp
  jbmc/src/java_bytecode/mz_zip_archive.h
Labels: Needs rebase

#4733 Unit test ssa_exprt
  unit/Makefile
  unit/util/ssa_expr.cpp
Labels: Tests, cleanup
