Repository diffblue/cbmc, pull requests merged in 2019-10, with the labels that each got.

#5133 Do not ignore invalid command line options in JSON/XML interface [TG-9049]
  regression/cbmc/json-interface1/test_wrong_flag.desc
  regression/cbmc/json-interface1/test_wrong_flag.json
  regression/cbmc/json-interface1/test_wrong_option.desc
  regression/cbmc/json-interface1/test_wrong_option.json
  regression/cbmc/xml-interface1/test_wrong_flag.desc
  regression/cbmc/xml-interface1/test_wrong_flag.xml
  regression/cbmc/xml-interface1/test_wrong_option.desc
  regression/cbmc/xml-interface1/test_wrong_option.xml
  src/goto-cc/goto_cc_cmdline.h
  src/util/cmdline.cpp
  src/util/cmdline.h
  src/xmllang/xml_interface.cpp
Labels: Do not merge

#5143 SMT2 parser: use hash tables instead of if() ... else...
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
  src/solvers/smt2/smt2_solver.cpp
Labels: Solvers, enhancement

#4992 let_exprt can now do multiple bindings
  src/util/irep_ids.def
  src/util/mathematical_expr.h
  src/util/std_expr.cpp
  src/util/std_expr.h
Labels: enhancement

#5160 Let with multiple bindings
  src/solvers/flattening/boolbv_let.cpp
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_parser.cpp
Labels: SMT Backend Interface, Solvers, enhancement

#5158 SMT-LIB2 parameter/let/quantifier scopes
  regression/smt2_solver/function-applications/function-scoping1.desc
  regression/smt2_solver/function-applications/function-scoping1.smt2
  regression/smt2_solver/let1/let-scoping1.desc
  regression/smt2_solver/let1/let-scoping1.smt2
  regression/smt2_solver/quanitfiers/quantifier-scoping.desc
  regression/smt2_solver/quanitfiers/quantifier-scoping.smt2
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
Labels: Solvers, Tests, bug

#5163 smt2 parser: track a 'kind' for all identifiers
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
Labels: Solvers, enhancement

#5124 remove deprecated bison option
  src/jsil/parser.y
  src/xmllang/parser.y
Labels: Build

#5164 Make virtual the destructor for symex_complexity_limit_exceeded_actiont.
  src/goto-symex/symex_complexity_limit_exceeded_action.h
Labels: bugfix

#5012 fix exprt::opX accesses in linker_script_merge
  src/goto-cc/linker_script_merge.cpp
Labels: cleanup

#5154 ansi-c: explicit casts from structs to structs
  regression/ansi-c/Initializer_cast1/main.c
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End

#5076 Fix accesses to exprt::opX() in ansi-c/
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
Labels: cleanup

#4984 fix exprt::opX() accesses in cpp/
  src/cpp/cpp_constructor.cpp
  src/cpp/cpp_static_assert.h
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_fargs.cpp
  src/cpp/cpp_typecheck_function.cpp
  src/cpp/cpp_typecheck_initializer.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/expr2cpp.cpp
Labels: cleanup
