Repository diffblue/cbmc, pull requests merged in 2019-04, with the labels that each got.

#4462 Remove value_sett::idt [blocks: #4463]
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set.h
Labels: blocker, cleanup

#4469 C++ front-end: parameter symbols are file- and thread-local
  src/cpp/cpp_typecheck_function.cpp
Labels: C++ Front End, bugfix

#4468 C++: Add support for indexed access to bitvectors
  regression/systemc/BitvectorCpp2/main.cpp
  regression/systemc/BitvectorCpp2/test.desc
  src/cpp/cpp_typecheck_code.cpp
Labels: C++ Front End, bugfix

#4409 Allow `static` attribute to be stripped from symbols
  regression/CMakeLists.txt
  regression/goto-cc-file-local/CMakeLists.txt
  regression/goto-cc-file-local/chain.sh
  regression/goto-cc-file-local/result-multi-file-bad/foo.c
  regression/goto-cc-file-local/result-multi-file-bad/main.c
  regression/goto-cc-file-local/result-multi-file-bad/test.desc
  regression/goto-cc-file-local/result-multi-file-good/foo.c
  regression/goto-cc-file-local/result-multi-file-good/main.c
  regression/goto-cc-file-local/result-multi-file-good/test.desc
  regression/goto-cc-file-local/result-multi-file-transitive/foo.c
  regression/goto-cc-file-local/result-multi-file-transitive/main.c
  regression/goto-cc-file-local/result-multi-file-transitive/test.desc
  regression/goto-cc-file-local/result-suffix/foo.c
  regression/goto-cc-file-local/result-suffix/main.c
  regression/goto-cc-file-local/result-suffix/test.desc
  regression/goto-cc-file-local/symbol-compiled/main.c
  regression/goto-cc-file-local/symbol-compiled/test.desc
  regression/goto-cc-file-local/symbol-fully-linked/main.c
  regression/goto-cc-file-local/symbol-fully-linked/test.desc
  regression/goto-cc-file-local/symbol-multi-file/foo.c
  regression/goto-cc-file-local/symbol-multi-file/main.c
  regression/goto-cc-file-local/symbol-multi-file/test.desc
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/ansi_c_language.h
  src/cpp/cpp_language.h
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
  src/goto-cc/gcc_cmdline.cpp
  src/goto-cc/ms_cl_cmdline.cpp
  src/goto-programs/Makefile
  src/goto-programs/name_mangler.cpp
  src/goto-programs/name_mangler.h
  src/langapi/language.h
  src/langapi/language_file.cpp
  src/langapi/language_file.h
  src/linking/remove_internal_symbols.cpp
  src/linking/remove_internal_symbols.h
Labels: C Front End, Instrumentations, enhancement, new feature

#4457 Replace fresh_java_symbol in object factory
  jbmc/src/java_bytecode/java_object_factory.cpp
Labels: RFC, cleanup

#4480 Get lhs_object from byte_extract for goto trace
  regression/cbmc/xml-trace/main.c
  regression/cbmc/xml-trace/test.desc
  src/goto-programs/goto_trace.cpp
Labels: bugfix

#4197 Do not generate nil_exprt in bv_get
  regression/cbmc/memory_allocation1/test.desc
  regression/cbmc/trace-values/unbounded_array.c
  regression/cbmc/trace-values/unbounded_array.desc
  regression/cbmc/union12/test.desc
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
Labels: Needs TG approval :owl:, bugfix

#4483 Add precondition that pointers point to structs in the object factory
  jbmc/src/java_bytecode/java_object_factory.cpp
Labels: cleanup

#4472 Handle ID_cpp_name in expr2cppt
  src/cpp/expr2cpp.cpp
Labels: C++ Front End

#4475 C++ front-end: Enable compilation with DEBUG defined [blocks: #1260]
  src/cpp/cpp_declaration.cpp
  src/cpp/cpp_declarator.cpp
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_namespace_spec.cpp
  src/cpp/cpp_scopes.cpp
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_declaration.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_method_bodies.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/parse.cpp
Labels: C++ Front End, blocker, cleanup

#4489 Prevent potential string solver failures
  jbmc/regression/jbmc-strings/StringConcat/Test.class
  jbmc/regression/jbmc-strings/StringConcat/Test.java
  jbmc/regression/jbmc-strings/StringConcat/test_string_nondet_array.desc
  src/solvers/strings/string_refinement.cpp
Labels: String solver, bugfix

#4490 Introduce java_reference_typet
  jbmc/src/java_bytecode/java_types.cpp
  jbmc/src/java_bytecode/java_types.h
Labels: Java Front End

#4493 introduce java_class_typet::componentt
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/unit/java-testing-utils/require_type.cpp
  jbmc/unit/java-testing-utils/require_type.h
  jbmc/unit/java_bytecode/java_bytecode_language/language.cpp
  src/util/std_types.h
Labels: Java Front End

#4471 C++ destructors: Ensure "this" is a fully qualified name
  regression/cbmc-cpp/cpp1/test.desc
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_destructor.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_fargs.cpp
  src/cpp/cpp_typecheck_function.cpp
  src/cpp/cpp_typecheck_initializer.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_type.cpp
Labels: C++ Front End, bugfix

#4496 clean up the includes in prop_conv.h
  src/goto-checker/goto_symex_property_decider.cpp
  src/solvers/flattening/functions.h
  src/solvers/prop/cover_goals.cpp
  src/solvers/prop/prop_conv.h
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_dec.h
Labels: Solvers, cleanup

#4498 Fix bug in the printing of double for limit values
  jbmc/regression/jbmc/double1/double1.class
  jbmc/regression/jbmc/double1/double1.java
  jbmc/regression/jbmc/double1/test-limit.desc
  jbmc/src/java_bytecode/expr2java.h
Labels: bugfix

#4501 Model GCC's __builtin_clz{,l,ll}
  regression/cbmc/gcc_clz1/main.c
  regression/cbmc/gcc_clz1/test.desc
  src/ansi-c/library/gcc.c
Labels: C Front End

#4506 Remove unused class_identifier parameter from Java object factory
  jbmc/src/java_bytecode/java_object_factory.cpp
Labels: cleanup

#4502 Ensure Java stubbing names parameters [blocks: #4485]
  jbmc/src/java_bytecode/simple_method_stubbing.cpp
  src/goto-programs/goto_convert_functions.cpp
Labels: blocker, bugfix

#4485 Extend and cleanup usability of __CPROVER_{r,w}_ok
  regression/cbmc/r_w_ok1/main.c
  regression/cbmc/r_w_ok1/test.desc
  regression/cbmc/r_w_ok2/main.c
  regression/cbmc/r_w_ok2/test.desc
  regression/cbmc/r_w_ok3/main.c
  regression/cbmc/r_w_ok3/test.desc
  src/analyses/goto_check.cpp
Labels: bugfix

#4512 goto_instrument_parse_options is not a message
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
Labels: cleanup

#4516 cbmc_parse_options is not a messaget
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
Labels: cleanup

#4515 Clean up usage of messaget in *_parse_options classes
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/janalyzer/janalyzer_parse_options.h
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.h
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-diff/goto_diff_parse_options.h
  src/goto-harness/goto_harness_parse_options.cpp
  src/goto-harness/goto_harness_parse_options.h
Labels: cleanup

#4519 Use bv_typet to fix type consistency in byte-operator lowering
  regression/cbmc/Bitfields3/paths.desc
  regression/cbmc/Bitfields3/test.desc
  regression/cbmc/Malloc23/test.desc
  regression/cbmc/Pointer_Arithmetic11/test.desc
  regression/cbmc/Pointer_byte_extract2/test.desc
  regression/cbmc/Pointer_byte_extract9/test.desc
  regression/cbmc/Quantifiers-assignment/test.desc
  regression/cbmc/byte_update3/test.desc
  regression/cbmc/byte_update5/test.desc
  regression/cbmc/memory_allocation2/test.desc
  src/solvers/flattening/boolbv_typecast.cpp
  src/solvers/lowering/byte_operators.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_int.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: bugfix

#4497 decision_proceduret interface
  src/solvers/prop/decision_procedure.h
  src/solvers/prop/prop_conv.cpp
  src/solvers/prop/prop_conv.h
Labels: Solvers

#4528 Makefile builds: fix goto-harness build dependencies
  src/Makefile
Labels: Build, bugfix

#4527 Support typecast from bv_typet to pointer_typet
  regression/cbmc/Typecast3/main.c
  regression/cbmc/Typecast3/test.desc
  src/solvers/flattening/bv_pointers.cpp
Labels: bugfix

#4529 functions lowering does not need prop_convt
  src/solvers/lowering/functions.cpp
  src/solvers/lowering/functions.h
Labels: Solvers, cleanup

#4500 prop_conv_solvert::get_bool now returns optional
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/prop/prop_conv_solver.h
Labels: Solvers

#4526 NULL compares equal to 0
  regression/cbmc/union13/main.c
  regression/cbmc/union13/no-arch.desc
  regression/cbmc/union13/test.desc
  src/util/simplify_expr_int.cpp
Labels: bugfix

#4524 Use constructors with fewer parameters if possible, for dereference_exprt and plus_exprt
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_pointer_casts.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  src/analyses/goto_check.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-instrument/wmm/shared_buffers.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/class_identifier.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_instrumentation.cpp
  src/goto-symex/symex_dereference.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#4531 Move decision_procedure.h [depends-on: #4530]
  jbmc/src/jbmc/bmc.h
  jbmc/src/jbmc/module_dependencies.txt
  src/goto-instrument/accelerate/scratch_program.cpp
  src/solvers/Makefile
  src/solvers/decision_procedure.cpp
  src/solvers/decision_procedure.h
  src/solvers/lowering/functions.h
  src/solvers/prop/cover_goals.h
  src/solvers/prop/module_dependencies.txt
  src/solvers/prop/prop_conv.h
  src/solvers/prop/prop_conv_solver.h
Labels: Solvers, dependent - do not merge

#2318 C++ function disambiguation and template scope cleanup [blocks: #1260]
  regression/systemc/BitvectorSc1/main.cpp
  regression/systemc/BitvectorSc2/main.cpp
  regression/systemc/BitvectorSc3/test.desc
  regression/systemc/EqualOp1/main.cpp
  regression/systemc/EqualOp2/main.cpp
  regression/systemc/EqualOp3/main.cpp
  regression/systemc/ForwardDecl1/test.desc
  regression/systemc/FunTempl1/main.cpp
  regression/systemc/Mult1/test.desc
  regression/systemc/SimpleSc1/main.cpp
  regression/systemc/Template1/main.cpp
  regression/systemc/Tuple1/test.desc
  regression/systemc/Tuple2/test.desc
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_id.h
  src/cpp/cpp_instantiate_template.cpp
  src/cpp/cpp_scope.h
  src/cpp/cpp_scopes.cpp
  src/cpp/cpp_typecheck.h
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_template.cpp
  src/cpp/expr2cpp.cpp
Labels: C++ Front End, blocker, bugfix

#4532 Java bytecode conversion: inline or move temporaries
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
Labels: Java Front End, cleanup

#2574 Field sensitive goto-symex
  jbmc/regression/jbmc-generics/constant_propagation/test.desc
  jbmc/regression/jbmc-strings/ClassName/test.desc
  regression/cbmc-concurrency/norace_struct1/test.desc
  regression/cbmc/Array_Propagation1/main.c
  regression/cbmc/Array_Propagation1/test.desc
  regression/cbmc/Struct_Propagation1/main.c
  regression/cbmc/Struct_Propagation1/test.desc
  regression/cbmc/variable-access-to-constant-array/test.desc
  regression/goto-harness/nondet_elements_longer_lists/test.desc
  regression/goto-harness/nondet_elements_longer_lists_global/test.desc
  src/goto-symex/Makefile
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/field_sensitivity.h
  src/goto-symex/goto_symex.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_dead.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_goto.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set.h
  src/util/ssa_expr.cpp
  src/util/ssa_expr.h
Labels: Epic, Needs TG approval :owl:, Symbolic Execution

#4542 use iterator in find_qvar instead of visitor
  src/solvers/strings/string_refinement.cpp
Labels: String solver, cleanup

#4535 Move array_poolt class to its own files
  src/solvers/Makefile
  src/solvers/strings/array_pool.cpp
  src/solvers/strings/array_pool.h
  src/solvers/strings/string_constraint_generator.h
  src/solvers/strings/string_constraint_generator_main.cpp
Labels: cleanup

#4402 exprt::visit post-order traversal variant
  src/util/expr.cpp
  src/util/expr.h
Labels: Needs rebase

#4541 Symex-driven lazy loading uses goto-checker [blocks: #2212]
  jbmc/src/jbmc/Makefile
  jbmc/src/jbmc/all_properties.cpp
  jbmc/src/jbmc/all_properties_class.h
  jbmc/src/jbmc/bmc.cpp
  jbmc/src/jbmc/bmc.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  src/goto-checker/all_properties_verifier.h
  src/goto-checker/multi_path_symex_only_checker.cpp
  src/goto-checker/properties.cpp
  src/goto-checker/properties.h
  src/goto-checker/single_path_symex_only_checker.cpp
  src/goto-symex/README.md
  src/goto-symex/goto_symex.h
  src/solvers/README.md
Labels: Goto-checker, blocker

#4521 Clean-up message_handler of parse_options_baset
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/janalyzer/janalyzer_parse_options.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-diff/goto_diff_parse_options.h
  src/goto-harness/goto_harness_main.cpp
  src/goto-harness/goto_harness_parse_options.cpp
  src/goto-harness/goto_harness_parse_options.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-programs/show_goto_functions.cpp
  src/goto-programs/show_goto_functions.h
  src/goto-programs/show_properties.cpp
  src/goto-programs/show_properties.h
  src/util/parse_options.cpp
  src/util/parse_options.h
  unit/compound_block_locations.cpp
  unit/path_strategies.cpp
Labels: cleanup

#4545 Create SSA-level 2 names for individual fields
  regression/cbmc/struct14/main.c
  regression/cbmc/struct14/test.desc
  src/goto-symex/symex_decl.cpp
Labels: Symbolic Execution, bugfix

#4533 goto_symex now uses decision_proceduret API
  src/goto-checker/bmc_util.cpp
  src/goto-checker/bmc_util.h
  src/goto-checker/counterexample_beautification.cpp
  src/goto-checker/goto_symex_fault_localizer.cpp
  src/goto-checker/goto_symex_fault_localizer.h
  src/goto-checker/goto_symex_property_decider.cpp
  src/goto-checker/multi_path_symex_checker.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/build_goto_trace.h
  src/goto-symex/ssa_step.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: Symbolic Execution

#4548 move goto_functionst::validate into .cpp file
  src/goto-programs/goto_functions.cpp
  src/goto-programs/goto_functions.h
Labels: cleanup

#4551 C++ front-end: store typedef names
  regression/cbmc-cpp/typedef1/main.cpp
  regression/cbmc-cpp/typedef1/test.desc
  src/cpp/cpp_declarator_converter.cpp
Labels: C++ Front End

#4549 avoid access to exprt::opX
  src/goto-programs/adjust_float_expressions.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-programs/goto_inline_class.cpp
Labels: cleanup

#4564 Fix L2 renaming after shift-to-rhs and enable validation
  regression/cbmc-concurrency/CMakeLists.txt
  regression/cbmc-concurrency/Makefile
  regression/cbmc/CMakeLists.txt
  regression/cbmc/Makefile
  src/goto-symex/symex_assign.cpp
Labels: Symbolic Execution, bugfix

#4557 Regression tests: Ensure __LINE__ is expanded
  regression/ansi-c/Struct_Bitfields1/main.c
  regression/ansi-c/Struct_Enum_Padding1/main.c
  regression/ansi-c/Struct_Initialization1/main.c
  regression/ansi-c/Struct_Initialization2/main.c
  regression/ansi-c/Struct_Padding2/main.c
  regression/ansi-c/Struct_Padding3/main.c
  regression/ansi-c/Struct_Padding4/main.c
  regression/ansi-c/Struct_Padding5/main.c
  regression/ansi-c/Struct_Padding6/main.c
  regression/ansi-c/Union_Padding1/main.c
  regression/ansi-c/Universal_characters1/main.c
  regression/ansi-c/_Alignof1/main.c
  regression/ansi-c/_Bool1/main.c
  regression/ansi-c/_Generic1/main.c
  regression/ansi-c/array_initialization1/main.c
  regression/ansi-c/array_initialization3/main.c
  regression/ansi-c/bitfields1/main.c
  regression/ansi-c/character_literals1/main.c
  regression/ansi-c/cprover_bool1/main.c
  regression/ansi-c/enum3/main.c
  regression/ansi-c/float_constant1/main.c
  regression/ansi-c/gcc_attributes10/main.c
  regression/ansi-c/gcc_attributes3/main.c
  regression/ansi-c/gcc_attributes4/main.c
  regression/ansi-c/gcc_attributes5/main.c
  regression/ansi-c/gcc_attributes6/main.c
  regression/ansi-c/gcc_attributes8/main.c
  regression/ansi-c/gcc_builtins2/main.c
  regression/ansi-c/gcc_builtins4/main.c
  regression/ansi-c/gcc_builtins5/main.c
  regression/ansi-c/gcc_types_compatible_p1/main.c
  regression/ansi-c/gcc_types_compatible_p2/main.c
  regression/ansi-c/gcc_types_compatible_p3/main.c
  regression/ansi-c/gcc_types_compatible_p4/main.c
  regression/ansi-c/integer_constant1/main.c
  regression/ansi-c/integer_constant2/main.c
  regression/ansi-c/pragma_pack1/main.c
  regression/ansi-c/pragma_pack2/main.c
  regression/ansi-c/pragma_pack3/main.c
  regression/ansi-c/sizeof1/main.c
  regression/ansi-c/sizeof3/main.c
  regression/ansi-c/sizeof4/main.c
  regression/ansi-c/sizeof5/main.c
  regression/ansi-c/struct3/main.c
  regression/cbmc-with-incr/Struct_Padding1/main.c
  regression/cbmc-with-incr/null1/main.c
  regression/cbmc/null1/main.c
Labels: Tests, bugfix

#4566 fix calls to validate_expr in util/std_code.h
  src/util/std_code.h
Labels: bugfix

#4562 C++ front-end: default constructed PODs are constants
  regression/cpp/enum3/test.desc
  src/cpp/cpp_typecheck_expr.cpp
Labels: C++ Front End, bugfix

#4573 Split out is_in_conflict solver capability [blocks: 4577]
  src/solvers/conflict_provider.h
  src/solvers/prop/prop_conv.cpp
  src/solvers/prop/prop_conv.h
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/prop/prop_conv_solver.h
Labels: blocker

#4580 clang 8 fixes
  src/ansi-c/parser.y
  src/ansi-c/parser_static.inc
  src/ansi-c/scanner.l
  src/goto-symex/goto_state.h
  src/jsil/parser.y
  src/jsil/scanner.l
  src/pointer-analysis/value_set.h
  src/util/parser.h
  src/util/symbol_table_builder.h
Labels: bugfix

#4583 Remove unnecessary blocks
  src/cbmc/cbmc_parse_options.cpp
Labels: cleanup

#4586 remove -y bison option
  src/common
Labels: Build

#4544 Clean up in string solver
  src/solvers/strings/array_pool.cpp
  src/solvers/strings/array_pool.h
  src/solvers/strings/string_constraint_generator_code_points.cpp
  src/solvers/strings/string_constraint_generator_concat.cpp
  src/solvers/strings/string_constraint_generator_constants.cpp
  src/solvers/strings/string_constraint_generator_float.cpp
  src/solvers/strings/string_constraint_generator_format.cpp
  src/solvers/strings/string_constraint_generator_insert.cpp
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_constraint_generator_transformation.cpp
  src/solvers/strings/string_constraint_generator_valueof.cpp
  src/solvers/strings/string_constraint_instantiation.cpp
  src/solvers/strings/string_constraint_instantiation.h
  src/solvers/strings/string_refinement.cpp
Labels: String solver, cleanup

#4567 Symex: shortcut the common case of whole-struct initialisation
  jbmc/regression/jbmc-generics/constant_propagation/test.desc
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_assign.cpp
Labels: Symbolic Execution

#4565 Mangle static functions using basename, not path
  regression/goto-cc-file-local/chain.sh
  regression/goto-cc-file-local/name-clash-with-suffix/bar/main.c
  regression/goto-cc-file-local/name-clash-with-suffix/foo/main.c
  regression/goto-cc-file-local/name-clash-with-suffix/test.desc
  regression/goto-cc-file-local/name-clash/bar/main.c
  regression/goto-cc-file-local/name-clash/foo/main.c
  regression/goto-cc-file-local/name-clash/test.desc
  regression/goto-cc-file-local/nested/foo/bar/baz/main.c
  regression/goto-cc-file-local/nested/test.desc
  regression/goto-cc-file-local/result-multi-file-bad/test.desc
  regression/goto-cc-file-local/result-multi-file-good/test.desc
  regression/goto-cc-file-local/result-multi-file-transitive/test.desc
  regression/goto-cc-file-local/result-suffix/test.desc
  regression/goto-cc-file-local/symbol-compiled/test.desc
  regression/goto-cc-file-local/symbol-fully-linked/test.desc
  regression/goto-cc-file-local/symbol-multi-file/test.desc
  src/goto-cc/ms_cl_cmdline.cpp
  src/goto-programs/name_mangler.cpp
Labels: bugfix

#4589 Clean up smt2_conv
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: cleanup

#4590 Implement parsing of hexadecimal Unicode characters from JSON
  src/json/parser.y
  unit/json/json_parser.cpp
Labels: bugfix

#4311 Read "is inlined" attribute of goto functions from the symbol table [blocks: #4167]
  src/ansi-c/ansi_c_declaration.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/goto-analyzer/unreachable_instructions.cpp
  src/goto-instrument/aggressive_slicer.cpp
  src/goto-instrument/remove_function.cpp
  src/goto-programs/goto_inline.cpp
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/property_checker.cpp
  src/goto-programs/property_checker.h
Labels: blocker, cleanup

#2466 expr2c: Remove precedence parameter where unused [blocks: #2310]
  jbmc/src/java_bytecode/expr2java.cpp
  jbmc/src/java_bytecode/expr2java.h
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/cpp/expr2cpp.cpp
Labels: C Front End, C++ Front End, Java Front End, blocker, bugfix, cleanup

#3867 goto-gcc hybrid binaries on OS X
  regression/goto-gcc/CMakeLists.txt
  regression/goto-gcc/Makefile
  regression/goto-gcc/archives/foo.c
  regression/goto-gcc/archives/main.c
  regression/goto-gcc/archives/test.desc
  src/goto-cc/as_mode.cpp
  src/goto-cc/as_mode.h
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/hybrid_binary.cpp
  src/goto-cc/hybrid_binary.h
  src/goto-cc/ld_mode.cpp
  src/goto-programs/module_dependencies.txt
  src/goto-programs/osx_fat_reader.cpp
  src/goto-programs/osx_fat_reader.h
  src/goto-programs/read_goto_binary.cpp
Labels: enhancement
