Repository diffblue/cbmc, pull requests merged in 2020-11, with the labels that each got.

#5550 Remove exprt::make_bool
  src/util/expr.cpp
  src/util/expr.h
Labels: cleanup

#5390 Byte-update lowering: handle sub-byte sized bit fields
  regression/cbmc/byte_update13/main.c
  regression/cbmc/byte_update13/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: aws

#5551 Remove codet::parametert() constructor
  jbmc/src/java_bytecode/lambda_synthesis.cpp
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_method.cpp
  src/util/std_types.h
Labels: cleanup

#4296 Remove link_to_library(goto_functions, symbol_table, ...) [blocks: #4056]
  src/goto-programs/link_to_library.cpp
  src/goto-programs/link_to_library.h
Labels: blocker, cleanup

#5549 Make IPASIR support compile
  src/Makefile
  src/memory-analyzer/Makefile
  src/solvers/sat/satcheck_ipasir.cpp
  src/solvers/sat/satcheck_ipasir.h
Labels: Solvers, bugfix

#5305 Satcheck need not implement hardness_collectort
  src/goto-checker/solver_factory.cpp
Labels: Solvers, bugfix

#5548 Make Glucose support compile
  scripts/glucose-syrup-patch
  src/solvers/sat/satcheck_glucose.cpp
  src/solvers/sat/satcheck_glucose.h
Labels: Solvers, bugfix

#5553 forall_operands should not trigger any non-const operations
  src/util/expr.h
  src/util/simplify_utils.cpp
  src/util/std_expr.h
Labels: cleanup

#5556 Add missing include for std::map
  src/util/irep_hash_container.h
Labels: bugfix

#5302 C front-end: clarify string initialiser control flow
  src/ansi-c/c_typecheck_initializer.cpp
Labels: cleanup

#5555 Remove deprecated function_application_exprt constructor
  jbmc/src/java_bytecode/java_utils.cpp
  jbmc/unit/solvers/strings/string_constraint_instantiation/instantiate_not_contains.cpp
  jbmc/unit/solvers/strings/string_refinement/dependency_graph.cpp
  jbmc/unit/solvers/strings/string_refinement/string_symbol_resolution.cpp
  src/goto-programs/builtin_functions.cpp
  src/util/mathematical_expr.h
Labels: cleanup

#5554 Remove deprecated side_effect_expr*t constructors
  jbmc/src/java_bytecode/code_with_references.cpp
  jbmc/src/java_bytecode/java_entry_point.cpp
  src/util/std_code.h
Labels: cleanup

#2289 Interpreter: de-duplicate code
  regression/CMakeLists.txt
  regression/Makefile
  regression/goto-interpreter/CMakeLists.txt
  regression/goto-interpreter/Makefile
  regression/goto-interpreter/byte_extract/main.c
  regression/goto-interpreter/byte_extract/test.desc
  regression/goto-interpreter/byte_extract/union.desc
  regression/goto-interpreter/chain.sh
  regression/goto-interpreter/help-output/main.c
  regression/goto-interpreter/help-output/test.desc
  regression/goto-interpreter/memory-dump/main.c
  regression/goto-interpreter/memory-dump/test.desc
  regression/goto-interpreter/step/main.c
  regression/goto-interpreter/step/r.desc
  regression/goto-interpreter/step/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/interpreter_class.h
  src/goto-programs/interpreter_evaluate.cpp
  src/util/sparse_vector.h
Labels: Needs TG approval :owl:

#5560 Remove deprecated variants of find_symbols
  src/util/find_symbols.cpp
  src/util/find_symbols.h
Labels: cleanup

#5567 Remove unnecessary deprecate.h includes
  src/goto-programs/link_to_library.h
  src/goto-programs/read_goto_binary.h
  src/util/string_utils.h
  src/util/type.h
Labels: cleanup

#5562 Remove deprecated byte_update_exprt non-const methods
  src/util/byte_operators.h
Labels: cleanup

#5563 Remove deprecated and unused methods
  jbmc/src/java_bytecode/java_utils.cpp
  jbmc/src/java_bytecode/java_utils.h
  src/goto-programs/interpreter.cpp
  src/goto-programs/interpreter_class.h
  src/goto-symex/renaming_level.cpp
  src/goto-symex/renaming_level.h
  src/util/ssa_expr.cpp
  src/util/ssa_expr.h
Labels: cleanup

#5561 Remove deprecated exprt::move_to_operands
  src/util/expr.cpp
  src/util/expr.h
Labels: cleanup

#5566 Remove deprecated goto_programt::instructiont methods
  src/goto-instrument/value_set_fi_fp_removal.cpp
  src/goto-programs/goto_program.h
  unit/goto-programs/goto_program_table_consistency.cpp
  unit/goto-programs/goto_program_validate.cpp
Labels: cleanup

#5564 Remove deprecated methods of value sets
  jbmc/unit/pointer-analysis/custom_value_set_analysis.cpp
  src/goto-instrument/value_set_fi_fp_removal.cpp
  src/goto-symex/symex_dereference_state.cpp
  src/goto-symex/symex_dereference_state.h
  src/pointer-analysis/dereference_callback.h
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/goto_program_dereference.h
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set.h
  src/pointer-analysis/value_set_analysis.h
  src/pointer-analysis/value_set_analysis_fi.h
  src/pointer-analysis/value_set_domain.h
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fi.h
  src/pointer-analysis/value_sets.h
Labels: cleanup

#5565 Remove deprecated variant of parse_unwindset
  src/goto-instrument/unwindset.cpp
  src/goto-instrument/unwindset.h
Labels: cleanup

#5576 Fix missing includes of deprecate.h
  src/analyses/ai.h
  src/analyses/ai_domain.h
  src/analyses/ai_storage.h
Labels: Build, bugfix

#5579 Fix path to java models library
  jbmc/regression/jbmc-concurrency/CMakeLists.txt
  jbmc/regression/jbmc-concurrency/synchronized/test.desc
Labels: Tests, bugfix

#5574 Regression tests: cleanup temporary files and directories
  regression/acceleration/accelerate.sh
  regression/goto-harness-multi-file-project/chain.sh
Labels: Tests, cleanup

#5577 Fix and re-enable regression tests that use goto-cl /c
  regression/goto-cc-file-local/CMakeLists.txt
  regression/goto-cc-file-local/chain.sh
  regression/goto-cl/CMakeLists.txt
  regression/goto-cl/Fo/Fo-no-directory.desc
  regression/test.pl
Labels: Tests, bugfix

#5571 Make test identifier_names_illegal_characters work on Windows
  regression/CMakeLists.txt
  regression/goto-cc-instrument-cbmc/CMakeLists.txt
  regression/goto-cc-instrument-cbmc/Makefile
  regression/goto-cc-instrument-cbmc/chain.sh
  regression/goto-instrument/identifier_names_illegal_characters/test.c
  regression/goto-instrument/identifier_names_illegal_characters/test.desc
Labels: Tests, bugfix

#4167 Use goto_functiont::parameter_identifiers and remove goto_functiont::type
  src/assembler/remove_asm.cpp
  src/goto-checker/symex_coverage.cpp
  src/goto-harness/function_call_harness_generator.cpp
  src/goto-harness/memory_snapshot_harness_generator.cpp
  src/goto-harness/recursive_initialization.cpp
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/generate_function_bodies.cpp
  src/goto-instrument/replace_calls.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_convert_functions.h
  src/goto-programs/goto_function.cpp
  src/goto-programs/goto_function.h
  src/goto-programs/goto_functions.cpp
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/read_bin_goto_object.cpp
  src/goto-programs/remove_complex.cpp
  src/goto-programs/remove_function_pointers.cpp
  src/goto-programs/remove_returns.cpp
  src/goto-programs/remove_vector.cpp
  src/goto-symex/symex_function_call.cpp
  unit/Makefile
  unit/goto-programs/goto_model_function_type_consistency.cpp
  unit/goto-programs/remove_returns.cpp
Labels: cleanup

#5578 Make goto-harness-multi-file-project regression test work on Windows
  regression/goto-harness-multi-file-project/CMakeLists.txt
  regression/goto-harness-multi-file-project/Makefile
  regression/goto-harness-multi-file-project/chain.sh
  regression/goto-harness-multi-file-project/static_functions/test.desc
  regression/goto-harness-multi-file-project/static_symbols_referencing/test.desc
Labels: Tests, bugfix

#4731 Use std::forward_list instead of std::map in irept by default
  src/util/irep.cpp
  src/util/irep.h
  src/util/irep_hash_container.cpp
  src/util/irep_serialization.cpp
  src/util/lispirep.cpp
  src/util/merge_irep.cpp
  src/util/type.h
  unit/util/irep.cpp
Labels: Performance Optimisations

#5557 Synchronise Makefile and CMake configuration of regression tests
  regression/CMakeLists.txt
  regression/Makefile
  regression/acceleration/accelerate.sh
  regression/cbmc-sequentialization/Makefile
  regression/goto-cc-cbmc-shared-options/Makefile
  regression/goto-cc-cbmc-shared-options/chain.sh
  regression/goto-cc-cbmc/chain.sh
  regression/goto-cc-goto-analyzer/chain.sh
  regression/goto-cc-multi-file/chain.sh
  regression/goto-instrument-typedef/chain.sh
  regression/k-induction/chain.sh
  regression/symtab2gb/chain.sh
Labels: Build, bugfix

#5584 Re-enable cbmc-incr* regression tests on Windows
  regression/cbmc-incr-oneloop/CMakeLists.txt
  regression/cbmc-incr-oneloop/alarm1/test.desc
  regression/cbmc-incr-oneloop/alarm3/test.desc
  regression/cbmc-incr-oneloop/cruise1/test.desc
  regression/cbmc-incr/CMakeLists.txt
  regression/cbmc-incr/alarm1/test.desc
  regression/cbmc-incr/alarm3/test.desc
  regression/cbmc-incr/cruise1/test.desc
Labels: Tests, bugfix

#4474 java_string_library_preprocesst isn't a messaget [blocks: #3800]
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.h
Labels: Java Front End, blocker, cleanup

#5600 CL preprocessing: cleanup unused temporary file and string
  src/ansi-c/c_preprocess.cpp
Labels: C Front End, cleanup

#5594 goto_inlinet isn't a messaget
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/goto_inline_class.h
Labels: cleanup

#5593 string_instrumentationt isn't messaget
  src/cbmc/cbmc_parse_options.cpp
  src/goto-programs/string_instrumentation.cpp
  src/goto-programs/string_instrumentation.h
Labels: cleanup

#5595 interpretert isn't a messaget
  src/goto-programs/interpreter.cpp
  src/goto-programs/interpreter.h
  src/goto-programs/interpreter_class.h
  src/goto-programs/interpreter_evaluate.cpp
Labels: cleanup

#5603 C front-end: anonymous struct/union members need not be of struct/union type
  regression/ansi-c/anonymous_member1/main.c
  regression/ansi-c/anonymous_member1/test.desc
  src/ansi-c/anonymous_member.cpp
Labels: C Front End, aws, bugfix

#5606 Upgrade setup-msbuild workflow to 1.0.2 to avoid deprecated add-path
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: Build, bugfix

#5583 Use jq for checking JSON syntax
  regression/solver-hardness/CMakeLists.txt
  regression/solver-hardness/Makefile
  regression/solver-hardness/chain.sh
  regression/solver-hardness/parse_json.py
  regression/solver-hardness/solver-hardness-simple/test.desc
Labels: Tests, cleanup

#5589 Coverage goal filters aren't messaget
  src/goto-instrument/cover.cpp
  src/goto-instrument/cover_filter.h
Labels: cleanup

#5588 jsil_convertt isn't a messaget
  src/jsil/jsil_convert.cpp
Labels: cleanup

#5590 Fix shl operator in JBMC
  jbmc/regression/jbmc/shift1/shift1.class
  jbmc/regression/jbmc/shift1/shift1.java
  jbmc/regression/jbmc/shift1/test.desc
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
Labels: Java Front End, bugfix

#5581 Update subclasses of ai_domain_baset to deprecate function
  src/analyses/ai_domain.h
  src/analyses/constant_propagator.cpp
  src/analyses/constant_propagator.h
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/custom_bitvector_analysis.h
  src/analyses/dependence_graph.cpp
  src/analyses/dependence_graph.h
  src/analyses/escape_analysis.cpp
  src/analyses/escape_analysis.h
  src/analyses/global_may_alias.cpp
  src/analyses/global_may_alias.h
  src/analyses/interval_domain.cpp
  src/analyses/interval_domain.h
  src/analyses/invariant_set_domain.cpp
  src/analyses/invariant_set_domain.h
  src/analyses/is_threaded.cpp
  src/analyses/reaching_definitions.cpp
  src/analyses/reaching_definitions.h
  src/analyses/uninitialized_domain.cpp
  src/analyses/uninitialized_domain.h
  src/analyses/variable-sensitivity/three_way_merge_abstract_interpreter.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_dependence_graph.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_dependence_graph.h
  src/analyses/variable-sensitivity/variable_sensitivity_domain.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_domain.h
  unit/analyses/ai/ai.cpp
  unit/analyses/ai/ai_simplify_lhs.cpp
Labels: cleanup

#5586 partial_order_concurrencyt isn't a messaget
  src/goto-checker/bmc_util.cpp
  src/goto-symex/memory_model.h
  src/goto-symex/memory_model_pso.cpp
  src/goto-symex/memory_model_pso.h
  src/goto-symex/memory_model_sc.cpp
  src/goto-symex/memory_model_sc.h
  src/goto-symex/memory_model_tso.cpp
  src/goto-symex/memory_model_tso.h
  src/goto-symex/partial_order_concurrency.cpp
  src/goto-symex/partial_order_concurrency.h
Labels: Symbolic Execution, cleanup

#5591 remove_java_newt isn't a messaget
  jbmc/src/java_bytecode/remove_java_new.cpp
Labels: Java Front End, cleanup

#5585 java_class_loader(_base)t isn't a messaget
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_class_loader.h
  jbmc/src/java_bytecode/java_class_loader_base.cpp
  jbmc/src/java_bytecode/java_class_loader_base.h
  jbmc/src/java_bytecode/java_class_loader_limit.cpp
  jbmc/src/java_bytecode/java_class_loader_limit.h
Labels: Java Front End, cleanup

#5592 ci_lazy_methodst isn't a messaget
  jbmc/src/java_bytecode/ci_lazy_methods.cpp
  jbmc/src/java_bytecode/ci_lazy_methods.h
  jbmc/src/java_bytecode/java_bytecode_language.cpp
Labels: Java Front End, cleanup

#5598 java_bytecode_instrumentt isn't a messaget
  jbmc/src/java_bytecode/java_bytecode_instrument.cpp
Labels: cleanup

#5596 java_bytecode_convert* aren't messaget
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method_class.h
  jbmc/src/java_bytecode/java_local_variable_table.cpp
Labels: cleanup

#5613 Visual Studio 16.8 has different floating point precision
  jbmc/unit/java_bytecode/expr2java.cpp
Labels: Tests, bugfix

#5614 remove_const_function_pointerst isn't a messaget
  src/goto-programs/remove_const_function_pointers.cpp
  src/goto-programs/remove_const_function_pointers.h
Labels: cleanup

#5609 Use CCache to speed up build times in GitHub actions
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: Build

#5475 CBMC additional profiling info: Pointer dereference, points-to set metric
  regression/cbmc/points-to-sets/main.c
  regression/cbmc/points-to-sets/test.desc
  regression/cbmc/points-to-sets/test_json.desc
  regression/cbmc/points-to-sets/test_xml.desc
  src/cbmc/cbmc_parse_options.cpp
  src/goto-checker/bmc_util.h
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_config.h
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/goto_program_dereference.h
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_dereference.h
Labels: aws

#5483 CBMC additional profiling info: Extend standard CBMC output to display runtime for different stages of CBMC
  regression/cbmc/runtime-profiling/main.c
  regression/cbmc/runtime-profiling/test.desc
  src/goto-checker/bmc_util.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_target_equation.cpp
  src/solvers/prop/prop_conv_solver.cpp
Labels: aws

#5622 smt2_dect isn't a messaget
  src/goto-checker/solver_factory.cpp
  src/goto-instrument/accelerate/scratch_program.h
  src/solvers/smt2/smt2_dec.cpp
  src/solvers/smt2/smt2_dec.h
Labels: cleanup

#5620 string_abstractiont isn't a messaget
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_abstraction.h
Labels: cleanup

#5480 CBMC additional profiling info: Extend solver hardness to track clauses mapped to an instruction
  regression/solver-hardness/solver-hardness-simple/test.desc
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/solver_hardness.cpp
  src/solvers/solver_hardness.h
Labels: aws

#5604 Fix float to int conversion bugs in JBMC
  jbmc/regression/jbmc/FloatToIntConversion/Test.class
  jbmc/regression/jbmc/FloatToIntConversion/Test.java
  jbmc/regression/jbmc/FloatToIntConversion/test_double_to_int.desc
  jbmc/regression/jbmc/FloatToIntConversion/test_double_to_long.desc
  jbmc/regression/jbmc/FloatToIntConversion/test_float_to_int.desc
  jbmc/regression/jbmc/FloatToIntConversion/test_float_to_long.desc
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
Labels: Java Front End, bugfix

#5612 Fix parallelism configuration for Windows build actions
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
  .github/workflows/vs2019/build-cbmc.bat
Labels: Build

#5478 CBMC additional profiling info: Count and report all array constraints added during postprocessing
  regression/cbmc/array-constraint/main.c
  regression/cbmc/array-constraint/test.desc
  regression/cbmc/array-constraint/test_json.desc
  regression/cbmc/array-constraint/test_xml.desc
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-checker/solver_factory.cpp
  src/solvers/flattening/arrays.cpp
  src/solvers/flattening/arrays.h
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
Labels: aws

#5573 Fix PATH separator and CMake syntax to make cbmc-cprover-smt2 tests work on Windows
  regression/cbmc/CMakeLists.txt
  regression/cbmc/address_space_size_limit1/test.desc
Labels: Tests, bugfix

#5625 GitHub actions: Make all Windows checks consistent
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
  .github/workflows/vs2019/build-cbmc.bat
  .github/workflows/vs2019/install-bison.bat
  .github/workflows/vs2019/run-tests.bat
  jbmc/regression/jbmc-json-ui/chain.sh
  jbmc/regression/jbmc-json-ui/pointer-simplification/filter.jq
  jbmc/regression/jbmc-json-ui/pointer-simplification/test.desc
  regression/cbmc/CMakeLists.txt
  regression/validate-trace-xml-schema/check.py
Labels: Build, cleanup

#5630 Makefile builds: memory-analyzer requires linking.dir
  src/Makefile
Labels: Build, bugfix

#5632 strtol must not overflow
  regression/cbmc-library/strtol-02/test.desc
  src/ansi-c/library/stdlib.c
Labels: C Front End, bugfix

#5619 linker_script_merget isn't a messaget
  src/goto-cc/linker_script_merge.cpp
  src/goto-cc/linker_script_merge.h
Labels: cleanup
