Repository diffblue/cbmc, pull requests merged in 2020-05, with the labels that each got.

#5333 Add documentation for memory primitives
  doc/architectural/memory-primitives.md
  doc/cprover-manual/api.md
Labels: aws

#5321 Tests to check inconsistent assumptions involving __CPROVER_r_ok
  regression/CMakeLists.txt
  regression/Makefile
  regression/cbmc-primitives/CMakeLists.txt
  regression/cbmc-primitives/Makefile
  regression/cbmc-primitives/r_w_ok_bug/main.c
  regression/cbmc-primitives/r_w_ok_bug/test.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_dead/main.c
  regression/cbmc-primitives/r_w_ok_inconsistent_dead/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_dead/test.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_deallocated/main.c
  regression/cbmc-primitives/r_w_ok_inconsistent_deallocated/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_deallocated/test.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_integer/main.c
  regression/cbmc-primitives/r_w_ok_inconsistent_integer/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_integer/test.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_invalid/main.c
  regression/cbmc-primitives/r_w_ok_inconsistent_invalid/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_invalid/test.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_nondet/main.c
  regression/cbmc-primitives/r_w_ok_inconsistent_nondet/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_inconsistent_nondet/test.desc
  regression/cbmc-primitives/r_w_ok_null/main.c
  regression/cbmc-primitives/r_w_ok_null/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_null/test.desc
  regression/cbmc-primitives/r_w_ok_valid/main.c
  regression/cbmc-primitives/r_w_ok_valid/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_valid/test.desc
  regression/cbmc-primitives/r_w_ok_valid_negated/main.c
  regression/cbmc-primitives/r_w_ok_valid_negated/test-no-cp.desc
  regression/cbmc-primitives/r_w_ok_valid_negated/test.desc
Labels: aws

#5340 remove deprecated split_string variant
  src/memory-analyzer/memory_analyzer_parse_options.cpp
  src/util/string_utils.cpp
  src/util/string_utils.h
Labels: cleanup

#5338 Update CBMC tutorial with compilation instructions
  doc/architectural/howto.md
Labels: aws, documentation

#5339 Document specifying compiler path when using CMake
  COMPILING.md
Labels: aws, documentation

#5324 Add tests to check semantics of pointer primitives
  regression/cbmc-primitives/dynamic-object-01/main.c
  regression/cbmc-primitives/dynamic-object-01/test-no-cp.desc
  regression/cbmc-primitives/dynamic-object-01/test.desc
  regression/cbmc-primitives/dynamic-object-02/main.c
  regression/cbmc-primitives/dynamic-object-02/test-no-cp.desc
  regression/cbmc-primitives/dynamic-object-02/test.desc
  regression/cbmc-primitives/object-size-01/main.c
  regression/cbmc-primitives/object-size-01/test-no-cp.desc
  regression/cbmc-primitives/object-size-01/test.desc
  regression/cbmc-primitives/pointer-offset-01/main.c
  regression/cbmc-primitives/pointer-offset-01/test-no-cp.desc
  regression/cbmc-primitives/pointer-offset-01/test.desc
  regression/cbmc-primitives/same-object-01/main.c
  regression/cbmc-primitives/same-object-01/test-no-cp.desc
  regression/cbmc-primitives/same-object-01/test.desc
  regression/cbmc-primitives/same-object-02/main.c
  regression/cbmc-primitives/same-object-02/test-no-cp.desc
  regression/cbmc-primitives/same-object-02/test.desc
  regression/cbmc-primitives/same-object-03/main.c
  regression/cbmc-primitives/same-object-03/test-no-cp.desc
  regression/cbmc-primitives/same-object-03/test.desc
  regression/cbmc-primitives/same-object-04/main.c
  regression/cbmc-primitives/same-object-04/test-no-cp.desc
  regression/cbmc-primitives/same-object-04/test.desc
Labels: aws

#5314 Build system: make C string converters read files
  src/ansi-c/CMakeLists.txt
  src/ansi-c/Makefile
  src/ansi-c/file_converter.cpp
  src/ansi-c/library/converter.cpp
  src/cpp/CMakeLists.txt
  src/cpp/Makefile
Labels: Build

#5360 Fix --nondet-volatile bug
  regression/goto-instrument/nondet-volatile-01/test.c
  regression/goto-instrument/nondet-volatile-01/test.desc
  src/goto-instrument/nondet_volatile.cpp
  src/goto-instrument/nondet_volatile.h
Labels: bugfix

#5341 remove two deprecated codet-related constructors/methods
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/goto-instrument/goto_program2code.cpp
  src/util/std_code.cpp
  src/util/std_code.h
Labels: cleanup

#5370 add stack dumps for Windows
  src/common
  src/util/invariant.cpp
Labels: enhancement
