Repository diffblue/cbmc, pull requests merged in 2020-12, with the labels that each got.

#5642 Print meaningful error message when trying to use undeclared uninterpreted functions
  regression/ansi-c/undeclared_function/undeclared_uninterpreted.desc
  regression/ansi-c/undeclared_function/uninterpreted.c
  src/goto-programs/builtin_functions.cpp
Labels: bugfix

#5652 __atomic_compare_exchange{,_n}: correctly handle not-equal case
  regression/cbmc/atomic_load_store-1/main.c
  src/ansi-c/c_typecheck_gcc_polymorphic_builtins.cpp
Labels: C Front End, aws, bugfix

#5645 Introduce a doxygen-checking github action
  .github/workflows/doxygen-check.yaml
  scripts/expected_doxygen_warnings.txt
  scripts/run_doxygen.sh
Labels: CI

#5655 C library/time: fix wrong is-null test
  regression/cbmc-library/time-01/main.c
  regression/cbmc-library/time-01/test.desc
  src/ansi-c/library/time.c
Labels: C Front End, bugfix

#5657 goto-symex: nil array size must not have a type added
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/renaming_level.cpp
  src/util/std_types.cpp
  src/util/std_types.h
  src/util/validate_types.cpp
Labels: bugfix

#5661 C library: Windows defines time to _time64 (or _time32)
  src/ansi-c/library/time.c
Labels: C Front End, bugfix

#5662 Help output: document that stop-on-fail implies trace
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/cbmc/README.md
  src/cbmc/cbmc_parse_options.cpp
Labels: documentation

#5660 GraphML fixes to ensure SV-COMP compatibility
  src/xmllang/graphml.cpp
Labels: bugfix

#5666 C library: *_chk implementations must handle -1 (unknown) as dest size
  regression/cbmc-library/strcpy-01/main.c
  regression/cbmc-library/strcpy-01/test.desc
  src/ansi-c/library/string.c
Labels: C Front End, bugfix

#5665 C library: define _fopen for OS X
  regression/cbmc-library/fopen-01/main.c
  regression/cbmc-library/fopen-01/test.desc
  src/ansi-c/library/stdio.c
Labels: C Front End

#5664 Do not fail an internal invariant when initialising an empty union
  regression/ansi-c/Union_Initialization2/main.c
  regression/ansi-c/Union_Initialization2/test.desc
  src/ansi-c/c_typecheck_initializer.cpp
Labels: C Front End, bugfix

#5659 value sets: do not try to access components of an empty struct/union
  regression/cbmc/empty_compound_type1/main.c
  regression/cbmc/empty_compound_type1/test.desc
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#5672 dump-c: when removing const-ness, also handle bit fields
  regression/goto-instrument/chain.sh
  regression/goto-instrument/dump-decl-const/main.c
  regression/goto-instrument/dump-decl-const/test.desc
  src/goto-instrument/goto_program2code.cpp
Labels: bugfix

#5618 goto_cc_modet isn't a messaget
  src/goto-cc/armcc_mode.cpp
  src/goto-cc/as_mode.cpp
  src/goto-cc/cw_mode.cpp
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/goto_cc_mode.cpp
  src/goto-cc/goto_cc_mode.h
  src/goto-cc/ld_mode.cpp
  src/goto-cc/ms_cl_mode.cpp
  src/goto-cc/ms_link_mode.cpp
Labels: cleanup

#5617 Mark unnecessarily-public members of compilet protected
  src/goto-cc/compile.h
Labels: cleanup

#5679 GitHub actions: Do not unnecessarily install recommended packages
  .github/workflows/build-and-test-Xen.yaml
  .github/workflows/doxygen-check.yaml
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: Build

#5676 C/C++ front-end: do not accept void-typed objects or members
  regression/ansi-c/invalid_use_of_void1/main.c
  regression/ansi-c/invalid_use_of_void1/test-global.desc
  regression/ansi-c/invalid_use_of_void1/test-non-member.desc
  regression/ansi-c/invalid_use_of_void1/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_declaration.cpp
Labels: C Front End

#5677 _Static_assert failures should be reported in the front-end
  regression/ansi-c/_Static_assert2/global.c
  regression/ansi-c/_Static_assert2/global.desc
  regression/ansi-c/_Static_assert2/local.c
  regression/ansi-c/_Static_assert2/local.desc
  regression/ansi-c/_Static_assert2/not_constant.c
  regression/ansi-c/_Static_assert2/not_constant.desc
  regression/cbmc-library/Float_lib1/main.c
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/scanner.l
  src/cpp/cpp_typecheck_static_assert.cpp
  src/util/simplify_expr_floatbv.cpp
Labels: C Front End, bugfix

#4297 goto-cc: also use the linker when processing multiple source files [blocks: #4056]
  regression/ansi-c/linking_conflicts1/test.desc
  regression/ansi-c/linking_conflicts2/test.desc
  scripts/expected_doxygen_warnings.txt
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/ld_mode.cpp
  src/goto-cc/ld_mode.h
  src/goto-cc/linker_script_merge.cpp
  src/goto-cc/linker_script_merge.h
Labels: Needs rebase, blocker

#5680 Add justification for GCC polymorphic function naming
  regression/cbmc/atomic_X_fetch-1/main.c
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, cleanup

#5611 C front-end: printing enum type declarations with bitvector awareness
  regression/goto-instrument/dump-enum/main.c
  regression/goto-instrument/dump-enum/test.desc
  src/ansi-c/expr2c.cpp
Labels: C Front End, bugfix

#5670 C front-end: report struct/union redefinition as an error
  regression/ansi-c/struct8/main.c
  regression/ansi-c/struct8/test.desc
  src/ansi-c/c_typecheck_type.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
Labels: C Front End, bugfix

#5674 C/C++ front-ends: report a meaningful error for invalid function definition
  regression/ansi-c/invalid_function_definition1/main.c
  regression/ansi-c/invalid_function_definition1/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/cpp/cpp_typecheck_function.cpp
Labels: C Front End

#5685 Handle MSVC's __noop in type checker
  regression/ansi-c/noop1/main.c
  regression/ansi-c/noop1/test.desc
  regression/cbmc-library/__noop-01/main.c
  regression/cbmc/noop1/main.c
  regression/cbmc/noop1/test.desc
  regression/cbmc/noop2/main.c
  regression/cbmc/noop2/test.desc
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/library/noop.c
  src/ansi-c/library_check.sh
  src/ansi-c/windows_builtin_headers.h
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert_function_call.cpp
Labels: C Front End

#5669 Cleanup side effects in declaration initialisers
  regression/cbmc/Sideeffects7/main.c
  regression/cbmc/Sideeffects7/test.desc
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_side_effect.cpp
Labels: bugfix

#5686 Refine void/ellipsis typing of GCC built-ins and assembler
  src/ansi-c/gcc_builtin_headers_math.h
  src/assembler/remove_asm.cpp
Labels: C Front End, blocker

#5690 process_array_expr must not generate arrays of negative size
  regression/cbmc-library/memcpy-07/main.c
  regression/cbmc-library/memcpy-07/test.desc
  src/goto-symex/symex_clean_expr.cpp
  src/util/simplify_expr.cpp
Labels: Symbolic Execution, bugfix

#5691 Use is_ssa_expr to avoid lower-level get_bool(ID_C_SSA_symbol)
  src/goto-symex/auto_objects.cpp
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/postcondition.cpp
  src/goto-symex/renaming_level.cpp
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_dereference_state.cpp
  src/util/validate_expressions.cpp
Labels: cleanup

#5689 Simplification of pointer comparison: do not assume numeric types
  regression/cbmc-library/memcpy-06/main.c
  regression/cbmc-library/memcpy-06/test.desc
  src/util/simplify_expr_int.cpp
Labels: bugfix

#5616 compilet isn't a messaget
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
Labels: cleanup

#5698 Make SAT checker unit tests quiet
  unit/solvers/sat/external_sat.cpp
  unit/solvers/sat/satcheck_minisat2.cpp
Labels: Tests, cleanup

#5702 C front-end: ignore or reject excess union initializers
  regression/cbmc/Union_Initialization5/main.c
  regression/cbmc/Union_Initialization5/test.desc
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/c_typecheck_initializer.cpp
Labels: C Front End
