Repository diffblue/cbmc, pull requests merged in 2020-06, with the labels that each got.

#5346 Treat uninitialized pointers like unknown pointers in address_check()
  regression/cbmc/pointer-check-01/test.c
  regression/cbmc/pointer-check-01/test.desc
  regression/cbmc/pointer-check-02/test.c
  regression/cbmc/pointer-check-02/test.desc
  regression/cbmc/pointer-extra-checks/test.desc
  regression/goto-harness/pointer-to-array-function-parameters-with-size/test.desc
  src/analyses/goto_check.cpp
Labels: bugfix

#5371 Remove deprecated expression constructors
  src/analyses/goto_check.cpp
  src/goto-instrument/accelerate/overflow_instrumenter.cpp
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/goto_symex.cpp
  src/util/std_expr.h
  unit/goto-symex/expr_skeleton.cpp
  unit/goto-symex/symex_assign.cpp
Labels: cleanup

#5365 Allow selective havocking of volatile variables
  .gitignore
  regression/goto-instrument/nondet-volatile-02/test.c
  regression/goto-instrument/nondet-volatile-02/test.desc
  regression/goto-instrument/nondet-volatile-03/test.c
  regression/goto-instrument/nondet-volatile-03/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-instrument/nondet_volatile.cpp
  src/goto-instrument/nondet_volatile.h
Labels: aws

#5353 Allow file-local symbol mangling for multi-file compilation
  regression/goto-cc-file-local/chain.sh
  regression/goto-cc-file-local/combined-compile-and-link/foo.c
  regression/goto-cc-file-local/combined-compile-and-link/main.c
  regression/goto-cc-file-local/combined-compile-and-link/test.desc
  src/goto-cc/compile.cpp
Labels: aws

#5374 Selective modelling of volatile variables
  regression/goto-instrument/nondet-volatile-03/test.desc
  regression/goto-instrument/nondet-volatile-04/test.c
  regression/goto-instrument/nondet-volatile-04/test.desc
  regression/goto-instrument/nondet-volatile-model-01/test.c
  regression/goto-instrument/nondet-volatile-model-01/test.desc
  regression/goto-instrument/nondet-volatile-model-02/test.c
  regression/goto-instrument/nondet-volatile-model-02/test.desc
  regression/goto-instrument/nondet-volatile-model-03/test.c
  regression/goto-instrument/nondet-volatile-model-03/test.desc
  regression/goto-instrument/nondet-volatile-model-04/test.c
  regression/goto-instrument/nondet-volatile-model-04/test1.desc
  regression/goto-instrument/nondet-volatile-model-04/test2.desc
  regression/goto-instrument/nondet-volatile-model-05/test.c
  regression/goto-instrument/nondet-volatile-model-05/test1.desc
  regression/goto-instrument/nondet-volatile-model-05/test2.desc
  src/goto-instrument/nondet_volatile.cpp
  src/goto-instrument/nondet_volatile.h
Labels: aws

#5212 Add malloc-may-fail option to goto-check
  doc/cprover-manual/properties.md
  regression/cbmc/Pointer_byte_extract5/no-simplify.desc
  regression/cbmc/Pointer_byte_extract5/test.desc
  regression/cbmc/array_constraints1/test.desc
  regression/cbmc/malloc-may-fail/main.c
  regression/cbmc/malloc-may-fail/test.desc
  regression/cbmc/malloc-may-fail/test_without_option.desc
  regression/cbmc/pointer-overflow1/test.desc
  regression/cbmc/r_w_ok1/test.desc
  regression/goto-analyzer/constant_propagation_01/test.desc
  regression/goto-analyzer/constant_propagation_02/test.desc
  regression/goto-analyzer/constant_propagation_03/test.desc
  regression/goto-analyzer/constant_propagation_04/test.desc
  regression/goto-analyzer/constant_propagation_07/test.desc
  regression/goto-analyzer/constant_propagation_12/test.desc
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/library/cprover.h
  src/ansi-c/library/stdlib.c
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/util/config.cpp
  src/util/config.h
Labels: Do not merge
