Repository diffblue/cbmc, pull requests merged in 2020-02, with the labels that each got.

#5221 Don't evaluate arbitrary python
  scripts/ls_parse.py
Labels: bugfix

#5172 Ensure strncmp(a,b,n) compares at most n characters.
  regression/cbmc-library/strncasecmp-01/main.c
  regression/cbmc-library/strncasecmp-01/test.desc
  regression/cbmc-library/strncmp-01/main.c
  regression/cbmc-library/strncmp-01/test.desc
  src/ansi-c/library/string.c
Labels: aws, bugfix

#5219 Improve replace_symbolt precondition message
  src/util/replace_symbol.cpp
Labels: documentation

#5111 Add docs for --export-file-local-symbols
  doc/architectural/static-functions.md
  regression/goto-cc-file-local/chain.sh
  src/goto-cc/compile.cpp
  src/goto-cc/gcc_cmdline.cpp
  src/goto-cc/ms_cl_cmdline.cpp
Labels: documentation

#5215 add file_exists(path)
  src/goto-cc/hybrid_binary.cpp
  src/util/file_util.cpp
  src/util/file_util.h
  src/util/tempfile.cpp
Labels: enhancement

#5242 Allow old --export-function-local-symbols flag
  regression/goto-cc-file-local/chain.sh
  regression/goto-cc-file-local/old-flag-name/foo.c
  regression/goto-cc-file-local/old-flag-name/main.c
  regression/goto-cc-file-local/old-flag-name/test.desc
  src/goto-cc/gcc_cmdline.cpp
Labels: aws, bugfix

#5236 Add support for gccs __builtin_mul_overflow
  regression/cbmc/gcc_builtin_mul_overflow/main.c
  regression/cbmc/gcc_builtin_mul_overflow/test.desc
  src/ansi-c/library/math.c
Labels: aws

#5247 Use OBJECT_SIZE(p) for dynamic memory bounds checking
  regression/cbmc/r_w_ok5/main.c
  regression/cbmc/r_w_ok5/test.desc
  regression/cbmc/r_w_ok6/main.c
  regression/cbmc/r_w_ok6/test.desc
  regression/cbmc/r_w_ok7/main.c
  regression/cbmc/r_w_ok7/test.desc
  regression/cbmc/r_w_ok8/main.c
  regression/cbmc/r_w_ok8/test.desc
  src/analyses/goto_check.cpp
Labels: aws

#5238 File rename
  src/goto-cc/as_mode.cpp
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/ld_mode.cpp
  src/util/file_util.cpp
  src/util/file_util.h
Labels: enhancement
