Repository diffblue/cbmc, pull requests merged in 2021-08, with the labels that each got.

#6253 Add conversion for rol and ror operators to c output
  regression/CMakeLists.txt
  regression/Makefile
  regression/goto-instrument-json/CMakeLists.txt
  regression/goto-instrument-json/Makefile
  regression/goto-instrument-json/chain.sh
  regression/goto-instrument-json/rol_signed/test-signed.desc
  regression/goto-instrument-json/rol_signed/test-signed.json
  regression/goto-instrument-json/rol_unsigned/test.desc
  regression/goto-instrument-json/rol_unsigned/test.json
  regression/goto-instrument-json/ror_signed/test-signed.desc
  regression/goto-instrument-json/ror_signed/test-signed.json
  regression/goto-instrument-json/ror_unsigned/test.desc
  regression/goto-instrument-json/ror_unsigned/test.json
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  unit/Makefile
  unit/ansi-c/expr2c.cpp
  unit/ansi-c/module_dependencies.txt
Labels: aws, bugfix

#6256 Add incremental SMT2 sort checked construction of bit vector predicate application and application of core theory functions
  src/solvers/Makefile
  src/solvers/smt2_incremental/smt_bit_vector_theory.cpp
  src/solvers/smt2_incremental/smt_bit_vector_theory.def
  src/solvers/smt2_incremental/smt_bit_vector_theory.h
  src/solvers/smt2_incremental/smt_commands.cpp
  src/solvers/smt2_incremental/smt_commands.h
  src/solvers/smt2_incremental/smt_core_theory.cpp
  src/solvers/smt2_incremental/smt_core_theory.h
  src/solvers/smt2_incremental/smt_sorts.cpp
  src/solvers/smt2_incremental/smt_sorts.h
  src/solvers/smt2_incremental/smt_terms.cpp
  src/solvers/smt2_incremental/smt_terms.def
  src/solvers/smt2_incremental/smt_terms.h
  src/solvers/smt2_incremental/smt_to_smt2_string.cpp
  unit/Makefile
  unit/solvers/smt2_incremental/smt_bit_vector_theory.cpp
  unit/solvers/smt2_incremental/smt_commands.cpp
  unit/solvers/smt2_incremental/smt_core_theory.cpp
  unit/solvers/smt2_incremental/smt_terms.cpp
  unit/solvers/smt2_incremental/smt_to_smt2_string.cpp
Labels: SMT Backend Interface

#6222 Symex max depth default max
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/goto-symex/symex_main.cpp
Labels: cleanup

#6269 Fix evaluation of decreases clause
  regression/contracts/variant_init_inside_loop/main.c
  regression/contracts/variant_init_inside_loop/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
Labels: Code Contracts, aws, bugfix

#6265 Properly checks struct members in alias expression
  doc/cprover-manual/contracts-assigns.md
  regression/contracts/assigns_enforce_structs_04/main.c
  regression/contracts/assigns_enforce_structs_04/test.desc
  regression/contracts/assigns_enforce_structs_05/main.c
  regression/contracts/assigns_enforce_structs_05/test.desc
  regression/contracts/assigns_enforce_structs_06/main.c
  regression/contracts/assigns_enforce_structs_06/test.desc
  src/goto-instrument/contracts/assigns.cpp
  src/goto-instrument/contracts/assigns.h
  src/goto-instrument/contracts/contracts.cpp
Labels: Code Contracts, aws, bugfix

#6277 Adds support for struct members in history variables
  doc/cprover-manual/contracts-history-variables.md
  regression/contracts/history-pointer-enforce-09/main.c
  regression/contracts/history-pointer-enforce-09/test.desc
  regression/contracts/history-pointer-enforce-10/main.c
  regression/contracts/history-pointer-enforce-10/test.desc
  regression/contracts/history-pointer-enforce-11/main.c
  regression/contracts/history-pointer-enforce-11/test.desc
  regression/contracts/history-pointer-replace-04/main.c
  regression/contracts/history-pointer-replace-04/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: bugfix, aws, Code Contracts

#6279 Skip checking frame conditions for local variables
  regression/contracts/assigns_enforce_16/main.c
  regression/contracts/assigns_enforce_16/test.desc
  regression/contracts/assigns_enforce_17/main.c
  regression/contracts/assigns_enforce_17/test.desc
  regression/contracts/assigns_enforce_scoping_01/test.desc
  regression/contracts/assigns_replace_03/main.c
  regression/contracts/assigns_replace_03/test.desc
  regression/contracts/assigns_type_checking_valid_cases/main.c
  regression/contracts/assigns_type_checking_valid_cases/test.desc
  regression/contracts/function-calls-05/test.desc
  regression/contracts/history-pointer-enforce-10/test.desc
  regression/contracts/quantifiers-exists-requires-enforce/test.desc
  regression/contracts/quantifiers-forall-ensures-enforce/test.desc
  regression/contracts/quantifiers-forall-requires-enforce/test.desc
  regression/contracts/test_array_memory_enforce/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: enhancement, aws, Code Contracts

#6252 remove unusuable goto_programt::make_return variant
  src/goto-programs/goto_program.h
  unit/goto-instrument/cover_instrument.cpp
  unit/goto-programs/goto_program_validate.cpp
Labels: cleanup

#6199 floating-point mod and remainder
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/library/cprover.h
  src/ansi-c/library/math.c
  src/goto-programs/adjust_float_expressions.cpp
  src/solvers/Makefile
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_floatbv_mod_rem.cpp
  src/solvers/flattening/boolbv_floatbv_op.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
  src/solvers/smt2/smt2_parser.cpp
  src/util/ieee_float.cpp
  src/util/ieee_float.h
  src/util/irep_ids.def
Labels: C Front End

#6188 Linking forward declarations of arrays must not yield type casts
  regression/cbmc/Linking4/test.desc
  regression/linking-goto-binaries/array_size/main.c
  regression/linking-goto-binaries/array_size/supp.c
  regression/linking-goto-binaries/array_size/supp.h
  regression/linking-goto-binaries/array_size/test.desc
  regression/linking-goto-binaries/chain.sh
  src/linking/linking.cpp
Labels: bugfix

#6287 remove rem_exprt
  src/util/irep_ids.def
  src/util/std_expr.h
Labels: cleanup

#6138 bv_pointerst: else case is just for byte updates
  src/solvers/flattening/bv_pointers.cpp
Labels: cleanup

#6296 Ensure result of to_predicates is deterministic
  src/analyses/variable-sensitivity/abstract_environment.cpp
  unit/analyses/variable-sensitivity/abstract_environment/to_predicate.cpp
Labels: bugfix

#6288 Introduce floatbv_rounding_mode(unsigned)
  src/util/Makefile
  src/util/floatbv_expr.cpp
  src/util/floatbv_expr.h
  src/util/ieee_float.cpp
  src/util/ieee_float.h
Labels: cleanup

#6289 introduce rounding_mode_identifier()
  jbmc/src/java_bytecode/java_bytecode_internal_additions.cpp
  jbmc/src/java_bytecode/java_entry_point.cpp
  src/analyses/constant_propagator.cpp
  src/ansi-c/ansi_c_internal_additions.cpp
  src/cpp/cpp_internal_additions.cpp
  src/cpp/module_dependencies.txt
  src/goto-instrument/full_slicer.cpp
  src/goto-programs/adjust_float_expressions.cpp
  src/goto-programs/adjust_float_expressions.h
  src/jsil/jsil_entry_point.cpp
  src/jsil/jsil_internal_additions.cpp
  src/linking/remove_internal_symbols.cpp
  src/statement-list/statement_list_entry_point.cpp
  src/util/ieee_float.h
Labels: cleanup

#6301 SMT-LIB2 now outputs negative integer/rational literals correctly
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#6292 Unify havocing codegen within code contracts
  regression/contracts/assigns_replace_06/main.c
  regression/contracts/assigns_replace_06/test.desc
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/assigns.cpp
  src/goto-instrument/contracts/assigns.h
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/havoc_loops.cpp
  src/goto-instrument/havoc_utils.cpp
  src/goto-instrument/havoc_utils.h
  src/goto-instrument/k_induction.cpp
  src/goto-instrument/loop_utils.cpp
  src/goto-instrument/loop_utils.h
Labels: bugfix, aws, Code Contracts

#6180 Piped communication on Windows
  src/util/piped_process.cpp
  src/util/piped_process.h
  src/util/run.h
  unit/util/piped_process.cpp
Labels: SMT Backend Interface

#6306 SMT-LIB2 parser: fix conversion of (fp ...) expressions
  regression/smt2_solver/fp/basic-fp2.desc
  regression/smt2_solver/fp/basic-fp2.smt2
  src/solvers/smt2/smt2_parser.cpp
Labels: Solvers, bugfix

#6305 SMT-LIB2: parse FloatX sorts
  regression/smt2_solver/fp/basic-fp3.desc
  regression/smt2_solver/fp/basic-fp3.smt2
  src/solvers/smt2/smt2_parser.cpp
Labels: Solvers

#6315 SMT-LIB2 parser: extract repeated code for operand type checking
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_parser.h
  src/solvers/smt2/smt2_tokenizer.h
Labels: cleanup

#6278 Added support for loop_entry history variable.
  regression/contracts/function_loop_history_ensures_fail/main.c
  regression/contracts/function_loop_history_ensures_fail/test.desc
  regression/contracts/function_loop_history_requires_fail/main.c
  regression/contracts/function_loop_history_requires_fail/test.desc
  regression/contracts/history-pointer-replace-03/test.desc
  regression/contracts/invar_function-old_fail/main.c
  regression/contracts/invar_function-old_fail/test.desc
  regression/contracts/invar_loop-entry_check/main.c
  regression/contracts/invar_loop-entry_check/test.desc
  regression/contracts/invar_loop-entry_fail/main.c
  regression/contracts/invar_loop-entry_fail/test.desc
  src/ansi-c/c_expr.h
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/util/irep_ids.def
Labels: enhancement, aws, Code Contracts
