Repository diffblue/cbmc, pull requests merged in 2021-12, with the labels that each got.

#6494 Remove irep_namet
  src/cpp/cpp_type2name.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/util/README.md
  src/util/dstring.h
  src/util/irep.cpp
  src/util/irep.h
  src/util/lispirep.cpp
  src/util/type.h
  src/util/xml_irep.cpp
Labels: cleanup

#6326 enable nondeterministic pointers
  regression/cbmc/Pointer14/main.c
  regression/cbmc/String_Abstraction14/pass-in-implicit.c
  regression/cbmc/String_Abstraction20/structs2.c
  regression/cbmc/double_deref/double_deref_with_pointer_arithmetic.desc
  regression/cbmc/double_deref/double_deref_with_pointer_arithmetic_single_alias.desc
  regression/cbmc/nondet-pointer/nondet-pointer1.c
  regression/cbmc/nondet-pointer/nondet-pointer1.desc
  regression/cbmc/nondet-pointer/nondet-pointer2.c
  regression/cbmc/nondet-pointer/nondet-pointer2.desc
  regression/cbmc/nondet-pointer/nondet-pointer3.c
  regression/cbmc/nondet-pointer/nondet-pointer3.desc
  regression/cbmc/nondet-pointer/nondet-pointer4.c
  regression/cbmc/nondet-pointer/nondet-pointer4.desc
  regression/cbmc/nondet-pointer/nondet-pointer5.c
  regression/cbmc/nondet-pointer/nondet-pointer5.desc
  src/pointer-analysis/value_set.cpp
Labels: aws, aws-high

#6376 Use remove-function-pointers code for restricted function pointers
  regression/cbmc/Function_Pointer_Init_No_Candidate/test.desc
  regression/goto-analyzer/approx-const-fp-array-variable-struct-const-fp-with-zero/test.desc
  regression/goto-analyzer/no-match-array-literal-const-fp-null/test.desc
  regression/goto-analyzer/no-match-const-fp-const-fp-null/test.desc
  regression/goto-analyzer/no-match-const-fp-const-pointer-const-struct-const-fp-null/test.desc
  regression/goto-analyzer/no-match-const-fp-dereference-const-pointer-null/test.desc
  regression/goto-analyzer/no-match-const-fp-null/test.desc
  regression/goto-analyzer/no-match-const-struct-non-const-fp-null/test.desc
  regression/goto-instrument/restrict-function-pointer-by-name-global/test.desc
  regression/goto-instrument/restrict-function-pointer-by-name-local/test.desc
  regression/goto-instrument/restrict-function-pointer-by-name-parameter/test.desc
  regression/goto-instrument/restrict-function-pointer-goto-target/test.desc
  regression/goto-instrument/restrict-function-pointer-to-compatible-function/test.c
  regression/goto-instrument/restrict-function-pointer-to-compatible-function/test.desc
  regression/goto-instrument/restrict-function-pointer-to-complex-expression/test.desc
  regression/goto-instrument/restrict-function-pointer-to-multiple-functions-incorrectly/test.desc
  regression/goto-instrument/restrict-function-pointer-to-multiple-functions-via-file-and-command-line-options/test.desc
  regression/goto-instrument/restrict-function-pointer-to-multiple-functions-via-file/test.desc
  regression/goto-instrument/restrict-function-pointer-to-multiple-functions-via-multiple-files/test.desc
  regression/goto-instrument/restrict-function-pointer-to-multiple-functions/test.desc
  regression/goto-instrument/restrict-function-pointer-to-single-function-incorrectly/test.desc
  regression/goto-instrument/restrict-function-pointer-to-single-function/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/remove_function_pointers.cpp
  src/goto-programs/remove_function_pointers.h
  src/goto-programs/restrict_function_pointers.cpp
  src/goto-programs/restrict_function_pointers.h
Labels: bugfix, cleanup, aws

#6486 Byte extract lowering: refactor lowering of arrays/vectors [blocks: #6488]
  src/solvers/lowering/byte_operators.cpp
Labels: cleanup, blocker

#6450 Adding `#pragma CPROVER enable "named-check"`
  doc/cprover-manual/properties.md
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.cpp
  regression/cbmc/pragma_cprover_enable1/main.c
  regression/cbmc/pragma_cprover_enable1/test.desc
  regression/cbmc/pragma_cprover_enable2/main.c
  regression/cbmc/pragma_cprover_enable2/test.desc
  regression/cbmc/pragma_cprover_enable3/main.c
  regression/cbmc/pragma_cprover_enable3/test.desc
  regression/cbmc/pragma_cprover_enable_all/main.c
  regression/cbmc/pragma_cprover_enable_all/test.desc
  regression/cbmc/pragma_cprover_enable_disable_global_off/main.c
  regression/cbmc/pragma_cprover_enable_disable_global_off/test.desc
  regression/cbmc/pragma_cprover_enable_disable_global_on/main.c
  regression/cbmc/pragma_cprover_enable_disable_global_on/test.desc
  regression/cbmc/pragma_cprover_enable_disable_multiple/main.c
  regression/cbmc/pragma_cprover_enable_disable_multiple/test.desc
  src/analyses/goto_check.cpp
  src/analyses/goto_check.h
  src/ansi-c/ansi_c_parser.cpp
  src/ansi-c/ansi_c_parser.h
  src/ansi-c/scanner.l
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/process_goto_program.cpp
Labels: aws, aws-high

#6475 Tidying up the options for goto-instrument
  regression/cbmc-cpp/Overloading_Operators16/test.desc
  regression/cbmc-cpp/virtual11/test.desc
  regression/cbmc-cpp/virtual12/test.desc
  regression/cbmc-cpp/virtual3/test.desc
  regression/goto-instrument/document-properties-basic/html.desc
  regression/goto-instrument/document-properties-basic/latex.desc
  regression/goto-instrument/document-properties-basic/main.c
  regression/goto-instrument/uninitialized-check/main.c
  regression/goto-instrument/uninitialized-check/test.desc
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-instrument/document_properties.h
  src/goto-instrument/dump_c.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-instrument/uninitialized.cpp
  src/goto-instrument/uninitialized.h
  src/goto-instrument/wmm/weak_memory.h
  src/pointer-analysis/goto_program_dereference.h
Labels: aws

#6493 Invoke goto_functions.update() after inlining
  regression/contracts/invar_check_large/main.c
  regression/contracts/invar_check_large/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: bugfix, aws

#6030 C front-end: support ID_integer-typed expressions in get_c_type
  regression/cbmc/integer-assignments1/integer-typecheck.desc
  regression/validate-trace-xml-schema/check.py
  src/ansi-c/c_typecast.cpp
Labels: bugfix, C Front End

#6497 Split goto_check
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/janalyzer/janalyzer_parse_options.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.h
  src/analyses/Makefile
  src/analyses/goto_check.cpp
  src/analyses/goto_check.h
  src/analyses/goto_check_c.cpp
  src/analyses/goto_check_c.h
  src/analyses/goto_check_java.cpp
  src/analyses/goto_check_java.h
  src/cbmc/cbmc_parse_options.h
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-diff/goto_diff_parse_options.h
  src/goto-instrument/goto_instrument_parse_options.h
Labels: Java Front End, C Front End, cleanup

#6471 Prevent multiple instrumentation of a same check and instrumentation of instrumentation assertions
  regression/contracts/no_redudant_checks/main.c
  regression/contracts/no_redudant_checks/test.desc
  src/analyses/goto_check_c.cpp
Labels: aws, aws-high

#6459 Disable unnecessary pointer checks, enable necessary pointer checks i…
  regression/contracts/assigns_enforce_free_dead/test.desc
  regression/contracts/quantifiers-forall-ensures-enforce/main.c
  src/goto-instrument/contracts/assigns.cpp
  src/goto-instrument/contracts/assigns.h
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
Labels: aws, aws-high, Code Contracts

#6498 C library: model currently supported behaviour of longjmp
  regression/cbmc-library/CMakeLists.txt
  regression/cbmc-library/Makefile
  regression/cbmc-library/_longjmp-01/main.c
  regression/cbmc-library/_longjmp-01/test.desc
  regression/cbmc-library/longjmp-01/main.c
  regression/cbmc-library/longjmp-01/test.desc
  regression/cbmc-library/pthread_barrier_destroy-01/test.desc
  regression/cbmc-library/pthread_barrier_init-01/test.desc
  regression/cbmc-library/pthread_barrier_wait-01/test.desc
  regression/cbmc-library/pthread_cancel-01/test.desc
  regression/cbmc-library/pthread_cond_broadcast-01/test.desc
  regression/cbmc-library/pthread_cond_init-01/test.desc
  regression/cbmc-library/pthread_cond_signal-01/test.desc
  regression/cbmc-library/pthread_cond_wait-01/test.desc
  regression/cbmc-library/pthread_create-01/test.desc
  regression/cbmc-library/pthread_exit-01/test.desc
  regression/cbmc-library/pthread_join-01/test.desc
  regression/cbmc-library/pthread_mutex_destroy-01/test.desc
  regression/cbmc-library/pthread_mutex_init-01/test.desc
  regression/cbmc-library/pthread_mutex_lock-01/test.desc
  regression/cbmc-library/pthread_mutex_trylock-01/test.desc
  regression/cbmc-library/pthread_mutex_unlock-01/test.desc
  regression/cbmc-library/pthread_mutexattr_settype-01/test.desc
  regression/cbmc-library/pthread_rwlock_destroy-01/test.desc
  regression/cbmc-library/pthread_rwlock_init-01/test.desc
  regression/cbmc-library/pthread_rwlock_rdlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_tryrdlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_trywrlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_unlock-01/test.desc
  regression/cbmc-library/pthread_rwlock_wrlock-01/test.desc
  regression/cbmc-library/pthread_spin_lock-01/test.desc
  regression/cbmc-library/pthread_spin_trylock-01/test.desc
  regression/cbmc-library/pthread_spin_unlock-01/test.desc
  regression/cbmc-library/setjmp-01/main.c
  regression/cbmc-library/setjmp-01/test.desc
  regression/cbmc-library/siglongjmp-01/main.c
  regression/cbmc-library/siglongjmp-01/test.desc
  regression/cbmc-library/sigsetjmp-01/main.c
  regression/cbmc-library/sigsetjmp-01/test.desc
  src/ansi-c/library/setjmp.c
Labels: C Front End

#6502 havoc call return value when replacing a call by its contract
  regression/contracts/replace-nondet-return-value/main.c
  regression/contracts/replace-nondet-return-value/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: aws, aws-high

#6503 Cleanup goto check java
  src/analyses/goto_check_java.cpp
Labels: Java Front End, cleanup

#5918 Update GCC builtin declarations
  src/ansi-c/CMakeLists.txt
  src/ansi-c/Makefile
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_internal_additions.h
  src/ansi-c/arm_builtin_headers.h
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/clang_builtin_headers.h
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/cw_builtin_headers.h
  src/ansi-c/gcc_builtin_headers_alpha.h
  src/ansi-c/gcc_builtin_headers_arm.h
  src/ansi-c/gcc_builtin_headers_generic.h
  src/ansi-c/gcc_builtin_headers_ia32-2.h
  src/ansi-c/gcc_builtin_headers_ia32-3.h
  src/ansi-c/gcc_builtin_headers_ia32-4.h
  src/ansi-c/gcc_builtin_headers_ia32-5.h
  src/ansi-c/gcc_builtin_headers_ia32.h
  src/ansi-c/gcc_builtin_headers_math.h
  src/ansi-c/gcc_builtin_headers_mem_string.h
  src/ansi-c/gcc_builtin_headers_omp.h
  src/ansi-c/gcc_builtin_headers_tm.h
  src/ansi-c/gcc_builtin_headers_types.h
  src/ansi-c/gcc_builtin_headers_ubsan.h
  src/ansi-c/get-gcc-builtins.sh
  src/ansi-c/windows_builtin_headers.h
Labels: C Front End

#6507 move goto_check_java.h/.cpp to the Java frontend
  jbmc/src/janalyzer/janalyzer_parse_options.h
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/goto_check_java.cpp
  jbmc/src/java_bytecode/goto_check_java.h
  jbmc/src/jbmc/jbmc_parse_options.h
  jbmc/src/jdiff/jdiff_parse_options.h
  src/analyses/Makefile
  src/analyses/goto_check.cpp
Labels: Java Front End, cleanup

#6490 C library header de-duplication
  regression/cbmc-library/__builtin_llabs-01/main.c
  regression/cbmc-library/__builtin_llabs-01/test.desc
  regression/cbmc-library/llabs-01/main.c
  regression/cbmc-library/llabs-01/test.desc
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/library/cprover.h
  src/ansi-c/library/math.c
  src/ansi-c/library/module_dependencies.txt
  src/ansi-c/library/pthread_lib.c
  src/ansi-c/library/setjmp.c
  src/ansi-c/library/stdio.c
  src/ansi-c/library/stdlib.c
  src/ansi-c/library_check.sh
Labels: C Front End, cleanup

#6504 goto-instrument: replace "modifies" by "assigns" terminology
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/assigns.h
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.h
  src/goto-instrument/function_assigns.cpp
  src/goto-instrument/function_assigns.h
  src/goto-instrument/function_modifies.cpp
  src/goto-instrument/function_modifies.h
  src/goto-instrument/havoc_loops.cpp
  src/goto-instrument/havoc_utils.cpp
  src/goto-instrument/havoc_utils.h
  src/goto-instrument/k_induction.cpp
  src/goto-instrument/loop_utils.cpp
  src/goto-instrument/loop_utils.h
Labels: cleanup

#6500 Handle malloc(0) and malloc(__CPROVER_max_malloc_size) in assigns clause instrumentation
  regression/contracts/assigns-enforce-malloc-zero/main.c
  regression/contracts/assigns-enforce-malloc-zero/test.desc
  regression/contracts/assigns-replace-malloc-zero/main.c
  regression/contracts/assigns-replace-malloc-zero/test.desc
  src/goto-instrument/contracts/assigns.cpp
Labels: aws, aws-high, Code Contracts

#6514 Swapping goto_programt::instructiont must preserve labels
  regression/goto-instrument/labels1/main.c
  regression/goto-instrument/labels1/test.desc
  src/goto-programs/goto_program.h
Labels: bugfix

#6513 jdiff: Remove processing of unsupported options
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.h
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-diff/goto_diff_parse_options.h
Labels: cleanup

#6517 Flattening: support quantifiers over unsigned variables
  regression/cbmc/Quantifiers-type/main.c
  regression/cbmc/Quantifiers-type/test.desc
  regression/cbmc/Quantifiers-type2/main.c
  regression/cbmc/Quantifiers-type2/test.desc
  src/solvers/flattening/boolbv_quantifier.cpp
Labels: bugfix

#6516 Pretty-printing of multi-variable let expressions
  src/ansi-c/expr2c.cpp
  src/util/format_expr.cpp
Labels: bugfix

#6522 Preserve labels when removing return statements
  regression/goto-analyzer/label/main.c
  regression/goto-analyzer/label/test.desc
  src/goto-programs/remove_returns.cpp
Labels: bugfix

#6509 Check inferred loop assigns clauses instead of blindly trusting them
  regression/contracts/github_6168_infinite_unwinding_bug/test.desc
  regression/contracts/invar_check_break_fail/test.desc
  regression/contracts/invar_check_break_pass/test.desc
  regression/contracts/invar_check_continue/test.desc
  regression/contracts/invar_check_multiple_loops/test.desc
  regression/contracts/invar_check_nested_loops/test.desc
  regression/contracts/invar_check_pointer_modifies-01/test.desc
  regression/contracts/invar_check_pointer_modifies-02/test.desc
  regression/contracts/invar_check_sufficiency/test.desc
  regression/contracts/invar_dynamic_struct_member/test.desc
  regression/contracts/invar_havoc_dynamic_array/main.c
  regression/contracts/invar_havoc_dynamic_array/test.desc
  regression/contracts/invar_havoc_dynamic_array_const_idx/test.desc
  regression/contracts/invar_havoc_static_array/main.c
  regression/contracts/invar_havoc_static_array/test.desc
  regression/contracts/invar_havoc_static_array_const_idx/test.desc
  regression/contracts/invar_havoc_static_multi-dim_array/test.desc
  regression/contracts/invar_havoc_static_multi-dim_array_all_const_idx/test.desc
  regression/contracts/invar_havoc_static_multi-dim_array_partial_const_idx/main.c
  regression/contracts/invar_havoc_static_multi-dim_array_partial_const_idx/test.desc
  regression/contracts/invar_loop-entry_check/test.desc
  regression/contracts/invar_loop-entry_fail/test.desc
  regression/contracts/invar_loop_constant_fail/test.desc
  regression/contracts/invar_loop_constant_no_modify/test.desc
  regression/contracts/invar_loop_constant_pass/test.desc
  regression/contracts/invar_struct_member/test.desc
  regression/contracts/invariant_side_effects/test.desc
  regression/contracts/loop_contracts_binary_search/test.desc
  regression/contracts/quantifiers-loop-01/main.c
  regression/contracts/quantifiers-loop-01/test.desc
  regression/contracts/quantifiers-loop-02/main.c
  regression/contracts/quantifiers-loop-02/test.desc
  regression/contracts/quantifiers-loop-03/main.c
  regression/contracts/quantifiers-loop-03/test.desc
  regression/contracts/variant_init_inside_loop/test.desc
  regression/contracts/variant_missing_invariant_warning/test.desc
  regression/contracts/variant_multidimensional_ackermann/test.desc
  regression/contracts/variant_multidimensional_not_decreasing_fail1/test.desc
  regression/contracts/variant_multidimensional_not_decreasing_fail2/test.desc
  regression/contracts/variant_multidimensional_two_index_variables/test.desc
  regression/contracts/variant_not_decreasing_fail/test.desc
  regression/contracts/variant_weak_invariant_fail/test.desc
  regression/contracts/variant_while_true_pass/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: enhancement, aws, aws-high

#6535 Add missing DECL and DEAD instructions in function pointer call site labelling
  src/goto-programs/goto_program.h
  src/goto-programs/label_function_pointer_call_sites.cpp
Labels: aws, aws-high

#6533 Function contracts: check loop freeness before instrumentation, skip assignments to locals and prune write set using CFG info.
  regression/contracts/assigns_enforce_04/test.desc
  regression/contracts/assigns_enforce_05/test.desc
  regression/contracts/assigns_enforce_18/test.desc
  regression/contracts/assigns_enforce_21/test.desc
  regression/contracts/assigns_enforce_arrays_01/main.c
  regression/contracts/assigns_enforce_arrays_03/main.c
  regression/contracts/assigns_enforce_arrays_03/test.desc
  regression/contracts/assigns_enforce_arrays_04/main.c
  regression/contracts/assigns_enforce_arrays_04/test.desc
  regression/contracts/assigns_enforce_arrays_05/main.c
  regression/contracts/assigns_enforce_arrays_05/test.desc
  regression/contracts/assigns_enforce_detect_local_statics/test.desc
  regression/contracts/assigns_enforce_free_dead/test.desc
  regression/contracts/assigns_enforce_malloc_01/main.c
  regression/contracts/assigns_enforce_malloc_01/test.desc
  regression/contracts/assigns_enforce_malloc_02/test.desc
  regression/contracts/assigns_enforce_multi_file_02/header.h
  regression/contracts/assigns_enforce_multi_file_02/test.desc
  regression/contracts/assigns_enforce_statics/test.desc
  regression/contracts/assigns_enforce_structs_01/main.c
  regression/contracts/assigns_enforce_structs_01/test.desc
  regression/contracts/assigns_enforce_structs_02/main.c
  regression/contracts/assigns_enforce_structs_02/test.desc
  regression/contracts/assigns_enforce_structs_03/main.c
  regression/contracts/assigns_enforce_structs_03/test.desc
  regression/contracts/assigns_enforce_structs_04/test.desc
  regression/contracts/assigns_enforce_subfunction_calls/test.desc
  regression/contracts/assigns_function_pointer/main.c
  regression/contracts/assigns_function_pointer/test.desc
  regression/contracts/assigns_type_checking_valid_cases/main.c
  regression/contracts/assigns_type_checking_valid_cases/test.desc
  regression/contracts/assigns_validity_pointer_01/test.desc
  regression/contracts/assigns_validity_pointer_02/test.desc
  regression/contracts/function_check_02/main.c
  regression/contracts/history-pointer-enforce-10/main.c
  regression/contracts/history-pointer-enforce-10/test.desc
  regression/contracts/loop-freeness-check/main.c
  regression/contracts/loop-freeness-check/test.desc
  regression/contracts/quantifiers-exists-ensures-enforce/main.c
  regression/contracts/quantifiers-exists-requires-enforce/main.c
  regression/contracts/quantifiers-forall-ensures-enforce/main.c
  regression/contracts/quantifiers-forall-ensures-enforce/test.desc
  regression/contracts/quantifiers-forall-requires-enforce/main.c
  regression/contracts/quantifiers-nested-01/main.c
  regression/contracts/quantifiers-nested-03/main.c
  regression/contracts/test_aliasing_ensure/main.c
  regression/contracts/test_aliasing_ensure_indirect/main.c
  regression/contracts/test_aliasing_ensure_indirect/test.desc
  src/goto-instrument/contracts/assigns.cpp
  src/goto-instrument/contracts/assigns.h
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
Labels: enhancement, aws, aws-high, Code Contracts

#6545 C front-end: support preprocessor line markers in inline asm
  regression/ansi-c/asm2/main.c
  src/ansi-c/scanner.l
Labels: bugfix, C Front End

#2254 Linking: perform macro expansion and type updates just once
  jbmc/src/java_bytecode/lazy_goto_model.cpp
  regression/goto-gcc/archives/test.desc
  src/goto-cc/compile.cpp
  src/goto-programs/initialize_goto_model.cpp
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/link_goto_model.h
  src/goto-programs/read_goto_binary.cpp
  src/goto-programs/read_goto_binary.h
  src/symtab2gb/module_dependencies.txt
  src/symtab2gb/symtab2gb_parse_options.cpp
Labels: Performance Optimisations

#6548 Linking: do not modify source symbol table
  src/linking/linking.cpp
  src/linking/linking.h
  src/linking/linking_class.h
Labels: cleanup

#6550 Quantifiers
  regression/smt2_solver/quantifiers/boolean-quantifier.desc
  regression/smt2_solver/quantifiers/boolean-quantifier.smt2
  regression/smt2_solver/quantifiers/bv-quantifier-valid.desc
  regression/smt2_solver/quantifiers/bv-quantifier-valid.smt2
  regression/smt2_solver/quantifiers/quantifier-scoping.desc
  regression/smt2_solver/quantifiers/quantifier-scoping.smt2
  src/solvers/flattening/boolbv_quantifier.cpp
Labels: Solvers
