Repository diffblue/cbmc, pull requests merged in 2021-11, with the labels that each got.

#6121 Concurrency: do not remove shared or dirty pointers from the value set
  regression/cbmc-concurrency/dirty_local3/main.c
  regression/cbmc-concurrency/dirty_local3/test-local.desc
  regression/cbmc-concurrency/dirty_local3/test.desc
  src/goto-symex/symex_dead.cpp
Labels: bugfix

#6437 fix the description of some assertions for ACSL operators
  regression/cbmc/ACSL/operators.c
Labels: Tests

#6395 enabling `#pragma disable "pointer-primitive"`
  doc/cprover-manual/properties.md
  regression/cbmc/pragma_cprover3/main.c
  regression/cbmc/pragma_cprover3/test.desc
  src/ansi-c/scanner.l
Labels: bugfix, aws, aws-high

#6434 Refinement of guard based on antecedent of implication statement
  regression/cbmc-primitives/implication_statement_checks_1/test.c
  regression/cbmc-primitives/implication_statement_checks_1/test.desc
  src/analyses/goto_check.cpp
Labels: bugfix

#6367 Crangler
  CMakeLists.txt
  regression/CMakeLists.txt
  regression/Makefile
  regression/crangler/CMakeLists.txt
  regression/crangler/Makefile
  regression/crangler/remove-static-object/remove_static1.c
  regression/crangler/remove-static-object/remove_static1.desc
  regression/crangler/remove-static-object/remove_static1.json
  regression/crangler/remove-static-regex/remove_static1.c
  regression/crangler/remove-static-regex/remove_static1.desc
  regression/crangler/remove-static-regex/remove_static1.json
  regression/crangler/remove-static/remove_static1.c
  regression/crangler/remove-static/remove_static1.desc
  regression/crangler/remove-static/remove_static1.json
  src/CMakeLists.txt
  src/Makefile
  src/crangler/CMakeLists.txt
  src/crangler/Makefile
  src/crangler/c_defines.cpp
  src/crangler/c_defines.h
  src/crangler/c_wrangler.cpp
  src/crangler/c_wrangler.h
  src/crangler/crangler_main.cpp
  src/crangler/crangler_parse_options.cpp
  src/crangler/crangler_parse_options.h
  src/crangler/cscanner.cpp
  src/crangler/cscanner.h
  src/crangler/ctoken.cpp
  src/crangler/ctoken.h
  src/crangler/ctokenit.cpp
  src/crangler/ctokenit.h
  src/crangler/mini_c_parser.cpp
  src/crangler/mini_c_parser.h
  src/crangler/module_dependencies.txt
  src/crangler/scanner.l
Labels: aws

#6086 Remove __CPROVER_malloc_size
  doc/architectural/memory-bounds-checking.md
  regression/cbmc-with-incr/Pointer_byte_extract8/main.c
  regression/contracts/function_check_mem_01/main.c
  regression/goto-analyzer/constant_propagation_01/test-vsd.desc
  regression/goto-analyzer/constant_propagation_01/test.desc
  regression/goto-analyzer/constant_propagation_02/test-vsd.desc
  regression/goto-analyzer/constant_propagation_02/test.desc
  regression/goto-analyzer/constant_propagation_03/test-vsd.desc
  regression/goto-analyzer/constant_propagation_03/test.desc
  regression/goto-analyzer/constant_propagation_04/test-vsd.desc
  regression/goto-analyzer/constant_propagation_04/test.desc
  regression/goto-analyzer/constant_propagation_07/test-vsd.desc
  regression/goto-analyzer/constant_propagation_07/test.desc
  regression/goto-analyzer/constant_propagation_08/test-vsd.desc
  regression/goto-analyzer/constant_propagation_11/test-vsd.desc
  regression/goto-analyzer/constant_propagation_11/test.desc
  regression/goto-analyzer/constant_propagation_12/test-vsd.desc
  regression/goto-analyzer/constant_propagation_12/test.desc
  regression/goto-analyzer/liveness-function-call/test-liveness-show.desc
  regression/goto-analyzer/liveness-function-call/test-liveness-three-way-show.desc
  regression/goto-analyzer/liveness-function-call/test-write-location-show.desc
  regression/goto-analyzer/liveness-function-call/test-write-location-three-way-show.desc
  regression/goto-analyzer/sensitivity-last-written-locations-arrays/test.desc
  regression/goto-analyzer/sensitivity-last-written-locations-pointers/test.desc
  regression/goto-analyzer/sensitivity-last-written-locations-structs/test.desc
  regression/goto-analyzer/sensitivity-last-written-locations-variables/test.desc
  regression/goto-analyzer/sensitivity-test-data-dependency-context/test.desc
  regression/goto-analyzer/variable-sensitivity-dependence-graph-toyota/test.desc
  regression/goto-analyzer/variable-sensitivity-dependence-graph/test.desc
  regression/goto-analyzer/variable-sensitivity-dependence-graph17/test.desc
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/library/cprover.h
  src/ansi-c/library/stdlib.c
  src/cpp/cpp_internal_additions.cpp
  src/cpp/library/cprover.h
  src/cpp/library/new.c
  src/linking/remove_internal_symbols.cpp
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: cleanup

#6430 Add new builtin __CPROVER_havoc_slice
  doc/cprover-manual/api.md
  regression/cbmc/havoc_slice/declarations.h
  regression/cbmc/havoc_slice/test_array_slice_1.c
  regression/cbmc/havoc_slice/test_array_slice_1.desc
  regression/cbmc/havoc_slice/test_array_slice_2.c
  regression/cbmc/havoc_slice/test_array_slice_2.desc
  regression/cbmc/havoc_slice/test_array_symbolic_size.c
  regression/cbmc/havoc_slice/test_array_symbolic_size.desc
  regression/cbmc/havoc_slice/test_nondet_conditional.c
  regression/cbmc/havoc_slice/test_nondet_conditional.desc
  regression/cbmc/havoc_slice/test_struct_a.c
  regression/cbmc/havoc_slice/test_struct_a.desc
  regression/cbmc/havoc_slice/test_struct_b.c
  regression/cbmc/havoc_slice/test_struct_b.desc
  regression/cbmc/havoc_slice/test_struct_b_slice.c
  regression/cbmc/havoc_slice/test_struct_b_slice.desc
  regression/cbmc/havoc_slice/test_struct_c.c
  regression/cbmc/havoc_slice/test_struct_c.desc
  regression/cbmc/havoc_slice/test_struct_d.c
  regression/cbmc/havoc_slice/test_struct_d.desc
  regression/cbmc/havoc_slice/test_struct_raw_bytes.c
  regression/cbmc/havoc_slice/test_struct_raw_bytes.desc
  regression/cbmc/havoc_slice/test_struct_union_a.c
  regression/cbmc/havoc_slice/test_struct_union_a.desc
  regression/cbmc/havoc_slice/test_struct_union_b.c
  regression/cbmc/havoc_slice/test_struct_union_b.desc
  regression/cbmc/havoc_slice/test_struct_union_b_slice.c
  regression/cbmc/havoc_slice/test_struct_union_b_slice.desc
  regression/cbmc/havoc_slice/test_struct_union_c.c
  regression/cbmc/havoc_slice/test_struct_union_c.desc
  regression/cbmc/havoc_slice/test_struct_union_d.c
  regression/cbmc/havoc_slice/test_struct_union_d.desc
  regression/cbmc/havoc_slice/test_whole_array.c
  regression/cbmc/havoc_slice/test_whole_array.desc
  regression/cbmc/havoc_slice/test_whole_array_with_offset.c
  regression/cbmc/havoc_slice/test_whole_array_with_offset.desc
  regression/cbmc/havoc_slice_checks/main.c
  regression/cbmc/havoc_slice_checks/test.desc
  src/ansi-c/cprover_builtin_headers.h
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_function_call.cpp
  src/goto-programs/goto_instruction_code.cpp
  src/goto-programs/goto_instruction_code.h
Labels: enhancement, aws, aws-high

#6461 Static-lifetime symbols require compile-time constant initialisers
  regression/ansi-c/static4/main.c
  regression/ansi-c/static4/test.desc
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/util/expr_util.cpp
Labels: bugfix, C Front End

#6094 Remove __CPROVER_malloc_object
  doc/architectural/memory-bounds-checking.md
  jbmc/src/java_bytecode/java_bytecode_internal_additions.cpp
  regression/goto-analyzer/sensitivity-last-written-locations-arrays/test.desc
  regression/goto-analyzer/sensitivity-last-written-locations-pointers/test.desc
  regression/goto-analyzer/sensitivity-last-written-locations-structs/test.desc
  regression/goto-analyzer/sensitivity-last-written-locations-variables/test.desc
  src/analyses/escape_analysis.cpp
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/library/cprover.h
  src/ansi-c/library/stdlib.c
  src/cpp/cpp_internal_additions.cpp
  src/cpp/library/cprover.h
  src/cpp/library/new.c
  src/jsil/jsil_internal_additions.cpp
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: cleanup

#6249 Add support for assigns clauses on loops
  regression/contracts/assigns_enforce_20/test.desc
  regression/contracts/assigns_enforce_address_of/test.desc
  regression/contracts/assigns_enforce_arrays_05/test.desc
  regression/contracts/assigns_enforce_elvis_4/test.desc
  regression/contracts/assigns_enforce_function_calls/test.desc
  regression/contracts/assigns_enforce_literal/test.desc
  regression/contracts/assigns_enforce_side_effects_1/test.desc
  regression/contracts/assigns_enforce_side_effects_2/test.desc
  regression/contracts/assigns_enforce_side_effects_3/test.desc
  regression/contracts/assigns_type_checking_invalid_case_01/test.desc
  regression/contracts/invar_assigns_alias_analysis/test.desc
  regression/contracts/invar_assigns_empty/main.c
  regression/contracts/invar_assigns_empty/test.desc
  regression/contracts/invar_assigns_opt/test.desc
  regression/contracts/invar_havoc_dynamic_multi-dim_array/test.desc
  regression/contracts/invar_havoc_dynamic_multi-dim_array_all_const_idx/main.c
  regression/contracts/invar_havoc_dynamic_multi-dim_array_all_const_idx/test.desc
  regression/contracts/invar_havoc_dynamic_multi-dim_array_partial_const_idx/test.desc
  regression/contracts/loop_assigns-01/main.c
  regression/contracts/loop_assigns-01/test.desc
  regression/contracts/loop_assigns-02/main.c
  regression/contracts/loop_assigns-02/test.desc
  regression/contracts/loop_assigns-03/main.c
  regression/contracts/loop_assigns-03/test.desc
  regression/contracts/loop_assigns-04/main.c
  regression/contracts/loop_assigns-04/test.desc
  regression/contracts/loop_assigns-fail/main.c
  regression/contracts/loop_assigns-fail/test.desc
  regression/contracts/loop_contracts_do_while/main.c
  regression/contracts/loop_contracts_do_while/test.desc
  regression/contracts/variant_missing_invariant_warning/test.desc
  regression/contracts/variant_multi_instruction_loop_head/main.c
  regression/contracts/variant_multi_instruction_loop_head/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/parser.y
  src/goto-instrument/contracts/assigns.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
  src/goto-instrument/loop_utils.cpp
  src/goto-programs/goto_convert.cpp
Labels: new feature, aws, aws-high, Code Contracts

#6477 String abstraction: use tag types
  src/goto-programs/string_abstraction.cpp
Labels: bugfix

#6476 Byte-operator lowering: Factor out unbounded array unpacking
  src/solvers/lowering/byte_operators.cpp
Labels: cleanup

#6448 Byte updates using bit fields require extension to full bytes
  regression/cbmc/Promotion3/test.desc
  regression/cbmc/havoc_slice/test_struct_b_slice.desc
  src/goto-programs/builtin_functions.cpp
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#6474 Add interpretation of SMT check-sat responses for incremental SMT solving support
  regression/cbmc-incr-smt2/nondeterministic-int-assert/valid_unsat.c
  regression/cbmc-incr-smt2/nondeterministic-int-assert/valid_unsat.desc
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  src/solvers/smt2_incremental/smt_response_validation.h
  src/solvers/smt2_incremental/smt_solver_process.cpp
  src/solvers/smt2_incremental/smt_solver_process.h
  unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
Labels: SMT Backend Interface, work in progress

#6481 Fixed typos
  regression/contracts/function_check_mem_01/main.c
Labels: aws

#6485 bv_typet is also sensitive to endianness
  src/solvers/lowering/byte_operators.cpp
  src/util/endianness_map.cpp
  unit/solvers/lowering/byte_operators.cpp
Labels: bugfix

#6484 Extend unit test of bits2expr/expr2bits with struct type
  unit/util/simplify_expr.cpp
Labels: Tests

#6473 Fix handling of DEAD instructions and function call inlining
  regression/contracts/loop_assigns-05/main.c
  regression/contracts/loop_assigns-05/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: bugfix, aws, aws-high, Code Contracts

#6492 Fix malloc declaration in Linked_List1 regression test
  regression/cbmc/Linked_List1/main.c
Labels: Tests
