Repository diffblue/cbmc, pull requests merged in 2021-02, with the labels that each got.

#5803 boolbvt::convert_bv: avoid unnecessary vector copy
  src/solvers/flattening/boolbv.cpp
Labels: cleanup

#5794 SMT-LIB 2 parser: implement unary minus
  regression/smt2_solver/basic-ia/basic-int1.desc
  regression/smt2_solver/basic-ia/basic-int1.smt2
  src/solvers/smt2/smt2_format.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_solver.cpp
Labels: Solvers, bugfix

#5802 Split unit test into two to avoid GCC warning
  unit/util/string_utils/escape_non_alnum.cpp
Labels: Build, Tests

#5810 remove dead boolbvt::literals(...)
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/prop/prop_conv_solver.h
Labels: cleanup

#5812 Fix type checking of vector expressions
  regression/cbmc/gcc_vector1/main.c
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/remove_vector.cpp
Labels: C Front End, bugfix

#5813 Pointer types must not be used with bit-level operators
  regression/ansi-c/invalid_bitop1/main.c
  regression/ansi-c/invalid_bitop1/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/solvers/flattening/bv_pointers.cpp
Labels: bugfix, cleanup

#5800 Array-element sensitive SSA: avoid string-to-integer-to-string
  scripts/expected_doxygen_warnings.txt
  src/util/ssa_expr.cpp
Labels: Performance Optimisations

#5814 Pointer arithmetic overflow is overflow on integer representation
  regression/cbmc/pointer-overflow2/test.desc
  src/analyses/goto_check.cpp
Labels: bugfix

#5799 dump-c: handle further byte_update union initializers
  regression/goto-instrument/dump-union2/main.c
  src/goto-instrument/dump_c.cpp
Labels: bugfix

#5816 [CI] [Hotfix] Add an apt-update step to the ubuntu CI jobs.
  .github/workflows/pull-request-checks.yaml
Labels: CI, bugfix

#5820 Byte extract with negative offset must not fail invariant
  regression/cbmc/byte_extract1/main.c
  regression/cbmc/byte_extract1/test.desc
  src/solvers/flattening/boolbv_byte_extract.cpp
Labels: bugfix

#5809 [CI] Port CMake Codecov job from Codebuild to Github Actions.
  .github/workflows/pull-request-checks.yaml
  CMakeLists.txt
  buildspec-linux-cmake-gcc-cov.yml
  buildspec-linux-make-gcc-cov.yml
Labels: CI, cleanup

#5826 Documentation: consistently use .gb suffix for goto binaries
  doc/architectural/howto.md
  doc/cprover-manual/properties.md
Labels: cleanup, documentation

#5822 Store pointer encoding configuration in boolbv_widtht
  scripts/expected_doxygen_warnings.txt
  src/solvers/Makefile
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_byte_update.cpp
  src/solvers/flattening/boolbv_union.cpp
  src/solvers/flattening/boolbv_width.cpp
  src/solvers/flattening/boolbv_width.h
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/flattening/bv_endianness_map.cpp
  src/solvers/flattening/bv_endianness_map.h
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
Labels: blocker

#5823 Tests demonstrating pointer-encoding unsoundness
  regression/cbmc/Pointer_Arithmetic18/main.c
  regression/cbmc/Pointer_Arithmetic18/test.desc
  regression/cbmc/Pointer_comparison1/main.c
  regression/cbmc/Pointer_comparison1/test.desc
Labels: Tests, blocker

#5831 bv_pointerst: make all members return (optional) bvt
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
Labels: cleanup

#5559 [CI] Add a linux+clang+make github actions job.
  .github/workflows/pull-request-checks.yaml
Labels: CI, enhancement

#5830 bv_utilst: mark non-modifying members static
  src/solvers/flattening/bv_utils.cpp
  src/solvers/flattening/bv_utils.h
Labels: cleanup

#5838 Fix pointer subtraction semantics
  regression/cbmc-library/posix_memalign-02/test.desc
  regression/cbmc/Pointer_difference2/main.c
  regression/cbmc/Pointer_difference2/test.desc
  regression/cbmc/void_pointer3/main.c
  src/analyses/goto_check.cpp
  src/solvers/flattening/bv_pointers.cpp
Labels: bugfix

#5844 Perform pointer validity checks when doing pointer arithmetic
  regression/cbmc/pointer-overflow1/main.c
  regression/cbmc/pointer-overflow1/test.desc
  regression/cbmc/pointer-overflow2/main.c
  regression/cbmc/pointer-overflow3/main.c
  regression/cbmc/pointer-overflow3/test.desc
  src/analyses/goto_check.cpp
  src/solvers/flattening/bv_pointers.cpp
Labels: bugfix

#5536 [CI] Remove codebuild configuration.
  AccessingCodebuildLogs.md
  buildspec-linux-clang-3.8.yml
  buildspec-linux-clang.yml
  buildspec-linux-cmake-gcc.yml
  buildspec-msbuild.yml
  buildspec-windows-cmake.yml
  buildspec-windows.yml
  buildspec.yml
Labels: CI, cleanup

#5849 Pointer arithmetic check: do not use pointer-to-int conversion
  regression/cbmc-library/getenv-01/test.desc
  regression/cbmc/pointer-overflow1/test.desc
  regression/cbmc/pointer-overflow2/test.desc
  src/analyses/goto_check.cpp
Labels: aws, bugfix

#5854 Remove arch package building script that is no longer maintained.
  pkg/arch/PKGBUILD
  pkg/arch/README.md
Labels: cleanup

#5856 Add goto-ld to .gitignore.
  .gitignore
Labels: cleanup, trivial

#5851 [CI] Cleanup .github/ folder
  .github/workflows/README.md
  .github/workflows/TODO.md
  .github/workflows/debian/64bit_regression_tests.patch
  .github/workflows/debian/Makefile
  .github/workflows/debian/README.md
  .github/workflows/debian/changelog
  .github/workflows/debian/surefire
  .github/workflows/doxygen-check.yaml
  .github/workflows/macos15/Makefile
  .github/workflows/pull-request-checks.yaml
  .github/workflows/version.py
Labels: CI, cleanup

#5858 Assignment side effects may require additional temporaries
  regression/cbmc/Sideeffects8/main.c
  regression/cbmc/Sideeffects8/test.desc
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_side_effect.cpp
Labels: bugfix

#5860 fixup! Assignment side effects may require additional temporaries
  regression/cbmc/Sideeffects8/main.c
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_side_effect.cpp
Labels: bugfix

#5852 De-duplicate explicit-allocation check construction
  src/analyses/goto_check.cpp
Labels: cleanup

#5870 Loop counter resetting must not result in unlimited unwinding
  regression/cbmc/unwind_counters4/main.c
  regression/cbmc/unwind_counters4/test.desc
  src/goto-symex/symex_main.cpp
Labels: bugfix
