Repository diffblue/cbmc, pull requests merged in 2021-03, with the labels that each got.

#5872 Simplify overflow-* expressions
  regression/ansi-c/simplify-overflow/main.c
  regression/ansi-c/simplify-overflow/test.desc
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
Labels: enhancement

#5867 dump-c: fix output of _Bool-typed constants
  regression/goto-instrument/dump-bool/main.c
  regression/goto-instrument/dump-bool/test.desc
  regression/goto-instrument/dump-union2/main.c
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/dump_c_class.h
  src/goto-instrument/goto_program2code.cpp
  src/util/expr.cpp
Labels: bugfix

#5877 Avoid spurious libgcc-s1 Debian package dependency
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
  cmake/packaging.cmake
Labels: Build, bugfix

#5884 Enforce __CPROVER_loop_invariant contracts in goto-instrument
  regression/contracts/invar_check_01/main.c
  regression/contracts/invar_check_01/test.desc
  regression/contracts/invar_check_02/test.desc
  regression/contracts/invar_check_03/test.desc
  regression/contracts/invar_check_04/main.c
  regression/contracts/invar_check_04/test.desc
  regression/contracts/invar_check_break_fail/main.c
  regression/contracts/invar_check_break_fail/test.desc
  regression/contracts/invar_check_break_pass/main.c
  regression/contracts/invar_check_break_pass/test.desc
  regression/contracts/invar_check_continue/main.c
  regression/contracts/invar_check_continue/test.desc
  regression/contracts/invar_check_large/main.c
  regression/contracts/invar_check_large/test.desc
  regression/contracts/invar_check_multiple_loops/main.c
  regression/contracts/invar_check_multiple_loops/test.desc
  regression/contracts/invar_check_nested_loops/main.c
  regression/contracts/invar_check_nested_loops/test.desc
  regression/contracts/invar_check_sufficiency/main.c
  regression/contracts/invar_check_sufficiency/test.desc
  regression/contracts/invar_loop_constant/main.c
  regression/contracts/invar_loop_constant/test.desc
  regression/contracts/invar_loop_constant_fail/main.c
  regression/contracts/invar_loop_constant_fail/test.desc
  regression/contracts/invar_loop_constant_no_modify/main.c
  regression/contracts/invar_loop_constant_no_modify/test.desc
  regression/contracts/invar_loop_constant_pass/main.c
  regression/contracts/invar_loop_constant_pass/test.desc
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
Labels: Code Contracts, aws

#5888 Fix off-by-one error in unbounded byte update
  regression/cbmc/byte_update15/main.c
  regression/cbmc/byte_update15/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#5894 move null_pointer_exprt to pointer_expr.h
  jbmc/src/java_bytecode/java_bytecode_internal_additions.cpp
  jbmc/src/java_bytecode/remove_exceptions.cpp
  jbmc/unit/java_bytecode/goto-programs/remove_virtual_functions_without_fallback.cpp
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/util/arith_tools.cpp
  src/util/pointer_expr.h
  src/util/pointer_predicates.cpp
  src/util/std_expr.h
  unit/interpreter/interpreter.cpp
Labels: cleanup

#5896 Fix copy&paste error: check_long_long should check __builtin_ssubll_overflow
  regression/cbmc/gcc_builtin_sub_overflow/main.c
  regression/cbmc/gcc_builtin_sub_overflow/test.desc
Labels: bugfix

#5895 Move pointer_typet into pointer_expr.h
  scripts/expected_doxygen_warnings.txt
  src/analyses/variable-sensitivity/abstract_pointer_object.cpp
  src/cpp/cpp_is_pod.cpp
  src/cpp/cpp_type2name.cpp
  src/cpp/expr2cpp.cpp
  src/goto-programs/xml_expr.cpp
  src/solvers/flattening/boolbv_width.cpp
  src/util/base_type.cpp
  src/util/c_types.h
  src/util/format_type.cpp
  src/util/pointer_expr.h
  src/util/refined_string_type.h
  src/util/std_types.h
  src/util/validate_types.cpp
Labels: cleanup

#5901 Enable acceleration tests
  regression/CMakeLists.txt
  regression/Makefile
  regression/acceleration/CMakeLists.txt
  regression/acceleration/Makefile
  regression/acceleration/accelerate.sh
  regression/acceleration/array_unsafe1/test.desc
  regression/acceleration/array_unsafe2/test.desc
  regression/acceleration/array_unsafe3/test.desc
  regression/acceleration/array_unsafe4/test.desc
  regression/acceleration/const_unsafe1/test.desc
  regression/acceleration/diamond_unsafe1/test.desc
  regression/acceleration/functions_unsafe1/test.desc
  regression/acceleration/nested_unsafe1/test.desc
  regression/acceleration/overflow_unsafe1/test.desc
  regression/acceleration/phases_unsafe1/test.desc
  regression/acceleration/simple_unsafe1/test.desc
  regression/acceleration/simple_unsafe4/test.desc
  src/goto-instrument/accelerate/scratch_program.cpp
  src/goto-instrument/accelerate/scratch_program.h
Labels: Tests, bugfix

#5902 Use 3 cores on GitHub macOS runners
  .github/workflows/pull-request-checks.yaml
Labels: Build

#5656 Cleanup doxygen comments
  doc/architectural/howto.md
  jbmc/src/java_bytecode/README.md
  jbmc/src/java_bytecode/assignments_from_json.cpp
  jbmc/src/java_bytecode/java_class_loader.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  scripts/expected_doxygen_warnings.txt
  src/analyses/reaching_definitions.cpp
  src/analyses/reaching_definitions.h
  src/analyses/variable-sensitivity/variable_sensitivity_dependence_graph.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_domain.h
  src/analyses/variable-sensitivity/variable_sensitivity_object_factory.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/goto-cc/compile.cpp
  src/goto-cc/compile.h
  src/goto-instrument/cover_basic_blocks.h
  src/goto-instrument/dot.cpp
  src/goto-programs/remove_unreachable.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/slice.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/solvers/sat/cnf.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/strings/string_constraint_instantiation.cpp
  src/solvers/strings/string_constraint_instantiation.h
  src/solvers/strings/string_refinement.cpp
  src/util/c_types_util.h
  src/util/config.cpp
  src/util/std_code.cpp
Labels: cleanup, documentation

#5893 Adds support for function calls within contracts
  src/linking/remove_internal_symbols.cpp
Labels: Code Contracts, aws

#5899 Move C types into util/c_types.h
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/padding.cpp
  src/ansi-c/type2name.cpp
  src/cpp/cpp_exception_id.cpp
  src/cpp/expr2cpp.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-programs/goto_trace.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/interpreter_evaluate.cpp
  src/goto-programs/json_expr.cpp
  src/goto-programs/xml_expr.cpp
  src/goto-symex/goto_symex_state.cpp
  src/jsil/jsil_types.h
  src/linking/linking.cpp
  src/solvers/flattening/boolbv_update.cpp
  src/solvers/flattening/boolbv_width.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/flattening/c_bit_field_replacement_type.cpp
  src/solvers/flattening/c_bit_field_replacement_type.h
  src/solvers/smt2/smt2_conv.h
  src/util/arith_tools.cpp
  src/util/c_types.cpp
  src/util/c_types.h
  src/util/endianness_map.cpp
  src/util/expr_util.cpp
  src/util/find_symbols.cpp
  src/util/format_type.cpp
  src/util/namespace.cpp
  src/util/simplify_expr_floatbv.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_struct.cpp
  src/util/simplify_utils.cpp
  src/util/std_types.cpp
  src/util/std_types.h
  src/util/validate_types.cpp
  unit/analyses/constant_propagator.cpp
  unit/util/expr.cpp
Labels: cleanup

#5855 [CI] Add a make + windows github action job.
  .github/workflows/pull-request-checks.yaml
  regression/cbmc-cpp/Makefile
  regression/cpp/Makefile
  regression/systemc/Makefile
  regression/test.pl
  src/common
Labels: CI

#5909 Use ccache in codecov-coverage-report GitHub action
  .github/workflows/pull-request-checks.yaml
Labels: Build

#5922 Use simplification for more reliable pointer comparison
  regression/cbmc/Pointer_comparison2/main.c
  regression/cbmc/Pointer_comparison2/test.desc
  src/goto-symex/symex_goto.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
Labels: bugfix

#5848 C library/str(n)cat: do not write spurious 0 byte
  regression/cbmc-library/strcat-01/main.c
  regression/cbmc-library/strcat-01/test.desc
  regression/cbmc-library/strncat-01/main.c
  regression/cbmc-library/strncat-01/test.desc
  src/ansi-c/library/string.c
Labels: C Front End, bugfix

#5927 MSVC supports multiple __declspec specifiers
  regression/ansi-c/VS_extensions1/main.c
  src/ansi-c/parser.y
Labels: C Front End

#5924 introduce code_with_contract_typet
  src/ansi-c/c_typecheck_base.cpp
  src/goto-instrument/code_contracts.cpp
  src/util/c_types.h
Labels: C Front End, cleanup

#5926 Fix and cleanup packages in Xen GitHub action
  .github/workflows/build-and-test-Xen.yaml
Labels: bugfix

#5906 use instructiont::get_function_call() and get_assign()
  jbmc/src/java_bytecode/replace_java_nondet.cpp
  src/analyses/ai.cpp
  src/analyses/call_graph.cpp
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/does_remove_const.cpp
  src/analyses/escape_analysis.cpp
  src/analyses/flow_insensitive_analysis.cpp
  src/analyses/global_may_alias.cpp
  src/analyses/goto_rw.cpp
  src/analyses/interval_domain.cpp
  src/analyses/local_may_alias.cpp
  src/analyses/reaching_definitions.cpp
  src/analyses/static_analysis.cpp
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/accelerate/cone_of_influence.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/undefined_functions.cpp
  src/goto-programs/compute_called_functions.cpp
  unit/analyses/ai/ai.cpp
  unit/analyses/constant_propagator.cpp
Labels: cleanup

#5928 C front-end: support inline (and its variants) after asm
  regression/ansi-c/asm2/main.c
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
Labels: C Front End, blocker, bugfix

#5730 C front-end: fallthrough and __fallthrough__ are the same attribute
  regression/ansi-c/gcc_attributes13/main.c
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
Labels: C Front End, bugfix

#5723 C front-end: hide our use of single-bit bool within sizeof
  regression/ansi-c/sizeof4/test.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End, bugfix

#5940 Support ==,!=,<,<=,>,>= over vectors
  regression/cbmc/gcc_vector1/main.c
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/remove_vector.cpp
  src/util/irep_ids.def
Labels: bugfix

#5938 Enable regression tests of k-induction instrumentation
  regression/CMakeLists.txt
  regression/Makefile
  regression/k-induction/CMakeLists.txt
  regression/k-induction/Makefile
  regression/k-induction/chain.sh
Labels: Tests

#5944 Add z3 package installation to CI pull request checks
  .github/workflows/pull-request-checks.yaml
  src/goto-instrument/accelerate/polynomial.cpp
Labels: CI

#5933 Enable goto-analyzer-simplify regression tests
  regression/CMakeLists.txt
  regression/Makefile
  regression/goto-analyzer-simplify/CMakeLists.txt
  regression/goto-analyzer-simplify/Makefile
  regression/goto-analyzer-simplify/chain.sh
  regression/goto-analyzer-simplify/partial-simplify-array/test.desc
  regression/goto-analyzer-simplify/simplify-complex-expression/test.desc
  regression/goto-analyzer-simplify/simplify-lhs-array-index/test.desc
  regression/goto-analyzer-simplify/simplify-lhs-array-pointers-index/test.desc
  regression/goto-analyzer-simplify/simplify-lhs-dereference/test.desc
  regression/goto-analyzer-simplify/simplify-lhs-member/test.desc
  regression/goto-analyzer-simplify/simplify-lhs-pointer-array-dereference/test.desc
  regression/goto-analyzer-simplify/simplify-multiply-by-zero/test.desc
Labels: Tests

#5911 Adds code contracts regression tests that involve function calls
  regression/contracts/chain.sh
  regression/contracts/function-calls-01/main.c
  regression/contracts/function-calls-01/test-enf.desc
  regression/contracts/function-calls-01/test-rep.desc
  regression/contracts/function-calls-02-1/main.c
  regression/contracts/function-calls-02-1/test-enf.desc
  regression/contracts/function-calls-02-1/test-mix.desc
  regression/contracts/function-calls-02-1/test-rep.desc
  regression/contracts/function-calls-02/main.c
  regression/contracts/function-calls-02/test-enf.desc
  regression/contracts/function-calls-02/test-mix.desc
  regression/contracts/function-calls-02/test-rep.desc
  regression/contracts/function-calls-03-1/main.c
  regression/contracts/function-calls-03-1/test-enf.desc
  regression/contracts/function-calls-03/main.c
  regression/contracts/function-calls-03/test-enf.desc
  regression/contracts/function-calls-03/test-mix.desc
  regression/contracts/function-calls-03/test-rep.desc
  regression/contracts/function-calls-04-1/main.c
  regression/contracts/function-calls-04-1/test-enf.desc
  regression/contracts/function-calls-04/main.c
  regression/contracts/function-calls-04/test-enf.desc
  regression/contracts/function-calls-04/test-mix-1.desc
  regression/contracts/function-calls-04/test-mix-2.desc
  regression/contracts/function-calls-04/test-rep.desc
Labels: Code Contracts, aws

#5954 Properly rename regression tests from cbmc-cpp
  regression/cbmc-cpp/lvalue2/main.cpp
  regression/cbmc-cpp/lvalue2/test.desc
  regression/cbmc-cpp/typedef4/main.cpp
  regression/cbmc-cpp/typedef4/test.desc
Labels: bugfix

#5961 Fix pointer havocing within loop invariant contracts
  regression/contracts/invar_check_pointer_modifies-01/main.c
  regression/contracts/invar_check_pointer_modifies-01/test.desc
  regression/contracts/invar_check_pointer_modifies-02/main.c
  regression/contracts/invar_check_pointer_modifies-02/test.desc
  src/goto-instrument/loop_utils.cpp
Labels: Code Contracts, aws, bugfix

#5946 allow contracts on function declarations
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/ansi_c_convert_type.h
  src/ansi-c/ansi_c_declaration.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/parser.y
  src/ansi-c/parser_static.inc
Labels: C Front End, Code Contracts

#5957 Remove "show" target from regression/*/Makefile
  regression/acceleration/Makefile
  regression/ansi-c/Makefile
  regression/array-refinement-with-incr/Makefile
  regression/array-refinement/Makefile
  regression/cbmc-concurrency/Makefile
  regression/cbmc-cover/Makefile
  regression/cbmc-cpp/Makefile
  regression/cbmc-incr-oneloop/Makefile
  regression/cbmc-incr/Makefile
  regression/cbmc-library/Makefile
  regression/cbmc-primitives/Makefile
  regression/cbmc-sequentialization/Makefile
  regression/cbmc-with-incr/Makefile
  regression/cbmc/Makefile
  regression/contracts/Makefile
  regression/cpp-linter/Makefile
  regression/cpp/Makefile
  regression/extract_type_header/Makefile
  regression/fault-localization/Makefile
  regression/goto-analyzer-simplify/Makefile
  regression/goto-analyzer-taint/Makefile
  regression/goto-analyzer/Makefile
  regression/goto-cc-cbmc-shared-options/Makefile
  regression/goto-cc-cbmc/Makefile
  regression/goto-cc-file-local/Makefile
  regression/goto-cc-goto-analyzer/Makefile
  regression/goto-cc-multi-file/Makefile
  regression/goto-cc-regression-gh-issue-5380/Makefile
  regression/goto-cl/Makefile
  regression/goto-diff/Makefile
  regression/goto-gcc/Makefile
  regression/goto-harness/Makefile
  regression/goto-instrument-typedef/Makefile
  regression/goto-instrument-wmm-core/Makefile
  regression/goto-instrument/Makefile
  regression/goto-interpreter/Makefile
  regression/goto-ld/Makefile
  regression/invariants/Makefile
  regression/k-induction/Makefile
  regression/linking-goto-binaries/Makefile
  regression/memory-analyzer/Makefile
  regression/smt2_solver/Makefile
  regression/smt2_strings/Makefile
  regression/snapshot-harness/Makefile
  regression/solver-hardness/Makefile
  regression/statement-list/Makefile
  regression/strings/Makefile
  regression/symtab2gb/Makefile
  regression/systemc/Makefile
  regression/test-script/Makefile
Labels: cleanup

#5948 Correctly handle SMT solver errors in loop acceleration code
  src/goto-instrument/accelerate/scratch_program.cpp
Labels: aws, bugfix

#5538 Improves support for assigns clauses
  doc/cprover-manual/assigns-clause.md
  regression/contracts/assigns_enforce_arrays_01/main.c
  regression/contracts/assigns_enforce_arrays_01/test.desc
  regression/contracts/assigns_enforce_arrays_02/main.c
  regression/contracts/assigns_enforce_arrays_02/test.desc
  regression/contracts/assigns_enforce_arrays_03/main.c
  regression/contracts/assigns_enforce_arrays_03/test.desc
  regression/contracts/assigns_enforce_arrays_04/main.c
  regression/contracts/assigns_enforce_arrays_04/test.desc
  regression/contracts/assigns_enforce_arrays_05/main.c
  regression/contracts/assigns_enforce_arrays_05/test.desc
  regression/contracts/assigns_enforce_multi_file_01/header.h
  regression/contracts/assigns_enforce_multi_file_01/main.c
  regression/contracts/assigns_enforce_multi_file_01/test.desc
  regression/contracts/assigns_enforce_multi_file_02/header.h
  regression/contracts/assigns_enforce_multi_file_02/main.c
  regression/contracts/assigns_enforce_multi_file_02/test.desc
  regression/contracts/assigns_enforce_structs_01/main.c
  regression/contracts/assigns_enforce_structs_01/test.desc
  regression/contracts/assigns_enforce_structs_02/main.c
  regression/contracts/assigns_enforce_structs_02/test.desc
  regression/contracts/assigns_enforce_structs_03/main.c
  regression/contracts/assigns_enforce_structs_03/test.desc
  regression/contracts/assigns_replace_06/main.c
  regression/contracts/assigns_replace_06/test.desc
  regression/contracts/assigns_replace_07/main.c
  regression/contracts/assigns_replace_07/test.desc
  regression/contracts/function-calls-02-1/test-enf.desc
  regression/contracts/function-calls-02/test-enf.desc
  regression/contracts/function-calls-03/test-enf.desc
  regression/contracts/function-calls-04/test-enf.desc
  regression/contracts/function-calls-04/test-mix-2.desc
  scripts/expected_doxygen_warnings.txt
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
Labels: Code Contracts, aws

#5971 [CI] Remove fixed windows SDK version lookup.
  .github/workflows/release-packages.yaml
Labels: CI, bugfix

#5912 Refactor expr2ct::convert_with_precedence to avoid MSVC limitation
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
Labels: blocker

#5923 Introduce ansi-c/c_expr.h
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/c_expr.h
Labels: C Front End, C++ Front End, cleanup

#5976 SMT2 parser: add 'as const'
  regression/smt2_solver/arrays/as_const1.desc
  regression/smt2_solver/arrays/as_const1.smt2
  regression/smt2_solver/arrays/as_const2.desc
  regression/smt2_solver/arrays/as_const2.smt2
  src/solvers/smt2/smt2_parser.cpp
Labels: Solvers

#5913 C front-end: __builtin_shuffle, __builtin_shufflevector
  regression/cbmc/gcc_vector3/main.c
  regression/cbmc/gcc_vector3/test.desc
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/Makefile
  src/ansi-c/c_expr.cpp
  src/ansi-c/c_expr.h
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_gcc_polymorphic_builtins.cpp
  src/ansi-c/clang_builtin_headers.h
  src/util/irep_ids.def
Labels: C Front End

#5900 Add side_effect_expr_overflowt
  src/ansi-c/c_expr.h
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_side_effect.cpp
Labels: blocker

#5544 Use bitvector types to implement __builtin_{add,sub,mul}_overflow
  regression/cbmc/gcc_builtin_add_overflow/main.c
  regression/cbmc/gcc_builtin_add_overflow/test.desc
  src/ansi-c/c_expr.h
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/goto_convert_side_effect.cpp
Labels: C Front End, bugfix

#5919 Provide implementations of __builtin_ia32_vec_ext_*
  regression/cbmc/SIMD1/main.c
  regression/cbmc/SIMD1/test.desc
  src/ansi-c/clang_builtin_headers.h
  src/ansi-c/gcc_builtin_headers_ia32-2.h
  src/ansi-c/library/gcc.c
  src/ansi-c/library/intrin.c
  src/goto-programs/goto_program.cpp
  src/goto-programs/remove_vector.cpp
Labels: C Front End

#5974 Fix SMT2 encoding of `array_of_exprt`
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: SMT Backend Interface, aws, bugfix

#5980 Minor cleanup of some SMT2 files
  regression/strings/test3/test-bv-to-int-onebyone.smt2
  regression/strings/test3/test-bv-to-int.smt2
  regression/strings/test3/test-int.smt2
Labels: SMT Backend Interface, cleanup

#5984 [CI] Lookup for code sign tool in App Certification Kit folder.
  .github/workflows/release-packages.yaml
Labels: CI, bugfix

#5985 Added new solver-specific tags for SMT regression tests
  regression/cbmc/CMakeLists.txt
  regression/cbmc/Makefile
  regression/readme.md
Labels: Solvers, Tests, aws, enhancement

#5904 Fix a crash during SMT translation of structs
  regression/cbmc/struct15/main.c
  regression/cbmc/struct15/test.desc
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: SMT Backend Interface, aws, bugfix

#5973 Fix SMT2 encoding of `array_comprehension_exprt`
  regression/cbmc/byte_update15/test.desc
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: SMT Backend Interface, aws, bugfix
