Repository diffblue/cbmc, pull requests merged in 2021-04, with the labels that each got.

#5821 goto-harness: create goto binary or C output
  doc/architectural/goto-harness.md
  regression/goto-harness/chain.sh
  regression/goto-harness/havoc-global-int-02/test.desc
  regression/goto-harness/havoc-global-int-03/test.desc
  regression/goto-harness/havoc-global-struct/test.desc
  regression/goto-harness/load-snapshot-recursive-static-global-int-01/test.desc
  regression/goto-harness/load-snapshot-static-global-array-01/test.desc
  regression/goto-harness/load-snapshot-static-global-int-01/test.desc
  regression/goto-harness/load-snapshot-static-global-int-02/test.desc
  regression/goto-harness/load-snapshot-static-global-int-03/test.desc
  regression/goto-harness/load-snapshot-static-global-int-04/test.desc
  regression/goto-harness/load-snapshot-static-global-pointer-01/test.desc
  src/goto-harness/goto_harness_parse_options.cpp
Labels: bugfix

#5996 cbmc-cpp/Temporary2 was fixed in ff128a6078
  regression/cbmc-cpp/Temporary2/test.desc
Labels: Tests

#5995 Mark cbmc-cpp/{Templates27,namespace2} as CORE
  regression/cbmc-cpp/Templates27/test.desc
  regression/cbmc-cpp/namespace2/test.desc
Labels: Tests

#5994 Mark cpp/{Conversion9,Friend4,Protection8} as CORE
  regression/cbmc-cpp/Friend4/test.desc
  regression/cbmc-cpp/Protection8/test.desc
  regression/cpp/Conversion9/main.cpp
  regression/cpp/Conversion9/test.desc
  regression/cpp/Friend4/main.cpp
  regression/cpp/Friend4/test.desc
  regression/cpp/Protection8/main.cpp
  regression/cpp/Protection8/test.desc
Labels: Tests

#5998 cbmc-cpp/Templates20 was fixed in f278f3db1
  regression/cbmc-cpp/Templates20/test.desc
Labels: Tests

#5999 cbmc-cpp/Templates16 was fixed in dda0a18ff
  regression/cbmc-cpp/Templates16/test.desc
Labels: Tests

#5997 cbmc-cpp/Templates6 was fixed in 42efbd7457
  regression/cbmc-cpp/Templates6/test.desc
Labels: Tests

#5989 r_w_ok_valid_negated/test-no-cp was fixed in 3acdb52dd6e
  regression/cbmc-primitives/r_w_ok_valid_negated/test-no-cp.desc
Labels: Tests

#5992 Remove duplicate no-built-in-assertions help output
  src/analyses/goto_check.h
Labels: cleanup

#5959 Supports quantifiers in function contracts
  regression/contracts/function_check_02/test.desc
  regression/contracts/quantifiers-exists-both-01/main.c
  regression/contracts/quantifiers-exists-both-01/test.desc
  regression/contracts/quantifiers-exists-both-02/main.c
  regression/contracts/quantifiers-exists-both-02/test.desc
  regression/contracts/quantifiers-exists-ensures-01/main.c
  regression/contracts/quantifiers-exists-ensures-01/test.desc
  regression/contracts/quantifiers-exists-ensures-02/main.c
  regression/contracts/quantifiers-exists-ensures-02/test.desc
  regression/contracts/quantifiers-exists-requires-01/main.c
  regression/contracts/quantifiers-exists-requires-01/test.desc
  regression/contracts/quantifiers-exists-requires-02/main.c
  regression/contracts/quantifiers-exists-requires-02/test.desc
  regression/contracts/quantifiers-forall-both-01/main.c
  regression/contracts/quantifiers-forall-both-01/test.desc
  regression/contracts/quantifiers-forall-both-02/main.c
  regression/contracts/quantifiers-forall-both-02/test.desc
  regression/contracts/quantifiers-forall-ensures-01/main.c
  regression/contracts/quantifiers-forall-ensures-01/test.desc
  regression/contracts/quantifiers-forall-ensures-02/main.c
  regression/contracts/quantifiers-forall-ensures-02/test.desc
  regression/contracts/quantifiers-forall-requires-01/main.c
  regression/contracts/quantifiers-forall-requires-01/test.desc
  regression/contracts/quantifiers-forall-requires-02/main.c
  regression/contracts/quantifiers-forall-requires-02/test.desc
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
Labels: Code Contracts, aws

#6008 Remove ID_width expression support from solvers
  src/solvers/flattening/boolbv.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: cleanup

#6002 Post-dominators: support multiple exit points
  regression/goto-instrument/slice25/main.c
  regression/goto-instrument/slice25/test.desc
  src/analyses/cfg_dominators.h
Labels: bugfix

#6010 Remove unnecessary config.h includes
  jbmc/src/java_bytecode/java_bytecode_typecheck.cpp
  jbmc/unit/java_bytecode/java_bytecode_convert_class/convert_abstract_class.cpp
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_initalizers.cpp
  jbmc/unit/java_bytecode/java_bytecode_parse_lambdas/java_bytecode_parse_lambda_method_table.cpp
  jbmc/unit/java_bytecode/java_replace_nondet/replace_nondet.cpp
  scripts/expected_doxygen_warnings.txt
  src/ansi-c/gcc_types.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-analyzer/goto_analyzer_parse_options.h
  src/goto-instrument/accelerate/util.cpp
  src/goto-instrument/cover.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/json_goto_trace.cpp
  src/linking/static_lifetime_init.cpp
  src/memory-analyzer/analyze_symbol.cpp
  unit/json_symbol_table.cpp
Labels: cleanup

#5859 Use endianness map for both big and little endian
  scripts/expected_doxygen_warnings.txt
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_byte_update.cpp
  src/solvers/flattening/boolbv_member.cpp
  src/solvers/flattening/boolbv_union.cpp
  src/solvers/flattening/boolbv_with.cpp
Labels: bugfix, cleanup

#6019 Remove changelog
  CHANGELOG
Labels: cleanup

#5968 Supports nested quantifiers in function contracts
  regression/contracts/quantifiers-nested-01/main.c
  regression/contracts/quantifiers-nested-01/test.desc
  regression/contracts/quantifiers-nested-02/main.c
  regression/contracts/quantifiers-nested-02/test.desc
  regression/contracts/quantifiers-nested-03/main.c
  regression/contracts/quantifiers-nested-03/test.desc
  regression/contracts/quantifiers-nested-04/main.c
  regression/contracts/quantifiers-nested-04/test.desc
  regression/contracts/quantifiers-nested-05/main.c
  regression/contracts/quantifiers-nested-05/test.desc
  regression/contracts/quantifiers-nested-06/main.c
  regression/contracts/quantifiers-nested-06/test.desc
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
Labels: Code Contracts, aws

#6034 Fix havocing of struct members when enforcing invariants
  regression/contracts/invar_dynamic_struct_member/main.c
  regression/contracts/invar_dynamic_struct_member/test.desc
  regression/contracts/invar_struct_member/main.c
  regression/contracts/invar_struct_member/test.desc
  src/goto-instrument/loop_utils.cpp
Labels: Code Contracts, aws, bugfix

#6026 Fix havocing of arrays when enforcing invariants
  regression/contracts/invar_havoc_dynamic_array/main.c
  regression/contracts/invar_havoc_dynamic_array/test.desc
  regression/contracts/invar_havoc_dynamic_array_const_idx/main.c
  regression/contracts/invar_havoc_dynamic_array_const_idx/test.desc
  regression/contracts/invar_havoc_dynamic_multi-dim_array/main.c
  regression/contracts/invar_havoc_dynamic_multi-dim_array/test.desc
  regression/contracts/invar_havoc_dynamic_multi-dim_array_all_const_idx/main.c
  regression/contracts/invar_havoc_dynamic_multi-dim_array_all_const_idx/test.desc
  regression/contracts/invar_havoc_dynamic_multi-dim_array_partial_const_idx/main.c
  regression/contracts/invar_havoc_dynamic_multi-dim_array_partial_const_idx/test.desc
  regression/contracts/invar_havoc_static_array/main.c
  regression/contracts/invar_havoc_static_array/test.desc
  regression/contracts/invar_havoc_static_array_const_idx/main.c
  regression/contracts/invar_havoc_static_array_const_idx/test.desc
  regression/contracts/invar_havoc_static_multi-dim_array/main.c
  regression/contracts/invar_havoc_static_multi-dim_array/test.desc
  regression/contracts/invar_havoc_static_multi-dim_array_all_const_idx/main.c
  regression/contracts/invar_havoc_static_multi-dim_array_all_const_idx/test.desc
  regression/contracts/invar_havoc_static_multi-dim_array_partial_const_idx/main.c
  regression/contracts/invar_havoc_static_multi-dim_array_partial_const_idx/test.desc
  scripts/expected_doxygen_warnings.txt
  src/goto-instrument/loop_utils.cpp
Labels: Code Contracts, aws, bugfix

#6004 [smt_convt] Fix usage of `use_array_of_bool`
  regression/cbmc/array_of_bool_as_bitvec/main.c
  regression/cbmc/array_of_bool_as_bitvec/test-smt2-outfile.desc
  regression/validate-trace-xml-schema/check.py
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, aws, bugfix

#6037 SMT2: implement check-sat-assuming
  regression/smt2_solver/basic-bv1/check-sat-assuming1.desc
  regression/smt2_solver/basic-bv1/check-sat-assuming1.smt2
  src/solvers/smt2/smt2_solver.cpp
Labels: Solvers

#6042 Memcpy for pointers involving structs was fixed via field sensitivity
  regression/cbmc-library/memcpy-01/test.desc
Labels: Tests, cleanup

#6040 [smt2_convt] Fix invalid and NULL pointer handling
  regression/cbmc/memset_null/main.c
  regression/cbmc/memset_null/test.desc
  regression/cbmc/ptr_arithmetic_on_null/main.c
  regression/cbmc/ptr_arithmetic_on_null/test.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, aws, bugfix

#6044 Pointer subtraction was fixed in 3acdb52dd
  regression/cbmc-primitives/r_w_ok_bug/test.desc
Labels: Tests, cleanup

#5967 Fix union initialization
  regression/ansi-c/Union_Initialization3/main.c
  regression/ansi-c/Union_Initialization3/test.desc
  src/ansi-c/c_typecheck_initializer.cpp
Labels: C Front End, blocker, bugfix

#6053 Cleanup and use propt::new_variables
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_case.cpp
  src/solvers/flattening/boolbv_cond.cpp
  src/solvers/flattening/boolbv_index.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_utils.cpp
  src/solvers/flattening/equality.cpp
  src/solvers/prop/prop.cpp
  src/solvers/prop/prop.h
  src/solvers/sat/cnf.cpp
  src/solvers/sat/cnf.h
Labels: cleanup

#6051 Remove unnecessary size_t -> unsigned cast
  src/goto-symex/goto_symex_state.cpp
Labels: cleanup

#6059 add support for parsing SMT-LIB2 to_fp
  regression/smt2_solver/fp/basic-fp1.desc
  regression/smt2_solver/fp/basic-fp1.smt2
  src/solvers/smt2/smt2_parser.cpp
Labels: Solvers

#6061 GitHub actions: ensure gdb remains installed on Ubuntu 18.04
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: Build, Tests

#6055 Avoid short-lived heap-allocated objects
  src/goto-symex/field_sensitivity.cpp
  src/solvers/flattening/boolbv.cpp
  src/solvers/sat/cnf.cpp
  src/util/pointer_expr.cpp
  src/util/pointer_expr.h
  src/util/sharing_node.h
  src/util/small_map.h
  src/util/ssa_expr.cpp
  src/util/ssa_expr.h
Labels: cleanup

#6067 Cleanup and correctly document get_new_name
  scripts/expected_doxygen_warnings.txt
  src/goto-harness/recursive_initialization.cpp
  src/util/fresh_symbol.cpp
  src/util/rename.cpp
  src/util/rename.h
Labels: cleanup

#6001 apply_condition: notequal need not have constant operand
  regression/cbmc/apply_condition1/main.c
  regression/cbmc/apply_condition1/test.desc
  src/goto-symex/goto_state.cpp
Labels: bugfix
