Repository diffblue/cbmc, pull requests merged in 2021-05, with the labels that each got.

#6063 introduce new address constructor expressions
  src/solvers/flattening/bv_pointers.cpp
  src/util/irep_ids.def
  src/util/pointer_expr.cpp
  src/util/pointer_expr.h
Labels: RFC

#5801 goto-checker properties: do not ignore ERROR
  src/goto-checker/properties.cpp
  unit/Makefile
  unit/goto-checker/properties/module_dependencies.txt
  unit/goto-checker/properties/property_status.cpp
Labels: bugfix

#5934 Add fault-localization regression tests
  doc/assets/xml_spec.xsd
  regression/cbmc/fault_localization-all_properties1/main.c
  regression/cbmc/fault_localization-all_properties1/test.desc
  regression/cbmc/fault_localization-all_properties2/main.c
  regression/cbmc/fault_localization-all_properties2/test.desc
  regression/cbmc/fault_localization-stop_on_fail1/main.c
  regression/cbmc/fault_localization-stop_on_fail1/test.desc
  regression/fault-localization/Makefile
  regression/fault-localization/all_properties1/main.c
  regression/fault-localization/all_properties1/test.desc
  regression/fault-localization/all_properties2/main.c
  regression/fault-localization/all_properties2/test.desc
  regression/fault-localization/stop_on_fail1/main.c
  src/goto-checker/bmc_util.cpp
Labels: Tests, bugfix

#5836 C front-end: clean-up strings being thrown as exceptions
  src/ansi-c/literals/convert_character_literal.cpp
  src/ansi-c/literals/convert_string_literal.cpp
Labels: C Front End, cleanup

#6081 Deprecate unnecessary dynamic_size pointer predicate
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: cleanup

#6082 Remove unnecessary use of dynamic_size
  regression/cbmc/Pointer_byte_extract5/no-simplify.desc
  regression/cbmc/bounds_check1/test.desc
  regression/cbmc/memory_allocation2/test.desc
  src/analyses/goto_check.cpp
Labels: cleanup

#6083 Remove unnecessary use of dynamic_object
  regression/cbmc-primitives/r_w_ok_bug/test.desc
  regression/cbmc/Malloc23/test.desc
  regression/cbmc/Malloc4/test.desc
  regression/cbmc/Malloc5/test.desc
  regression/cbmc/alloca1/test.desc
  regression/cbmc/array_constraints1/test.desc
  regression/cbmc/pointer-extra-checks/test.desc
  regression/cbmc/pointer-overflow1/test.desc
  regression/cbmc/pointer-overflow3/no-simplify.desc
  regression/cbmc/pointer-overflow3/test.desc
  regression/cbmc/pointer-primitive-check-01/test.desc
  regression/cbmc/pointer-primitive-check-04/test.desc
  regression/cbmc/union12/test.desc
  regression/goto-analyzer/value-set-function-pointers-structs/test.desc
  regression/goto-harness/pointer-to-array-function-parameters-multi-arg-wrong/test.desc
  regression/goto-harness/pointer-to-array-function-parameters-with-size/test.desc
  regression/goto-harness/pointer-to-array-function-parameters/test.desc
  src/analyses/goto_check.cpp
Labels: cleanup

#6080 Remove no-op handling of non-existent dynamic_size expression
  src/analyses/invariant_set.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: cleanup

#6084 Deprecate dynamic_object pointer predicate
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: cleanup

#6074 Enforce purity on missing assigns clause
  regression/contracts/assigns_enforce_05/test.desc
  regression/contracts/assigns_enforce_15/main.c
  regression/contracts/assigns_enforce_15/test.desc
  regression/contracts/function_check_02/main.c
  regression/contracts/quantifiers-exists-ensures-01/main.c
  regression/contracts/quantifiers-forall-ensures-01/main.c
  regression/contracts/quantifiers-nested-01/main.c
  regression/contracts/quantifiers-nested-03/main.c
  src/goto-instrument/code_contracts.cpp
Labels: Code Contracts, aws

#4879 (un)reachable functions: valid JSON even without source locations
  regression/goto-analyzer/unreachable-functions-basic-json/test.desc
  src/goto-analyzer/unreachable_instructions.cpp
Labels: bugfix

#6085 Deprecate malloc_object
  src/util/pointer_predicates.h
Labels: cleanup

#6096 CBMC library: fix dead code in pipe()
  regression/cbmc-library/pipe-01/main.c
  regression/cbmc-library/pipe-01/test.desc
  src/ansi-c/library/unistd.c
Labels: C Front End, bugfix

#6102 goto-instrument/wmm: do not lookup non-existent symbols in the namespace
  regression/goto-instrument-wmm-core/ppc_aclwdrr005_POWER_ALL/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwdrr005_POWER_OPC/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwdrr015_POWER_ALL/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwdrr015_POWER_OPC/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwsrr000_RMO_ALL/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwsrr000_RMO_OPC/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwsrr002_POWER_ALL/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwsrr002_POWER_OPC/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwsrr002_RMO_ALL/test.desc
  regression/goto-instrument-wmm-core/ppc_aclwsrr002_RMO_OPC/test.desc
  regression/goto-instrument-wmm-core/ppc_safe004_POWER_OPC/test.desc
  src/goto-instrument/wmm/shared_buffers.cpp
  src/goto-instrument/wmm/shared_buffers.h
Labels: blocker, bugfix

#6107 Value sets: fix byte extracts from structs
  regression/cbmc/Pointer_byte_extract8/main.c
  regression/cbmc/Pointer_byte_extract8/test.desc
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#6025 Supports history variables in function contracts
  regression/contracts/history-pointer-both-01/main.c
  regression/contracts/history-pointer-both-01/test.desc
  regression/contracts/history-pointer-enforce-01/main.c
  regression/contracts/history-pointer-enforce-01/test.desc
  regression/contracts/history-pointer-enforce-02/main.c
  regression/contracts/history-pointer-enforce-02/test.desc
  regression/contracts/history-pointer-enforce-03/main.c
  regression/contracts/history-pointer-enforce-03/test.desc
  regression/contracts/history-pointer-enforce-04/main.c
  regression/contracts/history-pointer-enforce-04/test.desc
  regression/contracts/history-pointer-enforce-05/main.c
  regression/contracts/history-pointer-enforce-05/test.desc
  regression/contracts/history-pointer-enforce-06/main.c
  regression/contracts/history-pointer-enforce-06/test.desc
  regression/contracts/history-pointer-enforce-07/main.c
  regression/contracts/history-pointer-enforce-07/test.desc
  regression/contracts/history-pointer-enforce-08/main.c
  regression/contracts/history-pointer-enforce-08/test.desc
  regression/contracts/history-pointer-replace-01/main.c
  regression/contracts/history-pointer-replace-01/test.desc
  regression/contracts/history-pointer-replace-02/main.c
  regression/contracts/history-pointer-replace-02/test.desc
  regression/contracts/history-pointer-replace-03/main.c
  regression/contracts/history-pointer-replace-03/test.desc
  src/ansi-c/c_expr.h
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/library/cprover.h
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
  src/util/irep_ids.def
Labels: Code Contracts, aws, enhancement

#6077 Check for validity of pointers in assigns clause
  regression/contracts/assigns_replace_03/test.desc
  regression/contracts/assigns_validity_pointer_01/main.c
  regression/contracts/assigns_validity_pointer_01/test.desc
  regression/contracts/assigns_validity_pointer_02/main.c
  regression/contracts/assigns_validity_pointer_02/test.desc
  regression/contracts/assigns_validity_pointer_03/main.c
  regression/contracts/assigns_validity_pointer_03/test.desc
  regression/contracts/assigns_validity_pointer_04/main.c
  regression/contracts/assigns_validity_pointer_04/test.desc
  src/goto-instrument/code_contracts.cpp
Labels: Code Contracts, aws, bugfix

#4550 Fix replace_return
  regression/goto-instrument/inline_18/main.c
  regression/goto-instrument/inline_18/test.desc
  src/goto-programs/goto_inline_class.cpp
Labels: bugfix

#6095 C library: make sleep() branch free
  regression/cbmc-library/sleep-01/main.c
  regression/cbmc-library/sleep-01/test.desc
  src/ansi-c/library/unistd.c
Labels: C Front End, cleanup

#6116 Updates codeowners for code contracts
  CODEOWNERS
Labels: Code Contracts, aws

#5764 Refine recursive calls within the simplifier
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_boolean.cpp
  src/util/simplify_expr_if.cpp
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
Labels: cleanup

#5942 Fix side-effect check on loop invariants
  regression/contracts/invariant_side_effects/main.c
  regression/contracts/invariant_side_effects/test.desc
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_class.h
Labels: Code Contracts, aws, bugfix

#5765 Remove forall_symbol_base_map
  .clang-format
  src/ansi-c/ansi_c_entry_point.cpp
  src/goto-instrument/interrupt.cpp
  src/jsil/jsil_entry_point.cpp
  src/util/get_module.cpp
  src/util/symbol_table.h
Labels: cleanup

#5675 C front-end: require numeric types for assign_bit* operations
  regression/ansi-c/invalid_bitop2/main.c
  regression/ansi-c/invalid_bitop2/test.desc
  regression/ansi-c/struct9/main.c
  regression/ansi-c/struct9/test.desc
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_typecast.cpp
Labels: C Front End, bugfix

#1998 Do not unnecessarily sort guard conjuncts [blocks: #3486]
  src/analyses/guard_expr.cpp
Labels: blocker

#6133 Fixes file path for code_contracts.* in CODEOWNERS file
  CODEOWNERS
Labels: aws

#6012 Allow quantifiers within loop invariants
  regression/contracts/quantifiers-loop-01/main.c
  regression/contracts/quantifiers-loop-01/test.desc
  regression/contracts/quantifiers-loop-02/main.c
  regression/contracts/quantifiers-loop-02/test.desc
  regression/contracts/quantifiers-loop-03/main.c
  regression/contracts/quantifiers-loop-03/test.desc
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
  src/util/c_types.h
Labels: Code Contracts, aws, enhancement

#6140 Equip bv_pointerst::postponedt with a constructor
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
Labels: cleanup

#6142 simplify_inequality_address_of only supports (not)equal
  regression/cbmc/Pointer_comparison3/main.c
  regression/cbmc/Pointer_comparison3/test.desc
  src/util/simplify_expr_int.cpp
Labels: bugfix

#6139 Remove conversion_failed(exprt, bvt)
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/bv_pointers.cpp
Labels: cleanup

#6137 bv_pointerst::offset_arithmetic: de-duplicate code
  src/solvers/flattening/bv_pointers.cpp
Labels: cleanup

#6146 bv_pointerst: use convert instead of convert_bv for Boolean expression
  src/solvers/flattening/bv_pointers.cpp
Labels: cleanup

#6147 XML trace test: do not hard-code pointer bit pattern
  regression/cbmc/xml-trace2/test.desc
Labels: Tests

#6131 Add start of foundational work for incremental SMT2 solving support
  CODEOWNERS
  regression/CMakeLists.txt
  regression/Makefile
  regression/cbmc-incr-smt2/CMakeLists.txt
  regression/cbmc-incr-smt2/Makefile
  regression/cbmc-incr-smt2/nondeterministic-int-assert/incremental_solver_called.desc
  regression/cbmc-incr-smt2/nondeterministic-int-assert/test.c
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-checker/solver_factory.cpp
  src/goto-checker/solver_factory.h
  src/solvers/Makefile
  src/solvers/smt2_incremental/module_dependencies.txt
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.h
Labels: SMT Backend Interface

#6108 Add source location and comments to assertions generated from function contracts
  regression/contracts/assigns_enforce_scoping_01/test.desc
  regression/contracts/assigns_enforce_scoping_02/test.desc
  regression/contracts/quantifiers-exists-both-enforce/test.desc
  regression/contracts/quantifiers-exists-both-replace/test.desc
  regression/contracts/quantifiers-exists-requires-enforce/test.desc
  regression/contracts/quantifiers-exists-requires-replace/test.desc
  regression/contracts/quantifiers-forall-both-enforce/test.desc
  regression/contracts/quantifiers-forall-both-replace/test.desc
  regression/contracts/quantifiers-forall-ensures-enforce/test.desc
  regression/contracts/quantifiers-forall-requires-enforce/test.desc
  regression/contracts/quantifiers-forall-requires-replace/test.desc
  src/goto-instrument/code_contracts.cpp
  src/goto-instrument/code_contracts.h
Labels: Code Contracts, aws, enhancement
