Repository diffblue/cbmc, pull requests merged in 2021-01, with the labels that each got.

#5703 Additional and updated union regression tests involving pointers
  regression/cbmc/union10/union_list2.desc
  regression/cbmc/union14/main.c
  regression/cbmc/union14/test.desc
Labels: C Front End, Tests

#5722 Fix r_w_ok3 test to demonstrate problem
  regression/cbmc/r_w_ok3/main.c
Labels: Tests

#5727 Array initializers can also be compound literals
  regression/cbmc/compound_literal1/main.c
  src/ansi-c/c_typecheck_initializer.cpp
Labels: C Front End, bugfix

#5713 Value sets must not be field sensitive for unions
  regression/cbmc/union14/test.desc
  regression/cbmc/union16/main.c
  regression/cbmc/union16/test.desc
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#5732 C/C++ front-end: void-typed symbols are permitted when extern
  regression/ansi-c/invalid_use_of_void1/main.c
  src/ansi-c/c_typecheck_base.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_declaration.cpp
Labels: C Front End, bugfix

#5728 GCC built-ins: implement __builtin_ffs{,l,ll}
  regression/cbmc-library/__builtin_ffs-01/main.c
  regression/cbmc-library/__builtin_ffs-01/test.desc
  src/ansi-c/library/gcc.c
Labels: C Front End

#5719 Mark various working KNOWNBUG tests "CORE"
  jbmc/regression/janalyzer-taint/taint-map1/test.desc
  jbmc/regression/jbmc-concurrency/get-current-thread/test2.desc
  jbmc/regression/jbmc-concurrency/get-current-thread/test_bug.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks-null-throw/test.desc
  jbmc/regression/jbmc-concurrency/synchronized-blocks-throw/test.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-capacity-fail.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors01/test-capacity-pass.desc
  jbmc/regression/jbmc-strings/StringBuilderConstructors02/test.desc
  jbmc/regression/jbmc-strings/StringFormatBool/test-bool-length-true-pass.desc
  jbmc/regression/jbmc-strings/StringFormatVerification/check_boolean_null.desc
  jbmc/regression/jbmc-strings/StringFormatVerification/fail_alternative.desc
  jbmc/regression/jbmc-strings/StringFormatVerification/fail_boolean_null.desc
  jbmc/regression/jbmc-strings/StringFormatVerification/fail_general_scientific.desc
  jbmc/regression/jbmc-strings/StringFormatVerification/fail_general_scientific_uppercase.desc
  jbmc/regression/jbmc/athrow1/test.desc
  jbmc/regression/jbmc/cprover-always-load-nondet-initialize/test.desc
  jbmc/regression/jbmc/deterministic_assignments_json/test_reference_to_other_class_fail.desc
  jbmc/regression/jbmc/function3/test.desc
  jbmc/regression/jbmc/lazyloading_nested_generic_parameters/test.desc
  jbmc/regression/jbmc/virtual9/test.desc
  jbmc/regression/strings-smoke-tests/java_contains/test_string_printable.desc
  regression/cbmc-library/_read-01/test.desc
  regression/cbmc-library/_write-01/test.desc
  regression/cbmc-library/abort-01/test.desc
  regression/cbmc-library/memcpy-05/test.desc
  regression/cbmc-library/memmove-01/test.desc
  regression/cbmc-library/vasprintf-01/test.desc
  regression/cbmc/Array_Propagation1/test.desc
  regression/cbmc/Float-equality1/test_equality.desc
  regression/cbmc/Initialization7/test.desc
  regression/cbmc/Pointer_Assume1/test.desc
  regression/cbmc/assert_func_four/test.desc
  regression/cbmc/assert_lhs/test.desc
  regression/cbmc/assert_one/test.desc
  regression/cbmc/assert_rtn_four/test.desc
  regression/cbmc/constant_folding2/test.desc
  regression/cbmc/gcc_builtin_va_arg_one/test.desc
  regression/cbmc/scanf1/big-endian.desc
  regression/cbmc/struct11/test.desc
  regression/cbmc/verifier_error_lhs/test.desc
  regression/cbmc/verifier_error_zero/test.desc
  regression/goto-analyzer/variable-sensitivity-bug-02/test.desc
  regression/goto-analyzer/variable-sensitivity-bug-03/test.desc
  regression/goto-instrument/slice17/test.desc
  regression/goto-instrument/slice21/main.c
  regression/goto-instrument/slice21/test.desc
Labels: Tests, cleanup

#5736 Switch the OSX universal binary build to X86 + ARM64
  src/common
Labels: Build

#5646 CMake builds: set a default build type (Release)
  CMakeLists.txt
  COMPILING.md
Labels: Build

#5712 Value set debug output: make it build, use DEBUG macro
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#5734 CBMC/SMT2 regression tests: distinguish slow from broken ones
  regression/cbmc/CMakeLists.txt
  regression/cbmc/Makefile
  regression/cbmc/array-tests/test.desc
Labels: Tests

#5733 5-seconds test is not a reason for broken-smt-backend
  regression/cbmc/Bitfields3/paths.desc
Labels: Tests

#5708 satcheck minisat2: make all solver hardness processing conditional
  src/solvers/sat/cnf.cpp
  src/solvers/sat/cnf.h
  src/solvers/sat/satcheck_minisat2.cpp
Labels: cleanup

#5699 Xen-build GitHub action: use ccache and Ubuntu 20.04
  .github/workflows/build-and-test-Xen.yaml
Labels: Build

#5709 Make Glucose configuration build after solver hardness changes
  .github/workflows/pull-request-checks.yaml
  src/solvers/sat/satcheck_glucose.cpp
Labels: bugfix

#5701 Ensure unique GitHub action cache keys
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: Build

#5700 Add CSmith GitHub action
  .github/workflows/csmith.yaml
  scripts/csmith.sh
Labels: Tests

#5726 Move expr2bits, bits2expr, try_get_string_data_array to simplify_utils
  scripts/expected_doxygen_warnings.txt
  src/goto-symex/goto_symex.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr.h
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
  src/util/simplify_expr_struct.cpp
  src/util/simplify_utils.cpp
  src/util/simplify_utils.h
  unit/solvers/lowering/byte_operators.cpp
  unit/util/simplify_expr.cpp
Labels: cleanup

#3641 added ACSL lambda expressions
  regression/cbmc/ACSL/operators.c
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
  src/util/format_expr.cpp
  src/util/mathematical_expr.cpp
  src/util/mathematical_expr.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
Labels: C Front End, enhancement

#5745 CSmith GitHub action: fix job name
  .github/workflows/csmith.yaml
  scripts/csmith.sh
Labels: Build

#5682 goto_symext::apply_goto_condition must honour --no-propagation
  regression/cbmc/no-propagation/main.c
  regression/cbmc/no-propagation/test.desc
  src/goto-symex/symex_goto.cpp
Labels: Symbolic Execution, bugfix

#5744 Make eliminate_common_addends file-local
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#5706 Overload field_sensitivityt::apply for ssa_exprt
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/field_sensitivity.h
Labels: Symbolic Execution

#5704 Union regression test of unspecified behaviour
  regression/cbmc/union15/main.c
  regression/cbmc/union15/test.desc
Labels: C Front End, Tests

#5750 Fix unpack_array_vector to produce an array of bytes
  regression/cbmc-library/memcpy-08/main.c
  regression/cbmc-library/memcpy-08/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#5019 byte-operators unpack_rec: enforce max-bytes if supplied
  regression/cbmc/byte_update14/test.c
  regression/cbmc/byte_update14/test.desc
  regression/cbmc/dynamic_size1/stack_object.desc
  regression/cbmc/pointer-function-parameters-struct-mutual-recursion/test.desc
  regression/cbmc/pointer-function-parameters-struct-simple-recursion-2/test.desc
  regression/cbmc/pointer-function-parameters-struct-simple-recursion/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#5683 Concurrency: ensure apply_condition's value is used
  regression/cbmc-concurrency/atomic_section_sc7/main.c
  regression/cbmc-concurrency/atomic_section_sc7/test-guard.desc
  regression/cbmc-concurrency/atomic_section_sc7/test.desc
  src/goto-symex/goto_symex_state.cpp
Labels: Concurrency, Symbolic Execution, bugfix

#5751 lower_byte_extract: Remove type-inconsistent hack
  src/solvers/lowering/byte_operators.cpp
Labels: cleanup

#5752 Remove ID_C_zero_initializer
  src/ansi-c/c_typecheck_base.cpp
  src/linking/linking.cpp
  src/linking/remove_internal_symbols.cpp
  src/util/irep_ids.def
Labels: cleanup

#5743 Remove unused simplify_exprt::objects_equal{,_address_of}
  src/util/simplify_expr_class.h
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#5291 Add details about opening the Cygwin shell
  COMPILING.md
Labels: documentation

#2366 SEC-477: Added three regression tests for the full-slicer.
  regression/goto-instrument/slice_general007/main.c
  regression/goto-instrument/slice_general007/test.desc
  regression/goto-instrument/slice_taint_crossing_substr_and_concatenation/main.c
  regression/goto-instrument/slice_taint_crossing_substr_and_concatenation/test.desc
  regression/goto-instrument/slice_taint_over_list/main.c
  regression/goto-instrument/slice_taint_over_list/test.desc
Labels: work in progress

#5739 rol and ror expressions
  regression/cbmc/clang_builtins/rotate.c
  regression/cbmc/clang_builtins/rotate.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/clang_builtin_headers.h
  src/solvers/smt2/smt2_conv.cpp
  src/util/std_expr.h
Labels: SMT Backend Interface, enhancement

#5754 Support c_bool in expr2bits/bits2expr
  regression/cbmc/Bool5/main.c
  regression/cbmc/Bool5/test.desc
  src/util/simplify_utils.cpp
Labels: enhancement

#5756 SMT-LIB2 QB_BV extensions
  regression/smt2_solver/basic-bv1/weber_qf_bv.desc
  regression/smt2_solver/basic-bv1/weber_qf_bv.smt2
  regression/smt2_solver/basic-bv1/weber_qf_bv_without_division.desc
  regression/smt2_solver/basic-bv1/weber_qf_bv_without_division.smt2
  src/solvers/smt2/smt2_parser.cpp
  src/util/bitvector_expr.h
Labels: enhancement

#5761 [CI] Get version information from $GITHUB_REF.
  .github/workflows/release-packages.yaml
Labels: CI

#5770 Remove forall_nodes
  .clang-format
  src/solvers/bdd/miniBDD/miniBDD.cpp
Labels: cleanup

#5742 Make simplify_exprt::get_values file-local
  .clang-format
  regression/cbmc/inequality-with-constant-normalisation1/main.c
  regression/cbmc/inequality-with-constant-normalisation1/test.desc
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
Labels: cleanup

#5766 Remove {f,F}orall_objects
  .clang-format
  src/pointer-analysis/value_set_fi.cpp
Labels: cleanup

#5769 Remove forall_rw_range_set_{r,w}_objects
  .clang-format
  src/analyses/dependence_graph.cpp
  src/analyses/goto_rw.cpp
  src/analyses/goto_rw.h
  src/analyses/reaching_definitions.cpp
Labels: cleanup

#5767 Remove {forall,Forall}_symbolptr_list
  .clang-format
  src/util/get_module.cpp
Labels: cleanup

#5773 Remove non-existent {f,F}orall_valid_objects from clang-format
  .clang-format
Labels: cleanup

#4832 Bugfix rewrite_with_to_field_symbols
  src/goto-symex/field_sensitivity.h
Labels: Needs rebase, Symbolic Execution, cleanup

#5774 XML output: ensure expressions are valid XML 1.0
  regression/cbmc/xml-trace2/main.c
  regression/cbmc/xml-trace2/test.desc
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/xml_goto_trace.cpp
  src/util/xml.cpp
  src/util/xml.h
Labels: bugfix

#5710 Make IPASIR configuration build after solver hardness changes
  .github/workflows/pull-request-checks.yaml
  src/solvers/sat/satcheck_ipasir.cpp
  unit/Makefile
Labels: bugfix

#4758 Add CaDiCaL support to CMake
  .github/workflows/pull-request-checks.yaml
  CMakeLists.txt
  scripts/cadical-patch
  src/Makefile
  src/solvers/CMakeLists.txt
  src/solvers/refinement/bv_refinement_loop.cpp
  src/solvers/refinement/refine_arithmetic.cpp
  src/solvers/sat/satcheck_cadical.cpp
  src/solvers/sat/satcheck_cadical.h
  unit/Makefile
  unit/solvers/sat/satcheck_cadical.cpp
Labels: Solvers

#5705 Initialise union of static lifetime with zeros
  regression/cbmc/Union_Initialization5/main.c
  regression/cbmc/union1/test.desc
  regression/goto-instrument/dump-union/main.c
  regression/goto-instrument/dump-union/test.desc
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/parser.y
  src/goto-instrument/dump_c.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_utils.cpp
Labels: C Front End, bugfix

#4920 Make goto_rw less conservative
  regression/goto-instrument/goto_rw_pointer_handling-2/main.c
  regression/goto-instrument/goto_rw_pointer_handling-2/test.desc
  src/analyses/goto_rw.cpp
Labels: bugfix

#5786 Remove {f,F}orall_named_irep
  .clang-format
  src/cpp/cpp_type2name.cpp
  src/util/irep.cpp
  src/util/irep.h
  src/util/irep_serialization.cpp
  src/util/lispirep.cpp
  src/util/merge_irep.cpp
  src/util/source_location.cpp
  src/util/xml_irep.cpp
Labels: cleanup

#5784 Remove forall_rw_set_{r,w}_entries
  .clang-format
  src/goto-instrument/interrupt.cpp
  src/goto-instrument/race_check.cpp
  src/goto-instrument/rw_set.h
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-instrument/wmm/shared_buffers.cpp
Labels: cleanup

#5681 Enable reading NULL_is_zero from symbol table
  regression/goto-instrument/show-symbol-table-json/test.desc
  src/util/config.cpp
Labels: cleanup

#5787 Remove {f,F}orall_literals
  .clang-format
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv_array.cpp
  src/solvers/flattening/boolbv_case.cpp
  src/solvers/flattening/boolbv_complex.cpp
  src/solvers/flattening/boolbv_cond.cpp
  src/solvers/flattening/boolbv_map.cpp
  src/solvers/flattening/boolbv_typecast.cpp
  src/solvers/flattening/boolbv_vector.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_utils.cpp
  src/solvers/prop/literal.h
  src/solvers/prop/prop_minimize.cpp
  src/solvers/refinement/refine_arrays.cpp
  src/solvers/sat/cnf.h
  src/solvers/sat/external_sat.cpp
  src/solvers/sat/satcheck_glucose.cpp
  src/solvers/sat/satcheck_ipasir.cpp
  src/solvers/sat/satcheck_lingeling.cpp
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/sat/satcheck_picosat.cpp
Labels: cleanup

#1997 Do not sort operands as part of simplification [blocks: #3486]
  jbmc/regression/jbmc-strings/ConstantEvaluationTrim/Main.class
  jbmc/regression/jbmc-strings/ConstantEvaluationTrim/Main.java
  jbmc/regression/jbmc-strings/ConstantEvaluationTrim/noprop.desc
  jbmc/regression/jbmc/throwing-function-return-value/test.desc
  regression/cbmc-library/float-nan-check/test.desc
  regression/cbmc/Float-equality2/main.c
  regression/cbmc/Float-equality2/test.desc
  regression/cbmc/array-cell-sensitivity2/test.desc
  regression/cbmc/field-sensitivity1/test.desc
  regression/cbmc/field-sensitivity11/test.desc
  regression/cbmc/field-sensitivity12/test.desc
  regression/cbmc/field-sensitivity13/test.desc
  regression/goto-analyzer/constant_propagation_07/test.desc
  src/util/simplify_expr.cpp
  src/util/simplify_expr_floatbv.cpp
  src/util/simplify_utils.cpp
  src/util/simplify_utils.h
Labels: blocker

#5788 Replace some uses of {F,f}orall_expr by ranged-for
  src/analyses/goto_rw.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-instrument/value_set_fi_fp_removal.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_convert_function_call.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/remove_function_pointers.cpp
  src/goto-symex/symex_function_call.cpp
  src/solvers/flattening/boolbv_array.cpp
  src/solvers/flattening/boolbv_complex.cpp
  src/solvers/flattening/boolbv_concatenation.cpp
  src/solvers/flattening/boolbv_vector.cpp
  src/solvers/prop/prop_conv_solver.cpp
  src/util/expr_util.cpp
Labels: cleanup

#5785 Remove {f,F}orall_irep
  .clang-format
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/parser_static.inc
  src/cpp/cpp_convert_type.cpp
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_enum_type.cpp
  src/cpp/cpp_name.cpp
  src/cpp/cpp_name.h
  src/cpp/cpp_type2name.cpp
  src/cpp/cpp_typecheck_bases.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_constructor.cpp
  src/cpp/cpp_typecheck_enum_type.cpp
  src/cpp/expr2cpp.cpp
  src/cpp/parse.cpp
  src/cpp/template_map.cpp
  src/goto-instrument/dump_c.cpp
  src/util/irep.cpp
  src/util/irep.h
  src/util/irep_hash_container.cpp
  src/util/irep_serialization.cpp
  src/util/lispirep.cpp
  src/util/merge_irep.cpp
  src/util/xml_irep.cpp
Labels: cleanup

#5707 Cleanup Java library build
  CMakeLists.txt
  jbmc/CMakeLists.txt
  jbmc/src/java_bytecode/CMakeLists.txt
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/library/CMakeLists.txt
  jbmc/src/java_bytecode/library/Makefile
  jbmc/src/java_bytecode/library/converter.cpp
  jbmc/src/java_bytecode/library/module_dependencies.txt
  jbmc/src/jbmc/CMakeLists.txt
Labels: Build, Java Front End, cleanup

#5783 Remove {f,F}orall_subtypes
  .clang-format
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/ansi_c_parser.cpp
  src/ansi-c/c_storage_spec.cpp
  src/ansi-c/type2name.cpp
  src/cpp/cpp_declaration.cpp
  src/cpp/cpp_storage_spec.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/template_map.cpp
  src/goto-instrument/dump_c.cpp
  src/util/find_symbols.cpp
  src/util/rename_symbol.cpp
  src/util/replace_symbol.cpp
  src/util/type.h
Labels: cleanup

#5780 Partly revert "Simplify initializer to remove byte_update"
  regression/goto-instrument/dump-union2/main.c
  regression/goto-instrument/dump-union2/test.desc
  src/ansi-c/c_typecheck_initializer.cpp
  src/goto-instrument/dump_c.cpp
Labels: bugfix

#5791 SMT2 uninterpreted functions
  regression/cbmc/uninterpreted_function/uf2.c
  regression/smt2_solver/uninterpreted-functions/boolean_uf1.desc
  regression/smt2_solver/uninterpreted-functions/boolean_uf1.smt2
  regression/smt2_solver/uninterpreted-functions/uf1.desc
  regression/smt2_solver/uninterpreted-functions/uf1.smt2
  src/solvers/flattening/boolbv.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2/smt2_solver.cpp
Labels: Solvers, bugfix

#5789 Replace some uses of {f,F}orall_goto_program_instructions by ranged-for
  jbmc/src/java_bytecode/remove_exceptions.cpp
  src/analyses/goto_check.cpp
  src/analyses/local_bitvector_analysis.cpp
  src/analyses/local_may_alias.cpp
  src/analyses/local_safe_pointers.cpp
  src/analyses/locals.cpp
  src/goto-cc/linker_script_merge.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/sat_path_enumerator.cpp
  src/goto-instrument/call_sequences.cpp
  src/goto-instrument/count_eloc.cpp
  src/goto-instrument/cover_filter.cpp
  src/goto-instrument/document_properties.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-instrument/model_argc_argv.cpp
  src/goto-instrument/nondet_static.cpp
  src/goto-instrument/undefined_functions.cpp
  src/goto-instrument/unwind.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-programs/compute_called_functions.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_functions.cpp
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/loop_ids.cpp
  src/goto-programs/remove_function_pointers.cpp
  src/goto-programs/remove_returns.cpp
  src/goto-programs/remove_unused_functions.cpp
  src/goto-programs/remove_virtual_functions.cpp
  src/goto-programs/rewrite_union.cpp
  src/goto-programs/slice_global_inits.cpp
  src/goto-programs/write_goto_binary.cpp
Labels: cleanup
