Repository diffblue/cbmc, pull requests merged in 2022-05, with the labels that each got.

#6795 Clarify commands in test comments required for goto-binary version changes
  regression/ansi-c/arch_flags_mcpu_bad/test.desc
  regression/ansi-c/arch_flags_mthumb_bad/test.desc
Labels: documentation

#6809 rename_symbolt: renaming in return values should affect the result
  src/util/rename_symbol.cpp
Labels: bugfix

#6671 Deprecate multi-argument variants of exprt::copy_to_operands
  jbmc/src/java_bytecode/remove_java_new.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/jsil/jsil_convert.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/lowering/byte_operators.cpp
  src/util/expr.h
  src/util/std_code.h
Labels: cleanup

#6518 Remove --debug-level from cbmc and jbmc
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-symex/symex_config.h
  src/goto-symex/symex_main.cpp
Labels: cleanup

#6720 Reaching definitions: distinguish recursion from function-without-body
  regression/goto-instrument/reaching-definitions/test.desc
  src/analyses/reaching_definitions.cpp
Labels: bugfix

#6716 Replace the goto_check indirection by direct use of goto_check_c [blocks: #6688]
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/goto_check.cpp
  src/goto-programs/goto_check.h
  src/goto-programs/process_goto_program.cpp
Labels: cleanup, blocker

#6840 CONTRACTS: track multiple malloc'd regions
  regression/contracts/assigns_enforce_malloc_03/main.c
  regression/contracts/assigns_enforce_malloc_03/test.desc
  src/goto-instrument/contracts/havoc_assigns_clause_targets.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
Labels: bugfix, aws, aws-high, Code Contracts

#6753 goto_rw/range_spect: wrap in a class instead of using just a typedef [blocks: #6749, #6768]
  src/analyses/dependence_graph.cpp
  src/analyses/goto_rw.cpp
  src/analyses/goto_rw.h
  src/analyses/reaching_definitions.cpp
  src/analyses/reaching_definitions.h
Labels: blocker

#6849 Tests: do not unnecessarily constrain what models solvers can produce [blocks: #6439]
  jbmc/regression/jbmc-strings/ConstantEvaluationContains/nondetArg.desc
  jbmc/regression/jbmc-strings/ConstantEvaluationContains/noprop.desc
  regression/cbmc-library/free-01/test.desc
Labels: Tests, blocker

#6852 remove goto_programt::get_ and set_condition
  src/analyses/constant_propagator.cpp
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/flow_insensitive_analysis.cpp
  src/analyses/goto_rw.cpp
  src/analyses/interval_analysis.cpp
  src/analyses/interval_domain.cpp
  src/analyses/invariant_propagation.cpp
  src/analyses/invariant_set_domain.cpp
  src/analyses/local_cfg.cpp
  src/analyses/local_safe_pointers.cpp
  src/analyses/static_analysis.cpp
  src/ansi-c/goto_check_c.cpp
  src/goto-analyzer/static_simplifier.cpp
  src/goto-analyzer/static_verifier.cpp
  src/goto-analyzer/taint_analysis.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/accelerate/all_paths_enumerator.cpp
  src/goto-instrument/accelerate/cone_of_influence.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/overflow_instrumenter.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/accelerate/sat_path_enumerator.cpp
  src/goto-instrument/accelerate/scratch_program.cpp
  src/goto-instrument/branch.cpp
  src/goto-instrument/call_sequences.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/cover.cpp
  src/goto-instrument/cover_instrument_assume.cpp
  src/goto-instrument/dot.cpp
  src/goto-instrument/full_slicer.cpp
  src/goto-instrument/generate_function_bodies.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-instrument/nondet_volatile.cpp
  src/goto-instrument/rw_set.cpp
  src/goto-instrument/unwind.cpp
  src/goto-instrument/wmm/weak_memory.cpp
  src/goto-programs/cfg.h
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_convert_functions.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_program.h
  src/goto-programs/goto_trace.cpp
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/instrument_preconditions.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/link_goto_model.cpp
  src/goto-programs/remove_skip.cpp
  src/goto-programs/remove_virtual_functions.cpp
  src/goto-programs/rewrite_union.cpp
  src/goto-programs/show_properties.cpp
  src/goto-programs/string_abstraction.cpp
  src/goto-symex/solver_hardness.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/goto_program_dereference.cpp
  src/pointer-analysis/value_set_domain.h
  unit/goto-instrument/cover_instrument.cpp
Labels: cleanup

#6844 Allow to force-load symbols from the cprover library
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/ansi_c_language.h
  src/ansi-c/cprover_library.cpp
  src/ansi-c/cprover_library.h
  src/linking/remove_internal_symbols.cpp
  src/linking/remove_internal_symbols.h
Labels: blocker, aws, aws-high

#6857 instructiont::get_code -> code
  jbmc/src/java_bytecode/remove_exceptions.cpp
  jbmc/src/java_bytecode/remove_instanceof.cpp
  jbmc/src/java_bytecode/replace_java_nondet.cpp
  jbmc/unit/java_bytecode/java_bytecode_instrument/virtual_call_null_checks.cpp
  jbmc/unit/java_bytecode/java_replace_nondet/replace_nondet.cpp
  src/analyses/cfg_dominators.h
  src/analyses/invariant_set_domain.cpp
  src/analyses/uncaught_exceptions_analysis.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/dot.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/wmm/fence.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/goto-instrument/wmm/shared_buffers.cpp
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/goto_program.h
  src/goto-programs/interpreter.cpp
  src/goto-programs/remove_returns.cpp
  src/goto-programs/remove_skip.cpp
  src/goto-programs/show_goto_functions_json.cpp
  src/goto-programs/show_goto_functions_xml.cpp
  src/goto-programs/validate_goto_model.cpp
  src/goto-programs/write_goto_binary.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/memory_model_tso.cpp
  src/goto-symex/solver_hardness.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/pointer-analysis/value_set_domain.h
  src/pointer-analysis/value_set_domain_fi.cpp
  unit/goto-programs/goto_program_function_call.cpp
Labels: cleanup

#6755 Disambiguate overloaded insert(...) calls [blocks: #6749]
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: cleanup, blocker

#6762 Full slicing: fix bugs in handling array_equal
  regression/cbmc/Array_operations1/full-slice.desc
  src/analyses/goto_rw.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: bugfix

#6763 Full slice: support havoc_object
  regression/cbmc/havoc_object1/full-slice.desc
  src/analyses/goto_rw.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: bugfix

#6848 Make compiling with DEBUG actually work
  src/analyses/variable-sensitivity/full_struct_abstract_object.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_domain.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-instrument/accelerate/cone_of_influence.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/trace_automaton.cpp
  src/goto-instrument/wmm/data_dp.cpp
  src/solvers/flattening/arrays.cpp
Labels: cleanup

#6784 Set base_name member for __CPROVER_start
  jbmc/src/java_bytecode/java_entry_point.cpp
  regression/goto-analyzer/reachable-functions-basic-json/test.desc
  regression/goto-analyzer/reachable-functions-basic-text/test.desc
  src/ansi-c/ansi_c_entry_point.cpp
  src/jsil/jsil_entry_point.cpp
  src/statement-list/statement_list_entry_point.cpp
  unit/analyses/ai/ai.cpp
Labels: bugfix, aws, aws-medium

#6727 Cleanup find_symbols API
  src/ansi-c/expr2c.cpp
  src/ansi-c/goto_check_c.cpp
  src/goto-instrument/accelerate/accelerate.cpp
  src/goto-instrument/accelerate/acceleration_utils.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/full_slicer.cpp
  src/goto-programs/goto_program.cpp
  src/goto-programs/slice_global_inits.cpp
  src/goto-symex/postcondition.cpp
  src/goto-symex/precondition.cpp
  src/util/find_macros.cpp
  src/util/find_symbols.cpp
  src/util/find_symbols.h
  src/util/irep_ids.def
Labels: cleanup, blocker

#6768 goto_rw/range_spect: gracefully handle arbitrarily large ranges
  regression/cbmc/havoc_slice_checks/full-slice.desc
  src/analyses/goto_rw.h
Labels: bugfix

#6860 Remove unused make_free_bv_expr
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/util/irep_ids.def
Labels: cleanup

#6873 SMT2 backend tweaks
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface

#6868 Support _Complex in the C++ front-end
  regression/ansi-c/gcc_attributes6/test.desc
  src/cpp/cpp_convert_type.cpp
  src/cpp/cpp_typecheck_type.cpp
Labels: C++ Front End, bugfix, blocker

#6728 Symex slicing: fixes and cleanup
  regression/cbmc/Malloc11/slice-formula.desc
  src/goto-symex/show_program.cpp
  src/goto-symex/slice.cpp
  src/goto-symex/symex_slice_class.h
Labels: bugfix

#6861 Use boolbv_width::get_member
  src/solvers/flattening/boolbv_member.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: cleanup

#6877 GitHub actions: add macOS 12
  .github/workflows/pull-request-checks.yaml
Labels: CI

#6889 C library: getrandom requires glibc >= 2.25
  regression/cbmc-library/getrandom-01/main.c
  src/ansi-c/library/random.c
Labels: bugfix, C Front End

#6888 Move left-hand side type casts to right-hand side
  regression/goto-instrument/dump-side-effect/main.c
  regression/goto-instrument/dump-side-effect/test.desc
  src/goto-programs/goto_clean_expr.cpp
Labels: bugfix

#6756 Remove unqualified use of nullopt [blocks: #6749]
  src/ansi-c/expr2c.cpp
  src/goto-analyzer/unreachable_instructions.cpp
  src/memory-analyzer/gdb_api.h
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_quantifier.cpp
  src/util/edit_distance.cpp
  src/util/optional_utils.h
  src/util/string2int.cpp
  unit/util/string2int.cpp
Labels: cleanup, blocker

#6896 Replace all uses of goto_programt::output_instruction
  src/analyses/ai.cpp
  src/analyses/flow_insensitive_analysis.cpp
  src/analyses/local_bitvector_analysis.cpp
  src/analyses/local_may_alias.cpp
  src/analyses/local_safe_pointers.cpp
  src/analyses/sese_regions.cpp
  src/analyses/static_analysis.cpp
  src/goto-analyzer/unreachable_instructions.cpp
  src/goto-diff/change_impact.cpp
  src/goto-diff/unified_diff.cpp
  src/goto-instrument/accelerate/disjunctive_polynomial_acceleration.cpp
  src/goto-instrument/accelerate/enumerating_loop_acceleration.cpp
  src/goto-instrument/accelerate/path.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/unwind.cpp
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/interpreter.cpp
  src/goto-programs/show_goto_functions.cpp
  src/goto-programs/show_goto_functions_json.cpp
  src/goto-programs/show_goto_functions_json.h
  src/goto-programs/show_goto_functions_xml.cpp
  src/goto-programs/show_goto_functions_xml.h
  src/pointer-analysis/value_set_analysis_fivr.h
  src/pointer-analysis/value_set_analysis_fivrns.h
Labels: cleanup

#6898 Generate-function-bodies: generate a meaningful assertion
  regression/goto-instrument/generate-function-body-assert-false-assume-false/test.desc
  regression/goto-instrument/generate-function-body-assert-false/test.desc
  regression/goto-instrument/generate-function-body/test.desc
  src/goto-instrument/generate_function_bodies.cpp
Labels: bugfix

#6788 Flexible array members: make type checking aware and fix bounds checking
  regression/cbmc/struct17/main.c
  regression/cbmc/struct17/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/goto_check_c.cpp
Labels: bugfix
