Repository diffblue/cbmc, pull requests merged in 2022-02, with the labels that each got.

#6560 Value sets should permit any order of operands in pointer arithmetic
  regression/cbmc/Pointer_Arithmetic19/main.c
  regression/cbmc/Pointer_Arithmetic19/test.desc
  regression/validate-trace-xml-schema/check.py
  src/pointer-analysis/value_set.cpp
Labels: bugfix

#6565 Fix and cleanup __CPROVER_{r,w,rw}_ok expansion
  regression/cbmc/r_w_ok9/main.c
  regression/cbmc/r_w_ok9/simplify.desc
  regression/cbmc/r_w_ok9/test.desc
  regression/validate-trace-xml-schema/check.py
  src/analyses/goto_check_c.cpp
Labels: bugfix

#6622 Use github.com Linux kernel mirror in integration test
  integration/linux/compile_linux.sh
Labels: Tests

#6610 Function pointer restrictions: support labels in JSON input
  regression/goto-instrument/restrict-function-pointer-by-label/json.desc
  regression/goto-instrument/restrict-function-pointer-by-label/restriction.json
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/restrict_function_pointers.cpp
  src/goto-programs/restrict_function_pointers.h
  unit/goto-programs/restrict_function_pointers.cpp
Labels: bugfix

#6640 Use source_locationt::nil() instead of local static_cast
  src/cpp/cpp_name.h
  src/goto-programs/goto_program.h
  src/util/expr.cpp
Labels: cleanup

#6642 List supported coverage criteria in CBMC's help output
  src/goto-instrument/cover.cpp
  src/goto-instrument/cover.h
Labels: cleanup

#6641 Block coverage reporting: do not use built-in locations
  src/goto-instrument/cover_basic_blocks.cpp
Labels: bugfix

#6636 goto_check_c: Remove unnecessary no_enum_check
  src/analyses/goto_check_c.cpp
Labels: cleanup

#6554 Linking/static lifetime init: do not use goto code types
  src/linking/static_lifetime_init.cpp
Labels: cleanup, blocker

#6630 goto-instrument --unwind: unwinding assertions do not disable unwinding assumptions
  regression/goto-instrument/unwind-assert2/main.c
  regression/goto-instrument/unwind-assert2/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/unwind.cpp
  src/goto-instrument/unwind.h
Labels: bugfix, blocker

#6553 C front-end: fix type checking with merged type
  regression/ansi-c/gcc_attributes1/main.c
  src/ansi-c/ansi_c_declaration.cpp
Labels: bugfix, C Front End

#6594 Do not generate enum-value checks for function call left-hand sides
  regression/cbmc/enum_is_in_range/enum_test3-simplified.desc
  regression/cbmc/enum_is_in_range/format.desc
  regression/cbmc/enum_is_in_range/no_duplicate.c
  regression/cbmc/enum_is_in_range/no_duplicate.desc
  regression/validate-trace-xml-schema/check.py
  src/analyses/goto_check_c.cpp
  src/goto-programs/builtin_functions.cpp
  src/util/arith_tools.cpp
  src/util/format_expr.cpp
  src/util/simplify_expr_boolean.cpp
Labels: bugfix

#6623 Diversify GitHub CI build platforms: add macOS 11, Windows 2022
  .github/workflows/pull-request-checks.yaml
  src/ansi-c/clang_builtin_headers.h
  src/ansi-c/gcc_builtin_headers_types.h
Labels: Tests

#6608 Exception utils: remove redundant what() implementations
  src/goto-programs/restrict_function_pointers.cpp
  src/goto-programs/slice_global_inits.h
  src/goto-programs/string_instrumentation.h
  src/memory-analyzer/gdb_api.h
  src/solvers/smt2/smt2_tokenizer.h
  src/util/exception_utils.cpp
  src/util/exception_utils.h
Labels: cleanup, blocker

#6649 Document steps to perform CMake configuration without network access
  COMPILING.md
Labels: documentation

#6652 Add missing test description file
  regression/cbmc/empty_compound_type3/test.desc
Labels: Tests

#6653 Support byte-extracting empty structs
  regression/cbmc/empty_compound_type4/main.c
  regression/cbmc/empty_compound_type4/test.desc
  src/solvers/flattening/boolbv_byte_extract.cpp
Labels: bugfix

#6664 Cleanup build_sizeof_expr
  src/ansi-c/expr2c.cpp
  src/util/pointer_offset_size.cpp
  src/util/pointer_offset_size.h
Labels: C Front End, cleanup

#6667 String abstraction: gracefully handle type casts from non-char types
  regression/cbmc/String_Abstraction24/main.c
  regression/cbmc/String_Abstraction24/test.desc
  src/goto-programs/string_abstraction.cpp
Labels: bugfix

#6673 Remove deprecated string abstraction methods
  src/goto-programs/string_abstraction.cpp
  src/goto-programs/string_abstraction.h
Labels: cleanup

#6674 Visual Studio rejects pointer arithmetic and dereferencing of void*
  regression/ansi-c/sizeof5/test.desc
  regression/cbmc-cpp/Function_Arguments1/test.desc
  regression/cbmc/null6/main.c
  regression/cbmc/ptr_arithmetic_on_null/test.desc
  regression/cbmc/void_pointer1/test.desc
  regression/cbmc/void_pointer2/test.desc
  regression/cbmc/void_pointer3/test.desc
  regression/cbmc/void_pointer5/test.desc
  regression/cbmc/void_pointer6/test.desc
  regression/cbmc/void_pointer7/test.desc
  regression/contracts/assigns_enforce_conditional_void_target/test.desc
  regression/contracts/assigns_enforce_conditional_void_target_list/test.desc
  regression/contracts/assigns_enforce_side_effects_1/test.desc
  regression/goto-cl/void-pointer/main.c
  regression/goto-cl/void-pointer/ptr-arithmetic.desc
  regression/goto-cl/void-pointer/test.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End

#6643 CONTRACTS: Moving `check_frame_conditions` to `instrument_assigns_clauset`.
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
Labels: cleanup, aws, aws-high, Code Contracts

#6683 MMIO rewriting must maintain type consistency
  regression/cbmc/mm_io1/main.c
  src/goto-programs/mm_io.cpp
Labels: bugfix

#6679 CONTRACTS: new method to detect static locals for contract instrumentation
  regression/contracts/assigns_enforce_19/main.c
  regression/contracts/assigns_enforce_19/test.desc
  regression/contracts/assigns_enforce_detect_replaced_local_statics/main.c
  regression/contracts/assigns_enforce_detect_replaced_local_statics/test.desc
  regression/contracts/loop_assigns_scoped_local_statics/main.c
  regression/contracts/loop_assigns_scoped_local_statics/test.desc
  regression/contracts/loop_assigns_scoped_local_statics_propagate/main.c
  regression/contracts/loop_assigns_scoped_local_statics_propagate/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/havoc_assigns_clause_targets.cpp
  src/goto-instrument/contracts/havoc_assigns_clause_targets.h
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
Labels: bugfix, aws, Code Contracts

#6505 Reachability slice requires function bodies
  jbmc/src/jbmc/jbmc_parse_options.cpp
  regression/goto-instrument/reachability-slice/main.c
  regression/goto-instrument/reachability-slice/test.desc
  src/cbmc/cbmc_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/reachability_slicer.cpp
  src/goto-instrument/reachability_slicer.h
  src/goto-instrument/reachability_slicer_class.h
  src/goto-programs/remove_calls_no_body.cpp
  src/goto-programs/remove_calls_no_body.h
Labels: bugfix

#6689 Add conversion of cast expressions to SMT terms for incremental SMT solving
  src/solvers/smt2_incremental/convert_expr_to_smt.cpp
  src/solvers/smt2_incremental/smt_bit_vector_theory.h
  src/solvers/smt2_incremental/smt_core_theory.h
  unit/solvers/smt2_incremental/convert_expr_to_smt.cpp
Labels: SMT Backend Interface

#6598 Add annotated_pointer_constant_exprt
  jbmc/src/java_bytecode/java_trace_validation.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/goto-programs/goto_trace.h
  src/goto-programs/json_expr.cpp
  src/solvers/flattening/boolbv_constant.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/util/format_expr.cpp
  src/util/irep_ids.def
  src/util/pointer_expr.h
  src/util/std_expr.h
Labels: blocker

#6680 Make CBMC and JBMC share solver-related command-line parsing
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-checker/solver_factory.cpp
  src/goto-checker/solver_factory.h
Labels: cleanup

#5835 Do not use invalid_source_file_exceptiont without source location
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/lazy_goto_model.cpp
  src/crangler/ctokenit.cpp
  src/crangler/mini_c_parser.cpp
  src/memory-analyzer/analyze_symbol.cpp
  src/symtab2gb/symtab2gb_parse_options.cpp
  src/util/exception_utils.cpp
  src/util/exception_utils.h
  unit/testing-utils/get_goto_model_from_c.cpp
Labels: blocker

#6682 Java front-end: fix vector index type in populate_live_range_holes
  jbmc/src/java_bytecode/java_local_variable_table.cpp
Labels: bugfix, blocker

#6693 C library: add models of mmap, munmap
  regression/cbmc-library/mmap-01/main.c
  regression/cbmc-library/mmap-01/test.desc
  src/ansi-c/library/mman.c
Labels: C Front End

#6687 goto_check_ct: Transforming assertions and assumptions is language-agnostic
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.cpp
  src/analyses/goto_check.cpp
  src/analyses/goto_check.h
  src/analyses/goto_check_c.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/process_goto_program.cpp
Labels: blocker

#6672 Remove deprecated dynamic_object pointer predicate
  src/pointer-analysis/value_set_dereference.cpp
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: cleanup

#6659 do_designated_initializer: code cleanup
  src/ansi-c/c_typecheck_initializer.cpp
Labels: cleanup

#5758 Handle bool expressions in implicit_typecast_arithmetic
  regression/ansi-c/int128_and_bool1/main.c
  regression/ansi-c/int128_and_bool1/test.desc
  regression/cbmc/enum9/main.c
  regression/cbmc/enum9/test.desc
  src/ansi-c/c_typecast.cpp
Labels: bugfix, C Front End

#2736 tolerate two cases of imprecision in value_set_fi; addresses issue #2653
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: bugfix

#6661 Support non-heap allocated flexible arrays
  regression/cbmc/struct16/main.c
  regression/cbmc/struct16/test.desc
  src/ansi-c/c_typecheck_initializer.cpp
Labels: bugfix

#6686 Remove goto_check_java
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/janalyzer/janalyzer_parse_options.h
  jbmc/src/java_bytecode/Makefile
  jbmc/src/java_bytecode/goto_check_java.cpp
  jbmc/src/java_bytecode/goto_check_java.h
  jbmc/src/jbmc/jbmc_parse_options.cpp
  jbmc/src/jbmc/jbmc_parse_options.h
  jbmc/src/jdiff/jdiff_parse_options.cpp
  jbmc/src/jdiff/jdiff_parse_options.h
Labels: cleanup

#6684 Remove ID_C_bounds_check special-case in goto_check_ct
  src/analyses/goto_check_c.cpp
  src/ansi-c/ansi_c_entry_point.cpp
  src/goto-programs/string_abstraction.cpp
Labels: cleanup
