Repository diffblue/cbmc, pull requests merged in 2022-06, with the labels that each got.

#6901 Remove "inline" from library models [blocks: #6863]
  regression/goto-analyzer/heap-allocation-nondet-1/main.c
  regression/goto-analyzer/heap-allocation-nondet-2/main.c
  regression/goto-analyzer/heap-allocation-nondet-3/main.c
  regression/goto-analyzer/heap-allocation-nondet-4/main.c
  regression/goto-analyzer/heap-allocation-nondet-5/main.c
  regression/goto-analyzer/heap-allocation-nondet-6/main.c
  regression/goto-analyzer/heap-allocation-write-2/main.c
  regression/goto-analyzer/heap-allocation-write/main.c
  regression/goto-analyzer/heap-allocation/main.c
  src/ansi-c/library/ctype.c
  src/ansi-c/library/errno.c
  src/ansi-c/library/fenv.c
  src/ansi-c/library/float.c
  src/ansi-c/library/gcc.c
  src/ansi-c/library/getopt.c
  src/ansi-c/library/intrin.c
  src/ansi-c/library/locale.c
  src/ansi-c/library/math.c
  src/ansi-c/library/pthread_lib.c
  src/ansi-c/library/semaphore.c
  src/ansi-c/library/setjmp.c
  src/ansi-c/library/stdio.c
  src/ansi-c/library/stdlib.c
  src/ansi-c/library/string.c
  src/ansi-c/library/unistd.c
  src/ansi-c/library/windows.c
  src/ansi-c/library/x86_assembler.c
Labels: bugfix, blocker

#6863 GitHub actions: Ubuntu 22.04 [depends-on: #6901]
  .github/workflows/pull-request-checks.yaml
Labels: CI

#6681 CBMC/JBMC: do not attempt to parse unused option pretty-names
  doc/man/cbmc.1
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/goto-checker/bmc_util.h
Labels: cleanup

#6909 Fix architecture typo x64_64 -> x86_64
  regression/ansi-c/sizeof1/main.c
  src/util/config.cpp
Labels: bugfix

#6915 String refinement: support pointers
  jbmc/regression/strings-smoke-tests/java_set_length/test.desc
  jbmc/unit/solvers/strings/string_constraint_instantiation/instantiate_not_contains.cpp
  src/goto-instrument/wmm/goto2graph.cpp
  src/solvers/README.md
  src/solvers/strings/string_builtin_function.cpp
  src/solvers/strings/string_builtin_function.h
  src/solvers/strings/string_concatenation_builtin_function.cpp
  src/solvers/strings/string_concatenation_builtin_function.h
  src/solvers/strings/string_constraint.cpp
  src/solvers/strings/string_constraint.h
  src/solvers/strings/string_constraint_generator.h
  src/solvers/strings/string_constraint_generator_comparison.cpp
  src/solvers/strings/string_constraint_generator_indexof.cpp
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_constraint_generator_testing.cpp
  src/solvers/strings/string_constraint_generator_transformation.cpp
  src/solvers/strings/string_dependencies.cpp
  src/solvers/strings/string_dependencies.h
  src/solvers/strings/string_format_builtin_function.cpp
  src/solvers/strings/string_format_builtin_function.h
  src/solvers/strings/string_insertion_builtin_function.cpp
  src/solvers/strings/string_insertion_builtin_function.h
  src/solvers/strings/string_refinement.cpp
  src/xmllang/graphml.cpp
  src/xmllang/graphml.h
Labels: bugfix

#6936 SMT2 backend: workaround for Z3 get-value limitation
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_dec.cpp
Labels: SMT Backend Interface, bugfix

#6942 Add symtab2gb man page
  doc/man/symtab2gb.1
Labels: documentation

#6940 SMT2 backend: generate simple symbols
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_dec.cpp
  src/solvers/smt2/smt2_tokenizer.cpp
  src/solvers/smt2/smt2_tokenizer.h
  src/solvers/smt2_incremental/smt_to_smt2_string.cpp
  unit/solvers/smt2/smt2_conv.cpp
  unit/solvers/smt2_incremental/smt_to_smt2_string.cpp
Labels: SMT Backend Interface

#6935 SMT2 backend: move quoting into convert_identifier
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_dec.cpp
  src/solvers/smt2_incremental/smt_to_smt2_string.cpp
  unit/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, cleanup

#6944 Add memory-analyzer man page
  doc/man/memory-analyzer.1
  src/memory-analyzer/CMakeLists.txt
Labels: documentation

#6932 Data-flow analyzers: don't document show-intervals, show-non-null
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.cpp
Labels: cleanup

#6959 Function pointer removal: argument conversion must use byte extract
  regression/cbmc/Function_Pointer19/main.c
  regression/cbmc/Function_Pointer19/test.desc
  regression/cbmc/Linking7/member-name-mismatch.desc
  regression/cbmc/Linking7/test.desc
  src/goto-programs/remove_function_pointers.cpp
Labels: bugfix

#6954 Byte update lowering: never create extractbits over unbounded arrays
  regression/cbmc/byte_update16/big-endian.desc
  regression/cbmc/byte_update16/little-endian.desc
  regression/cbmc/byte_update16/main.c
  src/solvers/lowering/byte_operators.cpp
Labels: bugfix

#6964 Document all supported options for --arch and --os
  src/util/config.h
Labels: bugfix

#6947 CONTRACTS: detect and handle locals in assigns clause checking for loops
  regression/contracts/detect_loop_locals/main.c
  regression/contracts/detect_loop_locals/test.desc
  regression/contracts/detect_loop_locals2/main.c
  regression/contracts/detect_loop_locals2/test.desc
  regression/contracts/invar_check_nested_loops/test.desc
  regression/contracts/loop_guard_with_side_effects/test.desc
  regression/contracts/loop_guard_with_side_effects_fail/test.desc
  src/goto-instrument/contracts/cfg_info.h
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/havoc_assigns_clause_targets.h
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
  src/goto-instrument/contracts/utils.h
Labels: bugfix, aws, aws-high, Code Contracts

#6945 Add goto-cc man page
  doc/man/goto-cc.1
  doc/man/goto-gcc.1
  doc/man/goto-ld.1
  src/goto-cc/goto_cc_mode.cpp
Labels: documentation

#6972 Add jbmc man page
  doc/man/jbmc.1
Labels: documentation

#5837 Add source location to invalid_source_file_exceptiont
  regression/ansi-c/character_literals1/unsupported-wide.desc
  regression/ansi-c/character_literals1/unsupported.c
  regression/ansi-c/character_literals1/unsupported.desc
  regression/ansi-c/enum_is_in_range/enum_test10.desc
  regression/ansi-c/enum_is_in_range/enum_test12.desc
  regression/cbmc/gcc_builtin_add_overflow/type-conflict.desc
  regression/cbmc/saturating_arithmetric/typeconflict.c
  regression/cbmc/saturating_arithmetric/typeconflict.desc
  src/ansi-c/ansi_c_typecheck.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/literals/convert_character_literal.cpp
  src/ansi-c/literals/convert_character_literal.h
  src/ansi-c/scanner.l
  src/cpp/cpp_typecheck.cpp
  src/crangler/mini_c_parser.cpp
  src/goto-cc/goto_cc_mode.cpp
  src/goto-programs/string_instrumentation.cpp
  src/goto-programs/string_instrumentation.h
  src/symtab2gb/symtab2gb_parse_options.cpp
  src/util/exception_utils.cpp
  src/util/exception_utils.h
  src/util/typecheck.cpp
Labels: cleanup

#6981 Location coverage reporting should ignore globals
  regression/cbmc-cover/location2/main.c
  regression/cbmc-cover/location2/test.desc
  src/goto-instrument/cover_basic_blocks.cpp
Labels: bugfix

#6962 goto-instrument: remove --check-invariant from help output
  src/goto-instrument/goto_instrument_parse_options.cpp
Labels: cleanup, blocker

#6856 Constant propagation for individual fields through byte extract
  jbmc/regression/jbmc/array-cell-sensitivity1/test-max-array-size-10.desc
  jbmc/regression/jbmc/array-cell-sensitivity1/test.desc
  regression/cbmc-incr-oneloop/Makefile
  regression/cbmc/Array_UF22/test.desc
  regression/cbmc/Pointer21/test.desc
  regression/cbmc/array-cell-sensitivity1/test.desc
  regression/cbmc/array-cell-sensitivity10/test.desc
  regression/cbmc/array-cell-sensitivity3/test.desc
  regression/cbmc/array-cell-sensitivity4/test.desc
  regression/cbmc/array-cell-sensitivity5/test.desc
  regression/cbmc/array-cell-sensitivity6/test.desc
  regression/cbmc/array-cell-sensitivity7/test.desc
  regression/cbmc/array-cell-sensitivity8/test.desc
  regression/cbmc/array-cell-sensitivity9/test.desc
  regression/cbmc/field-sensitivity14/main.c
  regression/cbmc/field-sensitivity14/test.desc
  regression/cbmc/field-sensitivity9/test.desc
  regression/cbmc/member_bounds3/test.desc
  regression/cbmc/member_bounds4/test.desc
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/field_sensitivity.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/goto_symex_state.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_main.cpp
  src/util/simplify_expr.cpp
  unit/goto-symex/apply_condition.cpp
  unit/goto-symex/goto_symex_state.cpp
  unit/goto-symex/symex_assign.cpp
  unit/goto-symex/try_evaluate_pointer_comparisons.cpp
Labels: Symbolic Execution, aws-high, Kani

#6985 De-duplicate and fix code of value-set backed function pointer removal
  regression/goto-instrument/value-set-fi-fp-removal7/main.c
  regression/goto-instrument/value-set-fi-fp-removal7/test.desc
  src/goto-instrument/value_set_fi_fp_removal.cpp
Labels: bugfix

#6799 CONTRACTS: store contracts in dedicated symbols
  regression/contracts/named-contracts/main-contract-after-declaration.c
  regression/contracts/named-contracts/main-contract-after-definition.c
  regression/contracts/named-contracts/main-contract-incomplete.c
  regression/contracts/named-contracts/main-contract-signature-conflict.c
  regression/contracts/named-contracts/main-definition-after-contract.c
  regression/contracts/named-contracts/main-no-definition.c
  regression/contracts/named-contracts/test-contract-after-declaration.desc
  regression/contracts/named-contracts/test-contract-after-definition.desc
  regression/contracts/named-contracts/test-contract-incomplete.desc
  regression/contracts/named-contracts/test-contract-signature-conflict.desc
  regression/contracts/named-contracts/test-definition-after-contract.desc
  regression/contracts/named-contracts/test-no-definition.desc
  src/ansi-c/c_typecheck_base.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/horn_encoding.cpp
  src/linking/linking.cpp
  src/linking/remove_internal_symbols.cpp
  src/util/c_types.h
  src/util/rename_symbol.cpp
  src/util/replace_symbol.cpp
Labels: aws, aws-high, Code Contracts
