Repository diffblue/cbmc, pull requests merged in 2022-01, with the labels that each got.

#6540 Fix havocking of dependent assigns clause targets
  regression/contracts/assigns-replace-ignored-return-value/main.c
  regression/contracts/assigns-replace-ignored-return-value/test.desc
  regression/contracts/assigns_enforce_21/test.desc
  regression/contracts/assigns_replace_08/test.desc
  regression/contracts/assigns_replace_09/test.desc
  regression/contracts/assigns_replace_havoc_dependent_targets_fail/enforce.desc
  regression/contracts/assigns_replace_havoc_dependent_targets_fail/main_enforce.c
  regression/contracts/assigns_replace_havoc_dependent_targets_fail/main_replace.c
  regression/contracts/assigns_replace_havoc_dependent_targets_fail/replace.desc
  regression/contracts/assigns_replace_havoc_dependent_targets_fail/vect.h
  regression/contracts/assigns_replace_havoc_dependent_targets_pass/enforce.desc
  regression/contracts/assigns_replace_havoc_dependent_targets_pass/main_enforce.c
  regression/contracts/assigns_replace_havoc_dependent_targets_pass/main_replace.c
  regression/contracts/assigns_replace_havoc_dependent_targets_pass/replace.desc
  regression/contracts/assigns_replace_havoc_dependent_targets_pass/vect.h
  regression/contracts/history-constant/main.c
  regression/contracts/history-constant/test.desc
  regression/contracts/history-typecast/main.c
  regression/contracts/history-typecast/test.desc
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/havoc_assigns_clause_targets.cpp
  src/goto-instrument/contracts/havoc_assigns_clause_targets.h
Labels: bugfix, aws, aws-high, Code Contracts

#6557 Value sets must not return an empty set for nondet symbols
  regression/cbmc/double_deref/double_deref_with_pointer_arithmetic.desc
  regression/cbmc/double_deref/double_deref_with_pointer_arithmetic_single_alias.desc
  regression/cbmc/symex_should_exclude_null_pointers/nondet.c
  regression/cbmc/symex_should_exclude_null_pointers/nondet.desc
  src/pointer-analysis/value_set.cpp
Labels: bugfix, aws-high

#6544 Remove and replace use of look_through_casts
  jbmc/src/java_bytecode/java_pointer_casts.cpp
  src/analyses/variable-sensitivity/interval_abstract_value.cpp
Labels: cleanup

#6567 CONTRACTS: remove redundant "::" in generated symbol names
  regression/contracts/history-pointer-replace-01/test.desc
  regression/contracts/history-pointer-replace-02/test.desc
  src/goto-instrument/contracts/utils.cpp
Labels: cleanup

#6549 move solver_hardness.* from solvers/ to goto-symex/
  src/goto-checker/multi_path_symex_checker.cpp
  src/goto-checker/solver_factory.cpp
  src/goto-symex/Makefile
  src/goto-symex/solver_hardness.cpp
  src/goto-symex/solver_hardness.h
  src/goto-symex/symex_target_equation.cpp
  src/solvers/Makefile
  src/solvers/flattening/arrays.h
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/boolbv_member.cpp
  src/solvers/flattening/boolbv_struct.cpp
  src/solvers/flattening/boolbv_typecast.cpp
  src/solvers/flattening/boolbv_update.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/hardness_collector.h
  src/solvers/module_dependencies.txt
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/prop/prop_conv_solver.h
  src/solvers/sat/satcheck_cadical.cpp
  src/solvers/sat/satcheck_cadical.h
  src/solvers/sat/satcheck_glucose.cpp
  src/solvers/sat/satcheck_glucose.h
  src/solvers/sat/satcheck_ipasir.cpp
  src/solvers/sat/satcheck_ipasir.h
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/sat/satcheck_minisat2.h
  src/solvers/strings/string_constraint.cpp
  unit/solvers/bdd/miniBDD/miniBDD.cpp
Labels: Solvers, cleanup

#6551 rename post_process to finish_eager_conversion
  src/solvers/flattening/arrays.h
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_quantifier.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
  src/solvers/flattening/equality.h
  src/solvers/lowering/functions.h
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/prop/prop_conv_solver.h
  src/solvers/refinement/bv_refinement.h
  src/solvers/refinement/bv_refinement_loop.cpp
  src/solvers/refinement/refine_arrays.cpp
Labels: Solvers, cleanup

#6568 CONTRACTS: fix typo member name
  src/goto-instrument/contracts/assigns.cpp
  src/goto-instrument/contracts/assigns.h
Labels: cleanup

#6569 C nondet factory: Ensure parameter initialisers use unique symbol names
  jbmc/src/java_bytecode/java_object_factory.cpp
  regression/cbmc/pointer-function-parameters/main.c
  regression/cbmc/pointer-function-parameters/test.desc
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/ansi-c/c_nondet_symbol_factory.h
  src/goto-programs/allocate_objects.cpp
  src/goto-programs/allocate_objects.h
Labels: bugfix, C Front End

#6580 introduce pointer_typet::base_type()
  jbmc/src/java_bytecode/assignments_from_json.cpp
  jbmc/src/java_bytecode/ci_lazy_methods_needed.cpp
  jbmc/src/java_bytecode/code_with_references.cpp
  jbmc/src/java_bytecode/generic_parameter_specialization_map_keys.cpp
  jbmc/src/java_bytecode/goto_check_java.cpp
  jbmc/src/java_bytecode/java_bytecode_concurrency_instrumentation.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_convert_method.cpp
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_pointer_casts.cpp
  jbmc/src/java_bytecode/java_string_library_preprocess.cpp
  jbmc/src/java_bytecode/java_types.cpp
  jbmc/src/java_bytecode/java_types.h
  jbmc/src/java_bytecode/java_utils.cpp
  jbmc/src/java_bytecode/select_pointer_type.cpp
  jbmc/unit/java_bytecode/goto_program_generics/generic_parameters_test.cpp
  jbmc/unit/java_bytecode/goto_program_generics/mutually_recursive_generics.cpp
  jbmc/unit/java_bytecode/java_bytecode_convert_method/convert_invoke_dynamic.cpp
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/parse_generic_array_class.cpp
  jbmc/unit/java_bytecode/java_bytecode_parse_generics/parse_generic_class_with_inner_classes.cpp
  jbmc/unit/java_bytecode/java_bytecode_parser/parse_java_annotations.cpp
  jbmc/unit/java_bytecode/java_static_initializers/assignments_from_json.cpp
  src/analyses/goto_check_c.cpp
  src/analyses/variable-sensitivity/two_value_pointer_abstract_object.cpp
  src/ansi-c/c_nondet_symbol_factory.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_gcc_polymorphic_builtins.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_virtual_table.cpp
  src/goto-harness/function_call_harness_generator.cpp
  src/goto-harness/recursive_initialization.cpp
  src/goto-instrument/thread_instrumentation.cpp
  src/goto-programs/builtin_functions.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-programs/json_expr.cpp
  src/goto-programs/restrict_function_pointers.cpp
  src/goto-programs/xml_expr.cpp
  src/goto-symex/auto_objects.cpp
  src/goto-symex/goto_symex.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/renaming_level.cpp
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_dereference.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/pointer_logic.cpp
  src/util/base_type.cpp
  src/util/format_expr.cpp
  src/util/format_type.cpp
  src/util/pointer_expr.cpp
  src/util/pointer_expr.h
  src/util/pointer_predicates.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#6578 Actually test linker script processing
  regression/ansi-c/Makefile
  regression/cbmc-cpp/Makefile
  regression/cpp/Makefile
  regression/goto-gcc/CMakeLists.txt
  regression/goto-gcc/Makefile
  regression/goto-gcc/linker_script_start+end/main.c
  regression/goto-gcc/linker_script_start+end/script.ld
  regression/goto-gcc/linker_script_start+end/test.desc
  regression/goto-gcc/linker_script_start+size/main.c
  regression/goto-gcc/linker_script_start+size/script.ld
  regression/goto-gcc/linker_script_start+size/test.desc
  regression/goto-gcc/linker_script_symbol-only/main.c
  regression/goto-gcc/linker_script_symbol-only/script.ld
  regression/goto-gcc/linker_script_symbol-only/test.desc
  regression/systemc/Makefile
  src/goto-cc/CMakeLists.txt
Labels: bugfix, Tests

#6574 CONTRACTS: is_fresh declarations are handled via the symbol table
  src/goto-instrument/contracts/memory_predicates.cpp
Labels: cleanup, Code Contracts

#6531 Use null_pointer_exprt
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/cpp/parse.cpp
  unit/interpreter/interpreter.cpp
Labels: cleanup

#6595 goto-cc: newlines in command files are just whitespace
  regression/goto-gcc/at_files/args
  src/goto-cc/gcc_cmdline.cpp
Labels: bugfix

#6597 Regression test scripts: use /Fe with goto-cl
  regression/contracts/chain.sh
  regression/goto-cc-cbmc-shared-options/chain.sh
  regression/goto-cc-cbmc/chain.sh
  regression/goto-cc-goto-analyzer/chain.sh
  regression/goto-cc-multi-file/chain.sh
  regression/goto-cc-regression-gh-issue-5380/chain.sh
  regression/goto-harness/chain.sh
  regression/goto-instrument-typedef/chain.sh
  regression/goto-instrument/chain.sh
  regression/goto-interpreter/chain.sh
Labels: cleanup, Tests

#6583 C library: define exactly one function per comment block
  src/ansi-c/library/pthread_lib.c
Labels: C Front End, blocker

#6603 Invoke functions marked __attribute__((destructor))
  regression/cbmc/destructor1/main.c
  regression/cbmc/destructor1/test.desc
  src/ansi-c/ansi_c_entry_point.cpp
Labels: C Front End

#6605 Enable rotate left/right tests on all platforms
  regression/cbmc/clang_builtins/rotate.c
  regression/cbmc/clang_builtins/rotate.desc
Labels: Tests

#6007 ansi_c_entry_point: avoid magic number
  regression/cbmc/argv2/main.i
  regression/cbmc/argv2/test.desc
  regression/cbmc/multiple-goto-traces/test.desc
  src/ansi-c/ansi_c_entry_point.cpp
  src/util/config.cpp
  src/util/config.h
Labels: C Front End

#5834 generate_ansi_c_start_function reports user errors via return code
  regression/ansi-c/human-readable-error-on-wrong-main-signature/main.c
  regression/ansi-c/human-readable-error-on-wrong-main-signature/test.desc
  src/ansi-c/ansi_c_entry_point.cpp
Labels: blocker

#6602 Bug fix piped process on Windows
  .github/workflows/pull-request-checks.yaml
  regression/cbmc-incr-smt2/nondeterministic-int-assert/control_flow.desc
  regression/cbmc-incr-smt2/nondeterministic-int-assert/incremental_solver_called.desc
  regression/cbmc-incr-smt2/nondeterministic-int-assert/trace.desc
  regression/cbmc-incr-smt2/nondeterministic-int-assert/valid_unsat.desc
  src/solvers/smt2_incremental/smt_solver_process.cpp
  src/util/piped_process.cpp
  src/util/piped_process.h
  unit/util/piped_process.cpp
Labels: SMT Backend Interface

#6612 Cleanup processing and use __builtin_X_overflow
  regression/cbmc/gcc_builtin_add_overflow/main.c
  regression/cbmc/gcc_builtin_add_overflow/test.desc
  regression/cbmc/gcc_builtin_add_overflow/type-conflict-2.desc
  regression/cbmc/gcc_builtin_add_overflow/type-conflict.c
  regression/cbmc/gcc_builtin_add_overflow/type-conflict.desc
  regression/cbmc/gcc_builtin_mul_overflow/main.c
  regression/cbmc/gcc_builtin_mul_overflow/test.desc
  regression/cbmc/gcc_builtin_sub_overflow/main.c
  regression/cbmc/gcc_builtin_sub_overflow/test.desc
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/library/math.c
  src/ansi-c/library/stdlib.c
  src/ansi-c/library_check.sh
Labels: C Front End, cleanup
