Repository diffblue/cbmc, pull requests merged in 2022-09, with the labels that each got.

#7083 CONTRACTS: Handle all 4 inlining warning types in `inlining_decoratort`
  regression/contracts/function-calls-03-1/test-enf-f1.desc
  regression/contracts/function-calls-03-1/test-enf-f2.desc
  regression/contracts/function-calls-04-1/test-enf-f1.desc
  regression/contracts/function-calls-04-1/test-enf-f2_in.desc
  regression/contracts/function-calls-04-1/test-enf-f2_out.desc
  regression/contracts/function-calls-recursive-01/test.desc
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/inlining_decorator.cpp
  src/goto-instrument/contracts/inlining_decorator.h
Labels: aws, aws-high, Code Contracts

#6878 remove uses of typet::subtype() const
  jbmc/src/java_bytecode/assignments_from_json.cpp
  jbmc/src/java_bytecode/java_types.cpp
  jbmc/src/java_bytecode/remove_instanceof.cpp
  jbmc/src/java_bytecode/remove_java_new.cpp
  src/analyses/variable-sensitivity/constant_pointer_abstract_object.cpp
  src/analyses/variable-sensitivity/full_array_abstract_object.cpp
  src/analyses/variable-sensitivity/value_set_pointer_abstract_object.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_domain.cpp
  src/goto-programs/remove_const_function_pointers.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_fi.cpp
Labels: cleanup

#7097 protect typet::subtype() const
  jbmc/unit/java-testing-utils/require_goto_statements.cpp
  jbmc/unit/java-testing-utils/require_type.cpp
  src/cpp/cpp_typecheck_conversions.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/goto-programs/string_abstraction.cpp
  src/util/type.h
Labels: cleanup

#7099 Install a newer version of z3 in Ubuntu 18.04 release package build job
  .github/workflows/release-packages.yaml
Labels: bugfix, CI

#7100 Improve slack notifications on releases for Linux packages
  .github/workflows/regular-release.yaml
  .github/workflows/release-packages.yaml
Labels: CI

#7102 Fix macOS home-brew PR slack notifications for new release
  .github/workflows/release-packages.yaml
  scripts/slack_notification_action.go
Labels: CI

#7098 remove uses of typet::subtype() nonconst
  jbmc/src/java_bytecode/java_bytecode_convert_class.cpp
  jbmc/src/java_bytecode/java_bytecode_typecheck_type.cpp
  jbmc/src/java_bytecode/java_object_factory.cpp
  jbmc/src/java_bytecode/java_pointer_casts.cpp
  jbmc/src/java_bytecode/java_types.cpp
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/literals/convert_string_literal.cpp
  src/cpp/cpp_template_type.h
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/function.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/class_identifier.cpp
  src/goto-programs/goto_convert_side_effect.cpp
  src/goto-programs/remove_complex.cpp
  src/goto-programs/remove_vector.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/symex_dereference.cpp
  src/pointer-analysis/add_failed_symbols.cpp
  src/pointer-analysis/value_set_fi.cpp
  src/solvers/strings/string_constraint_generator_main.cpp
  src/solvers/strings/string_refinement.cpp
  src/util/rename_symbol.cpp
  src/util/replace_symbol.cpp
  src/util/simplify_expr_pointer.cpp
Labels: cleanup

#7116 SMT2 backend: remove extra whitespace
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface

#7114 add clang's __builtin_assume
  src/ansi-c/clang_builtin_headers.h
Labels: C Front End

#7119 add __CPROVER_live_object and __CPROVER_writeable_object
  src/util/irep_ids.def
  src/util/pointer_expr.h
Labels: C Front End

#7118 add __CPROVER_is_list(p)
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
Labels: C Front End

#7122 bv_utilst::zeros: code cleanup, use more widely
  src/solvers/flattening/boolbv_div.cpp
  src/solvers/flattening/bv_utils.cpp
  src/solvers/flattening/bv_utils.h
Labels: cleanup

#7117 add __CPROVER_is_cstring(p) and __CPROVER_cstrlen(p)
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/util/irep_ids.def
  src/util/pointer_expr.h
Labels: C Front End, Needs rebase

#6970 Add goto-diff man page
  doc/man/goto-diff.1
Labels: documentation

#6968 Update goto-instrument man page
  doc/architectural/nondet-volatile.md
  doc/architectural/restrict-function-pointer.md
  doc/cprover-manual/goto-instrument.md
  doc/man/goto-instrument.1
Labels: documentation

#7123 add three doubly-linked list predicates
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
Labels: C Front End

#7125 writeable_object and live_object
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/expr2c.cpp
Labels: C Front End

#7128 introduce cstrlen_exprt
  src/ansi-c/c_typecheck_expr.cpp
  src/util/irep_ids.def
  src/util/pointer_expr.h
Labels: C Front End

#7137 fix expr2c on lambda expressions
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
Labels: bugfix

#7129 Update CODEOWNERS for code contracts
  CODEOWNERS
Labels: aws

#7063 CONTRACTS: filter out contract symbols when resolving entry points and interrupt handlers
  regression/contracts/entry_point/main.c
  regression/contracts/entry_point/test.desc
  src/ansi-c/ansi_c_entry_point.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/goto-instrument/interrupt.cpp
  src/jsil/jsil_entry_point.cpp
Labels: bugfix, aws, aws-high, Code Contracts

#7140 add index type to the array type
  src/ansi-c/c_typecheck_type.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/irep_ids.def
  src/util/std_types.cpp
  src/util/std_types.h
Labels: C Front End

#7142 Test __CPROVER_ID support in the C front-end
  regression/cbmc/cprover_id1/main.c
  regression/cbmc/cprover_id1/test.desc
  src/ansi-c/parser.y
Labels: C Front End, Tests, documentation

#7045 Remove well-alignedness assumption from pointer dereferencing
  regression/cbmc/Array_operations2/main.c
  regression/cbmc/Array_operations2/test.desc
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_dereference.h
Labels: bugfix, aws, aws-high, soundness

#7143 add index type to the C vector type
  src/ansi-c/c_expr.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/util/std_types.cpp
  src/util/std_types.h
  unit/solvers/lowering/byte_operators.cpp
Labels: C Front End

#6741 Symex: ignore assignments to string constant even through type casts
  regression/cbmc/string_assignment1/main.c
  regression/cbmc/string_assignment1/test.desc
  src/goto-symex/goto_symex_state.h
Labels: bugfix, aws, aws-high

#7065 Crangler: add loop invariants with loop numbers
  regression/crangler/loop-invariant-03/main.c
  regression/crangler/loop-invariant-03/test.desc
  regression/crangler/loop-invariant-03/test.json
  src/crangler/c_wrangler.cpp
Labels: aws, aws-medium, Synthesis

#5740 Evaluate __builtin_ffs{,l,ll} over constants at compile time
  regression/cbmc/__builtin_ffs-01/main.c
  regression/cbmc/__builtin_ffs-01/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/library/gcc.c
  src/solvers/flattening/boolbv.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/bitvector_expr.cpp
  src/util/bitvector_expr.h
  src/util/format_expr.cpp
  src/util/irep_ids.def
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
Labels: C Front End

#7023 Cleanup GOTO model validation of function calls
  src/goto-programs/validate_goto_model.cpp
  src/goto-programs/validate_goto_model.h
  unit/goto-programs/goto_program_validate.cpp
Labels: aws, aws-medium

#7150 Function pointer restrictions: fix empty reason in error reporting
  regression/goto-instrument/restrict-function-pointer-error-reporting/main.c
  regression/goto-instrument/restrict-function-pointer-error-reporting/test.desc
  src/goto-programs/restrict_function_pointers.cpp
  src/goto-programs/restrict_function_pointers.h
Labels: bugfix, aws

#7151 Upgrade CodeQL GitHub action to v2
  .github/workflows/codeql-analysis.yml
Labels: CI

#7149 Publish documentation
  .github/workflows/publish.yaml
  doc/ADR/README.md
  doc/ADR/homebrew_tap.md
  doc/ADR/release_process.md
  doc/API/README.md
  doc/API/util/piped_process.md
  doc/architectural/background-concepts.md
  doc/architectural/cbmc-architecture.md
  doc/architectural/code-walkthrough.md
  doc/architectural/compilation-and-development.md
  doc/architectural/folder-walkthrough.md
  doc/architectural/front-page.md
  doc/architectural/howto.md
  doc/architectural/memory-analyzer.md
  doc/architectural/memory-bounds-checking.md
  doc/architectural/other-tools.md
  doc/cprover-manual/cbmc-tutorial.md
  doc/cprover-manual/contracts-loops.md
  doc/cprover-manual/contracts.md
  doc/cprover-manual/goto-analyzer.md
  doc/cprover-manual/index.md
  doc/cprover-manual/properties.md
  doc/doxygen-root/.gitignore
  doc/doxygen-root/DoxygenLayout.xml
  doc/doxygen-root/Makefile
  doc/doxygen-root/README.md
  doc/doxygen-root/contributing.md
  doc/doxygen-root/developer_guide.md
  doc/doxygen-root/doxyfile
  doc/doxygen-root/doxyfile-doc-adr
  doc/doxygen-root/doxyfile-doc-api
  doc/doxygen-root/doxyfile-doc-assets
  doc/doxygen-root/doxyfile-doc-cprover-manual
  doc/doxygen-root/doxygen-markdown/append-last-modified-dates.py
  doc/doxygen-root/doxygen-markdown/doxygen-markdown-preprocessor.py
  doc/doxygen-root/doxygen-markdown/markdown.sh
  doc/doxygen-root/doxygen-markdown/pandoc-codeblock-repair.sh
  doc/doxygen-root/doxygen-markdown/pandoc-cprover-link-filter.py
  doc/doxygen-root/index.md
  doc/doxygen-root/installation.md
  doc/doxygen-root/reference_guide.md
  doc/doxygen-root/user_guide.md
  doc/satabs-user-manual.md
  src/goto-harness/README.md
  src/goto-symex/README.md
Labels: documentation, aws, aws-high

#7155 Remove deprecated functions from find_symbols
  src/util/find_symbols.cpp
  src/util/find_symbols.h
Labels: cleanup

#7154 Remove deprecated variants of exprt::{add,copy}_to_operands
  src/util/expr.h
Labels: cleanup

#6976 C entry point generator: no unconditional conversion to pointer type
  regression/ansi-c/main1/main.c
  regression/ansi-c/main1/test.desc
  src/ansi-c/ansi_c_entry_point.cpp
Labels: bugfix, C Front End

#7160 Use Ubuntu-provided git-clang-format in CI check
  .github/workflows/pull-request-check-clang-format.sh
  .github/workflows/pull-request-checks.yaml
Labels: bugfix, CI

#7145 SMT2 back-end: make declare-datatypes standards compatible
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#7089 CONTRACTS: Documenting semantic of loop invariant synthesizers
  src/goto-instrument/synthesizer/enumerative_loop_invariant_synthesizer.h
  src/goto-instrument/synthesizer/loop_invariant_synthesizer_base.h
Labels: documentation, aws, Synthesis

#7162 Dump-C: support struct/union types without tags
  regression/goto-instrument/dump-non-tag-struct/main.c
  regression/goto-instrument/dump-non-tag-struct/test.desc
  src/goto-instrument/dump_c.cpp
Labels: bugfix
