Repository diffblue/cbmc, pull requests merged in 2022-07, with the labels that each got.

#6986 Crangler: support semicolon in post-declarator expressions
  regression/crangler/assigns-clause-syntax/main-contract-after-declaration.c
  regression/crangler/assigns-clause-syntax/test.desc
  regression/crangler/assigns-clause-syntax/test.json
  src/crangler/mini_c_parser.cpp
Labels: bugfix

#6995 string_constantt::to_array_expr must maintain the source location
  regression/cbmc/String_Literal1/main.c
  regression/cbmc/String_Literal1/test.desc
  src/util/expr.h
  src/util/std_expr.h
  src/util/string_constant.cpp
  src/util/string_constant.h
Labels: bugfix

#6934 Goto-harness, memory analyzer: print version, help to stdout
  src/goto-harness/common_harness_generator_options.h
  src/goto-harness/goto_harness_parse_options.cpp
  src/memory-analyzer/memory_analyzer_parse_options.cpp
Labels: blocker

#6996 Use cmdlinet::get_comma_separated_values where possible
  jbmc/src/jbmc/jbmc_parse_options.cpp
  regression/goto-instrument/unwind-unwindset4/test.desc
  regression/memory-analyzer/pointer_05/test.desc
  src/cbmc/cbmc_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/unwindset.cpp
  src/memory-analyzer/analyze_symbol.cpp
  src/memory-analyzer/analyze_symbol.h
  src/memory-analyzer/memory_analyzer_parse_options.cpp
Labels: cleanup

#7003 Remove under-documented perf-test script
  scripts/perf-test/build.yaml
  scripts/perf-test/ebs.yaml
  scripts/perf-test/ec2-terminate.sh
  scripts/perf-test/ec2.yaml
  scripts/perf-test/make-tables.sh
  scripts/perf-test/perf_test.py
  scripts/perf-test/run-on-ec2.sh
  scripts/perf-test/s3.yaml
  scripts/perf-test/sns.yaml
  scripts/perf-test/sqs.yaml
Labels: cleanup

#6963 Document versioning scheme
  doc/ADR/release_process.md
Labels: documentation

#6119 Concurrency: do not lose L2 entries of procedure-local variables
  regression/cbmc-concurrency/stack2/main.c
  regression/cbmc-concurrency/stack2/test.desc
  src/goto-symex/symex_goto.cpp
Labels: bugfix

#6122 Dirty locals copied across threads require program-order constraints
  regression/cbmc-concurrency/dirty_local3/test-local.desc
  src/goto-symex/symex_start_thread.cpp
Labels: bugfix

#6511 Remove redundant compute_loop_numbers call
  src/goto-programs/process_goto_program.cpp
Labels: cleanup

#6593 Remove useless system_library_symbolst::is_type_internal
  regression/goto-instrument/dump-typedef/main.c
  regression/goto-instrument/dump-typedef/test.desc
  src/goto-instrument/dump_c.cpp
  src/goto-programs/system_library_symbols.cpp
  src/goto-programs/system_library_symbols.h
Labels: cleanup

#6969 Add janalyzer man page
  doc/man/janalyzer.1
Labels: documentation

#6971 Add jdiff man page
  doc/man/jdiff.1
Labels: documentation

#7028 Move CI runners away from `macOS-10.15` because of sunsetting by Github.
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: CI

#6922 introduce named_term expressions
  src/solvers/flattening/boolbv.cpp
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/util/irep_ids.def
  src/util/std_expr.h
Labels: Solvers

#6958 CHC encoder: universally quantify nondeterministic choices
  regression/goto-instrument-chc/basic/nondet1.desc
  src/goto-instrument/horn_encoding.cpp
Labels: Needs rebase

#6938 Add crangler man page
  doc/man/crangler.1
Labels: documentation
