Repository diffblue/cbmc, pull requests merged in 2022-11, with the labels that each got.

#7270 Assignments to bit-fields yield results of bit-field type
  regression/cbmc/Bitfields4/main.c
  regression/cbmc/Bitfields4/test.desc
  src/ansi-c/expr2c.cpp
  src/goto-programs/goto_clean_expr.cpp
  src/goto-programs/goto_convert_side_effect.cpp
Labels: bugfix, soundness

#7290 SMT2: implement flattening for arrays
  regression/cbmc/union/union_initialization.desc
  regression/cbmc/union/union_member.desc
  regression/cbmc/union/union_update.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface

#7259 Field sensitivity: using apply is now always safe
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/field_sensitivity.h
Labels: Symbolic Execution, cleanup, blocker, aws, aws-high

#7297 performance improvement for large bitvectors
  regression/cbmc/bounds_check1/test.desc
  regression/cbmc/union/union_large_array.c
  regression/cbmc/union/union_large_array.desc
  src/solvers/flattening/boolbv_get.cpp
Labels: Solvers, Tests

#7299 SMT back-end: use_array_theory compatibility with unions
  regression/cbmc/bounds_check1/test.desc
  regression/cbmc/union/union_member.desc
  regression/cbmc/union/union_update.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#7303 SMT back-end: support floatbv to raw bitvector cast
  regression/cbmc/Float-no-simp2/test.desc
  regression/cbmc/Float-no-simp3/test.desc
  regression/cbmc/Float-no-simp5/test.desc
  regression/cbmc/Float-zero-sum1/test.desc
  regression/cbmc/Float12/test.desc
  regression/cbmc/Float22/test.desc
  regression/cbmc/Float3/test.desc
  src/solvers/floatbv/float_bv.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#7305 Contracts/DFCC: do not access invalidated references
  src/goto-instrument/contracts/dynamic-frames/dfcc_is_freeable.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.cpp
Labels: bugfix, blocker, Code Contracts

#7307 CONTRACTS: Fix language mode on wrapper symbol
  src/goto-instrument/contracts/dynamic-frames/dfcc_utils.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_wrapper_program.cpp
Labels: bugfix, aws, Code Contracts

#7309 Solver stats reporting: fix expression mapping for guards
  regression/solver-hardness/guards/main.c
  regression/solver-hardness/guards/test.desc
  src/goto-symex/symex_target_equation.cpp
Labels: bugfix

#4717 Byte-operator lowering: Add support for byte-extracting unions
  regression/cbmc/union17/main.c
  regression/cbmc/union17/test.desc
  src/solvers/lowering/byte_operators.cpp
Labels: enhancement

#7314 [CI] Fix windows slack notification.
  .github/workflows/release-packages.yaml
Labels: CI

#6838 Document and use malloc(0) behaviour
  doc/cprover-manual/memory-primitives.md
  doc/cprover-manual/properties.md
  src/ansi-c/library/stdlib.c
Labels: documentation, aws

#7318 CONTRACTS: Unwind transformed loops after loop contract transformation
  regression/contracts/invar_assigns_empty/test.desc
  regression/contracts/invar_loop_constant_pass/test_unwind.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
Labels: bugfix, aws, Code Contracts

#6892 GOTO programs do not have code-typed struct members
  jbmc/src/java_bytecode/expr2java.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/expr2c.cpp
  src/goto-instrument/dump_c.cpp
  src/goto-programs/graphml_witness.cpp
  src/goto-programs/interpreter.cpp
  src/memory-analyzer/analyze_symbol.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_fi.cpp
  src/util/expr_initializer.cpp
Labels: cleanup, aws, Kani

#7322 goto_programt::get_target: fix const-ness of operations
  src/goto-programs/goto_convert.cpp
  src/goto-programs/goto_program.h
Labels: cleanup

#7328 CONTRACTS: Drop function pointer contract support
  regression/contracts/function-pointer-contracts-enforce/test.desc
  regression/contracts/function-pointer-contracts-replace/test.desc
  src/goto-instrument/contracts/contracts.cpp
Labels: aws, Code Contracts

#7326 CONTRACTS: use vars auxiliary for DFCC
  src/goto-instrument/contracts/dynamic-frames/dfcc_utils.cpp
Labels: aws, Code Contracts

#7329 Move has_byte_operator to util
  src/solvers/flattening/boolbv_equality.cpp
  src/solvers/lowering/byte_operators.cpp
  src/solvers/lowering/expr_lowering.h
  src/util/byte_operators.cpp
  src/util/byte_operators.h
Labels: blocker

#7330 Move byte-operator lowering to util [depends-on: #7329]
  src/solvers/Makefile
  src/solvers/flattening/boolbv_byte_extract.cpp
  src/solvers/flattening/boolbv_byte_update.cpp
  src/solvers/flattening/boolbv_equality.cpp
  src/solvers/flattening/boolbv_index.cpp
  src/solvers/lowering/expr_lowering.h
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  src/util/Makefile
  src/util/byte_operators.h
  src/util/lower_byte_operators.cpp
  unit/Makefile
  unit/solvers/lowering/module_dependencies.txt
  unit/util/lower_byte_operators.cpp
Labels: blocker

#7337 SMT2: fix pointer arithmetic
  regression/cbmc/Pointer24/test.desc
  regression/cbmc/pointer-overflow3/no-simplify.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix

#7336 cbmc/r_w_ok6/test.desc works with SMT2
  .github/workflows/pull-request-checks.yaml
  regression/cbmc/r_w_ok6/test.desc
Labels: Tests

#7310 SMT back-end: Extend trace value evaluation
  regression/cbmc/Empty_struct3/main.c
  regression/cbmc/Empty_struct3/test.desc
  regression/cbmc/trace-values/trace-values.desc
  regression/cbmc/trace_options_json_extended/extended.desc
  regression/cbmc/trace_options_json_extended/non-extended.desc
  regression/validate-trace-xml-schema/check.py
  src/solvers/smt2/smt2_conv.cpp
Labels: bugfix, blocker, aws, Kani

#7338 SMT2 backend: minus on void pointers
  regression/cbmc/void_pointer3/test.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, blocker

#7352 Byte-operator lowering: struct and union constants are not ID_constant
  src/util/lower_byte_operators.cpp
  src/util/simplify_expr_struct.cpp
Labels: bugfix, Kani

#7341 Simplify non-trivial pointer subtraction
  src/util/simplify_expr_int.cpp
Labels: Kani

#7345 SMT2 backend: implement saturating arithmetic
  regression/cbmc/saturating_arithmetric/test.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface

#7360 Byte-extract lowering: extracting zero-width struct members is fine
  regression/cbmc-library/memcpy-09/main.c
  regression/cbmc-library/memcpy-09/test.desc
  src/util/lower_byte_operators.cpp
Labels: bugfix, Kani

#7356 CONTRACTS: Disable checks on `cprover_contracts.c`
  src/ansi-c/library/cprover_contracts.c
  src/goto-instrument/contracts/dynamic-frames/dfcc.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.h
Labels: enhancement, aws, aws-high, Code Contracts

#7016 Cleanup the API of bv_utilst::adder
  src/solvers/flattening/bv_utils.cpp
  src/solvers/flattening/bv_utils.h
Labels: cleanup

#7339 Value sets: handle extractbits out of pointers
  src/pointer-analysis/value_set.cpp
Labels: blocker, Kani

#7017 propt::l_set_to: avoid duplicate work
  src/solvers/prop/prop.cpp
Labels: cleanup

#7373 ansi-c tests: add Makefile rule to rebuild goto binaries
  regression/ansi-c/Makefile
  regression/ansi-c/arch_flags_mcpu_bad/test.desc
  regression/ansi-c/arch_flags_mcpu_good/test.desc
  regression/ansi-c/arch_flags_mthumb_bad/test.desc
  regression/ansi-c/arch_flags_mthumb_good/test.desc
Labels: Build, Tests

#7372 External SAT back-end: not all variables are required
  src/solvers/sat/external_sat.cpp
  unit/solvers/sat/external_sat.cpp
Labels: Solvers, bugfix, blocker

#7370 Value sets: type casts need not be towards a pointer type
  src/pointer-analysis/value_set.cpp
Labels: bugfix, blocker

#7365 C library: Avoid arithmetic overflow with pipe operations
  regression/cbmc-library/write-01/main.c
  regression/cbmc-library/write-01/test.desc
  src/ansi-c/library/unistd.c
Labels: C Front End

#7371 C library: Fix type inconsistencies in contracts code
  src/ansi-c/library/cprover_contracts.c
  src/cpp/library/cprover.h
Labels: C Front End, blocker

#7369 C library: handle side effects of scanf
  regression/cbmc-library/scanf-01/main.c
  regression/cbmc-library/scanf-01/test.desc
  src/ansi-c/library/stdio.c
Labels: C Front End

#7376 Simplify byte extract: fix unconditional read from optional values
  src/util/simplify_expr.cpp
Labels: bugfix

#7384 Cleanup chrono includes
  src/goto-checker/bmc_util.h
  src/goto-checker/multi_path_symex_checker.cpp
  src/goto-checker/multi_path_symex_checker.h
  src/goto-checker/multi_path_symex_only_checker.cpp
  src/goto-checker/single_loop_incremental_symex_checker.cpp
  src/goto-checker/single_path_symex_checker.h
  src/goto-checker/single_path_symex_only_checker.cpp
  src/goto-checker/single_path_symex_only_checker.h
  src/goto-checker/symex_coverage.cpp
  src/goto-symex/symex_target_equation.cpp
  src/solvers/prop/prop_conv_solver.cpp
Labels: cleanup, blocker

#7343 Extend simplification of extractbits
  src/util/simplify_expr_int.cpp
Labels: blocker, Kani

#7355 CONTRACTS: add __CPROVER_obeys_contract predicate
  regression/contracts-dfcc/function-pointer-contracts-enforce/main.c
  regression/contracts-dfcc/function-pointer-contracts-enforce/test.desc
  regression/contracts-dfcc/function-pointer-contracts-replace-1/main.c
  regression/contracts-dfcc/function-pointer-contracts-replace-1/test.desc
  regression/contracts-dfcc/function-pointer-contracts-replace-2/main.c
  regression/contracts-dfcc/function-pointer-contracts-replace-2/test.desc
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-1/main.c
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-1/test.desc
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-2/main.c
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-2/test.desc
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-3/main.c
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-3/test.desc
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-4/main.c
  regression/contracts-dfcc/function-pointer-contracts-typecheck-error-4/test.desc
  regression/contracts/function-pointer-contracts-enforce/main.c
  regression/contracts/function-pointer-contracts-enforce/test.desc
  regression/contracts/function-pointer-contracts-replace/main.c
  regression/contracts/function-pointer-contracts-replace/test.desc
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/cprover_builtin_headers.h
  src/ansi-c/library/cprover_contracts.c
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/doc/developer/contracts-dev-arch.md
  src/goto-instrument/contracts/doc/developer/contracts-dev-spec-dfcc-instrument.md
  src/goto-instrument/contracts/doc/developer/contracts-dev-spec-obeys-contract.md
  src/goto-instrument/contracts/doc/developer/contracts-dev-spec-reminder.md
  src/goto-instrument/contracts/doc/user/contracts-assigns.md
  src/goto-instrument/contracts/doc/user/contracts-decreases.md
  src/goto-instrument/contracts/doc/user/contracts-function-pointer-predicates.md
  src/goto-instrument/contracts/doc/user/contracts-functions.md
  src/goto-instrument/contracts/doc/user/contracts-history-variables.md
  src/goto-instrument/contracts/doc/user/contracts-loop-invariants.md
  src/goto-instrument/contracts/doc/user/contracts-memory-predicates.md
  src/goto-instrument/contracts/doc/user/contracts-quantifiers.md
  src/goto-instrument/contracts/doc/user/contracts-requires-ensures.md
  src/goto-instrument/contracts/dynamic-frames/dfcc.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_obeys_contract.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_obeys_contract.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_swap_and_wrap.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_wrapper_program.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_wrapper_program.h
Labels: aws, aws-high, Code Contracts

#7380 CONTRACTS: Fix conditional havoc code
  regression/contracts-dfcc/havoc-conditional-target/check-foo.c
  regression/contracts-dfcc/havoc-conditional-target/check-foo.desc
  regression/contracts-dfcc/havoc-conditional-target/replace-foo.c
  regression/contracts-dfcc/havoc-conditional-target/replace-foo.desc
  src/ansi-c/library/cprover_contracts.c
  src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp
Labels: bugfix, aws, aws-high, Code Contracts

#7344 Simplify typecast over ID_bv and pointers
  src/util/simplify_expr.cpp
Labels: Kani

#7385 Remove null_pointer predicate
  src/ansi-c/goto_check_c.cpp
  src/cprover/axioms.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
Labels: cleanup

#7374 C library: add imaxabs
  regression/cbmc-library/imaxabs-01/main.c
  regression/cbmc-library/imaxabs-01/test.desc
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/library/stdlib.c
Labels: C Front End

#7347 Consistently name README files and clean up
  doc/architectural/compilation-and-development.md
  jbmc/unit/java_bytecode/java_bytecode_parse_lambdas/lambda_examples/README.md
  regression/README.md
  regression/cbmc-incr-smt2/bitvector-flag-tests/README.md
  regression/goto-cc-cbmc-shared-options/README.md
  regression/goto-cc-cbmc/malloc-may-fail-should-work-with-compiled-binaries/test.desc
  regression/symtab2gb-cbmc/README.md
  regression/symtab2gb/README.md
  scripts/bash-autocomplete/README.md
Labels: cleanup, documentation

#7394 get_subexpression_at_offset: do not permit out-of-bounds access
  jbmc/src/java_bytecode/java_trace_validation.cpp
  regression/cbmc/union-unequal-element-size1/test.desc
  src/solvers/flattening/boolbv_get.cpp
  src/util/pointer_offset_size.cpp
Labels: bugfix

#7331 Byte extract and extract bits can be constant
  regression/cbmc-library/memcpy-01/constant-propagation.desc
  src/analyses/constant_propagator.cpp
  src/analyses/constant_propagator.h
  src/ansi-c/c_typecheck_expr.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
  src/goto-instrument/havoc_loops.cpp
  src/goto-instrument/havoc_utils.h
  src/goto-instrument/k_induction.cpp
  src/goto-symex/goto_state.cpp
  src/goto-symex/goto_symex_is_constant.h
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/symex_goto.cpp
  src/util/expr_util.cpp
  src/util/expr_util.h
  unit/analyses/constant_propagator.cpp
  unit/goto-symex/is_constant.cpp
Labels: blocker, aws, Kani

#7342 Further simplification of (in)equalities over pointers
  src/util/simplify_expr_int.cpp
Labels: aws, Kani

#7386 Remove good_pointer, good_pointer_def
  src/ansi-c/expr2c.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
  src/util/irep_ids.def
  src/util/pointer_predicates.cpp
  src/util/pointer_predicates.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_pointer.cpp
Labels: cleanup, aws

#7396 Fix constant-propagation test pattern
  regression/cbmc-library/memcpy-01/constant-propagation.desc
Labels: bugfix, Tests

#7359 CONTRACTS: Insert reachability canary assertions
  regression/contracts-dfcc/assigns_replace_02/main.c
  regression/contracts-dfcc/cprover-assignable-fail/test.desc
  regression/contracts-dfcc/cprover-assignable-pass/test.desc
  regression/contracts-dfcc/missing-function-body/main.c
  regression/contracts-dfcc/missing-function-body/test.desc
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.h
Labels: aws, aws-high, Code Contracts

#7340 Simplify byte extract: use lowering when expression is a constant
  regression/cbmc-library/memcpy-01/constant-propagation.desc
  src/util/simplify_expr.cpp
  src/util/simplify_expr_int.cpp
Labels: aws-high, Kani

#7399 Fix the markdown syntax in the folder walkthrough doc
  doc/architectural/folder-walkthrough.md
Labels: bug, documentation

#7400 SMT2 back-end: parse c_bool values
  regression/cbmc/Bool/bool3.desc
  regression/validate-trace-xml-schema/check.py
  src/solvers/smt2/smt2_conv.cpp
Labels: SMT Backend Interface, bugfix
