Repository diffblue/cbmc, pull requests merged in 2022-03, with the labels that each got.

#6632 Remove spurious use of ID_property
  src/goto-programs/goto_convert.cpp
  src/util/irep_ids.def
Labels: cleanup

#6703 Fix count-trailing-zeros lowering for value zero
  regression/cbmc/__builtin_ctz-01/main.c
  regression/cbmc/__builtin_ctz-01/test.desc
  src/util/bitvector_expr.cpp
Labels: bugfix

#6708 Restore conditional bounds-checking of count_{leading,trailing}_zeros
  src/ansi-c/goto_check_c.cpp
Labels: bugfix

#6709 smt2: convert mathematical_function types and function_application
  regression/cbmc/uninterpreted_function/uf1.desc
  regression/cbmc/uninterpreted_function/uf2.desc
  src/solvers/smt2/smt2_conv.cpp
Labels: Solvers

#6701 CONTRACTS: Several fixes for loop contracts
  regression/contracts/invar_check_nested_loops/test.desc
  regression/contracts/loop_contracts_reject_overlapping_loops/main.c
  regression/contracts/loop_contracts_reject_overlapping_loops/test.desc
  regression/contracts/loop_guard_with_side_effects/main.c
  regression/contracts/loop_guard_with_side_effects/test.desc
  regression/contracts/loop_guard_with_side_effects_fail/main.c
  regression/contracts/loop_guard_with_side_effects_fail/test.desc
  regression/contracts/nonvacuous_loop_contracts/main.c
  regression/contracts/nonvacuous_loop_contracts/test.desc
  regression/contracts/variant_missing_invariant_warning/test.desc
  regression/contracts/variant_multi_instruction_loop_head/main.c
  regression/contracts/variant_multi_instruction_loop_head/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/instrument_spec_assigns.h
Labels: enhancement, aws, aws-high, Code Contracts

#6718 Remove unused make_assertions_false
  src/goto-programs/set_properties.cpp
  src/goto-programs/set_properties.h
Labels: cleanup

#6710 Handle array_{copy,replace,set} in dependence graph
  regression/cbmc/Bool5/full-slice.desc
  src/analyses/goto_rw.cpp
  src/analyses/goto_rw.h
  src/analyses/reaching_definitions.cpp
Labels: bugfix

#6721 Dependence graph: entry points may have additional control dependencies
  regression/cbmc/Pointer18/full-slice.desc
  src/analyses/dependence_graph.cpp
Labels: bugfix

#6729 CONTRACTS: Remove helper method check_for_looped_mallocs
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
Labels: cleanup, Code Contracts

#6733 CONTRACTS: Error-out on unknown functions (replace/enforce).
  regression/contracts/enforce-replace-unknown-function/enforce.desc
  regression/contracts/enforce-replace-unknown-function/main.c
  regression/contracts/enforce-replace-unknown-function/replace.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
Labels: bugfix, aws, Code Contracts

#6742 can_cast_expr<is_dynamic_object_exprt>: fix copy&paste error
  src/util/pointer_expr.h
Labels: bugfix

#6541 Simplification of nested pointer arithmetic: do not assume same type
  regression/cbmc/Pointer_Arithmetic15/main.c
  src/util/simplify_expr_int.cpp
Labels: bugfix

#6719 goto_rw: do not assume that all types have constant size
  regression/cbmc/byte_update5/full-slice.desc
  src/analyses/goto_rw.cpp
Labels: bugfix

#6746 Simplify index: ensure consistent types
  src/util/simplify_expr_array.cpp
Labels: bugfix

#6725 Remove duplicate implementation of stash_variables
  src/goto-instrument/accelerate/polynomial_accelerator.cpp
  src/goto-instrument/accelerate/polynomial_accelerator.h
Labels: cleanup

#6723 goto_rw: left shift may be larger than object size
  regression/cbmc/overflow/leftshift_overflow-c99-full-slice.desc
  src/analyses/goto_rw.cpp
Labels: bugfix

#6726 goto-symex: do not rely on undocumented find_symbols(expr) behaviour
  src/goto-symex/goto_symex_state.cpp
Labels: cleanup, blocker

#6764 Add missing <functional> include [blocks: #6749]
  src/goto-programs/resolve_inherited_component.h
  src/solvers/flattening/boolbv_map.h
  src/util/expr.h
Labels: cleanup, blocker

#6772 Array theory: gracefully handle negative out-of-bounds access
  regression/cbmc/Array_UF21/main.c
  regression/cbmc/Array_UF21/test.desc
  src/solvers/flattening/arrays.cpp
Labels: bugfix
