Repository diffblue/cbmc, pull requests merged in 2022-04, with the labels that each got.

#6775 Avoid line break in goto-check options [blocks: #6776]
  src/ansi-c/goto_check_c.h
Labels: blocker

#6779 run: return interpreted exit code
  src/util/run.cpp
Labels: bugfix

#6782 CONTRACTS: Fix targett comparison in loop instrumentation
  src/goto-instrument/contracts/contracts.cpp
Labels: bugfix, Code Contracts

#6791 CI jobs: upgrade CVC5 to 1.0.0 [depends-on: #6790]
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: dependent - do not merge, CI

#6798 CONTRACTS: apply: use previously computed mode
  src/goto-instrument/contracts/contracts.cpp
Labels: cleanup, Code Contracts

#6797 CONTRACTS: Replace return_value_visitor by has_subexpr
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/memory_predicates.cpp
  src/goto-instrument/contracts/memory_predicates.h
Labels: cleanup, Code Contracts

#6793 Remove unused contracts-related functions from ansi_c_declarationt
  src/ansi-c/ansi_c_declaration.h
Labels: cleanup

#6794 Remove internal symbols: use API to access code contract
  src/linking/remove_internal_symbols.cpp
Labels: cleanup

#6806 convenience methods for division expressions
  src/util/std_expr.h
Labels: Needs rebase

#6816 Crangler: also apply remove-static to declarations
  regression/crangler/remove-static/remove_static1.c
  regression/crangler/remove-static/remove_static1.desc
  src/crangler/c_wrangler.cpp
Labels: bugfix

#6819 C front-end: use proper index type for argv and envp access
  src/ansi-c/ansi_c_entry_point.cpp
Labels: cleanup

#6808 Allow instrumentation of loops with "holes"
  regression/contracts/loop_assigns-04/test.desc
  regression/contracts/loop_assigns-05/test.desc
  regression/contracts/loop_assigns_scoped_local_statics/test.desc
  regression/contracts/loop_body_with_hole/main.c
  regression/contracts/loop_body_with_hole/test.desc
  regression/contracts/loop_guard_with_side_effects/test.desc
  regression/contracts/loop_guard_with_side_effects_fail/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
Labels: enhancement, aws, aws-high, Code Contracts

#6818 CONTRACTS: handle locals with composite types when checking assigns clauses
  regression/contracts/assigns-local-composite/main.c
  regression/contracts/assigns-local-composite/test.desc
  regression/contracts/assigns_type_checking_valid_cases/main.c
  regression/contracts/assigns_type_checking_valid_cases/test.desc
  src/goto-instrument/contracts/instrument_spec_assigns.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
  src/goto-instrument/contracts/utils.h
Labels: aws, aws-high, Code Contracts

#6823 Use instantiate() when flattening array_comprehension_exprt
  src/solvers/flattening/boolbv.cpp
Labels: cleanup

#6824 Failing test to demonstrate need for extensionality rule
  regression/cbmc/Array_UF22/main.c
  regression/cbmc/Array_UF22/test.desc
Labels: Tests

#6828 CONTRACTS: do not rely on replace_symbol for bound variables [blocks: #6827]
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
Labels: blocker

#6826 Test trace-values: create reads to enforce instantiation
  regression/cbmc/trace-values/unbounded_array.c
Labels: Tests

#6817 Add new documentation for homebrew tap
  README.md
  doc/ADR/README.md
  doc/ADR/homebrew_tap.md
Labels: documentation

#6830 bv_pointert cleanup
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/flattening/bv_pointers.h
Labels: Solvers, cleanup

#6821 CONTRACTS: adding requires and ensures clauses for function pointers
  regression/contracts/function-pointer-contracts-enforce/main.c
  regression/contracts/function-pointer-contracts-enforce/test.desc
  regression/contracts/function-pointer-contracts-replace/main.c
  regression/contracts/function-pointer-contracts-replace/test.desc
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/ansi_c_convert_type.h
  src/ansi-c/c_expr.h
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/langapi/language_util.cpp
  src/langapi/language_util.h
  src/util/c_types.h
  src/util/irep_ids.def
Labels: aws, aws-high, Code Contracts

#6834 show bit-pattern of pointers in trace
  regression/cbmc/hex_trace/main.c
  regression/cbmc/hex_trace/test.desc
  src/goto-programs/goto_trace.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: enhancement
