Repository diffblue/cbmc, pull requests merged in 2023-10, with the labels that each got.

#7930 [DOCS] Partial doxygen for shadow_memory_util
  src/goto-symex/shadow_memory_util.cpp
  src/goto-symex/shadow_memory_util.h
Labels: documentation

#7900 SYNTHESIZER: Allow goto-synthesizer accept all CBMC options
  doc/man/goto-synthesizer.1
  src/goto-synthesizer/goto_synthesizer_parse_options.cpp
  src/goto-synthesizer/goto_synthesizer_parse_options.h
  src/goto-synthesizer/module_dependencies.txt
Labels: aws, Synthesis

#7954 Simplification towards singleton intervals requires single variable
  regression/cbmc/simplify_singleton_interval_7953/main.c
  regression/cbmc/simplify_singleton_interval_7953/test.desc
  src/util/simplify_expr_boolean.cpp
Labels: bugfix

#7956 std::sort requires strict weak ordering
  src/analyses/variable-sensitivity/value_set_abstract_object.cpp
  src/cprover/generalization.cpp
Labels: bugfix

#7933 Simplify byte_extract(byte_update(...)) when extracting from update
  src/util/simplify_expr.cpp
Labels: aws, Kani

#7947 C front-end: support vector expressions as compile-time constants
  regression/ansi-c/MMX2/main.c
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End

#7958 Restrict memory-analyzer build to Linux x86_64/i386
  CMakeLists.txt
  regression/Makefile
  src/CMakeLists.txt
  src/Makefile
  unit/Makefile
Labels: Build

#7970 SYNTHESIZER: Use only symbols from the original goto as terminals
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.h
Labels: aws, Synthesis

#7906 C library: add exp, log, pow models
  regression/cbmc-library/exp-01/main.c
  regression/cbmc-library/exp-01/test.desc
  regression/cbmc-library/exp2-01/main.c
  regression/cbmc-library/exp2-01/test.desc
  regression/cbmc-library/exp2f-01/main.c
  regression/cbmc-library/exp2f-01/test.desc
  regression/cbmc-library/exp2l-01/main.c
  regression/cbmc-library/exp2l-01/test.desc
  regression/cbmc-library/expf-01/main.c
  regression/cbmc-library/expf-01/test.desc
  regression/cbmc-library/expl-01/main.c
  regression/cbmc-library/expl-01/test.desc
  regression/cbmc-library/log-01/main.c
  regression/cbmc-library/log-01/test.desc
  regression/cbmc-library/logf-01/main.c
  regression/cbmc-library/logf-01/test.desc
  regression/cbmc-library/logl-01/main.c
  regression/cbmc-library/logl-01/test.desc
  regression/cbmc-library/pow-01/main.c
  regression/cbmc-library/pow-01/test.desc
  regression/cbmc-library/powf-01/main.c
  regression/cbmc-library/powf-01/test.desc
  regression/cbmc-library/powl-01/main.c
  regression/cbmc-library/powl-01/test.desc
  src/ansi-c/library/math.c
  src/ansi-c/library_check.sh
Labels: aws, Kani

#7976 propt: change interface for solving under assumptions
  src/solvers/prop/prop.cpp
  src/solvers/prop/prop.h
  src/solvers/prop/prop_conv_solver.cpp
  src/solvers/refinement/bv_refinement_loop.cpp
  src/solvers/sat/cnf_clause_list.h
  src/solvers/sat/dimacs_cnf.h
  src/solvers/sat/external_sat.cpp
  src/solvers/sat/external_sat.h
  src/solvers/sat/pbs_dimacs_cnf.cpp
  src/solvers/sat/pbs_dimacs_cnf.h
  src/solvers/sat/satcheck_booleforce.cpp
  src/solvers/sat/satcheck_booleforce.h
  src/solvers/sat/satcheck_cadical.cpp
  src/solvers/sat/satcheck_cadical.h
  src/solvers/sat/satcheck_glucose.cpp
  src/solvers/sat/satcheck_glucose.h
  src/solvers/sat/satcheck_ipasir.cpp
  src/solvers/sat/satcheck_ipasir.h
  src/solvers/sat/satcheck_lingeling.cpp
  src/solvers/sat/satcheck_lingeling.h
  src/solvers/sat/satcheck_minisat.cpp
  src/solvers/sat/satcheck_minisat.h
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/sat/satcheck_minisat2.h
  src/solvers/sat/satcheck_picosat.cpp
  src/solvers/sat/satcheck_picosat.h
  src/solvers/sat/satcheck_zchaff.cpp
  src/solvers/sat/satcheck_zchaff.h
  src/solvers/sat/satcheck_zcore.cpp
  src/solvers/sat/satcheck_zcore.h
  unit/solvers/bdd/miniBDD/miniBDD.cpp
  unit/solvers/sat/satcheck_cadical.cpp
  unit/solvers/sat/satcheck_minisat2.cpp
Labels: Solvers
