Repository diffblue/cbmc, pull requests merged in 2023-01, with the labels that each got.

#7472 Field sensitivity: fully expand nested objects
  regression/cbmc/field-sensitivity15/main.c
  regression/cbmc/field-sensitivity15/test.desc
  regression/cbmc/field-sensitivity16/main.c
  regression/cbmc/field-sensitivity16/test.desc
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/symex_assign.cpp
Labels: bugfix, aws-high, Kani

#6699 SSA steps: don't guess the property id, set it during construction
  src/goto-checker/bmc_util.cpp
  src/goto-checker/goto_symex_fault_localizer.cpp
  src/goto-checker/goto_symex_property_decider.cpp
  src/goto-symex/build_goto_trace.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/ssa_step.cpp
  src/goto-symex/ssa_step.h
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_goto.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_target.h
  src/goto-symex/symex_target_equation.cpp
  src/goto-symex/symex_target_equation.h
Labels: cleanup

#7458 SYNTHESIZER: Synthesize loop assigns before loop invariants.
  regression/goto-synthesizer/loop_contracts_synthesis_08/main.c
  regression/goto-synthesizer/loop_contracts_synthesis_08/test.desc
  src/goto-synthesizer/cegis_verifier.cpp
  src/goto-synthesizer/cegis_verifier.h
  src/goto-synthesizer/dump_loop_contracts.cpp
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.h
  src/goto-synthesizer/expr_enumerator.cpp
  src/goto-synthesizer/expr_enumerator.h
Labels: aws, aws-medium, Synthesis

#7403 GOTO trace: no timestamps for single-threaded programs
  src/goto-symex/build_goto_trace.cpp
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
Labels: cleanup

#7476 Fix documentation links
  doc/doxygen-root/user_guide.md
  doc/satabs-user-manual.md
Labels: bugfix, documentation

#7475 Library functions may require converting additional inline functions
  regression/cbmc-library/__signbitd-01/main.c
  regression/cbmc-library/__signbitd-01/test.desc
  regression/cbmc-library/copysignf-01/main.c
  regression/cbmc-library/copysignf-01/test.desc
  src/ansi-c/compiler_headers/gcc_builtin_headers_math.h
  src/ansi-c/library/math.c
  src/goto-programs/link_to_library.cpp
Labels: bugfix, aws, aws-high, Kani

#7410 Expose CProver API version tag through to Rust API
  CMakeLists.txt
  src/libcprover-cpp/CMakeLists.txt
  src/libcprover-cpp/api.cpp
  src/libcprover-cpp/api.h
  src/libcprover-rust/.gitignore
  src/libcprover-rust/Cargo.lock
  src/libcprover-rust/Cargo.toml
  src/libcprover-rust/build.rs
  src/libcprover-rust/include/c_api.h
  src/libcprover-rust/include/module_dependencies.txt
  src/libcprover-rust/src/c_api.cc
  src/libcprover-rust/src/lib.rs
  src/libcprover-rust/src/module_dependencies.txt
  src/solvers/CMakeLists.txt
Labels: aws, Kani

#7480 Cleanup GitHub actions
  .github/workflows/build-and-test-Linux.yaml
  .github/workflows/build-and-test-Xen.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/csmith.yaml
  .github/workflows/doxygen-check.yaml
  .github/workflows/publish.yaml
  .github/workflows/pull-request-checks.yaml
Labels: CI

#7481 GitHub Actions: cpplint and clang-format checks on PRs only
  .github/workflows/pull-request-checks.yaml
  .github/workflows/syntax-checks.yaml
Labels: CI

#7492 Increase nominal ccache cache size for coverage CI job
  .github/workflows/pull-request-checks.yaml
Labels: CI

#7494 Fix symex coverage reporting of recursive calls
  regression/cbmc/coverage_report2/main.c
  regression/cbmc/coverage_report2/test.desc
  regression/validate-trace-xml-schema/check.py
  src/goto-checker/symex_coverage.cpp
Labels: bugfix

#7495 Change default build to *not* include Rust API.
  CMakeLists.txt
  COMPILING.md
Labels: Build, Rust API

#7488 SYNTHESIZER: Enable enumerating mode for checks other than pointer checks
  regression/goto-synthesizer/loop_contracts_synthesis_assert_false/main.c
  regression/goto-synthesizer/loop_contracts_synthesis_assert_false/test.desc
  regression/goto-synthesizer/loop_contracts_synthesis_other_assertion/main.c
  regression/goto-synthesizer/loop_contracts_synthesis_other_assertion/test.desc
  src/goto-synthesizer/cegis_verifier.cpp
  src/goto-synthesizer/cegis_verifier.h
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
  src/goto-synthesizer/expr_enumerator.cpp
  src/goto-synthesizer/synthesizer_utils.cpp
Labels: aws-medium, Kani, Synthesis

#7501 Array_UF21 does not always work with incremental SMT back-end
  regression/cbmc/Array_UF21/test.desc
Labels: Tests, CI

#7496 Test builds using clang-14 in CI
  .github/workflows/pull-request-checks.yaml
  src/ansi-c/Makefile
  src/ansi-c/library/cprover_contracts.c
  src/ansi-c/library/stdio.c
  src/ansi-c/library_check.sh
  src/cpp/CMakeLists.txt
  src/cpp/Makefile
  src/cpp/library/new.c
Labels: CI

#7504 GitHub PR actions: update timing comments
  .github/workflows/pull-request-checks.yaml
Labels: cleanup, documentation, CI

#7487 CONTRACTS: Avoid skipping transformed loop with jumps to the loop head
  regression/contracts/labled_loop_head/main.c
  regression/contracts/labled_loop_head/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
Labels: aws-medium, Code Contracts, Kani

#7507 Fix bug in solver hardness stats
  regression/solver-hardness/solver-hardness-simple/main.c
  regression/solver-hardness/solver-hardness-simple/test.desc
  src/goto-checker/goto_symex_property_decider.cpp
  src/goto-symex/solver_hardness.cpp
  src/goto-symex/solver_hardness.h
Labels: bugfix

#7503 SMT2 back-end: improve support for zero-sized components
  regression/cbmc/Float-flags-no-simp1/test.desc
  regression/cbmc/Float-flags-simp1/test.desc
  regression/cbmc/Float-no-simp3/test.desc
  regression/cbmc/Float-no-simp9/test.desc
  regression/cbmc/Multi_Dimensional_Array2/test.desc
  regression/cbmc/Multi_Dimensional_Array3/test.desc
  regression/cbmc/Pointer_byte_extract5/no-simplify.desc
  regression/cbmc/Quantifiers-assertion/test.desc
  regression/cbmc/Quantifiers-two-dimension-array/fixed.desc
  regression/cbmc/byte_update12/test.desc
  regression/cbmc/field-sensitivity16/test.desc
  regression/cbmc/havoc_slice/test_struct_raw_bytes.desc
  regression/cbmc/integer-assignments1/test.desc
  regression/cbmc/memory_allocation1/test.desc
  regression/cbmc/printf1/test.desc
  regression/cbmc/union10/union_list2.desc
  regression/cbmc/union11/union_list.desc
  regression/cbmc/union12/test.desc
  regression/cbmc/va_list3/test.desc
  regression/cbmc/void_pointer5/test.desc
  regression/cbmc/xml-trace/test.desc
  regression/cbmc/z3/trace-char.desc
  regression/cbmc/z3/trace.desc
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: SMT Backend Interface, aws, Kani

#7498 Add Github Actions jobs for testing the Rust API in CI
  .github/workflows/pull-request-check-rust-api.yaml
  .github/workflows/pull-request-checks.yaml
  src/libcprover-rust/other/example.c
  src/libcprover-rust/src/lib.rs
Labels: CI, Rust API

#7508 Reduce Codecov failure rate by using a token
  .github/workflows/pull-request-checks.yaml
Labels: CI
