Repository diffblue/cbmc, pull requests merged in 2023-03, with the labels that each got.

#6479 Warn user when unsound flags are enabled.
  doc/cprover-manual/api.md
  doc/cprover-manual/cbmc-assertions.md
  doc/cprover-manual/cbmc-tutorial.md
  doc/cprover-manual/goto-analyzer.md
  doc/cprover-manual/index.md
  doc/cprover-manual/installation.md
  doc/cprover-manual/memory-primitives.md
  doc/cprover-manual/properties.md
  doc/cprover-manual/static-functions.md
  doc/cprover-manual/test-suite.md
  doc/cprover-manual/unsound_options.md
  doc/man/cbmc.1
  doc/man/goto-instrument.1
  doc/man/jbmc.1
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/goto-checker/bmc_util.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-instrument/reachability_slicer.h
Labels: aws, soundness

#7556 Simplify tests of is-null that use integer types
  regression/cbmc/null8/main.c
  regression/cbmc/null8/test.desc
  src/util/simplify_expr_int.cpp
Labels: aws, Kani

#7570 Simplify overflow-result-minus over (X + n), X
  regression/cbmc/gcc_builtin_sub_overflow/simplify.c
  regression/cbmc/gcc_builtin_sub_overflow/simplify.desc
  src/util/simplify_expr.cpp
Labels: aws, Kani

#7574 Free up additional disk space on GitHub runner
  .github/workflows/pull-request-checks.yaml
Labels: blocker

#7571 Byte-operator lowering: do not unconditionally insert bv cast
  src/util/lower_byte_operators.cpp
Labels: aws, Kani

#7577 CMake: clean up setting CMAKE_VERSION
  jbmc/src/CMakeLists.txt
  src/CMakeLists.txt
Labels: cleanup

#7569 ITE and binary relations are constant when all operands are constants
  regression/cbmc/constant_folding3/main.c
  regression/cbmc/constant_folding3/test.desc
  src/util/expr_util.cpp
Labels: aws, Kani

#7578 Fix documentation links
  doc/architectural/symex-instructions.md
  doc/doxygen-root/doxyfile
Labels: bugfix, documentation

#7585 C front-end: address-of-label is a compile-time constant
  regression/cbmc/Computed-Goto1/main.c
  src/ansi-c/c_typecheck_expr.cpp
Labels: bugfix, C Front End

#7590 Tests: Fix decision-procedure-runtime pattern
  regression/cbmc/Failing_Assert1/dimacs.desc
  regression/cbmc/Failing_Assert1/test.desc
Labels: bugfix, Tests

#7589 C front-end: fix type2name for vectors
  regression/ansi-c/gcc_vector2/main.c
  regression/ansi-c/gcc_vector2/test.desc
  regression/goto-instrument/bitfield_naming/test.desc
  src/ansi-c/type2name.cpp
Labels: bugfix, C Front End

#7594 Constructor attribute is not required with forward declaration
  regression/cbmc/constructor1/main.c
  src/ansi-c/c_typecheck_base.cpp
Labels: C Front End

#7592 Rename object files so that we don't have collisions between different
  src/libcprover-cpp/add_dependencies.sh
Labels: aws, Kani, Rust API

#7593 C front-end: declare further GCC built-ins
  src/ansi-c/CMakeLists.txt
  src/ansi-c/Makefile
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_internal_additions.h
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/compiler_headers/clang_builtin_headers.h
  src/ansi-c/compiler_headers/clang_builtins.py
  src/ansi-c/compiler_headers/gcc_builtin_headers_ia32-5.h
  src/ansi-c/compiler_headers/gcc_builtin_headers_ia32-6.h
  src/ansi-c/compiler_headers/gcc_builtin_headers_ia32.h
  src/ansi-c/compiler_headers/gcc_builtin_headers_types_gcc7plus.h
  src/libcprover-cpp/api.cpp
Labels: C Front End

#7516 Rust API crate preparation
  .github/workflows/pull-request-check-rust-api.yaml
  CMakeLists.txt
  src/libcprover-rust/Cargo.lock
  src/libcprover-rust/Cargo.toml
  src/libcprover-rust/build.rs
  src/libcprover-rust/readme.md
  src/libcprover-rust/src/lib.rs
Labels: Rust API

#7597 C front-end: fix the interaction between packing and alignment
  regression/ansi-c/gcc_attributes15/main.c
  regression/ansi-c/gcc_attributes15/test.desc
  regression/ansi-c/pragma_pack4/main.c
  regression/ansi-c/pragma_pack4/test.desc
  src/ansi-c/padding.cpp
  src/ansi-c/parser.y
Labels: bugfix, C Front End

#7600 Enhance documentation for functions and modules of the Rust API
  src/libcprover-rust/Cargo.toml
  src/libcprover-rust/build.rs
  src/libcprover-rust/include/c_api.h
  src/libcprover-rust/src/c_api.cc
  src/libcprover-rust/src/lib.rs
  src/libcprover-rust/tutorial.md
Labels: documentation, Kani, Rust API

#7602 Ignore empty loops during loop-contracts synthesis
  regression/goto-synthesizer/empty_loop/main.c
  regression/goto-synthesizer/empty_loop/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
Labels: bugfix, aws, Code Contracts

#7601 Constructor/destructor attributes also work with forward declarations
  regression/cbmc/constructor1/main.c
  src/ansi-c/c_typecheck_base.cpp
Labels: bugfix, C Front End

#7554 Add documentation for an overview of the goto program transformation passes
  doc/architectural/cbmc-architecture.md
  doc/architectural/goto-program-transformations.md
Labels: documentation

#7605 Function-pointer removal: fix interaction with slice-global-inits
  regression/goto-instrument/slice-global-inits5/main.c
  regression/goto-instrument/slice-global-inits5/test.desc
  regression/goto-instrument/slice-global-inits6/main.c
  regression/goto-instrument/slice-global-inits6/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/remove_const_function_pointers.cpp
Labels: bugfix

#7620 Support all `objdump --syms` formats in `ls_parse.py`
  scripts/ls_parse.py
Labels: aws

#7624 SMT back-end: report too-many-addressed-objects
  regression/cbmc/address_space_size_limit1/test.desc
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2_incremental/convert_expr_to_smt.cpp
  unit/solvers/smt2_incremental/convert_expr_to_smt.cpp
Labels: SMT Backend Interface, bugfix

#7638 Update release process ADR with info on Rust crate
  doc/ADR/release_process.md
Labels: documentation, Rust API
