Repository diffblue/cbmc, pull requests merged in 2023-06, with the labels that each got.

#7744 SYNTHESIZER: Conver do{ }while(0) to non-loop block
  regression/goto-synthesizer/do_while_loop_0/main.c
  regression/goto-synthesizer/do_while_loop_0/test.desc
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
Labels: aws, Code Contracts, Synthesis

#7763 CONTRACTS: track function parameters explicitly
  regression/contracts-dfcc/loop_assigns_function_paramters/main.c
  regression/contracts-dfcc/loop_assigns_function_paramters/test.desc
  src/goto-instrument/contracts/dynamic-frames/dfcc_cfg_info.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.cpp
Labels: aws, Code Contracts

#7786 CONTRACTS: fix fresh symbols for quantified vars
  regression/contracts-dfcc/quantifiers-loops-fresh-bound-vars-smt/main.c
  regression/contracts-dfcc/quantifiers-loops-fresh-bound-vars-smt/test.desc
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument_loop.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument_loop.h
Labels: blocker, aws, aws-high

#7778 Add ADR outlining rationale for libcprover-cpp and goto-bmc integration
  doc/ADR/README.md
  doc/ADR/cpp_api_modularisation.md
Labels: documentation

#7617 Floating-point normalization must not overflow
  regression/cbmc/Float-rounding2/main.c
  regression/cbmc/Float-rounding2/test.desc
  src/solvers/floatbv/float_bv.cpp
  src/solvers/floatbv/float_utils.cpp
Labels: bugfix
