Repository diffblue/cbmc, pull requests merged in 2023-07, with the labels that each got.

#7796 Fix groff syntax errors in man pages
  doc/man/cbmc.1
  doc/man/goto-analyzer.1
  doc/man/goto-harness.1
  doc/man/janalyzer.1
Labels: bugfix

#7800 Fix typo in function-pointer removal
  src/goto-programs/remove_function_pointers.cpp
Labels: bugfix

#7788 CONTRACTS: Add goto-level loop-contract annotation
  doc/man/goto-instrument.1
  regression/contracts-dfcc/CMakeLists.txt
  regression/contracts-dfcc/dont_skip_cprover_prefixed_vars_fail/test.json
  regression/contracts-dfcc/dont_skip_cprover_prefixed_vars_fail/test_contracts_file.desc
  regression/contracts-dfcc/dont_skip_cprover_prefixed_vars_pass/test.json
  regression/contracts-dfcc/dont_skip_cprover_prefixed_vars_pass/test_contracts_file.desc
  regression/contracts-dfcc/history-index/test.json
  regression/contracts-dfcc/history-index/test_contracts_file.desc
  regression/contracts-dfcc/loop_contracts_file_fail/main.c
  regression/contracts-dfcc/loop_contracts_file_fail/test_matching_more_than_one_function.desc
  regression/contracts-dfcc/loop_contracts_file_fail/test_matching_more_than_one_function.json
  regression/contracts-dfcc/loop_contracts_file_fail/test_matching_no_function.desc
  regression/contracts-dfcc/loop_contracts_file_fail/test_matching_no_function.json
  regression/contracts-dfcc/loop_contracts_memcmp/main.c
  regression/contracts-dfcc/loop_contracts_memcmp/test.desc
  regression/contracts-dfcc/loop_contracts_memcmp/test.json
  regression/contracts-dfcc/loop_contracts_memcmp/test_contracts_file.desc
  regression/contracts-dfcc/variant_multi_instruction_loop_head/test.json
  regression/contracts-dfcc/variant_multi_instruction_loop_head/test_contracts_file.desc
  src/ansi-c/c_typecheck_base.h
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/contracts_wrangler.cpp
  src/goto-instrument/contracts/contracts_wrangler.h
  src/goto-instrument/contracts/module_dependencies.txt
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
Labels: aws, Code Contracts

#7787 Add incremental SMT support for struct with and member expressions
  regression/cbmc-incr-smt2/structs/large_array_of_struct_nondet_index.c
  regression/cbmc-incr-smt2/structs/large_array_of_struct_nondet_index.desc
  regression/cbmc/array-cell-sensitivity9/test.desc
  regression/cbmc/array-cell-sensitivity9/test_execution.desc
  regression/cbmc/field-sensitivity-trace-wrong-counterexample-1/test.desc
  regression/cbmc/simplify_singleton_interval_7690/test_smt2.desc
  src/solvers/smt2_incremental/encoding/struct_encoding.cpp
  src/solvers/smt2_incremental/encoding/struct_encoding.h
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.h
  unit/solvers/smt2_incremental/encoding/struct_encoding.cpp
Labels: SMT Backend Interface

#7736 Remove support for vector-typed expressions from back-ends
  src/solvers/Makefile
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_add_sub.cpp
  src/solvers/flattening/boolbv_floatbv_op.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/flattening/boolbv_unary_minus.cpp
  src/solvers/flattening/boolbv_vector.cpp
  src/solvers/flattening/boolbv_width.cpp
  src/solvers/smt2/smt2_conv.cpp
Labels: cleanup

#7716 Value sets: make pointers nondet only once
  jbmc/unit/pointer-analysis/custom_value_set_analysis.cpp
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set.h
  src/pointer-analysis/value_set_fi.cpp
  src/pointer-analysis/value_set_fi.h
Labels: Performance Optimisations

#7824 Avoid conversion check failure sysconf library model
  regression/cbmc-library/sysconf-01/test.desc
  src/ansi-c/library/unistd.c
Labels: aws, aws-high
