Repository diffblue/cbmc, pull requests merged in 2023-09, with the labels that each got.

#7851 Fix C++ test Templates1
  regression/cbmc-cpp/Templates1/main.cpp
  regression/cbmc-cpp/Templates1/test.desc
Labels: Tests

#7882 fixup! Fix cpp-linter tests to avoid .git dependency
  regression/cpp-linter/CMakeLists.txt
Labels: bugfix, Tests

#7395 Move CPROVER_{r,w,rw}_ok processing to back-end
  src/ansi-c/expr2c.cpp
  src/ansi-c/expr2c_class.h
  src/ansi-c/goto_check_c.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-programs/Makefile
  src/goto-programs/process_goto_program.cpp
  src/goto-programs/rewrite_rw_ok.cpp
  src/goto-programs/rewrite_rw_ok.h
  src/goto-synthesizer/goto_synthesizer_parse_options.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2_incremental/convert_expr_to_smt.cpp
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  src/util/irep_ids.def
  src/util/pointer_expr.cpp
  src/util/pointer_expr.h
  src/util/simplify_expr.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_pointer.cpp
Labels: aws, aws-high

#7896 Fix crangler Makefile
  src/crangler/Makefile
Labels: Build

#7880 Add a table to track the checks for C11 undefined behavior
  doc/C/c11-undefined-behavior.html
  doc/C/n1570-j-2.txt
Labels: documentation

#7898 fix for boolbvt::convert_extractbit
  src/solvers/flattening/boolbv_extractbit.cpp
Labels: Solvers, bugfix

#7855 Fix byte update of struct/array elements
  regression/cbmc/byte_update18/main.c
  regression/cbmc/byte_update18/test.desc
  src/util/lower_byte_operators.cpp
Labels: bugfix, aws, aws-high, Kani

#7874 A couple of minor documentation fixes
  src/analyses/README.md
  src/goto-instrument/contracts/doc/user/contracts-loops.md
Labels: Code Contracts

#7853 Fix help formatting errors and omissions
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_domain.h
  src/goto-cc/goto_cc_mode.cpp
  src/goto-checker/bmc_util.h
  src/goto-instrument/contracts/dynamic-frames/dfcc.h
  src/memory-analyzer/memory_analyzer_parse_options.cpp
Labels: bugfix

#7902 C library: model inet_ntoa
  regression/cbmc-library/inet_ntoa-01/main.c
  regression/cbmc-library/inet_ntoa-01/test.desc
  src/ansi-c/library/inet.c
Labels: C Front End

#7903 C library: model strftime
  regression/cbmc-library/_strftime-01/main.c
  regression/cbmc-library/_strftime-01/test.desc
  regression/cbmc-library/strftime-01/main.c
  regression/cbmc-library/strftime-01/test.desc
  src/ansi-c/library/time.c
Labels: C Front End

#7904 C library: model and test several __*_chk variants
  regression/cbmc-library/fgets-01/__fgets_chk.desc
  regression/cbmc-library/fprintf-01/__fprintf_chk.desc
  regression/cbmc-library/fread-01/__fread_chk.desc
  regression/cbmc-library/fread-01/main.c
  regression/cbmc-library/fread-01/test.desc
  regression/cbmc-library/printf-01/__printf_chk.desc
  regression/cbmc-library/syslog-01/__syslog_chk.desc
  regression/cbmc-library/syslog-01/main.c
  regression/cbmc-library/syslog-01/test.desc
  regression/cbmc-library/vfprintf-01/__vfprintf_chk.desc
  regression/cbmc-library/vfprintf-01/main.c
  regression/cbmc-library/vfprintf-01/test.desc
  src/ansi-c/library/stdio.c
  src/ansi-c/library/syslog.c
  src/ansi-c/library_check.sh
Labels: C Front End

#7912 Make constant_propagation_08 test platform agnostic
  regression/goto-analyzer/constant_propagation_08/main.c
  regression/goto-analyzer/constant_propagation_08/test-vsd.desc
Labels: Tests

#7913 [DOCS] Add documentation on CBMC Shadow Memory intrinsics
  doc/cprover-manual/index.md
  doc/cprover-manual/modeling-shadow-memory.md
Labels: documentation

#7925 Interval expressions: cleanup type hierarchy
  src/util/interval.cpp
  src/util/interval.h
  unit/util/interval/bitwise.cpp
  unit/util/interval/comparisons.cpp
  unit/util/interval/divide.cpp
  unit/util/interval/eval.cpp
  unit/util/interval/modulo.cpp
  unit/util/interval/multiply.cpp
  unit/util/interval/shift.cpp
  unit/util/interval/subtract.cpp
  unit/util/interval/to_string.cpp
Labels: cleanup

#7931 Rename {min,max}_exprt to {min,max}_value_exprt
  src/analyses/variable-sensitivity/abstract_environment.cpp
  src/analyses/variable-sensitivity/interval_abstract_value.cpp
  src/analyses/variable-sensitivity/value_set_abstract_object.cpp
  src/analyses/variable-sensitivity/widened_range.cpp
  src/util/interval.cpp
  src/util/interval.h
  src/util/irep_ids.def
  unit/analyses/variable-sensitivity/interval_abstract_value/extremes-go-top.cpp
  unit/analyses/variable-sensitivity/interval_abstract_value/meet.cpp
  unit/analyses/variable-sensitivity/interval_abstract_value/widening_merge.cpp
  unit/analyses/variable-sensitivity/value_expression_evaluation/assume_prune.cpp
  unit/analyses/variable-sensitivity/value_set_abstract_object/extremes-go-top.cpp
  unit/analyses/variable-sensitivity/value_set_abstract_object/widening_merge.cpp
  unit/analyses/variable-sensitivity/variable_sensitivity_test_helpers.cpp
  unit/util/interval/add.cpp
  unit/util/interval/comparisons.cpp
  unit/util/interval/divide.cpp
  unit/util/interval/eval.cpp
  unit/util/interval/modulo.cpp
  unit/util/interval/multiply.cpp
  unit/util/interval/subtract.cpp
  unit/util/interval/to_string.cpp
Labels: cleanup

#7919 C library: model getpwnam, getpwuid
  regression/cbmc-library/getpwnam-01/main.c
  regression/cbmc-library/getpwnam-01/test.desc
  regression/cbmc-library/getpwuid-01/main.c
  regression/cbmc-library/getpwuid-01/test.desc
  src/ansi-c/library/pwd.c
Labels: C Front End

#7916 C library: fix and test getopt model
  regression/cbmc-library/getopt-01/main.c
  regression/cbmc-library/getopt-01/test.desc
  src/ansi-c/library/getopt.c
  src/ansi-c/library_check.sh
Labels: C Front End
