Repository diffblue/cbmc, pull requests merged in 2023-02, with the labels that each got.

#7510 Fix file encoding of bigint-func.cc
  src/big-int/bigint-func.cc
Labels: bugfix

#7513 Add myself as a codeowner for the Rust API
  CODEOWNERS
Labels: Rust API

#7511 Translate exceptions from C++ API into Rust `Result` types.
  src/libcprover-rust/include/c_api.h
  src/libcprover-rust/include/module_dependencies.txt
  src/libcprover-rust/src/c_api.cc
  src/libcprover-rust/src/lib.rs
Labels: Kani, Rust API

#7428 Do not simplify (T)bv-typed when T has smaller bit width
  src/solvers/flattening/boolbv_typecast.cpp
Labels: bugfix

#7470 Add documentation for the central data structures in CBMC IR
  .github/workflows/publish.yaml
  doc/architectural/cbmc-architecture.md
  doc/architectural/central-data-structures.md
  doc/doxygen-root/doxygen-markdown/markdown.sh
Labels: documentation

#7521 C model library: Support ARM64 va_list types
  src/ansi-c/library/stdio.c
Labels: bugfix

#7524 CONTRACTS: Add an option to not unwind transformed loops after applying loop contracts
  doc/man/goto-instrument.1
  doc/man/goto-synthesizer.1
  regression/contracts/loop_contracts_no_unwind/main.c
  regression/contracts/loop_contracts_no_unwind/test.desc
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
  src/goto-synthesizer/cegis_verifier.cpp
  src/goto-synthesizer/goto_synthesizer_parse_options.cpp
  src/goto-synthesizer/goto_synthesizer_parse_options.h
Labels: aws, Code Contracts, Kani

#7529 Remove unused function_depth variable
  src/goto-programs/goto_trace.cpp
Labels: cleanup

#7523 Shadow memory interface and integration hooks [blocks 7535]
  src/goto-checker/multi_path_symex_only_checker.cpp
  src/goto-checker/single_path_symex_only_checker.cpp
  src/goto-symex/Makefile
  src/goto-symex/goto_symex.cpp
  src/goto-symex/goto_symex.h
  src/goto-symex/goto_symex_state.h
  src/goto-symex/shadow_memory.cpp
  src/goto-symex/shadow_memory.h
  src/goto-symex/shadow_memory_field_definitions.h
  src/goto-symex/shadow_memory_state.h
  src/goto-symex/symex_assign.cpp
  src/goto-symex/symex_assign.h
  src/goto-symex/symex_builtin_functions.cpp
  src/goto-symex/symex_clean_expr.cpp
  src/goto-symex/symex_decl.cpp
  src/goto-symex/symex_dereference.cpp
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_main.cpp
  src/goto-symex/symex_start_thread.cpp
  unit/goto-symex/symex_assign.cpp
  unit/path_strategies.cpp
Labels: blocker

#7539 Limit counterexample size to speed up regression tests
  jbmc/regression/jbmc/assume-inputs-non-null/string_assume.desc
  jbmc/regression/jbmc/context-include-exclude/test_exclude_from_include.desc
  jbmc/regression/jbmc/context-include-exclude/test_include.desc
  jbmc/regression/jbmc/exceptions29/test.desc
Labels: Tests

#7534 Restore named_sub map entries ordering when reading from a goto binary.
  src/analyses/variable-sensitivity/value_set_pointer_abstract_object.cpp
  src/cprover/generalization.cpp
  src/cprover/inductiveness.cpp
  src/cprover/state_encoding.cpp
  src/goto-instrument/contracts/instrument_spec_assigns.h
  src/goto-instrument/unwindset.cpp
  src/solvers/flattening/boolbv_bitreverse.cpp
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/smt2_incremental/ast/smt_commands.cpp
  src/solvers/smt2_incremental/convert_expr_to_smt.cpp
  src/util/forward_list_as_map.h
  src/util/irep.cpp
  src/util/irep_hash_container.cpp
  src/util/irep_serialization.cpp
  src/util/lispirep.cpp
  src/util/simplify_expr_int.cpp
Labels: aws, aws-high, Kani

#7493 Allow building CBMC with multiple backend SAT solvers that can be selected at runtime via a new `--sat-solver` option
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
  .gitignore
  CMakeLists.txt
  COMPILING.md
  Dockerfile
  doc/man/cbmc.1
  doc/man/jbmc.1
  regression/cbmc/sat-solver-error/test.c
  regression/cbmc/sat-solver-error/test.desc
  regression/cbmc/sat-solver-warning/test.c
  regression/cbmc/sat-solver-warning/test.desc
  regression/cbmc/sat-solver/test.c
  regression/cbmc/sat-solver/test.desc
  regression/validate-trace-xml-schema/check.py
  scripts/cadical-1.4.1-patch
  scripts/cadical_CMakeLists.txt
  src/Makefile
  src/goto-checker/solver_factory.cpp
  src/goto-checker/solver_factory.h
  src/libcprover-rust/build.rs
  src/solvers/CMakeLists.txt
  src/solvers/Makefile
  src/solvers/sat/satcheck.h
Labels: aws, Kani

#7532 Remove never-read variable seen_terms
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
Labels: cleanup, Code Contracts

#7127 CONTRACTS: Support slice targets in loop assigns clauses
  regression/contracts-dfcc/assigns_enforce_address_of/test.desc
  regression/contracts-dfcc/assigns_enforce_conditional_non_lvalue_target/test.desc
  regression/contracts-dfcc/assigns_enforce_conditional_non_lvalue_target_list/test.desc
  regression/contracts-dfcc/assigns_enforce_literal/test.desc
  regression/contracts-dfcc/assigns_enforce_side_effects_2/test.desc
  regression/contracts-dfcc/assigns_enforce_side_effects_3/test.desc
  regression/contracts-dfcc/assigns_type_checking_invalid_case_01/test.desc
  regression/contracts-dfcc/reject_history_expr_in_assigns_clause/test.desc
  regression/contracts/assigns_enforce_address_of/test.desc
  regression/contracts/assigns_enforce_conditional_non_lvalue_target/test.desc
  regression/contracts/assigns_enforce_conditional_non_lvalue_target_list/test.desc
  regression/contracts/assigns_enforce_literal/test.desc
  regression/contracts/assigns_enforce_side_effects_2/test.desc
  regression/contracts/assigns_enforce_side_effects_3/test.desc
  regression/contracts/assigns_type_checking_invalid_case_01/test.desc
  regression/contracts/invar_havoc_dynamic_array/main.c
  regression/contracts/invar_havoc_static_array/main.c
  regression/contracts/invar_havoc_static_multi-dim_array_partial_const_idx/main.c
  regression/contracts/loop_assigns-01/main.c
  regression/contracts/loop_assigns-03/main.c
  regression/contracts/loop_assigns-04/main.c
  regression/contracts/loop_assigns-slice-assignable-ptr/main.c
  regression/contracts/loop_assigns-slice-assignable-ptr/test.desc
  regression/contracts/loop_assigns-slice-assignable-scalar/main.c
  regression/contracts/loop_assigns-slice-assignable-scalar/test.desc
  regression/contracts/loop_assigns-slice-from/main.c
  regression/contracts/loop_assigns-slice-from/test.desc
  regression/contracts/loop_assigns-slice-upto-fail/main.c
  regression/contracts/loop_assigns-slice-upto-fail/test.desc
  regression/contracts/loop_assigns-slice-upto-pass/main.c
  regression/contracts/loop_assigns-slice-upto-pass/test.desc
  regression/contracts/quantifiers-loop-01/main.c
  regression/contracts/quantifiers-loop-02/main.c
  regression/contracts/quantifiers-loop-03/main.c
  regression/contracts/reject_history_expr_in_assigns_clause/test.desc
  src/ansi-c/c_typecheck_code.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
  src/goto-instrument/havoc_utils.cpp
  src/goto-instrument/havoc_utils.h
Labels: aws, aws-high, Code Contracts

#7543 Use CaDiCaL for selected THOROUGH regression tests
  .github/workflows/pull-request-checks.yaml
  jbmc/regression/jbmc-strings/VerifStringLastIndexOf/test.desc
  jbmc/regression/jbmc-strings/java_easychair/test.desc
  jbmc/regression/strings-smoke-tests/java_parselong_unknown_radix/test.desc
  regression/cbmc/Float-equality1/test_equality.desc
  regression/cbmc/gcc_popcount2/test.desc
Labels: Tests, CI

#7548 Run macos-12 CI build using Clang 15
  .github/workflows/pull-request-checks.yaml
Labels: CI

#7550 Add new function to inline a list of calls in a goto_program
  src/goto-programs/goto_inline.cpp
  src/goto-programs/goto_inline.h
  src/goto-programs/goto_inline_class.cpp
  src/goto-programs/goto_inline_class.h
  unit/Makefile
  unit/goto-programs/goto_program_goto_program_inline.cpp
Labels: aws

#7553 Refactor and add documentation for `mmio` goto-program pass
  src/goto-programs/mm_io.cpp
  src/goto-programs/mm_io.h
Labels: cleanup

#7551 CONTRACTS: refactor DFCC code for loop contracts
  src/ansi-c/library/cprover_contracts.c
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/dynamic-frames/dfcc.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_clauses_codegen.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_clauses_codegen.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_functions.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_functions.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_handler.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_handler.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_is_freeable.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_library.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_utils.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_utils.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_wrapper_program.cpp
Labels: aws, aws-high, Code Contracts

#7557 CONTRACTS: place contracts after do for do-while loops
  regression/contracts/do_while_syntax_fail/main.c
  regression/contracts/do_while_syntax_fail/test.desc
  regression/contracts/do_while_syntax_pass/main.c
  regression/contracts/do_while_syntax_pass/test.desc
  regression/contracts/loop_contracts_do_while/main.c
  regression/contracts/loop_contracts_do_while/test.desc
  src/ansi-c/parser.y
Labels: aws, Code Contracts

#7558 Disable array-cell-sensitivity3 with new SMT back-end
  regression/cbmc/array-cell-sensitivity3/test_execution.desc
Labels: Tests

#7561 remove typet::subtype()
  src/cpp/cpp_template_type.h
  src/util/c_types.h
  src/util/pointer_expr.h
  src/util/type.h
Labels: cleanup

#7560 Avoid confusing "__CPROVER_{r,w,rw}_ok is not declared" warning
  regression/ansi-c/r_w_ok-expected-failures/main.c
  regression/ansi-c/r_w_ok-expected-failures/not_a_pointer.desc
  regression/ansi-c/r_w_ok-expected-failures/too_many_arguments.desc
  regression/ansi-c/r_w_ok-expected-failures/void_pointer_no_size.desc
  regression/ansi-c/r_w_ok1/main.c
  regression/ansi-c/r_w_ok1/test.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End

#7563 Minor formatting fix to contracts help
  src/goto-instrument/contracts/dynamic-frames/dfcc.h
  src/goto-instrument/goto_instrument_parse_options.cpp
Labels: cleanup, aws, Code Contracts

#7565 Fix handling of "enable:named-check" pragmas
  regression/goto-instrument/enable-pragmas/main.c
  regression/goto-instrument/enable-pragmas/test.desc
  src/ansi-c/goto_check_c.cpp
Labels: bugfix

#7559 protect array_typet::subtype and vector_typet::subtype
  src/solvers/flattening/boolbv_get.cpp
  src/solvers/strings/string_refinement.cpp
  src/util/std_types.h
Labels: cleanup

#7497 Document symex instructions
  doc/architectural/cbmc-architecture.md
  doc/architectural/symex-instructions.md
Labels: documentation

#7566 remove three deprecated goto_instructiont methods
  src/cprover/cprover_parse_options.cpp
  src/goto-instrument/cover_basic_blocks.cpp
  src/goto-instrument/full_slicer.cpp
  src/goto-instrument/goto_program2code.cpp
  src/goto-programs/goto_program.h
Labels: cleanup
