Repository diffblue/cbmc, pull requests merged in 2023-08, with the labels that each got.

#7825 preconditions for abs, labs, llabs, imaxabs
  regression/cbmc-library/abs-01/main.c
  src/ansi-c/library/stdlib.c
Labels: enhancement, C Front End

#7834 SYNTHESIZER: add array-uf options
  doc/man/goto-synthesizer.1
  regression/goto-synthesizer/array_uf/main.c
  regression/goto-synthesizer/array_uf/test.desc
  regression/goto-synthesizer/chain.sh
  src/goto-synthesizer/goto_synthesizer_parse_options.cpp
  src/goto-synthesizer/goto_synthesizer_parse_options.h
Labels: Synthesis

#7845 Fix little-endian MIPS definition
  src/util/config.cpp
Labels: bugfix

#7844 Fix tests for unsigned-char architectures
  regression/cbmc-incr-smt2/bitvector-bitwise-operators/shift_right.desc
  regression/cbmc/integral-trace/test.desc
  regression/cbmc/pointer-offset-01/test.desc
  regression/goto-instrument-json/rol_signed/test-signed.desc
  regression/goto-instrument-json/rol_unsigned/test.desc
  regression/goto-instrument-json/ror_signed/test-signed.desc
  regression/goto-instrument-json/ror_unsigned/test.desc
Labels: bugfix, Tests

#7842 Fix undefined shift on non-64-bit architectures
  unit/solvers/smt2_incremental/convert_expr_to_smt.cpp
Labels: bugfix

#7843 Fix __float128 portability
  regression/ansi-c/gcc_version1/gcc-5.c
  regression/ansi-c/gcc_version1/gcc-7.c
  regression/cbmc/ts18661_typedefs/main.c
  src/cpp/cpp_internal_additions.cpp
Labels: bugfix, C Front End

#7852 Silence another spurious maybe-uninitialized warning
  src/util/lower_byte_operators.cpp
Labels: aws
