Repository diffblue/cbmc, pull requests merged in 2023-11, with the labels that each got.

#7982 typecheckt::errort
  src/ansi-c/c_typecheck_type.cpp
  src/util/typecheck.cpp
  src/util/typecheck.h
Labels: C++ Front End, C Front End

#7992 remove index_type()
  src/goto-symex/shadow_memory_util.cpp
  src/memory-analyzer/analyze_symbol.cpp
  src/util/c_types.cpp
  src/util/c_types.h
Labels: cleanup

#7994 Fix line-number output in document-properties-*
  regression/goto-instrument/document-properties-basic/html.desc
  src/goto-instrument/document_properties.cpp
Labels: bugfix

#7995 CODING_STANDARD.md: fix references to clang-format
  CODING_STANDARD.md
Labels: documentation

#6118 Use simplify_exprtt::resultt in pre-order simplification steps
  src/util/simplify_expr.cpp
  src/util/simplify_expr_array.cpp
  src/util/simplify_expr_class.h
  src/util/simplify_expr_if.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
Labels: cleanup

#7987 CBMC version 6 release process changes
  .github/workflows/regular-release.yaml
  .github/workflows/release-packages.yaml
  CMakeLists.txt
  src/config.inc
  src/libcprover-rust/Cargo.toml
  v6_undo_stack.markdown
Labels: Version 6

#7989 Change C++ version to C++17
  .clang-format
  CMakeLists.txt
  COMPILING.md
  scripts/bash-autocomplete/extract_switches.sh
  scripts/cadical_CMakeLists.txt
  scripts/check_help.sh
  scripts/glucose_CMakeLists.txt
  scripts/minisat2_CMakeLists.txt
  src/common
  src/solvers/CMakeLists.txt
Labels: Version 6

#8031 Remove local declaration of void_t
  src/solvers/smt2_incremental/ast/smt_terms.h
  src/solvers/smt2_incremental/type_traits.h
Labels: cleanup

#8028 [CI] Minor fixes to CI accompanying C++17 version change
  .github/workflows/pull-request-check-rust-api.yaml
  src/libcprover-rust/Cargo.toml
  src/libcprover-rust/build.rs
  src/libcprover-rust/src/lib.rs
Labels: CI

#8035 Refactor `smt_function_application_termt::indices` using C++17 feature
  src/solvers/smt2_incremental/ast/smt_terms.h
Labels: Version 6

#8037 Replace usage of `std::result_of` with `std::invoke_result`
  src/util/range.h
Labels: Version 6

#8045 DFCC instrumentation: ensure programs are well-formed
  .github/workflows/pull-request-checks.yaml
  src/goto-instrument/contracts/dynamic-frames/dfcc_wrapper_program.cpp
Labels: bugfix

#8047 Make -Wno-maybe-uninitialized the default with GCC
  CMakeLists.txt
  src/config.inc
  src/goto-instrument/unwindset.cpp
  src/util/cmdline.cpp
  src/util/lower_byte_operators.cpp
  src/util/simplify_expr_int.cpp
Labels: Build

#8050 C library check: do not warn about the need for MMX
  src/ansi-c/library_check.sh
Labels: Build

#8036 Use the C++17 standard `[[nodiscard]]` attribute directly
  jbmc/src/java_bytecode/java_utils.cpp
  jbmc/src/java_bytecode/java_utils.h
  src/cprover/bv_pointers_wide.h
  src/goto-programs/link_goto_model.h
  src/goto-symex/field_sensitivity.h
  src/goto-symex/goto_symex.h
  src/goto-symex/goto_symex_state.h
  src/goto-symex/symex_clean_expr.cpp
  src/solvers/flattening/bv_pointers.h
  src/solvers/flattening/bv_utils.h
  src/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
  src/solvers/smt2_incremental/smt_response_validation.h
  src/solvers/strings/string_dependencies.h
  src/util/interval_union.h
  src/util/nodiscard.h
  src/util/piped_process.cpp
  src/util/piped_process.h
  src/util/rename.h
  src/util/simplify_expr_class.h
Labels: Version 6

#7973 SYNTHESIZER: Add quick filter into goto-synthesizer
  regression/goto-synthesizer/loop_contracts_synthesis_03/main.c
  regression/goto-synthesizer/loop_contracts_synthesis_04/test.desc
  src/goto-synthesizer/Makefile
  src/goto-synthesizer/cegis_evaluator.cpp
  src/goto-synthesizer/cegis_evaluator.h
  src/goto-synthesizer/cegis_verifier.cpp
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.h
Labels: aws, aws-high, Synthesis

#8085 The emscripten compiler has alloca.h
  src/big-int/allocainc.h
Labels: Build

#8032 Remove util_make_unique
  jbmc/src/janalyzer/janalyzer_parse_options.cpp
  jbmc/src/java_bytecode/java_bytecode_language.cpp
  jbmc/src/java_bytecode/java_bytecode_language.h
  jbmc/src/java_bytecode/java_qualifiers.cpp
  jbmc/src/jbmc/jbmc_parse_options.cpp
  src/analyses/ai.h
  src/analyses/ai_domain.h
  src/analyses/dependence_graph.cpp
  src/analyses/goto_rw.cpp
  src/analyses/invariant_propagation.cpp
  src/analyses/local_may_alias.h
  src/analyses/reaching_definitions.cpp
  src/analyses/variable-sensitivity/abstract_value_object.cpp
  src/analyses/variable-sensitivity/abstract_value_object.h
  src/analyses/variable-sensitivity/constant_abstract_value.cpp
  src/analyses/variable-sensitivity/interval_abstract_value.cpp
  src/analyses/variable-sensitivity/value_set_abstract_object.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_dependence_graph.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_domain.h
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/ansi_c_language.h
  src/ansi-c/c_qualifiers.cpp
  src/ansi-c/goto_check_c.cpp
  src/cbmc/cbmc_parse_options.cpp
  src/cpp/cpp_language.cpp
  src/cpp/cpp_language.h
  src/goto-analyzer/build_analyzer.cpp
  src/goto-checker/bmc_util.cpp
  src/goto-checker/single_path_symex_checker.cpp
  src/goto-checker/solver_factory.cpp
  src/goto-harness/function_call_harness_generator.cpp
  src/goto-harness/goto_harness_parse_options.cpp
  src/goto-instrument/accelerate/enumerating_loop_acceleration.h
  src/goto-instrument/accelerate/scratch_program.h
  src/goto-instrument/cover.cpp
  src/goto-instrument/cover.h
  src/goto-instrument/generate_function_bodies.cpp
  src/goto-symex/path_storage.cpp
  src/goto-symex/symex_main.cpp
  src/goto-synthesizer/cegis_verifier.cpp
  src/jsil/jsil_language.cpp
  src/jsil/jsil_language.h
  src/json-symtab-language/json_symtab_language.h
  src/libcprover-cpp/api.cpp
  src/libcprover-cpp/api_options.cpp
  src/libcprover-cpp/verification_result.cpp
  src/pointer-analysis/value_set_analysis.h
  src/solvers/sat/satcheck_glucose.cpp
  src/solvers/sat/satcheck_minisat2.cpp
  src/solvers/smt2_incremental/encoding/struct_encoding.cpp
  src/solvers/strings/string_dependencies.cpp
  src/statement-list/statement_list_language.cpp
  src/util/make_unique.h
  src/util/piped_process.cpp
  src/util/range.h
  src/util/sharing_node.h
  src/util/ui_message.cpp
  unit/solvers/smt2_incremental/smt2_incremental_decision_procedure.cpp
Labels: cleanup

#8034 Replace nonstd::optional by C++17 std::optional
  CODEOWNERS
  doc/architectural/folder-walkthrough.md
  jbmc/src/java_bytecode/ci_lazy_methods.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_cfg_info.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_lift_memory_predicates.cpp
  src/goto-programs/link_goto_model.cpp
  src/nonstd/README.md
  src/nonstd/module_dependencies.txt
  src/nonstd/optional.hpp
  src/solvers/flattening/boolbv_overflow.cpp
  src/solvers/flattening/boolbv_width.h
  src/solvers/strings/string_dependencies.h
  src/util/arith_tools.h
  src/util/module_dependencies.txt
  src/util/numbering.h
  src/util/optional.h
  src/util/sharing_map.h
  src/util/string2int.h
  unit/Makefile
  unit/util/optional.cpp
Labels: cleanup
