Repository diffblue/cbmc, pull requests merged in 2024-06, with the labels that each got.

#8297 `goto_check_ct::add_guarded_property` now has `is_fatal` parameter
  src/ansi-c/goto-conversion/goto_check_c.cpp
Labels: C++ Front End, C Front End, soundness

#8291 C++ front-end: fix parsing of >> as closing template args
  regression/cpp/Templates4/main.cpp
  regression/cpp/Templates4/test.desc
  src/cpp/parse.cpp
Labels: C++ Front End

#8318 Lower-byte-operators: bv_to_expr should support bool target type
  src/util/lower_byte_operators.cpp
Labels: bugfix

#8323 Add support for __fp16 where appropriate
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/ansi_c_parser.h
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/gcc_version.cpp
  src/ansi-c/scanner.l
  src/cpp/cpp_parser.cpp
  src/goto-instrument/contracts/contracts_wrangler.cpp
  src/util/config.cpp
  src/util/config.h
  unit/cpp_scanner.cpp
Labels: C Front End

#8315 mod-by-zero is now fatal
  src/ansi-c/goto-conversion/goto_check_c.cpp
Labels: C++ Front End, C Front End, soundness

#8314 array-bounds checks are now fatal
  src/ansi-c/goto-conversion/goto_check_c.cpp
Labels: C++ Front End, C Front End, soundness

#8247 Simplifier: c_bool (and others) are also bitvector types
  src/util/simplify_expr_class.h
  src/util/simplify_expr_int.cpp
  unit/util/simplify_expr.cpp
Labels: aws-high, Kani

#8143 Remove deprecated messaget() constructor
  src/goto-symex/complexity_limiter.h
  src/util/message.h
  src/util/parser.h
Labels: cleanup

#8325 `__CPROVER_bool` should not have a memory layout
  regression/ansi-c/cprover_bool1/main.c
  regression/ansi-c/cprover_bool1/test.desc
  regression/cpp/cprover_bool1/main.cpp
  regression/cpp/cprover_bool1/test.desc
  src/ansi-c/library/cprover_contracts.c
  src/util/pointer_expr.cpp
  src/util/pointer_offset_size.cpp
  unit/solvers/smt2_incremental/object_tracking.cpp
Labels: C++ Front End, C Front End

#8292 generate assert(false) when calling undefined function
  doc/man/cbmc.1
  regression/cbmc-cpp/Overloading_Functions4/main.cpp
  regression/cbmc-library/fprintf-01/__fprintf_chk.desc
  regression/cbmc-library/printf-01/__printf_chk.desc
  regression/cbmc-library/syslog-01/__syslog_chk.desc
  regression/cbmc/Array_UF17/main.c
  regression/cbmc/Function_Pointer5/main.c
  regression/cbmc/Malloc2/main.c
  regression/cbmc/Pointer28/test.desc
  regression/cbmc/Promotion4/main.i
  regression/cbmc/String_Abstraction11/anon-retval.c
  regression/cbmc/String_Abstraction19/structs.c
  regression/cbmc/Undefined_Function1/test.desc
  regression/cbmc/Undefined_Function2/test.desc
  regression/cbmc/havoc_undefined_functions/main.c
  regression/cbmc/havoc_undefined_functions/test.desc
  regression/cbmc/issue_5952_soundness_bug_smt_encoding/short.c
  regression/cbmc/issue_5952_soundness_bug_smt_encoding/test_short.desc
  regression/cbmc/memory_allocation2/test.desc
  regression/cbmc/pointer-overflow2/test.desc
  regression/cbmc/union12/test.desc
  regression/contracts/assigns_replace_02/main.c
  regression/contracts/cprover-assignable-pass/test.desc
  regression/goto-instrument-wmm-core/CMakeLists.txt
  regression/goto-instrument-wmm-core/Makefile
  regression/goto-instrument/dump-vararg1/test.desc
  regression/goto-instrument/inline_16/test.desc
  regression/goto-instrument/inline_17/test.desc
  regression/goto-instrument/remove-function-body1/test.desc
  src/ansi-c/library/syslog.c
  src/ansi-c/library_check.sh
  src/cbmc/cbmc_parse_options.cpp
  src/cbmc/cbmc_parse_options.h
  src/goto-checker/symex_bmc.cpp
  src/goto-checker/symex_bmc.h
  src/goto-symex/goto_symex.h
  src/goto-symex/symex_config.h
  src/goto-symex/symex_function_call.cpp
  src/goto-symex/symex_main.cpp
Labels: Symbolic Execution, soundness, Version 6

#8261 Make DFCC is_dead_object_update less restrictive
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.cpp
Labels: aws, Code Contracts

#8316 pointer checks are now fatal
  regression/cbmc-incr-smt2/pointer_arithmetic/pointer_subtraction.desc
  regression/cbmc-incr-smt2/pointers-relational-operators/pointers_assume.desc
  regression/cbmc-primitives/exists_memory_checks/invalid_index_range.desc
  regression/cbmc-primitives/exists_memory_checks/smt_missing_range_check.desc
  regression/cbmc-primitives/forall_6231_3/test_malloc_less_than_bound.desc
  regression/cbmc/Function_Pointer18/test.desc
  regression/cbmc/Function_Pointer_Init_One_Candidate/test.desc
  regression/cbmc/Function_Pointer_Init_Two_Candidates/test.desc
  regression/cbmc/array-cell-sensitivity10/test_execution.desc
  regression/cbmc/array-cell-sensitivity3/test_execution.desc
  regression/cbmc/array-cell-sensitivity7/test_execution.desc
  regression/cbmc/array-cell-sensitivity8/test_execution.desc
  regression/cbmc/byte_update14/test.desc
  regression/cbmc/memory_allocation1/test.desc
  regression/cbmc/pointer-extra-checks/test.desc
  regression/cbmc/ptr_arithmetic_on_null/test.desc
  regression/cbmc/switch8/test.desc
  regression/contracts-dfcc/assigns_enforce_structs_06/test-f2.desc
  regression/contracts-dfcc/assigns_replace_conditional_targets/main.c
  regression/contracts-dfcc/assigns_replace_conditional_targets/test.desc
  regression/contracts-dfcc/invar_dynamic_struct_member/main.c
  regression/contracts-dfcc/invar_dynamic_struct_member/test.desc
  regression/contracts-dfcc/loop_assigns-02/main.c
  regression/contracts-dfcc/loop_assigns-02/test.desc
  regression/contracts-dfcc/loop_assigns-04/main.c
  regression/contracts-dfcc/loop_assigns-04/test.desc
  regression/contracts/assigns_enforce_free_dead/test.desc
  regression/contracts/invar_dynamic_struct_member/test.desc
  regression/contracts/loop_assigns-02/test.desc
  regression/contracts/loop_assigns-04/test.desc
  regression/contracts/loop_assigns-fail/test.desc
  regression/goto-instrument/generate-function-body-complex-struct/test.desc
  regression/goto-instrument/nondet_static_exclude/test.desc
  src/ansi-c/goto-conversion/goto_check_c.cpp
Labels: C++ Front End, C Front End, soundness, Version 6

#8321 Expand list of known compiler built-ins
  .gitignore
  src/ansi-c/CMakeLists.txt
  src/ansi-c/Makefile
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_internal_additions.h
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/compiler_headers/clang_builtins.py
  src/ansi-c/compiler_headers/gcc_builtin_headers_ia32-7.h
  src/ansi-c/compiler_headers/gcc_builtin_headers_ia32-8.h
  src/ansi-c/compiler_headers/gcc_builtin_headers_ia32-9.h
Labels: C Front End

#8168 Declutter linking implementation
  src/linking/Makefile
  src/linking/casting_replace_symbol.cpp
  src/linking/casting_replace_symbol.h
  src/linking/linking.cpp
  src/linking/linking_class.h
  src/linking/linking_diagnostics.cpp
  src/linking/linking_diagnostics.h
Labels: cleanup

#8281 [CONTRACTS] Allow loop contracts annotated to goto statement
  src/ansi-c/goto-conversion/goto_convert.cpp
  src/ansi-c/goto-conversion/goto_convert_class.h
Labels: aws, Code Contracts

#8219 cprover: Replace uses of namespacet::follow
  src/cprover/bv_pointers_wide.cpp
Labels: cleanup

#8333 increase verbosity of warning about missing `__builtin_` declaration
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End

#8222 goto-symex: Replace uses of namespacet::follow
  src/goto-symex/auto_objects.cpp
  src/goto-symex/field_sensitivity.cpp
  src/goto-symex/goto_symex_state.cpp
  src/goto-symex/shadow_memory.cpp
  src/goto-symex/shadow_memory_util.cpp
  src/goto-symex/shadow_memory_util.h
  src/goto-symex/symex_assign.cpp
Labels: cleanup

#7946 C front-end: typecheck conditional operator over string literal and 0
  regression/ansi-c/null_pointer_constant1/main.c
  regression/ansi-c/null_pointer_constant1/test.desc
  src/ansi-c/c_typecheck_expr.cpp
Labels: C Front End

#8344 Fix Python syntax error
  doc/doxygen-root/doxygen-markdown/doxygen-markdown-preprocessor.py
Labels: bugfix

#8345 Use GNU parallel in Windows CI job
  .github/workflows/pull-request-checks.yaml
Labels: CI

#8348 goto-synthesizer: ignore __CPROVER_-prefixed symbols
  src/goto-synthesizer/enumerative_loop_contracts_synthesizer.cpp
Labels: bugfix, Code Contracts

#8347 Union member fix
  src/solvers/flattening/boolbv_member.cpp
Labels: Solvers, bugfix

#8349 GOTO conversion: Declaration hops must not invalidate incomplete gotos
  src/ansi-c/goto-conversion/goto_convert.cpp
  src/ansi-c/goto-conversion/goto_convert_class.h
Labels: bugfix

#8346 Increase Windows/clcache size to 2 GB
  .github/workflows/pull-request-checks.yaml
Labels: CI

#8340 homebrew-pr CI notification: install go
  .github/workflows/release-packages.yaml
Labels: CI

#8356 [CONTRACTS] Use unified loop contract config
  src/goto-instrument/Makefile
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/dynamic-frames/dfcc.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_cfg_info.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_cfg_info.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_contract_functions.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_instrument.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_lift_memory_predicates.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_loop_contract_mode.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_loop_contract_mode.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_spec_functions.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_swap_and_wrap.cpp
  src/goto-instrument/contracts/dynamic-frames/dfcc_swap_and_wrap.h
  src/goto-instrument/contracts/loop_contract_config.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-synthesizer/cegis_verifier.cpp
  src/goto-synthesizer/goto_synthesizer_parse_options.cpp
Labels: aws, Code Contracts
