Repository diffblue/cbmc, pull requests merged in 2024-05, with the labels that each got.

#7858 Permit re-setting --object-bits
  doc/cprover-manual/goto-cc.md
  doc/man/goto-cc.1
  regression/CMakeLists.txt
  regression/Makefile
  regression/cbmc/simplify_singleton_interval_7690/singleton_interval_in_assume_7690.c
  regression/contracts-dfcc/memory-predicates-pointer-in-range-requires/test.desc
  regression/goto-cc-cbmc-shared-options/CMakeLists.txt
  regression/goto-cc-cbmc-shared-options/Makefile
  regression/goto-cc-cbmc-shared-options/README.md
  regression/goto-cc-cbmc-shared-options/chain.sh
  regression/goto-cc-cbmc/object-bits/default_bits.desc
  regression/goto-cc-cbmc/object-bits/fewer_bits.desc
  regression/goto-cc-cbmc/object-bits/more_bits.desc
  regression/goto-cc-cbmc/object-bits/test.c
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/cprover_library.h
  src/ansi-c/library/cprover.h
  src/ansi-c/library/cprover_contracts.c
  src/cbmc/cbmc_parse_options.cpp
  src/goto-cc/gcc_cmdline.cpp
  src/goto-cc/goto_cc_mode.cpp
  src/goto-instrument/nondet_static.cpp
  src/goto-instrument/nondet_static.h
  src/goto-programs/initialize_goto_model.cpp
  src/goto-programs/initialize_goto_model.h
  src/goto-synthesizer/goto_synthesizer_parse_options.cpp
  src/util/config.cpp
  src/util/config.h
  src/util/simplify_expr_pointer.cpp
  unit/Makefile
  unit/ansi-c/max_malloc_size.cpp
  unit/util/max_malloc_size.cpp
  unit/util/simplify_expr.cpp
Labels: Version 6

#8246 simplify `extractbits_exprt` representation
  src/ansi-c/expr2c.cpp
  src/ansi-c/goto_check_c.cpp
  src/cpp/expr2cpp.cpp
  src/solvers/flattening/boolbv_extractbits.cpp
  src/solvers/floatbv/float_bv.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_parser.cpp
  src/solvers/smt2_incremental/convert_expr_to_smt.cpp
  src/solvers/smt2_incremental/encoding/struct_encoding.cpp
  src/solvers/strings/string_constraint_generator_float.cpp
  src/util/bitvector_expr.cpp
  src/util/bitvector_expr.h
  src/util/expr_util.cpp
  src/util/lower_byte_operators.cpp
  src/util/simplify_expr_int.cpp
  unit/solvers/smt2_incremental/convert_expr_to_smt.cpp
  unit/solvers/smt2_incremental/encoding/struct_encoding.cpp
  unit/util/simplify_expr.cpp
Labels: Version 6

#8215 analyses: Replace uses of namespacet::follow
  src/analyses/custom_bitvector_analysis.cpp
  src/analyses/goto_rw.cpp
  src/analyses/invariant_propagation.cpp
  src/analyses/invariant_set.cpp
  src/analyses/variable-sensitivity/abstract_aggregate_object.h
  src/analyses/variable-sensitivity/abstract_environment.cpp
  src/analyses/variable-sensitivity/constant_pointer_abstract_object.cpp
  src/analyses/variable-sensitivity/full_struct_abstract_object.cpp
  src/analyses/variable-sensitivity/variable_sensitivity_object_factory.cpp
Labels: cleanup

#8220 goto-harness: remove use of namespacet::follow
  src/goto-harness/function_call_harness_generator.cpp
Labels: cleanup

#8231 Pointer analysis: Replace uses of namespacet::follow
  src/pointer-analysis/value_set.cpp
  src/pointer-analysis/value_set_analysis_fi.cpp
  src/pointer-analysis/value_set_dereference.cpp
  src/pointer-analysis/value_set_fi.cpp
  unit/goto-symex/symex_assign.cpp
Labels: cleanup

#8274 goto-instrument/unwinding: enable unwinding assertions by default
  doc/man/cbmc.1
  doc/man/goto-instrument.1
  regression/goto-instrument/slice01/test.desc
  regression/goto-instrument/slice08/test.desc
  regression/goto-instrument/slice16/test.desc
  regression/goto-instrument/unwind-assume2/test.desc
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
Labels: Version 6

#8235 Solvers: Replace uses of namespacet::follow
  src/solvers/flattening/boolbv_struct.cpp
  src/solvers/flattening/boolbv_typecast.cpp
  src/solvers/flattening/boolbv_update.cpp
  src/solvers/flattening/bv_pointers.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2_incremental/encoding/struct_encoding.cpp
  src/solvers/strings/string_refinement.cpp
Labels: cleanup

#8283 C library: add __to{lower,upper} as alternative names for {tolower,toupper}
  regression/cbmc-library/tolower-01/main.c
  regression/cbmc-library/tolower-01/test.desc
  regression/cbmc-library/toupper-01/main.c
  regression/cbmc-library/toupper-01/test.desc
  src/ansi-c/library/ctype.c
  src/ansi-c/library_check.sh
Labels: C Front End

#8286 C++ front-end: permit GCC attributes in using declarations
  regression/cpp/using1/main.cpp
  regression/cpp/using1/test.desc
  src/cpp/parse.cpp
Labels: C++ Front End

#8287 C++ front-end: support [[__nodiscard__]] and [[nodiscard]]
  regression/cpp/nodiscard1/main.cpp
  regression/cpp/nodiscard1/test.desc
  src/ansi-c/ansi_c_convert_type.cpp
  src/ansi-c/c_qualifiers.cpp
  src/ansi-c/c_qualifiers.h
  src/ansi-c/parser.y
  src/ansi-c/scanner.l
  src/cpp/parse.cpp
  src/util/irep_ids.def
Labels: C++ Front End

#8288 C++ front-end: fix parentheses matching for alignas parsing
  regression/cpp/alignas1/main.cpp
  regression/cpp/alignas1/test.desc
  src/cpp/parse.cpp
Labels: C++ Front End

#8293 cbmc-cpp/Array4 test now works
  regression/cbmc-cpp/Array4/test.desc
Labels: C++ Front End, Tests

#8294 Visual Studio has added _Static_assert
  regression/ansi-c/_Static_assert1/main.c
  regression/ansi-c/_Static_assert2/global.desc
  regression/ansi-c/_Static_assert2/local.desc
  regression/ansi-c/_Static_assert2/not_constant.desc
  regression/ansi-c/anonymous_member1/main.c
  regression/ansi-c/simplify-overflow/main.c
  regression/ansi-c/sizeof2/main.c
  regression/cbmc/Bitfields5/main.c
  regression/cbmc/inequality-with-constant-normalisation1/main.c
  regression/cbmc/member_bounds3/main.c
  src/ansi-c/scanner.l
Labels: C Front End

#8273 JBMC: enable unwinding assertions by default
  doc/man/jbmc.1
  jbmc/regression/jbmc-strings/StringConcat/test_string_nondet_array.desc
  jbmc/regression/jbmc-strings/StringIndexOf/test_thorough.desc
  jbmc/regression/jbmc-strings/VerifStringLastIndexOf/test.desc
  jbmc/regression/jbmc/NondetArray2/test.desc
  jbmc/regression/jbmc/NondetArray3/test.desc
  jbmc/regression/jbmc/dynamic-multi-dimensional-array/test.desc
  jbmc/regression/jbmc/enum/test_enum1.desc
  jbmc/regression/jbmc/nondet_propagation1/andNot_Pass.desc
  jbmc/regression/jbmc/nondet_propagation1/test.desc
  jbmc/regression/jbmc/output-options/test.desc
  jbmc/src/jbmc/jbmc_parse_options.cpp
Labels: Version 6

#8299 [CONTRACTS] Refactor quantified symbol detection for loop contracts
  regression/contracts-dfcc/quantifiers-loop-01/main.c
  regression/contracts-dfcc/quantifiers-loop-01/test.desc
  regression/contracts/quantifiers-loop-01/main.c
  src/goto-instrument/contracts/utils.cpp
Labels: aws, aws-high

#8289 C++ front-end: support attributes with tag-less structs
  regression/cpp/gcc_attributes2/main.cpp
  src/cpp/parse.cpp
Labels: C++ Front End

#8307 introduce `literal_vector_exprt`
  src/solvers/flattening/boolbv.cpp
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/literal_vector_expr.h
  src/util/irep_ids.def
Labels: Solvers
