Repository diffblue/cbmc, pull requests merged in 2024-07, with the labels that each got.

#8341 Bump Homebrew/git-user-config version to avoid deprecation warnings
  .github/workflows/release-packages.yaml
Labels: CI

#8339 Refactor Codecov CI job
  .github/workflows/coverage.yaml
  .github/workflows/pull-request-checks.yaml
Labels: CI

#8369 Regression cleanup: don't repeatedly remove the same file
  regression/cbmc-output-file/Makefile
  regression/contracts/Makefile
  regression/crangler/Makefile
  regression/extract_type_header/Makefile
  regression/goto-cc-cbmc/Makefile
  regression/goto-cc-file-local/Makefile
  regression/goto-instrument-chc/Makefile
  regression/goto-instrument-json/Makefile
  regression/goto-instrument/Makefile
  regression/goto-interpreter/Makefile
  regression/goto-synthesizer/Makefile
  regression/symtab2gb-cbmc/Makefile
  regression/symtab2gb/Makefile
  regression/test-script/Makefile
Labels: Tests

#7857 Purge winbug from regression tests
  regression/README.md
  regression/book-examples/CMakeLists.txt
  regression/cbmc/CMakeLists.txt
  regression/cbmc/export-symex-ready-goto/test-bad-usage.desc
Labels: cleanup, Tests

#8361 Make sure free symbols are declared in SMT2_conv after quantifier rewriting
  regression/contracts-dfcc/quantifiers-loop-05/main.c
  regression/contracts-dfcc/quantifiers-loop-05/test.desc
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
Labels: bugfix

#8370 Regression test: support big and little endian
  regression/cbmc-incr-smt2/unions/padded.desc
Labels: Tests

#8379 SMT2 back-end: detect when solver returns unexpected model
  regression/cbmc-primitives/exists_memory_checks/smt_missing_range_check.desc
  regression/cbmc/Quantifiers-assertion/test.desc
  regression/cbmc/z3/Issue5977.desc
  src/solvers/smt2/smt2_dec.cpp
Labels: SMT Backend Interface

#8380 C front-end: place requires and ensures in designated scope
  regression/ansi-c/contracts_scope1/main.c
  regression/ansi-c/contracts_scope1/test.desc
  src/ansi-c/parser.y
Labels: C Front End

#8360 [CONTRACTS] Check side effect of loop contracts during instrumentation
  doc/man/goto-instrument.1
  regression/contracts-dfcc/loop_contracts_statement_expression/main.c
  regression/contracts-dfcc/loop_contracts_statement_expression/test.desc
  regression/contracts-dfcc/variant_function_call_fail/test.desc
  regression/contracts-dfcc/variant_side_effects_fail/test.desc
  regression/contracts/loop_contracts_statement_expression/main.c
  regression/contracts/loop_contracts_statement_expression/test.desc
  src/ansi-c/goto-conversion/goto_convert.cpp
  src/cprover/instrument_given_invariants.cpp
  src/goto-instrument/contracts/contracts.cpp
  src/goto-instrument/contracts/contracts.h
  src/goto-instrument/contracts/dynamic-frames/dfcc_cfg_info.cpp
  src/goto-instrument/contracts/utils.cpp
  src/goto-instrument/contracts/utils.h
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.h
Labels: Code Contracts

#8383 CI jobs: upgrade CVC5 from 1.0.0 to 1.1.2
  .github/workflows/coverage.yaml
  .github/workflows/pull-request-checks.yaml
  .github/workflows/release-packages.yaml
Labels: blocker, CI

#8396 implement flattening for +/- for the range type
  src/solvers/flattening/boolbv_add_sub.cpp
Labels: Solvers
