Repository diffblue/cbmc, pull requests merged in 2024-02, with the labels that each got.

#8133 Make ansi_c_internal_additions independent of the parser object
  src/ansi-c/ansi_c_internal_additions.cpp
  src/ansi-c/ansi_c_internal_additions.h
  src/ansi-c/ansi_c_language.cpp
  src/ansi-c/builtin_factory.cpp
  src/ansi-c/builtin_factory.h
  src/ansi-c/c_typecheck_base.h
  src/ansi-c/c_typecheck_expr.cpp
  src/cpp/cpp_typecheck.cpp
  src/cpp/cpp_typecheck.h
Labels: cleanup, blocker

#8174 argc/argv modelling: argument string must remain in scope
  regression/goto-instrument/argc-argv1/main.c
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/model_argc_argv.cpp
Labels: bugfix

#8182 update_bits_exprt
  src/solvers/Makefile
  src/solvers/flattening/boolbv.h
  src/solvers/flattening/boolbv_update_bits.cpp
  src/solvers/flattening/boolbv_with.cpp
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
  src/util/bitvector_expr.cpp
  src/util/bitvector_expr.h
  src/util/irep_ids.def
Labels: Solvers

#8180 SMT2: fix extractbit with non-const index
  src/solvers/smt2/smt2_conv.cpp
Labels: Solvers, SMT Backend Interface

#8179 Full slicing always requires consistent location numbers
  src/goto-instrument/goto_instrument_parse_options.cpp
Labels: bugfix

#8139 assembler_parsert: construct with message handler
  doc/architectural/goto-program-transformations.md
  src/assembler/assembler_parser.cpp
  src/assembler/assembler_parser.h
  src/assembler/remove_asm.cpp
  src/assembler/remove_asm.h
  src/assembler/scanner.l
  src/cbmc/cbmc_parse_options.cpp
  src/goto-analyzer/goto_analyzer_parse_options.cpp
  src/goto-diff/goto_diff_parse_options.cpp
  src/goto-instrument/goto_instrument_parse_options.cpp
  src/goto-synthesizer/cegis_verifier.cpp
  src/libcprover-cpp/api.cpp
Labels: cleanup, blocker

#8123 SMT2: simplify interface
  src/solvers/smt2/smt2_conv.cpp
  src/solvers/smt2/smt2_conv.h
  src/solvers/smt2/smt2_dec.cpp
Labels: Solvers

#7932 C library: ASM functions take void* pointers
  .github/workflows/build-and-test-Xen.yaml
  src/ansi-c/library/x86_assembler.c
  src/assembler/remove_asm.cpp
Labels: cleanup

#8195 C library: additional floating-point functions and cleanup
  regression/cbmc-library/feraiseexcept-01/main.c
  regression/cbmc-library/feraiseexcept-01/test.desc
  regression/cbmc-library/fma-01/main.c
  regression/cbmc-library/fma-01/test.desc
  regression/cbmc-library/fmaf-01/main.c
  regression/cbmc-library/fmaf-01/test.desc
  regression/cbmc-library/fmal-01/main.c
  regression/cbmc-library/fmal-01/test.desc
  regression/cbmc-library/log10-01/main.c
  regression/cbmc-library/log10-01/test.desc
  regression/cbmc-library/log10f-01/main.c
  regression/cbmc-library/log10f-01/test.desc
  regression/cbmc-library/log10l-01/main.c
  regression/cbmc-library/log10l-01/test.desc
  regression/cbmc-library/log2-01/main.c
  regression/cbmc-library/log2-01/test.desc
  regression/cbmc-library/log2f-01/main.c
  regression/cbmc-library/log2f-01/test.desc
  regression/cbmc-library/log2l-01/main.c
  regression/cbmc-library/log2l-01/test.desc
  regression/cbmc-library/pow-01/main.c
  src/ansi-c/library/fenv.c
  src/ansi-c/library/math.c
Labels: C Front End, Kani

#8212 Make tests pass when char is unsigned
  regression/cbmc-cpp/Pointer_Conversion2/main.cpp
  regression/cbmc/pragma_cprover_enable_all/test.desc
Labels: bugfix, Tests

#8192 C library: model __builtin_powi{,f,l}
  regression/cbmc-library/__builtin_powi-01/main.c
  regression/cbmc-library/__builtin_powi-01/test.desc
  regression/cbmc-library/__builtin_powif-01/main.c
  regression/cbmc-library/__builtin_powif-01/test.desc
  regression/cbmc-library/__builtin_powil-01/main.c
  regression/cbmc-library/__builtin_powil-01/test.desc
  regression/goto-synthesizer/loop_contracts_synthesis_04/test.desc
  src/ansi-c/library/math.c
Labels: C Front End, Kani

#8201 Remove unused goto_convertt::has_function_call
  src/goto-programs/goto_convert_class.h
  src/goto-programs/goto_convert_side_effect.cpp
Labels: cleanup
