Repository diffblue/cbmc, pull requests merged in 2024-04, with the labels that each got.

#8244 Remove parsert::clear and all of its overrides
  src/ansi-c/ansi_c_parser.h
  src/assembler/assembler_parser.h
  src/cpp/cpp_language.cpp
  src/cpp/cpp_parser.h
  src/json/json_parser.cpp
  src/json/json_parser.h
  src/statement-list/statement_list_parser.cpp
  src/statement-list/statement_list_parser.h
  src/util/parser.h
  src/xmllang/xml_parser.h
Labels: cleanup

#8236 util: Replace uses of namespacet::follow
  src/util/lower_byte_operators.cpp
  src/util/pointer_offset_size.cpp
  src/util/simplify_expr.cpp
  src/util/simplify_expr_pointer.cpp
  src/util/simplify_expr_struct.cpp
  src/util/std_expr.cpp
  src/util/std_types.cpp
Labels: cleanup

#8229 goto-instrument: Replace uses of namespacet::follow
  src/goto-instrument/dump_c.cpp
  src/goto-instrument/goto_program2code.cpp
Labels: cleanup

#1359 Avoid duplicate "warning:" or "error:" output
  regression/ansi-c/linking_conflicts1/test.desc
  regression/ansi-c/linking_conflicts2/test.desc
  regression/cbmc/incomplete-structs/test.desc
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_typecast.cpp
  src/cpp/cpp_declarator_converter.cpp
  src/cpp/cpp_typecheck_bases.cpp
  src/cpp/cpp_typecheck_code.cpp
  src/cpp/cpp_typecheck_compound_type.cpp
  src/cpp/cpp_typecheck_enum_type.cpp
  src/cpp/cpp_typecheck_expr.cpp
  src/cpp/cpp_typecheck_resolve.cpp
  src/cpp/cpp_typecheck_type.cpp
  src/goto-cc/armcc_mode.cpp
  src/goto-cc/as_mode.cpp
  src/goto-cc/cl_message_handler.cpp
  src/goto-cc/cl_message_handler.h
  src/goto-cc/cw_mode.cpp
  src/goto-cc/gcc_message_handler.cpp
  src/goto-cc/gcc_message_handler.h
  src/goto-cc/gcc_mode.cpp
  src/goto-cc/ld_mode.cpp
  src/goto-cc/ms_cl_mode.cpp
  src/goto-cc/ms_link_mode.cpp
  src/goto-programs/builtin_functions.cpp
  src/linking/linking.cpp
Labels: cleanup

#8239 C library: implement {v,}snprintf
  regression/cbmc-library/snprintf-01/main.c
  regression/cbmc-library/snprintf-01/test.desc
  regression/cbmc-library/vsnprintf-01/main.c
  regression/cbmc-library/vsnprintf-01/test.desc
  src/ansi-c/library/stdio.c
  src/ansi-c/library_check.sh
Labels: C Front End

#8238 C library: implement {v,}dprintf
  regression/cbmc-library/dprintf-01/main.c
  regression/cbmc-library/dprintf-01/test.desc
  regression/cbmc-library/vdprintf-01/main.c
  regression/cbmc-library/vdprintf-01/test.desc
  src/ansi-c/library/stdio.c
Labels: C Front End

#8218 C front-end: Replace uses of namespacet::follow
  src/ansi-c/anonymous_member.cpp
  src/ansi-c/c_typecast.cpp
  src/ansi-c/c_typecheck_base.cpp
  src/ansi-c/c_typecheck_code.cpp
  src/ansi-c/c_typecheck_expr.cpp
  src/ansi-c/c_typecheck_initializer.cpp
  src/ansi-c/c_typecheck_type.cpp
  src/ansi-c/expr2c.cpp
  src/ansi-c/padding.cpp
  src/cpp/cpp_typecheck_resolve.cpp
Labels: cleanup

#8265 initialisation of `_Complex` with an initializer list
  regression/cbmc/complex/complex_initialization1.c
  regression/cbmc/complex/complex_initialization1.desc
  src/ansi-c/c_typecheck_initializer.cpp
Labels: C Front End

#8267 C library: provide implementations of fopen64, freopen64
  src/ansi-c/library/stdio.c
  src/ansi-c/library_check.sh
Labels: C Front End

#8269 C library: add mmap64
  src/ansi-c/library/mman.c
  src/ansi-c/library_check.sh
Labels: C Front End

#8270 Remove unanchored "error" string from symtab2gb test specs
  regression/symtab2gb/multiple_symtabs/test.desc
  regression/symtab2gb/single_symtab/test.desc
Labels: Tests, blocker

#8271 C library: add creat, open, openat
  regression/cbmc-library/creat-01/main.c
  regression/cbmc-library/creat-01/test.desc
  regression/cbmc-library/fcntl-01/main.c
  regression/cbmc-library/fcntl-01/test.desc
  regression/cbmc-library/open-01/main.c
  regression/cbmc-library/open-01/test.desc
  regression/cbmc-library/openat-01/main.c
  regression/cbmc-library/openat-01/test.desc
  src/ansi-c/library/fcntl.c
  src/ansi-c/library_check.sh
Labels: C Front End
